src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/echosign_dev1__Agreement_Template__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <description>Agreement Templates allow you to predefine default settings and options for your agreements which can save you time and help minimize errors.</description>
    <fields>
        <fullName>echosign_dev1__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls visibility of the Agreement Template.</description>
        <inlineHelpText>If checked, the Agreement Template is visible, else it is not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Name__c</fullName>
        <defaultValue>&quot;Adobe Sign Agreement&quot;</defaultValue>
        <description>Enter a name for the agreement.</description>
        <inlineHelpText>Enter a name for the agreement.</inlineHelpText>
        <label>Agreement Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Agreement Template</label>
    <nameField>
        <label>Agreement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact who signs the contract in EchoSign.</inlineHelpText>
        <label>Contract Signer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JavascriptButtonServiceTest.cls
@isTest
private class JavascriptButtonServiceTest {
    
  static testMethod void validateSignature1() {

    Map<String, SObject> testObjects =TestClassUtility.buildLocalData(false);

    test.startTest();

    Account testAcc = (Account)testObjects.get('Account');
    Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
    Contact testContact = (Contact)testObjects.get('Contact');
    Zuora__CustomerAccount__c testBillingAccount = (Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c');

    Map<String, SObject> testSubObjects = TestClassUtility.buildSubscriptionData(testAcc, testContact, testOpp, testBillingAccount);

    String eStdTemplateName = 'Local Amendment Agreement Template 20160127';
    echosign_dev1__Agreement_Template__c eStdTemplate = new echosign_dev1__Agreement_Template__c();
    eStdTemplate.Name = eStdTemplateName;
    eStdTemplate.echosign_dev1__Name__c = eStdTemplateName;
    eStdTemplate.echosign_dev1__Active__c = true;
    insert eStdTemplate;
    
    zqu__Quote__c testQuote = (zqu__Quote__c)testSubObjects.get('zqu__Quote__c');
    testQuote.zqu__SubscriptionType__c= 'Amend Subscription';
    testQuote.zqu__TermStartDate__c = DateUtility.AddBusinessDays(Date.today(), 4);
    update testQuote;
    
    testOpp.Contract_Signer__c = testContact.id;
    update testOpp;

    JavascriptButtonService.validateSignatureProceed(testOpp.Id);
    test.stopTest();

  }

  static testMethod void validateSignature2() {

    Map<String, SObject> testObjects =TestClassUtility.buildLocalData(true);

    test.startTest();
    String eStdTemplateName = 'Local Standard Agreement Template 20170524';
    echosign_dev1__Agreement_Template__c eStdTemplate = new echosign_dev1__Agreement_Template__c();
    eStdTemplate.Name = eStdTemplateName;
    eStdTemplate.echosign_dev1__Name__c = eStdTemplateName;
    eStdTemplate.echosign_dev1__Active__c = true;
    insert eStdTemplate;
    
    zqu__Quote__c testQuote = (zqu__Quote__c)testObjects.get('zqu__Quote__c');
    testQuote.zqu__SubscriptionType__c= 'New Subscription';
    testQuote.zqu__TermStartDate__c = DateUtility.AddBusinessDays(Date.today(), 4);
    update testQuote;

    Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
    Contact testContact = (Contact)testObjects.get('Contact');
    testOpp.Contract_Signer__c = testContact.id;
    update testOpp;
    
    JavascriptButtonService.validateSignatureProceed(testOpp.Id);
    test.stopTest();

  }

  static testMethod void validateSignature3() {

    test.startTest();

    JavascriptButtonService.validateSignatureProceed('');
    JavascriptButtonService.validateSignatureProceed('BAD ID');

    test.stopTest();
  }


  // CSP-1306 Added by Nick Wu
  static testMethod void updateAutoCloseDate() {

    Map<String, SObject> testObjects = TestClassUtility.buildLocalData(true);

    test.startTest();
    JavascriptButtonService.updateAutoCloseDate('');
    JavascriptButtonService.updateAutoCloseDate('BAD ID');    
    Opportunity testOpportunity = (Opportunity)testObjects.get('Opportunity');
    JavascriptButtonService.updateAutoCloseDate(testOpportunity.id);
    test.stopTest();
  }

  static testMethod void updateEchosignExpirationDate(){
    
    Map<String, SObject> testObjects = TestClassUtility.buildLocalData(true);

    test.startTest();
    Opportunity testOpportunity = (Opportunity)testObjects.get('Opportunity');
    JavascriptButtonService.updateEchosignExpirationDate(testOpportunity.id);
    test.stopTest();
  }
}