src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Batch_Process_Run_History__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lists the last successful run of the subscription batch process</description>
    <fields>
        <fullName>Last_Successfully_Completed__c</fullName>
        <label>Last Successfully Completed</label>
        <type>DateTime</type>
    </fields>
    <label>Subscription Batch Process Run History</label>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ProductSKU__c</fullName>
        <label>Product SKU (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionBatchClas_test.cls
@istest 
public class SubscriptionBatchClas_test{

	public static testmethod void TestSubscriptionBatchClas(){

		Subscription_Batch_Process_Run_History__c subLastRun = new Subscription_Batch_Process_Run_History__c();
		subLastRun.name = 'test';
		subLastRun.Last_Successfully_Completed__c = Date.today() - 1;
		insert subLastRun;
		
		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.stopTest();

		Account testAccount = (Account)testObjects.get('Account');

		Zuora__Subscription__c zs = new Zuora__Subscription__c(name='testjs',
																Zuora__status__c='Active',
																Zuora__account__c=testAccount.id,
																Zuora__SubscriptionEndDate__c = Date.today() - 1
																);
		insert zs;
		Zuora__SubscriptionProductCharge__c zsc = new Zuora__SubscriptionProductCharge__c(Product_Type__c ='Print', 
																							name='testzsc',
																							Zuora__ProductSKU__c ='test123',
																							Zuora__Subscription__c=zs.id
																							);
		insert zsc;
		zqu__ZProduct__c zp=new zqu__ZProduct__c(name='testzp', 
												zqu__SKU__c='test123',
												ProductType__c='testgroup',
												zqu__ZuoraId__c='123'
												);
		insert zp;

		SubscriptionBatchClass b = new SubscriptionBatchClass();
		database.executebatch(b);
	}

	public static testmethod void TestSubscriptionBatchClas1(){
		
		Subscription_Batch_Process_Run_History__c subLastRun = new Subscription_Batch_Process_Run_History__c();
		subLastRun.name = 'test';
		subLastRun.Last_Successfully_Completed__c = Date.today() - 1;
		insert subLastRun;

		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.stopTest();

		Account testAccount = (Account)testObjects.get('Account');


		Zuora__Subscription__c zs = new Zuora__Subscription__c(name='testjs',
																Zuora__status__c='Active',
																Zuora__account__c=testAccount.id,
																Zuora__SubscriptionEndDate__c = Date.today() + 1
																);
		insert zs;
		Zuora__SubscriptionProductCharge__c zsc = new Zuora__SubscriptionProductCharge__c(Product_Type__c ='print',
																							name='testzsc',
																							Zuora__ProductSKU__c ='test123',
																							Zuora__Subscription__c=zs.id
																							);
		insert zsc;
		zqu__ZProduct__c zp=new zqu__ZProduct__c(name='testzp', 
												zqu__SKU__c='test123',
												ProductType__c='testgroup',
												zqu__ZuoraId__c='123'
												);
		insert zp;

		SubscriptionBatchClass b = new SubscriptionBatchClass();
		database.executebatch(b);

	}

	public static testmethod void TestSubscriptionBatchClas2(){

		Subscription_Batch_Process_Run_History__c subLastRun = new Subscription_Batch_Process_Run_History__c();
		subLastRun.name = 'test';
		subLastRun.Last_Successfully_Completed__c = Date.today() - 1;
		insert subLastRun;

		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.stopTest();

		Account testAccount = (Account)testObjects.get('Account');

		Zuora__Subscription__c zs=new Zuora__Subscription__c(name='testjs',
															Zuora__status__c='Active',
															Zuora__account__c=testAccount.id,
															Zuora__SubscriptionEndDate__c = Date.today() + 1
															);
		insert zs;

		Zuora__SubscriptionProductCharge__c zsc = new Zuora__SubscriptionProductCharge__c(Product_Type__c ='Concierge Venue',
																						name='testzsc',
																						Zuora__ProductSKU__c ='test123',
																						Zuora__Subscription__c=zs.id);
		insert zsc;

		zqu__ZProduct__c zp=new zqu__ZProduct__c(name='testzp', 
												zqu__SKU__c='test123',
												ProductType__c='testgroup',
												zqu__ZuoraId__c='123'
												);
		insert zp;

		SubscriptionBatchClass b = new SubscriptionBatchClass();
		database.executebatch(b);
	}
}