src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Callback__c.object
<CustomObject>
    <description>Object named &quot;Callback&quot; which will be used to store callbacks generated through the system</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Callbacks</relationshipLabel>
        <relationshipName>Callbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Follow Up</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <description>Name of the Subscription for which this Callback is associated. Specifically added to query/delete Callbacks for Charges that were removed in an Amendment Quote. (CSP-1464)</description>
        <externalId>true</externalId>
        <label>Subscription Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Callback</label>
    <nameField>
        <label>Callback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CallbackManagerControllerTest.cls
/*******************************************************************************
 *  Summary         : Test class for call back manager controller
 *  Refer Object    : 
 *  Author          : Nick
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
private class CallbackManagerControllerTest {

	@isTest static void testCallbackManager() {
		
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		
		Test.startTest();
		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
														 					(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));


		Zuora__Subscription__c testSubscription = (Zuora__Subscription__c)testsub.get('Zuora__Subscription__c');
		Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = (Zuora__SubscriptionProductCharge__c)testsub.get('Zuora__SubscriptionProductCharge__c');
		testSubscriptionProductCharge.Zuora__SubscriptionChargeNumber__c = 'TEST-001';
		update testSubscriptionProductCharge;

		Callback__c testCallback = new Callback__c();
		testCallback.Name = testSubscription.Name;
		testCallback.Subscription_Name__c = testSubscription.Name;
		testCallback.Status__c = 'New';
		insert testCallback;

		
		CallbackManagerController.getCallbacks(2, 'all', 'all', 
												'all', 'all', 'all', 
												'all', 'Account__r.Name ASC ', '',
												'', '', '',
												'all');
		CallbackManagerController.getCallbacks(2, 'mine', 'internet', 
												'open', 'AK-Alaska', 'Accessories - ACC', 
												'VIP', 'Account__r.Name ASC ', 'AccountName', 
												'SubName', String.valueOf(Date.today() - 1), String.valueOf(Date.today() + 1),
												'all');
		CallbackManagerController.getStatusPicklistValues();
		CallbackManagerController.updateCallbackStatus(testCallback.Id, 'Proof Out');
		CallbackManagerController.getOwnerPicklistValues();
		CallbackManagerController.getMarketPicklistValues();
		CallbackManagerController.getCategoryPicklistValues();
		CallbackManagerController.updateCallbackDate(testCallback.Id, String.valueOf(Date.today()), new Map<String, String>());
		CallbackManagerController.getSubscriptionDetails(testCallback.Id);
		CallbackManagerController.updatecallbackOwner(testCallback.Id, UserInfo.getUserId());
		CallbackManagerController.getStrategySpecialistPicklistValues();

		// testing CallbackManagerController methods with an invalid Callback record Id
		Id invalidCallbackId = 'a4J11000000D7klEAC';
		CallbackManagerController.updateCallbackStatus(invalidCallbackId, 'Proof Out');
		CallbackManagerController.updateCallbackDate(invalidCallbackId, String.valueOf(Date.today()), new Map<String, String>());
		CallbackManagerController.getSubscriptionDetails(invalidCallbackId);
		CallbackManagerController.updatecallbackOwner(invalidCallbackId, UserInfo.getUserId());
		CallbackManagerController.getCallbackNotes(invalidCallbackId);
		CallbackManagerController.createCallbackNote(invalidCallbackId, 'test');

		Test.stopTest();
	}

	@isTest static void testZuoraSubscriptionTriggerHandler() {
		
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		
		Test.startTest();
		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
														 					(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));

		Zuora__Subscription__c testSubscription = (Zuora__Subscription__c)testsub.get('Zuora__Subscription__c');
		Callback__c testCallback = new Callback__c();
		testCallback.Name = testSubscription.Name;
		testCallback.Subscription_Name__c = testSubscription.Name;
		testCallback.Status__c = 'New';
		insert testCallback;

		ZuoraSubscriptionTriggerHandler.closeOpenCallbacksForCancelledSubs(new Set<String>{testSubscription.Name});
		Test.stopTest();
	}

	@isTest static void testZuoraSubscriptionPCTriggerHandler() {
		
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.startTest();
		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
														 					(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));


		Zuora__Subscription__c testSubscription = (Zuora__Subscription__c)testsub.get('Zuora__Subscription__c');
		Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = (Zuora__SubscriptionProductCharge__c)testsub.get('Zuora__SubscriptionProductCharge__c');
		testSubscriptionProductCharge.Zuora__SubscriptionChargeNumber__c = 'TEST-001';
		update testSubscriptionProductCharge;

		Callback__c testCallback = new Callback__c();
		testCallback.Name = testSubscription.Name;
		testCallback.Subscription_Name__c = testSubscription.Name;
		testCallback.Status__c = 'New';
		insert testCallback;

		Map<String, Zuora__SubscriptionProductCharge__c> amendedSubCallbackMap = new Map<String, Zuora__SubscriptionProductCharge__c>();
		amendedSubCallbackMap.put(testSubscriptionProductCharge.Zuora__SubscriptionChargeNumber__c, testSubscriptionProductCharge);

		ZuoraSubscriptionPCTriggerHandler.createAndUpdateCallbacks(amendedSubCallbackMap, new Map<String, List<Zuora__SubscriptionProductCharge__c>>());

		Test.stopTest();
	}

	@isTest static void testCallbackTrigger() {
		
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.startTest();
		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
														 					(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));
		

		Zuora__Subscription__c testSubscription = (Zuora__Subscription__c)testsub.get('Zuora__Subscription__c');

		Callback__c testCallback = new Callback__c();
		testCallback.Name = testSubscription.Name;
		testCallback.Subscription_Name__c = testSubscription.Name;
		testCallback.Status__c = 'New';
		insert testCallback;

		try {
			delete testCallback;
		}
		catch (Exception e) {
			// don't do anything, this is testing the CallbackTrigger code to prevent deletions
		}
		Test.stopTest();
	}
}