src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>NeedToUpdateAccountDetails__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1603</description>
        <label>NeedToUpdateAccountDetails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZDU_RetrieveSoldToContactFailureCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>CSP-1659</description>
        <label>ZDU - RetrieveSoldToContactFailureCount</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZDU_RetrieveSoldToContact__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CSP-1659</description>
        <label>ZDU - RetrieveSoldToContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZDU_UpdateAccountFailureCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>CSP-1659</description>
        <label>ZDU - UpdateAccountFailureCount</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZDU_UpdateContactsFailureCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>CSP-1659</description>
        <label>ZDU - UpdateContactsFailureCount</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZDU_UpdateContacts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1659</description>
        <label>ZDU - UpdateContacts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToId__c</fullName>
        <label>Sold To Contact Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchZuoraDataUpdaterTest.cls
@isTest
private class BatchZuoraDataUpdaterTest {
    @testSetup static void createTestData(){
      TestClassUtility.createCBSSCustomSettings();
    }
    
    static testMethod void testMethod1() {

      Test.startTest();

      Account testAcc = TestClassUtility.createAccount(true);
      Contact testCont = TestClassUtility.createContact(true);
      Zuora__CustomerAccount__c testCustomerAccount = TestClassUtility.createCustomerAccount(false,testAcc);
      testCustomerAccount.Zuora__SoldToId__c = testCont.Id;
      testCustomerAccount.ZDU_RetrieveSoldToContact__c = true;
      testCustomerAccount.ZDU_RetrieveSoldToContactFailureCount__c = 2;
      testCustomerAccount.ZDU_UpdateContacts__c = true;
      testCustomerAccount.ZDU_UpdateContactsFailureCount__c = 3;
      testCustomerAccount.NeedToUpdateAccountDetails__c = true;
      testCustomerAccount.ZDU_UpdateAccountFailureCount__c = 3;
      insert testCustomerAccount;

      
      BatchZuoraDataUpdater batch = new BatchZuoraDataUpdater();
      Database.executeBatch(batch,10);
      Test.stopTest();
    }
}