src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Hold__c</fullName>
        <formula>IF(ISPICKVAL(CreditHold__c,&apos;Yes&apos;) , TRUE , FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Hold</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <description>for CSP-1786</description>
        <label>AutoRenewal</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Renewal_Rep_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Subscriptions_Reporting_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__AutoRenew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoRenew?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__MRR__c</fullName>
        <label>CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__TCV__c</fullName>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubsEntityWrapper.cls
public class SubsEntityWrapper implements Comparable {
    public zuora__Subscription__c zSub{get;set;}
    public Boolean showRenewalButton{get;set;}
    public Boolean showRemoveButton{get;set;}
    public String oppStageName{get;set;}
    public Id oppId{get;set;}
    public Decimal totalRenewal{get;set;}
    public Integer recordNum{get;set;}
    public String autoRenew{get;set;}
    
    public subsentityWrapper()
    {
        this.showRenewalButton =false;
        this.showRemoveButton =false;
        this.oppStageName = '';
        this.oppId=null; 
        this.totalRenewal = 0;
        this.recordNum = 0;
        this.autoRenew = '';
        this.zSub = new zuora__Subscription__c ();
    }
    
    public subsentityWrapper(zuora__Subscription__c zSub, Boolean showRenewalButton, Boolean showRemoveButton, String oppStageName, Id oppId, Decimal totalrenewal, Integer recordNum,String autoRenew)
    {
        this.zSub = zSub;
        this.showRenewalButton =showRenewalButton;
        this.showRemoveButton =showRemoveButton;
        this.oppStageName =oppStageName;
        this.oppId=oppId;
        this.totalrenewal =totalrenewal;
        this.recordNum =recordNum;
        this.autoRenew = autoRenew;
    }

    public static String sortBy;
    public static String ascOrDesc;

    public Integer compareTo(Object objToCompare) {
        SubsEntityWrapper compareToEmp = (SubsEntityWrapper)objToCompare;
        if(sortBy == 'SubscriptionName'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.name== compareToEmp.zSub.name) return 0;
                if (this.zSub.name> compareToEmp.zSub.name ) return 1;
                return -1;  
            }else{
                if (this.zSub.name== compareToEmp.zSub.name) return 0;
                if (this.zSub.name> compareToEmp.zSub.name) return -1;
                return 1;  
            }
        }else if(sortBy == 'Account'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__Account__r.Name == compareToEmp.zSub.Zuora__Account__r.Name) return 0;
                if (this.zSub.Zuora__Account__r.Name > compareToEmp.zSub.Zuora__Account__r.Name) return 1;
                return -1;  
            }else{
                if (this.zSub.Zuora__Account__r.Name == compareToEmp.zSub.Zuora__Account__r.Name) return 0;
                if (this.zSub.Zuora__Account__r.Name > compareToEmp.zSub.Zuora__Account__r.Name) return -1;
                return 1; 
            }
        }else if(sortBy == 'TermStartDate'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__TermStartDate__c == compareToEmp.zSub.Zuora__TermStartDate__c) return 0;
                if (this.zSub.Zuora__TermStartDate__c > compareToEmp.zSub.Zuora__TermStartDate__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Zuora__TermStartDate__c == compareToEmp.zSub.Zuora__TermStartDate__c) return 0;
                if (this.zSub.Zuora__TermStartDate__c > compareToEmp.zSub.Zuora__TermStartDate__c) return -1;
                return 1; 
            }
        }
        else if(sortBy == 'TermEndDate'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__TermEndDate__c == compareToEmp.zSub.Zuora__TermEndDate__c) return 0;
                if (this.zSub.Zuora__TermEndDate__c > compareToEmp.zSub.Zuora__TermEndDate__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Zuora__TermEndDate__c == compareToEmp.zSub.Zuora__TermEndDate__c) return 0;
                if (this.zSub.Zuora__TermEndDate__c > compareToEmp.zSub.Zuora__TermEndDate__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'ReportingRep'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Reporting_Rep__c == compareToEmp.zSub.Reporting_Rep__c) return 0;
                if (this.zSub.Reporting_Rep__c > compareToEmp.zSub.Reporting_Rep__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Reporting_Rep__c == compareToEmp.zSub.Reporting_Rep__c) return 0;
                if (this.zSub.Reporting_Rep__c > compareToEmp.zSub.Reporting_Rep__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'RenewalRep'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Renewal_Rep__c == compareToEmp.zSub.Renewal_Rep__c) return 0;
                if (this.zSub.Renewal_Rep__c > compareToEmp.zSub.Renewal_Rep__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Renewal_Rep__c == compareToEmp.zSub.Renewal_Rep__c) return 0;
                if (this.zSub.Renewal_Rep__c > compareToEmp.zSub.Renewal_Rep__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'Total'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__TCV__c == compareToEmp.zSub.Zuora__TCV__c) return 0;
                if (this.zSub.Zuora__TCV__c > compareToEmp.zSub.Zuora__TCV__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Zuora__TCV__c == compareToEmp.zSub.Zuora__TCV__c) return 0;
                if (this.zSub.Zuora__TCV__c > compareToEmp.zSub.Zuora__TCV__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'MonthlyRate'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__MRR__c == compareToEmp.zSub.Zuora__MRR__c) return 0;
                if (this.zSub.Zuora__MRR__c > compareToEmp.zSub.Zuora__MRR__c) return 1;
                return -1;  
            }else{
                if (this.zSub.Zuora__MRR__c == compareToEmp.zSub.Zuora__MRR__c) return 0;
                if (this.zSub.Zuora__MRR__c > compareToEmp.zSub.Zuora__MRR__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'autoRenew'){
            // if(this.zSub.AutoRenewal__c == true){
            //     this.autoRenew = 'true';
            // }else{
            //     this.autoRenew = 'false';
            // }
            // if(compareToEmp.zSub.Zuora__autoRenew__c == true){
            //     compareToEmp.autoRenew = 'true';
            // }else{
            //     compareToEmp.autoRenew = 'false';
            // }
            // if(ascOrDesc == 'ASC'){
            //     if (this.autoRenew == compareToEmp.autoRenew) return 0;
            //     if (this.autoRenew > compareToEmp.autoRenew) return 1;
            //     return -1;  
            // }else{
            //     if (this.autoRenew == compareToEmp.autoRenew) return 0;
            //     if (this.autoRenew > compareToEmp.autoRenew) return -1;
            //     return 1; 
            // }
            if(ascOrDesc == 'ASC'){
                if (this.zSub.AutoRenewal__c == compareToEmp.zSub.AutoRenewal__c) return 0;
                if (this.zSub.AutoRenewal__c > compareToEmp.zSub.AutoRenewal__c) return 1;
                return -1;  
            }else{
                if (this.zSub.AutoRenewal__c == compareToEmp.zSub.AutoRenewal__c) return 0;
                if (this.zSub.AutoRenewal__c > compareToEmp.zSub.AutoRenewal__c) return -1;
                return 1; 
            }
        }else if(sortBy == 'AccountCreditHoldStatus'){
            if(ascOrDesc == 'ASC'){
                if (this.zSub.Zuora__Account__r.Credit_Hold__c == compareToEmp.zSub.Zuora__Account__r.Credit_Hold__c) return 0;
                if (this.zSub.Zuora__Account__r.Credit_Hold__c== FALSE && compareToEmp.zSub.Zuora__Account__r.Credit_Hold__c == TRUE) return -1;
                return 1;  
            }else{
                if (this.zSub.Zuora__Account__r.Credit_Hold__c == compareToEmp.zSub.Zuora__Account__r.Credit_Hold__c) return 0;
                if (this.zSub.Zuora__Account__r.Credit_Hold__c== FALSE && compareToEmp.zSub.Zuora__Account__r.Credit_Hold__c == TRUE) return 1;
                return -1; 
            }
        }
        else{
            if(ascOrDesc == 'ASC'){
                if (this.oppStageName == compareToEmp.oppStageName) return 0;
                if (this.oppStageName > compareToEmp.oppStageName) return 1;
                return -1;  
            }else{
                if (this.oppStageName == compareToEmp.oppStageName) return 0;
                if (this.oppStageName > compareToEmp.oppStageName) return -1;
                return 1; 
            }
        }
    }
}