src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Used to hold Fulfillment Information received from Partners through the REST API</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>AccountStatus__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToAddress1__c</fullName>
        <label>Bill To Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCity__c</fullName>
        <label>Bill To Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCountry__c</fullName>
        <label>Bill To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToPostalCode__c</fullName>
        <label>Bill To Address Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToState__c</fullName>
        <label>Bill To Address State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToWorkEmail__c</fullName>
        <label>Bill To Work E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReassignMyTaskControllerTest.cls
@isTest
private class ReassignMyTaskControllerTest {
    static testMethod void processSelectedTest() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);  
        
        Test.startTest();
            Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();

        Account testAccount = (Account)testData.get('Account'); 

        testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
        update testAccount;
        
        Zuora__CustomerAccount__c testZuoraCustomerAccount = new Zuora__CustomerAccount__c(); 
        testZuoraCustomerAccount.Name = 'Test Billing Account'; 
        testZuoraCustomerAccount.Zuora__Account__c = testAccount.id;
        testZuoraCustomerAccount.Zuora__BillToAddress1__c = '123 ABC Dr';
        testZuoraCustomerAccount.Zuora__BillToCity__c = 'Austin'; 
        testZuoraCustomerAccount.Zuora__BillToCountry__c = 'United States';  
        testZuoraCustomerAccount.Zuora__BillToName__c = 'Test'; 
        testZuoraCustomerAccount.Zuora__BillToPostalCode__c = '77857'; 
        testZuoraCustomerAccount.Zuora__BillToState__c = 'Texas'; 
        testZuoraCustomerAccount.Zuora__BillToWorkEmail__c = 'abc@gmail.com';  
        testZuoraCustomerAccount.Zuora__Zuora_Id__c = '2c92c0f94ed8d0d7014ee476a6e419ee'; 
        testZuoraCustomerAccount.AccountStatus__c = 'Active';
        insert testZuoraCustomerAccount;
        
        Task testTask = new Task();
        testTask.Subject = 'Test';
        testTask.Type = 'Voicemail';
        testTask.ActivityDate = Date.Today();
        testTask.OwnerId = UserInfo.getUserId();
        testTask.Status = 'Not Started';
        testTask.Priority = 'Normal';
        testTask.WhatId = testZuoraCustomerAccount.id;
        insert testTask;
        
        ReassignMyTaskController newReassignTaskController = new ReassignMyTaskController();
        newReassignTaskController.tskRecord.ownerId = UserInfo.getUserId();
        ReassignMyTaskController.tTask rTst = new ReassignMyTaskController.tTask(testTask);
        newReassignTaskController.processSelected();    

        // scenario when tasks are empty 
        ReassignMyTaskController.tTask rTst1 = new ReassignMyTaskController.tTask(null);
        newReassignTaskController.processSelected();
    }    
}