src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Batch_Process_Run_History__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lists the last successful run of the subscription batch process</description>
    <fields>
        <fullName>Last_Successfully_Completed__c</fullName>
        <label>Last Successfully Completed</label>
        <type>DateTime</type>
    </fields>
    <label>Subscription Batch Process Run History</label>
</CustomObject>

src/objects/Zuora__Product__c.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zuora__Description__c</fullName>
        <label>Description</label>
        <length>25535</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SKU__c</fullName>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_ID__c</fullName>
        <description>A textfield that captures the ID of the parent Quote Rate Plan in order to sync it to the resulting Subscription Product Charge record. Created specifically for Inventory management, could potentially also be used for Fulfillment purposes.</description>
        <label>Quote Rate Plan ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__ProductName__c</fullName>
        <label>Product Name (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanId__c</fullName>
        <description>This field holds rateplan id.</description>
        <externalId>true</externalId>
        <label>RatePlan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanName__c</fullName>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionBatchClassScheduledJobTest.cls
/* 
<class>
  <name>SubscriptionBatchClassScheduledJobTest</name>
  <purpose>For testing the SubscriptionBatchClassScheduledJob class</purpose>
  <created>
	<by>Jonathan Satterfield</by>
	<date>8/17/2015</date>
	<ticket>SF-612</ticket>
  </created>
</class>
*/
@isTest
public class SubscriptionBatchClassScheduledJobTest {
	/* 
	<method>
		<name>testScheduledJob</name>
		<purpose>Test the scheduled job</purpose>
		<created>
		<by>Jonathan Satterfield</by>
		<date>8/17/2015</date>
		<ticket>SF-612</ticket>
	  </created>
	</method>
	*/
	@isTest
	static void testScheduledJob() {
		Test.startTest();
		SubscriptionBatchClassScheduledJob sj = new SubscriptionBatchClassScheduledJob();
		String sch = '0 0 23 * * ?';
		System.schedule('Test Territory Check', sch, sj);
		Test.stopTest();
	}
	
	@isTest
	static void testSubscriptionBatchClass2() {
		
		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.stopTest();
		
		Account testAccount = (Account)testObjects.get('Account');

		Subscription_Batch_Process_Run_History__c sbprh = new Subscription_Batch_Process_Run_History__c();
		sbprh.Name = 'test';
		sbprh.Last_Successfully_Completed__c = dateTime.now().adddays(-1);
		insert sbprh;
		
		Zuora__Product__c testZuoraProduct = new Zuora__Product__c();
		testZuoraProduct.Zuora__Description__c = 'Test Product';
		testZuoraProduct.Zuora__EffectiveEndDate__c = Date.Today();
		testZuoraProduct.Zuora__External_Id__c = '123ed';
		testZuoraProduct.ProductType__c = 'Concierge Venue';
		testZuoraProduct.Zuora__SKU__c = 'SKU-00000044';
		insert testZuoraProduct;
		
		Zuora__Subscription__c testZquSubscription = new Zuora__Subscription__c();
		testZquSubscription.Name = 'Test Subscription';
		testZquSubscription.Zuora__SubscriptionStartDate__c = Date.Today();
		testZquSubscription.Zuora__SubscriptionEndDate__c = Date.Today() + 365;
		testZquSubscription.Zuora__Status__c = 'Active';
		testZquSubscription.Zuora__Account__c = testAccount.Id;
		testZquSubscription.Zuora__Zuora_Id__c = 'abc123';
		insert testZquSubscription;
		
		Zuora__SubscriptionProductCharge__c testZquSubscriptionProductCharge = new Zuora__SubscriptionProductCharge__c();
		testZquSubscriptionProductCharge.Name = 'Test Subscription Product Charge';
		testZquSubscriptionProductCharge.Zuora__EffectiveEndDate__c = Date.newinstance(2015, 9, 10);
		testZquSubscriptionProductCharge.Zuora__Zuora_Id__c = 'zinrid12nd45oidl';
		testZquSubscriptionProductCharge.Quote_Rate_Plan_ID__c = 'qweqweqwe';
		testZquSubscriptionProductCharge.Zuora__RatePlanId__c = 'asdasdasdasdas';
		testZquSubscriptionProductCharge.Zuora__Subscription__c = testZquSubscription.id;
		testZquSubscriptionProductCharge.Zuora__ProductName__c = 'Test Product';
		testZquSubscriptionProductCharge.Zuora__RatePlanName__c = 'Test Product Rate Plan';
		testZquSubscriptionProductCharge.Zuora__Product__c = testZuoraProduct.id;
		testZquSubscriptionProductCharge.Zuora__Account__c = testAccount.id;
		testZquSubscriptionProductCharge.Product_Type__c = 'Concierge Venu';
		insert testZquSubscriptionProductCharge;
		
		Zuora__Subscription__c testZquSubscription1 = new Zuora__Subscription__c();
		testZquSubscription1.Name = 'Test Subscription1';
		testZquSubscription1.Zuora__SubscriptionStartDate__c = Date.Today();
		testZquSubscription1.Zuora__SubscriptionEndDate__c = Date.Today().adddays(-1);
		testZquSubscription1.Zuora__Status__c = 'Active';
		testZquSubscription1.Zuora__Account__c = testAccount.Id;
		testZquSubscription1.Zuora__Zuora_Id__c = 'abc1231';
		insert testZquSubscription1;
		
		Zuora__SubscriptionProductCharge__c testZquSubscriptionProductCharge1 = new Zuora__SubscriptionProductCharge__c();
		testZquSubscriptionProductCharge1.Name = 'Test Subscription Product Charge1';
		testZquSubscriptionProductCharge1.Zuora__EffectiveEndDate__c = Date.newinstance(2015, 9, 10);
		testZquSubscriptionProductCharge1.Zuora__Zuora_Id__c = 'zinrid12nd45oidl';
		testZquSubscriptionProductCharge1.Quote_Rate_Plan_ID__c = 'qweqweqwe';
		testZquSubscriptionProductCharge1.Zuora__RatePlanId__c = 'asdasdasdasdas';
		testZquSubscriptionProductCharge1.Zuora__Subscription__c = testZquSubscription1.id;
		testZquSubscriptionProductCharge1.Zuora__ProductName__c = 'Test Product';
		testZquSubscriptionProductCharge1.Zuora__RatePlanName__c = 'Test Product Rate Plan';
		testZquSubscriptionProductCharge1.Zuora__Product__c = testZuoraProduct.id;
		testZquSubscriptionProductCharge1.Zuora__Account__c = testAccount.id;
		insert testZquSubscriptionProductCharge1;
		
		SubscriptionBatchClass2 bb = new SubscriptionBatchClass2();
		Database.executeBatch(bb);
	}
}