src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_at_Last_Month_Start__c</fullName>
        <description>CSP-3159 Last AM Transfer Date
Total Value of &quot;Live&quot; items as of the first of the last month</description>
        <label>Live at Last Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Live_at_Month_Start__c</fullName>
        <description>Total Value of &quot;Live&quot; items as of the first of the current month</description>
        <label>Live at Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TotalContractValue__c</fullName>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCalculateLiveChargeTCVMonthlyTest.cls
@isTest
private class BatchCalculateLiveChargeTCVMonthlyTest {
    static testMethod void testBatch() {
    	Map<String,SObject> loacalData = TestClassUtility.buildLocalData(true);
      Account TestAcc = (Account)loacalData.get('Account');
      TestAcc.Last_AM_Transfer__c = system.today();
      TestAcc.Live_at_Last_Month_Start__c = 100;
      TestAcc.Live_at_Month_Start__c = 0;
      update TestAcc;

      Zuora__SubscriptionProductCharge__c charge = (Zuora__SubscriptionProductCharge__c)loacalData.get('Zuora__SubscriptionProductCharge__c');
      charge.Zuora__Account__c = TestAcc.id;
      charge.Zuora__TotalContractValue__c = 100;
      charge.Zuora__EffectiveStartDate__c = system.today().addDays(-7);
      charge.Zuora__EffectiveEndDate__c = system.today().addDays(7);
      update charge;
     
      Zuora__SubscriptionProductCharge__c charge2 = charge.clone();
      insert charge2;
      
      Test.startTest();
      	database.executebatch(new BatchCalculateLiveChargeTCVMonthly());
      Test.stopTest();

      account acc = [select id, Live_at_Month_Start__c from Account where id =: TestAcc.Id ];
      system.assert(acc.Live_at_Month_Start__c == 200.00);

    }
}