src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormant</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DE_Backlog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SS-4768</description>
        <label>DE Backlog</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Negative_Disposition_Reason__c</fullName>
        <label>Negative Disposition Reason</label>
        <picklist>
            <controllingField>Account_Status__c</controllingField>
            <picklistValues>
                <fullName>Bad Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Required Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Timeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not My Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Wedding Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Notify_Sales_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Notify_Sales_Team__c</fullName>
        <formula>Campaign.Notify_Sales_Team__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notify Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DE_Backlog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SS-4768</description>
        <label>DE Backlog</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Negative_Disposition_Reason__c</fullName>
        <description>csp-2440</description>
        <label>Negative Disposition Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Verify Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No contact information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor outside US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Timeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Claim Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Required Information</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CampaignMemberTriggerHandlerTest.cls
@isTest
private class CampaignMemberTriggerHandlerTest {
    static testMethod void testMethod1() {
        test.startTest();
            lead testLead = TestClassUtility.createLead(false);
            testLead.DE_Backlog__c = true;
            testLead.Negative_Disposition_Reason__c = 'Duplicate';
            testLead.Status = 'Invalid';
            testLead.Website  = 'www.theknot.com';
            insert testLead;

            Campaign testCam = new Campaign();
            testCam.Notify_Sales_Team__c = true;
            testCam.Type = 'Paid Media';
            testCam.Name = 'Test Campaign';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.LeadId = testLead.Id;
            // testCamMem.Name = 'test';
            insert testCamMem;

            update testCamMem;

            delete testCamMem;
        test.stopTest();
        
    }

    static testMethod void testMethod2() {
        test.startTest();
            Account testAcc = TestClassUtility.createAccount(false);
            testAcc.DE_Backlog__c = true;
            insert testAcc;

            Contact testCon = TestClassUtility.createContact(true, testAcc);

            Campaign testCam = new Campaign();
            testCam.Notify_Sales_Team__c = true;
            testCam.Name = 'Test Campaign';
            testCam.Type = 'Paid Media';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.ContactId = testCon.Id;
            // testCamMem.Name = 'test';
            insert testCamMem;

            update testCamMem;

            delete testCamMem;
        test.stopTest();
        
    }

    static testMethod void testMethod3() {
        test.startTest();
            lead testLead = TestClassUtility.createLead(false);
            testLead.Negative_Disposition_Reason__c = 'Duplicate';
            testLead.Status = 'Invalid';
            testLead.Website  = 'www.theknot.com';
            insert testLead;

            Campaign testCam = new Campaign();
            testCam.Type = 'Paid Media';
            testCam.Name = 'Test Campaign';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.LeadId = testLead.Id;
            // testCamMem.Name = 'test';
            insert testCamMem;

            update testCamMem;

            delete testCamMem;
        test.stopTest();
        
    }

    static testMethod void testMethod4() {
        test.startTest();
            lead testLead = TestClassUtility.createLead(false);
            testLead.DE_Backlog__c = true;
            testLead.Negative_Disposition_Reason__c = 'Duplicate';
            testLead.Status = 'Invalid';
            testLead.Website  = 'www.theknot.com';
            insert testLead;

            Campaign testCam = new Campaign();
            testCam.Notify_Sales_Team__c = true;
            testCam.Type = 'Other';
            testCam.Name = 'Test Campaign';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.LeadId = testLead.Id;
            // testCamMem.Name = 'test';
            insert testCamMem;

            update testCamMem;

            delete testCamMem;
        test.stopTest();
        
    }

    static testMethod void testMethod5() {
        test.startTest();
            Account testAcc = TestClassUtility.createAccount(false);
            testAcc.Account_Status__c = 'Qualified';
            testAcc.DE_Backlog__c = true;
            insert testAcc;
            Contact testCon = TestClassUtility.createContact(false, testAcc);
            testCon.FirstName = 'Siva';
            testCon.LastName = 'Vankadaru';
            insert testCon;

            Campaign testCam = new Campaign();
            testCam.Notify_Sales_Team__c = true;
            testCam.Name = 'Test Campaign';
            testCam.Status = 'Responded';
            testCam.Type = 'Internal Referral';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.ContactId = testCon.Id;
            testCamMem.Status = 'Responded';
            //testCamMem.HasResponded = true;
            // testCamMem.Name = 'test';
            insert testCamMem;

            update testCamMem;

            //Account camMemberAcc = testCamMem.Contact.Account;
            //camMemberAcc = CampaignMemberTriggerHandler.accOwnerAssignment(camMemberAcc);

            delete testCamMem;

        test.stopTest();
        
    }

    static testMethod void testMethod6() {
        test.startTest();
            Account testAcc = TestClassUtility.createAccount(false);
            testAcc.Account_Status__c = 'Qualified';
            testAcc.DE_Backlog__c = true;
            insert testAcc;

            Contact testCon = TestClassUtility.createContact(true, testAcc);

            Campaign testCam = new Campaign();
            testCam.Notify_Sales_Team__c = true;
            testCam.Name = 'Test Campaign';
            testCam.Type = 'Internal Referral';
            insert testCam;

            CampaignMember testCamMem = new CampaignMember();
            testCamMem.CampaignId = testCam.Id;
            testCamMem.ContactId = testCon.Id;
            // testCamMem.Name = 'test';
            insert testCamMem;

            testCamMem.Status = 'Responded';
            update testCamMem;

            delete testCamMem;
        test.stopTest();
        
    }


}