src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <description>Phase 1 of National</description>
        <label>National</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AccStrategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Phase 1 National</description>
        <label>Account Strategist</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Account Strategist</value>
            </filterItems>
            <filterItems>
                <field>User.Username</field>
                <operation>equals</operation>
                <value>naste@xogrp.com</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <businessProcess>Sales National</businessProcess>
        <description>Phase 1 National</description>
        <label>National</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <label>National</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ThoughtStarter_RFP__c.object
<CustomObject>
    <fields>
        <fullName>Account_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Account Strategist</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CTR__c</fullName>
        <label>CTR (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Clicks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clicks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Developer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Development</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ThoughtStarters_RFPs_SalesDev</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if you are ready to submit the ThoughtStarter/RFP for materials development</inlineHelpText>
        <label>Submitted for Production</label>
        <type>Checkbox</type>
    </fields>
    <label>ThoughtStarter / RFP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ThoughtStarters / RFPs</pluralLabel>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <label>RFP</label>
    </recordTypes>
    <recordTypes>
        <fullName>ThoughtStarter</fullName>
        <active>true</active>
        <label>ThoughtStarter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesDevAssignmentControllerTest.cls
@isTest 
private class SalesDevAssignmentControllerTest {
	
	@isTest static void test_method_one() {
		Set<String> stringTypes = new Set<String>{'PICKLIST', 'STRING', 'MULTIPICKLIST', 'TEXTAREA'};
		Set<String> numberTypes = new Set<String>{'CURRENCY', 'DOUBLE', 'INTEGER'};
		Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtOppMapByName = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtTSRFPMapByName = Schema.SObjectType.ThoughtStarter_RFP__c.getRecordTypeInfosByName();
		List<Schema.FieldSetMember> rfpFieldSetList = SObjectType.ThoughtStarter_RFP__c.FieldSets.Required_RFP_Fields.getFields();
		List<Schema.FieldSetMember> tsFieldSetList = SObjectType.ThoughtStarter_RFP__c.FieldSets.Required_ThoughtStarter_Fields.getFields();
		
		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
		Test.stopTest();

		Account testAccount = (Account)testObjects.get('Account');

		//Create your product
		Product2 prod = new Product2(
			Name = 'Uncategorized Revenue',
			ProductCode = 'Pro-X',
			isActive = true
		);
		insert prod;

		Id pricebookId = Test.getStandardPricebookId();

		//Create your pricebook entry
		PricebookEntry pbEntry = new PricebookEntry(
			Pricebook2Id = pricebookId,
			Product2Id = prod.Id,
			UnitPrice = 100.00,
			IsActive = true
		);
		insert pbEntry;

		List<Opportunity> newOpportunityList = new List<Opportunity>();
		for(Integer i = 0; i < 50; i++){
			Opportunity testOpportunity = new Opportunity();
			testOpportunity.Name = 'Test Opportunity';
			testOpportunity.RecordTypeId = rtOppMapByName.get('National').getRecordTypeId();
			testOpportunity.AccountId = testAccount.Id;
			testOpportunity.StageName = 'Prospecting';
			testOpportunity.CloseDate = date.today().addDays(5);
			testOpportunity.AccStrategist__c = UserInfo.getUserId();
			testOpportunity.Amount = 50000;
			testOpportunity.Description = 'test data for test class';
			newOpportunityList.add(testOpportunity);
		}
		insert newOpportunityList;

		List<ThoughtStarter_RFP__c> tsList = new List<ThoughtStarter_RFP__c>();
		for(Integer i = 0; i < 25; i++){
			ThoughtStarter_RFP__c newThoughtStarter = new ThoughtStarter_RFP__c();
			newThoughtStarter.Opportunity__c = newOpportunityList[i].Id;
			newThoughtStarter.RecordTypeId = rtTSRFPMapByName.get('ThoughtStarter').getRecordTypeId();
			newThoughtStarter.Clicks__c = true;
			newThoughtStarter.CTR__c = 2;
			newThoughtStarter.Submitted_for_Production__c = true;
			newThoughtStarter.Account_Strategist__c = newOpportunityList[i].AccStrategist__c;
			for(Schema.FieldSetMember record : tsFieldSetList){
				String typeValue = String.valueof(record.getType());
				String fieldPathValue = String.valueof(record.getFieldPath());

				if(stringTypes.contains(typeValue) == true){
					newThoughtStarter.put(fieldPathValue, 'Test Value');
				}else if(numberTypes.contains(typeValue) == true){
					newThoughtStarter.put(fieldPathValue, 500);
				}else if(typeValue == 'DATE'){
					newThoughtStarter.put(fieldPathValue, Date.today().addDays(5));
				}
			}
			tsList.add(newThoughtStarter);
		}
		system.debug(tsList);
		insert tsList;

		List<ThoughtStarter_RFP__c> rfpList = new List<ThoughtStarter_RFP__c>();
		for(Integer i = 0; i < 25; i++){
			ThoughtStarter_RFP__c newRFP = new ThoughtStarter_RFP__c();
			newRFP.Opportunity__c = newOpportunityList[i].Id;
			newRFP.RecordTypeId = rtTSRFPMapByName.get('RFP').getRecordTypeId();
			newRFP.Clicks__c = true;
			newRFP.CTR__c = 2;
			newRFP.Submitted_for_Production__c = true;
			newRFP.Account_Strategist__c = newOpportunityList[i].AccStrategist__c;
			for(Schema.FieldSetMember record : rfpFieldSetList){
				String typeValue = String.valueof(record.getType());
				String fieldPathValue = String.valueof(record.getFieldPath());

				if(stringTypes.contains(typeValue) == true){
					newRFP.put(fieldPathValue, 'Test Value');
				}else if(numberTypes.contains(typeValue) == true){
					newRFP.put(fieldPathValue, 500);
				}else if(typeValue == 'DATE'){
					newRFP.put(fieldPathValue, Date.today().addDays(5));
				}
			}
			rfpList.add(newRFP);
		}
		
		SalesDevAssignmentController contr = new SalesDevAssignmentController(new ApexPages.StandardController(new ThoughtStarter_RFP__c()));
		contr.getUnassignedTSRFP();
		contr.refresh();

		system.debug(contr.hasNext);
		system.debug(contr.hasPrevious);
		system.debug(contr.pageNumber);
		contr.last();
		contr.first();
		contr.next();
		contr.previous();

		contr.filterObject.recordType = 'RFP';
		contr.filterObject.nameValues = 'T';
		contr.filterObject.repStrat = 'A';
		contr.filterObject.salesDev = 'a';
		contr.filterResults();
		contr.refresh();

		Id salesDevId = [select Id from User where UserRole.DeveloperName = 'Sales_Development' limit 1].id;

		for(ThoughtStarter_RFP__c record : (List<ThoughtStarter_RFP__c>)contr.setCon.getRecords()){
			record.Sales_Developer__c = salesDevId;
		}

		contr.saveSalesDeveloper();
		
		list<selectOption> testSO = contr.getSortByList();
		
	}
	
}