src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Phase 1</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConciergePrgQua__c</fullName>
        <description>Phase 1</description>
        <label>Concierge program qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified from Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified for Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DynamicsAccID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Location ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DynamicsLeadID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Dynamics Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Used to hold Fulfillment Information received from Partners through the REST API</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operative_Owner__c</fullName>
        <label>Operative Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ConciergePrgQua__c</fullName>
        <description>Phase 1</description>
        <label>Concierge program qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified for Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified from Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DynamicsLeadID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Dynamics Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Fulfillment data received from Partners</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Local_Sales_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Local Sales Rep Assignment</label>
    <nameField>
        <label>Local Sales Rep Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Sales Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadParentAccountControllerTest.cls
@isTest
public class LeadParentAccountControllerTest{
	
	public static testMethod void test_method_one() {
		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		
		List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
		Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
	  
		
		Map<String, SObject> testLocalDate = TestClassUtility.buildLocalData(false);
		
		Test.startTest();
		

		Category__c testCategory = (Category__c)testLocalDate.get('Category__c');
		Market__c testMarket = (Market__c)testLocalDate.get('Market__c');
		// CSP-1999  Brand__c testBrand = (Brand__c)testLocalDate.get('Brand__c');
		Zip__c testzip = (Zip__c)testLocalDate.get('Zip__c');

		Local_Sales_Rep_Assignment__c testlsrp = TestClassUtility.createLocalSalesRepAssignment(false,
																								testCategory,
																								testMarket,
																								testzip);
		testlsrp.Market__c = null;
		insert testlsrp;
		// CSP-1999 
		// Lead testLead = TestClassUtility.createLead(false,testMarket,testCategory,testBrand); 
		Lead testLead = TestClassUtility.createLead(false,testMarket,testCategory); 
		testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
		testLead.DynamicsLeadID__c = 'testDynamicsLeadID';
		testLead.Fulfillment_Data__c = '{"tier":"tier", "marketCode":"marketCode", "categoryId":"categoryId", "parentGUID":"TestRestAPIDynamicsPartnerAcctUpdateScheduleTest"}';
		testLead.Status = 'Valid';
		testLead.PostalCode  = '12345';
		testLead.Country = 'United States';
		testLead.CountryCode = 'US';
		testLead.LeadSource= 'Other';
		testLead.City = 'New York';
		testLead.State= 'New York';
		testLead.Phone = '1234567890';
		insert testLead;
		
	  
		
		test.setCurrentPageReference(Page.LeadParentAccount);

		System.currentPageReference().getParameters().put('id',testLead.id);

		LeadParentAccountController testcase = new LeadParentAccountController(); 

		testLead.Status = 'Qualified';
		update testLead;
		LeadParentAccountController testcase1 = new LeadParentAccountController(); 

		testLead.PostalCode = '';
		update testLead;

		Test.stopTest();
	}


	public static testMethod void test_method_two() {
		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
		Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
		Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
		 
		
		Map<String, SObject> testLocalDate = TestClassUtility.buildLocalData(false);

		Test.startTest();

		Category__c testCategory = (Category__c)testLocalDate.get('Category__c');
		Market__c testMarket = (Market__c)testLocalDate.get('Market__c');
		// CSP-1999  Brand__c testBrand = (Brand__c)testLocalDate.get('Brand__c');
		Zip__c testzip = (Zip__c)testLocalDate.get('Zip__c');

		Local_Sales_Rep_Assignment__c testlsrp = TestClassUtility.createLocalSalesRepAssignment(false,
																								testCategory,
																								testMarket,
																								testzip);
		testlsrp.Market__c = null;
		insert testlsrp;

		Lead testLead = TestClassUtility.createLead(false,testMarket,testCategory); 
		testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
		testLead.DynamicsLeadID__c = 'testDynamicsLeadID';
		testLead.Fulfillment_Data__c = '{"tier":"tier", "marketCode":"marketCode", "categoryId":"categoryId", "parentGUID":"TestRestAPIDynamicsPartnerAcctUpdateScheduleTest"}';
		testLead.Status = 'Valid';
		testLead.PostalCode  = '12345';
		testLead.Country = 'United States';
		testLead.CountryCode = 'US';
		testLead.LeadSource= 'Other';
		testLead.City = 'New York';
		testLead.State= 'New York';
		testLead.Phone = '1234567890';
		insert testLead;

		LeadParentAccountController testcase2 = new LeadParentAccountController(); 
		// testcase1.saveParent();
		// testcase1.cancelConvert();
		
		Account testAccount = (Account)testLocalDate.get('Account');
		testAccount.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
		testAccount.BU__c = 'Local';
		testAccount.Type = 'Agency';
		testAccount.Operative_Owner__c = userList[0].Name;
		testAccount.ConciergePrgQua__c = 'In Program';
		testAccount.Type = 'Advertiser';
		testAccount.DynamicsAccID__c = 'TestRestAPIDynamicsPartnerAcctUpdateScheduleTest';
		update testAccount;
		
		
		LeadParentAccountController testcase3 = new LeadParentAccountController(); 
		testcase3.saveParent();

		testLead.PostalCode = '12345';
		testLead.Email = 'Test@test.com';
		testLead.FirstName = 'testfortest';
		testLead.LastName = 'testfortest';
		update testLead;
		testcase3.saveParent();
		testcase3.cancelConvert();

   	boolean testresult;
    testresult = LeadParentAccountController.fulfillStorefront(testLead);

    Test.stopTest();
	}
}