src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Phase 1</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DynamicsAccID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Location ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Phase 1 National</description>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/DefaulCBSSValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CSP-1128</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>DefaultCBSSValues</label>
</CustomObject>

src/objects/Generate_Quote_Pdf_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generate Quote Pdf Config</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountContactRoleSyncTest.cls
@isTest     
private class AccountContactRoleSyncTest {
  @isTest static void checkPrimarySync() {
      DefaulCBSSValues__c defCBSScustomSetting = new DefaulCBSSValues__c();
      defCBSScustomSetting.Name = 'InvoiceTemplate';
      defCBSScustomSetting.Phone__c = '(800)843-4983';
      defCBSScustomSetting.Email__c = 'theknotaccounting@xogrp.com';
      insert defCBSScustomSetting;

      Deactivate_Trigger__c dtTrigger = TestClassUtility.createNotesDeactivateTriggerSetting(true);
      Generate_Quote_Pdf_Config__c gcr = TestClassUtility.generateQuotePdfConfig(true);
      
      Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();

      // CSP-1999
      // Map<String,Schema.RecordTypeInfo> rtBrandMapByName = Schema.SObjectType.Brand__c.getRecordTypeInfosByName();
      // Brand__c brand = TestClassUtility.createBrand(false);
      // brand.RecordTypeId = rtBrandMapByName.get('Local').getRecordTypeId();
      // insert brand;
      // Category__c category = TestClassUtility.createCategory(true,brand);
      Category__c category = TestClassUtility.createCategory(true);
      
      Market__c market = TestClassUtility.createMarket(false);
      market.Market_ID__c ='222';
      insert market;
      
      Zip__c zipCode = TestClassUtility.createZip(true);
      
      // CSP-1999
      // Account testAccount = TestClassUtility.createAccount(false,brand,category,market);
      Account testAccount = TestClassUtility.createAccount(false,category,market);
      testAccount.Type = 'Advertiser';
      testAccount.DynamicsAccID__c = 'testDynamicsLeadID';
      testAccount.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
      testAccount.BU__c = 'Local';
      insert testAccount; 

      Contact testContact = TestClassUtility.createContact(true, testAccount);
      
      AccountContactRole acr = TestClassUtility.createAccountContactRole(true,testAccount,testContact);  
      
      Opportunity opp = TestClassUtility.createOpportunity(true,testAccount);
      
      Test.startTest();
        AccountContactRoleSync roleSync = new AccountContactRoleSync(System.Today().addDays(-1),'Primary');
        Database.executeBatch(roleSync);        
      Test.stopTest();        

      Contact testCon = [SELECT id,name,Primary__c FROM Contact WHERE id =: testContact.id];
      System.assertEquals(testCon.Primary__c,true);
  }
}