src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>text(Primary_Category__r.Category_Group__c)</formula>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SubCategory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>text(Primary_Category__r.Category_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select active Markets within the Primary Brand</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select an active Category</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecordAssignmentControllerTest.cls
// 94% - 08/22/2016
@isTest
private class RecordAssignmentControllerTest {
	
	@isTest static void controllerTest() {
    // Get object filters for known objects
  	RecordAssignmentController.getObjectFilters('Lead', true);
    RecordAssignmentController.getObjectFilters('Account', false);

    // Get object filters for fake object(failure)
    RecordAssignmentController.getObjectFilters('Not_Real_Object__c', false);

    // Correct format
    RecordAssignmentController.getInputQueryData('Lead', 'Local_Sales_Market__c', 'Something', false);

    // Correct format - OwnerId field AND only active users
    RecordAssignmentController.getInputQueryData('Lead', 'OwnerId', 'Something', true);

    // Sending a null value
    RecordAssignmentController.getInputQueryData(null, 'Local_Sales_Market__c', 'Something', false);

    // Get user information - use current running user
    RecordAssignmentController.getUserInformation(UserInfo.getUserId());

    // Get user information sending a null value
    RecordAssignmentController.getUserInformation(null);

    // Query with filter and object - filter is JSON representation of javascript object
    RecordAssignmentController.queryWithFilters('{"checkbox":{"Owner.IsActive":[{"userInput":"true","include":true}]},"picklist":{"Primary_Category__c":[{"userInput":"a3Uj0000000fy8qEAA","include":true}]}}', 'Lead');

    // Query with filter and object both being null
    RecordAssignmentController.queryWithFilters(null, null);

    Market__c testMarket = new Market__c();
    testMarket.Name = 'Test Market';
    testMarket.Market_ID__c = '222';
    testMarket.Short_Description__c = 'Nothing';
    insert testMarket;

    Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
    Category__c testCategory = TestClassUtility.createCategory(false);
    testCategory.RecordTypeId = rtCategoryMapByName.get('Local').getRecordTypeId();
    testCategory.Category_Group__c = 'Primary';
    insert testCategory;

    Lead testLead = TestClassUtility.createLead(false,testMarket,testCategory);
    insert testLead;

    // Assign Records
    RecordAssignmentController.assignOwner(new List<String>{testLead.Id}, UserInfo.getUserId(), 'Lead');

    // Fail Assignment
    RecordAssignmentController.assignOwner(new List<String>{testLead.Id}, 'sfafasfaf', 'Lead');

    // Assign Records - null values
    RecordAssignmentController.assignOwner(null, null, null);
 
    // Instantiate Objects
    new RecordAssignmentController.FieldResponse();
    new RecordAssignmentController.FieldOptions();
    new RecordAssignmentController.UpdateFailure();
	}
}