src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>Phase 1 National</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Need_to_Recalculate_Active_Hierarchy__c</fullName>
        <label>Need to Recalculate Active Hierarchy</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Plan to Deprecated for CSP-2731
Phase 1</description>
        <label>Region</label>
        <picklist>
            <controllingField>ConciergeState__c</controllingField>
            <picklistValues>
                <fullName>Appalachian Plateau</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlanta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Suburb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Suburbs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central East FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Pittsburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Valley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central West FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chesapeake Bay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal Plain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>​Dallas/Fort Worth​</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerHandlerAccess__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Handler_Name__c</fullName>
        <label>Handler Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TriggerHandlerAccess</label>
</CustomObject>

src/classes/BatchAccountAcitveHierarchyTest.cls
@isTest
private class BatchAccountAcitveHierarchyTest {
    static testMethod void testMethod1() {
    		
    		Test.startTest();
    	  Map<String,SObject> testMap = TestClassUtility.buildLocalData(false);
    	  System.debug(LoggingLevel.INFO, '*** Limits.getQueries(): ' + Limits.getQueries());
    	  Test.stopTest();
    	 
    	  Account testAccount = (Account)testMap.get('Account');
    	  testAccount.Need_to_Recalculate_Active_Hierarchy__c = 'Yes';
    	  update testAccount;

    	  BatchAccountAcitveHierarchy bat = new BatchAccountAcitveHierarchy();
    	  Database.executeBatch(bat);
    	 
    }

    static testMethod void testMethod2() {
    		
				Map<String,Schema.RecordTypeInfo> rtAccountMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();

				Category__c testCategory = TestClassUtility.createCategory(true);
				Region__c testRegion = TestClassUtility.createRegion(true);
				Market__c testMarket = TestClassUtility.createMarket(true, testRegion);

    	  Account testAccount = TestClassUtility.createAccount(false, testCategory, testMarket);
    	  testAccount.Need_to_Recalculate_Active_Hierarchy__c = 'Yes';
    	  testAccount.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  insert testAccount;

    	  Account testAccount2 = TestClassUtility.createAccount(false, testCategory, testMarket);
    	  testAccount2.Need_to_Recalculate_Active_Hierarchy__c = 'Yes';
    	  testAccount2.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount2.ParentId = testAccount.Id;
    	  insert testAccount2;

				Test.startTest();
    	  BatchAccountAcitveHierarchy bat = new BatchAccountAcitveHierarchy();
    	  Database.executeBatch(bat,10);

    	  Test.stopTest();

    }

    static testMethod void testMethod3() {
    		
				Map<String,Schema.RecordTypeInfo> rtAccountMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();

				TriggerHandlerAccess__c newTHA = new TriggerHandlerAccess__c();
        newTHA.Name = 'AccountTriggerHandler';
        newTHA.Active__c = false;
        newTHA.Handler_Name__c = 'AccountTriggerHandler';
        newTHA.Object__c = 'Account';
        insert 	newTHA;	

				Category__c testCategory = TestClassUtility.createCategory(true);
				Region__c testRegion = TestClassUtility.createRegion(true);
				Market__c testMarket = TestClassUtility.createMarket(true, testRegion);

    	  Account testAccount = TestClassUtility.createAccount(false);
    	  testAccount.Need_to_Recalculate_Active_Hierarchy__c = 'No';
    	  testAccount.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount.ParentId = null;
    	  insert testAccount;

    	  Account testAccount2 = TestClassUtility.createAccount(false);
    	  testAccount2.Need_to_Recalculate_Active_Hierarchy__c = 'No';
    	  testAccount2.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount2.ParentId = testAccount.Id;
    	  insert testAccount2;


    	  Account testAccount3 = TestClassUtility.createAccount(false);
    	  testAccount3.Need_to_Recalculate_Active_Hierarchy__c = 'Yes';
    	  testAccount3.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount3.ParentId = testAccount2.Id;
    	  insert testAccount3;

				Test.startTest();
    	  BatchAccountAcitveHierarchy bat = new BatchAccountAcitveHierarchy();
    	  Database.executeBatch(bat,10);

    	  Test.stopTest();

    }

   static testMethod void testMethod4() {
    		
				Map<String,Schema.RecordTypeInfo> rtAccountMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();

				TriggerHandlerAccess__c newTHA = new TriggerHandlerAccess__c();
        newTHA.Name = 'AccountTriggerHandler';
        newTHA.Active__c = false;
        newTHA.Handler_Name__c = 'AccountTriggerHandler';
        newTHA.Object__c = 'Account';
        insert 	newTHA;	

				Category__c testCategory = TestClassUtility.createCategory(true);
				Region__c testRegion = TestClassUtility.createRegion(true);
				Market__c testMarket = TestClassUtility.createMarket(true, testRegion);

    	  Account testAccount = TestClassUtility.createAccount(false);
    	  testAccount.Need_to_Recalculate_Active_Hierarchy__c = 'No';
    	  testAccount.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount.ParentId = null;
    	  insert testAccount;

    	  Account testAccount2 = TestClassUtility.createAccount(false);
    	  testAccount2.Need_to_Recalculate_Active_Hierarchy__c = 'No';
    	  testAccount2.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount2.ParentId = testAccount.Id;
    	  insert testAccount2;


    	  Account testAccount3 = TestClassUtility.createAccount(false);
    	  testAccount3.Need_to_Recalculate_Active_Hierarchy__c = 'No';
    	  testAccount3.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount3.ParentId = testAccount2.Id;
    	  insert testAccount3;


    	  Account testAccount4 = TestClassUtility.createAccount(false);
    	  testAccount4.Need_to_Recalculate_Active_Hierarchy__c = 'Yes';
    	  testAccount4.RecordTypeId = rtAccountMapByName.get('Local').getRecordTypeId();
    	  testAccount4.ParentId = testAccount3.Id;
    	  insert testAccount4;

				Test.startTest();
    	  BatchAccountAcitveHierarchy bat = new BatchAccountAcitveHierarchy();
    	  Database.executeBatch(bat,10);

    	  Test.stopTest();

    }

}