src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Card_Declined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Card Declined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_on_Payment_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box to identify whether a customer is on Payment Arrangement or not.</description>
        <label>Customer on Payment Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Used to hold Fulfillment Information received from Partners through the REST API</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <description>Plan to Deprecated for CSP-2731
SF-613</description>
        <label>Local Paid Status(deprecated)</label>
        <picklist>
            <picklistValues>
                <fullName>Unpaid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Plan to Deprecated for CSP-2731
Phase 1</description>
        <label>Region</label>
        <picklist>
            <controllingField>ConciergeState__c</controllingField>
            <picklistValues>
                <fullName>Appalachian Plateau</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlanta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Suburb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Suburbs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central East FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Pittsburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Valley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central West FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chesapeake Bay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal Plain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>​Dallas/Fort Worth​</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field will hold the lookup relationship for the Bill To Contact that is being used to sync Bill To information to Zuora.</description>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To Billing Accounts</relationshipLabel>
        <relationshipName>Bill_To_Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <label>Default Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>CC_Failure_Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CC Failure Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default payment method or not</description>
        <inlineHelpText>Default payment method or not</inlineHelpText>
        <label>Default Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__NumConsecutiveFailures__c</fullName>
        <label>Number of Consecutive Failures</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchNotifyPaymentMethodExpirationTest.cls
/*
  Class(es) Tested:
    BatchNotifyPaymentMethodExpiration
 */
@isTest
private class BatchNotifyPaymentMethodExpirationTest {
    
  @isTest static void test_method_one() {
    // Implement test code
    Test.startTest();
    
      Map<String, Object> nationTestData = TestClassUtility.buildNationalData();
      
      BatchNotifyPaymentMthdExpScheduledJob job = new BatchNotifyPaymentMthdExpScheduledJob();
      String sch = '0 1 0 * * ?';
      System.schedule('Test BatchNotifyPaymentMethodExpirationTest Job', sch, job);
    
    Test.stopTest();
  }
 
  @isTest static void test_method_two() {

    // Region__c testRegion = TestClassUtility.createRegion(true);
    // Category__c testCategory = TestClassUtility.createCategory(true);
    // Market__c testMarket = TestClassUtility.createMarket(true, testRegion);
    // Account testAcc = TestClassUtility.createAccount(true, testCategory, testMarket);
    // Zuora__CustomerAccount__c testCustomerAcc = TestClassUtility.createCustomerAccount(true, testAcc);
    // Zuora__PaymentMethod__c testPaymentMethod = TestClassUtility.createPaymentMethod(true, testCustomerAcc);    
    
    Test.startTest();
    Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
    Test.stopTest();

    Account testAccount = (Account)testLocalData.get('Account');
    testAccount.Local_Paid_Status__c = 'Paid';
    testAccount.Card_Declined__c = true;
    testAccount.Customer_on_Payment_Arrangement__c = false;
    update testAccount;


    // Deactivate_Trigger__c dtNote = TestClassUtility.createNotesDeactivateTriggerSetting(false);
    // dtNote.After_Delete__c = false;
    // dtNote.After_Insert__c = false;
    // dtNote.After_Update__c = false;
    // dtNote.Before_Delete__c = false;
    // dtNote.Before_Insert__c = false;
    // dtNote.Before_Update__c = false;
    // insert dtNote; 

    // testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
    // update testAccount;
    
    Zuora__CustomerAccount__c testZuoraCustomerAccount = (Zuora__CustomerAccount__c)testLocalData.get('Zuora__CustomerAccount__c');

    Zuora__PaymentMethod__c testPaymentMthd = TestClassUtility.createPaymentMethod(false,testZuoraCustomerAccount);
    testPaymentMthd.CC_Failure_Notification_Sent__c = false;
    testPaymentMthd.Zuora__NumConsecutiveFailures__c = 3;
    testPaymentMthd.Zuora__DefaultPaymentMethod__c = true;
    insert testPaymentMthd;

    // List<Zuora__PaymentMethod__c> updatezpmlist = new List<Zuora__PaymentMethod__c>();
    // updatezpmlist.add(testPaymentMthd);

    // insert updatezpmlist;

    BatchNotifyPaymentMethodExpiration bt = new BatchNotifyPaymentMethodExpiration();
    Database.executeBatch(bt, 1);
    
    
  }

  @isTest static void test_method_three() {
  
    Test.startTest();
    Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
    Test.stopTest();

    Account testAccount = (Account)testLocalData.get('Account');
    testAccount.Local_Paid_Status__c = 'Paid';
    testAccount.Card_Declined__c = true;
    testAccount.Customer_on_Payment_Arrangement__c = false;
    update testAccount;

    Contact testContact = (Contact)testLocalData.get('Contact');

    Zuora__CustomerAccount__c testZuoraCustomerAccount = (Zuora__CustomerAccount__c)testLocalData.get('Zuora__CustomerAccount__c');
    testZuoraCustomerAccount.Bill_To_Contact__c = testContact.Id;
    update testZuoraCustomerAccount;

    Zuora__PaymentMethod__c testPaymentMthd = TestClassUtility.createPaymentMethod(false,testZuoraCustomerAccount);
    testPaymentMthd.CC_Failure_Notification_Sent__c = false;
    testPaymentMthd.Zuora__NumConsecutiveFailures__c = 3;
    testPaymentMthd.Zuora__DefaultPaymentMethod__c = true;
    insert testPaymentMthd;


    BatchNotifyPaymentMethodExpiration bt = new BatchNotifyPaymentMethodExpiration();
    Database.executeBatch(bt, 1);
    
    
  }

  // @isTest static void test_method_three() {

  //   List<Account> accountList = new List<Account>();
  //   List<Zuora__CustomerAccount__c> zuoraCustomerAccountList = new List<Zuora__CustomerAccount__c>();
  //   List<Zuora__PaymentMethod__c> zpmlist = new List<Zuora__PaymentMethod__c>();

  //   Region__c testRegion = TestClassUtility.createRegion(true);
  //   Category__c testCategory = TestClassUtility.createCategory(true);
  //   Market__c testMarket = TestClassUtility.createMarket(true, testRegion);

  //   Test.startTest();

  //   for(Integer i=0; i<7; i++){
  //     Account testAccount = TestClassUtility.createAccount(false, testCategory, testMarket); 
  //     testAccount.Local_Paid_Status__c = 'Paid';
  //     testAccount.Card_Declined__c = true;
  //     testAccount.Customer_on_Payment_Arrangement__c = false;
  //     System.debug(LoggingLevel.INFO, '*** testAccount: ' + testAccount);

  //     accountList.add(testAccount);
  //   }
  //   insert accountList;


  //   for(Integer j=0; j<7; j++){
  //     Zuora__CustomerAccount__c testZuoraCustomerAccount = TestClassUtility.createCustomerAccount(false, accountList[j]);
      
  //     zuoraCustomerAccountList.add(testZuoraCustomerAccount);
  //   }
  //   insert zuoraCustomerAccountList;

    
  //   for(Integer k=0; k<7; k++){
  //     Zuora__PaymentMethod__c testPaymentMthd = TestClassUtility.createPaymentMethod(false, zuoraCustomerAccountList[k]); 
  //     testPaymentMthd.CC_Failure_Notification_Sent__c = false;
  //     testPaymentMthd.Zuora__NumConsecutiveFailures__c = 3;
  //     testPaymentMthd.Zuora__DefaultPaymentMethod__c = true;

  //     zpmlist.add(testPaymentMthd);
  //   }
  //   insert zpmlist;       
    
  //   Test.stopTest();


  //   BatchNotifyPaymentMethodExpiration bt = new BatchNotifyPaymentMethodExpiration();
  //   Database.executeBatch(bt, 10);
    

    
  // }  
}