src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <externalId>true</externalId>
        <label>Category Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <fields>
        <fullName>ZipCode__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code (External ID)</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchUpdateAcctMarketSaleabilityTest.cls
@isTest
private class BatchUpdateAcctMarketSaleabilityTest {

    //Comment by CSP-2712 Decommission Marketplace Health code
    // static testMethod void testMethod1() {
    //     Test.startTest();

    //     	Zip__c testZip = TestClassUtility.createzip(true);

    //     	Category__c testCategory = TestClassUtility.createCategory(false);
    //     	testCategory.Category_Code__c = 'ACC';
    //     	insert testCategory;

	   //      Account testAcct = TestClassUtility.createAccount(false);
	   //      testAcct.BillingPostalCode = testZip.ZipCode__c;
	   //      testAcct.Primary_Category__c = testCategory.id;
	   //      insert testAcct;

	   //      Marketplace_Health__c  testMS = new Marketplace_Health__c();
	   //      testMS.Category__c = testCategory.Id;
	   //      testMS.Zip__c = testZip.Id;
	   //      testMS.External_Key__c = testZip.ZipCode__c + testCategory.Category_Code__c;
	   //      insert testMS;

    //     	//Excute batch for update account market saleability 
    //     	BatchUpdateAcctMarketSaleability cls = new BatchUpdateAcctMarketSaleability();
    //     	Database.executeBatch(cls,2000);


    //     Test.stopTest();
    // }
}