src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Generate_Quote_Pdf_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generate Quote Pdf Config</label>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lost_Reason_Details__c</fullName>
        <label>Lost Reason Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <inlineHelpText>Select the primary reason that the Opportunity was lost</inlineHelpText>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Advertises w/a competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Already Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel/ Re-enter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact not responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of non-payment terms and conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of payment terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not contact again</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improperly Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue w/T&amp;Cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Client Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer doing weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason Given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Issue/Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Issue/Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhappy w/Results</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__CommunicationProfile__c.object
<CustomObject>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id of this Communication Profile.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id of this Communication Profile.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Communication Profile</label>
    <nameField>
        <label>Communication Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__CommunicationProfile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication Profile</label>
        <referenceTo>zqu__CommunicationProfile__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__BillCycleDay__c</fullName>
        <description>Indicates the charge&apos;s billing cycle day (BCD), which is when bill runs generate invoices for charges associated with the product rate plan charge or the account.</description>
        <label>Bill Cycle Day</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuora__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraSubscriptionUtilityTest.cls
@isTest
private class ZuoraSubscriptionUtilityTest {
	@isTest 
	static void testGenerateRenewalQuoteFromSubcription_one() {
		/////////////////////
		// BUILD TEST DATA //
		/////////////////////
		Test.startTest();
		
		Generate_Quote_Pdf_Config__c gqpc = TestClassUtility.generateQuotePdfConfig(true);

    Account testAccount = TestClassUtility.createAccount(true);

    Contact testContact = TestClassUtility.createContact(true, testAccount);

    Zuora__CustomerAccount__c testCustomerAccount = TestClassUtility.createCustomerAccount(false);
    testCustomerAccount.Zuora__BillCycleDay__c = '10';
    insert testCustomerAccount;

    Opportunity testOpportunity = TestClassUtility.createOpportunity(false, testAccount, testContact);
    testOpportunity.Lost_Reason__c = 'Some Reason';
    testOpportunity.Lost_Reason_Details__c = 'Something';
    insert testOpportunity;

		TestClassUtility.generateInventoryExpireDateOffsets(true);
    
		TestClassUtility.createQuoteTemplate(true);

		Test.stopTest();

    zqu__Quote__c testQuote = TestClassUtility.createQuote(true, testOpportunity, testAccount, testContact);

    Zuora__ZInvoice__c testInvoice = TestClassUtility.createInvoice(true, testAccount, testCustomerAccount);

    Product2 testLocalProduct = TestClassUtility.createLocalProduct2(true);
		
    zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true, testLocalProduct);

    zqu__ProductRatePlanCharge__c testProductRatePlanCharge = TestClassUtility.createProductRatePlanCharge(true, testProductRatePlan);
    
    Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(true, testAccount);

    Zuora__Product__c testZuoraProduct = TestClassUtility.createZuoraProduct(true);

    Inventory__c testInventory = TestClassUtility.createInventory(true, testProductRatePlan);

    zqu__CommunicationProfile__c testzquCP =new zqu__CommunicationProfile__c();
    testzquCP.name = 'Default Profile';
    testzquCP.zqu__ZuoraId__c = '2c92c0f94e4d3a41014e655c389b63cp';
    insert testzquCP;

    Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge1 = TestClassUtility.createSubscriptionProductCharge(true, testAccount, testSubscription, testZuoraProduct);

		zqu__Quote__c generatedQuote = ZuoraSubscriptionUtility.generateRenewalQuoteFromSubscription(testSubscription.Id, testOpportunity);
	}

	@isTest 
	static void testGenerateRenewalQuoteFromSubcription_two() {
		/////////////////////
		// BUILD TEST DATA //
		/////////////////////
		Test.startTest();
		
		Generate_Quote_Pdf_Config__c gqpc = TestClassUtility.generateQuotePdfConfig(true);

    Account testAccount = TestClassUtility.createAccount(true);

    Contact testContact = TestClassUtility.createContact(true, testAccount);

    Zuora__CustomerAccount__c testCustomerAccount = TestClassUtility.createCustomerAccount(false);
    testCustomerAccount.Zuora__BillCycleDay__c = '10';
    insert testCustomerAccount;

    Opportunity testOpportunity = TestClassUtility.createOpportunity(false, testAccount, testContact);
    testOpportunity.Lost_Reason__c = 'Some Reason';
    testOpportunity.Lost_Reason_Details__c = 'Something';
    insert testOpportunity;

		TestClassUtility.generateInventoryExpireDateOffsets(true);
    
		TestClassUtility.createQuoteTemplate(true);

		Test.stopTest();

    zqu__Quote__c testQuote = TestClassUtility.createQuote(true, testOpportunity, testAccount, testContact);

    Zuora__ZInvoice__c testInvoice = TestClassUtility.createInvoice(true, testAccount, testCustomerAccount);

    Product2 testLocalProduct = TestClassUtility.createLocalProduct2(true);
		
    zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true, testLocalProduct);

    zqu__ProductRatePlanCharge__c testProductRatePlanCharge = TestClassUtility.createProductRatePlanCharge(true, testProductRatePlan);
    
    Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false, testAccount);
    testSubscription.Zuora__CustomerAccount__c = testCustomerAccount.Id;
    insert testSubscription;

    Zuora__Product__c testZuoraProduct = TestClassUtility.createZuoraProduct(true);

    Inventory__c testInventory = TestClassUtility.createInventory(true, testProductRatePlan);

    zqu__CommunicationProfile__c testzquCP =new zqu__CommunicationProfile__c();
    testzquCP.name = 'Default Profile';
    testzquCP.zqu__ZuoraId__c = '2c92c0f94e4d3a41014e655c389b63cp';
    insert testzquCP;

    List<Zuora__SubscriptionProductCharge__c> zspclist = new  List<Zuora__SubscriptionProductCharge__c> ();

    // Create Subscription Product Charge
    Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge1 = TestClassUtility.createSubscriptionProductCharge(false, testAccount, testSubscription, testZuoraProduct);
		// Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge2 = TestClassUtility.createSubscriptionProductCharge(false, testAccount, testSubscription, testZuoraProduct);
		// Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge3 = TestClassUtility.createSubscriptionProductCharge(false, testAccount, testSubscription, testZuoraProduct);
		// Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge4 = TestClassUtility.createSubscriptionProductCharge(false, testAccount, testSubscription, testZuoraProduct);

		zspclist.add(testSubscriptionProductCharge1);
		// zspclist.add(testSubscriptionProductCharge2);
		// zspclist.add(testSubscriptionProductCharge3);
		// zspclist.add(testSubscriptionProductCharge4);

		insert zspclist;


		zqu__Quote__c generatedQuote = ZuoraSubscriptionUtility.generateRenewalQuoteFromSubscription(testSubscription.Id, testOpportunity);
	}
	

	@isTest
	static void testGenerateRenewalQuoteFromSubscriptionBatch() {
		/////////////////////
		// BUILD TEST DATA //
		/////////////////////
		Test.startTest();
			Map<String, SObject> subData = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		subData.putAll(TestClassUtility.buildSubscriptionData((Account)subData.get('Account'), (Contact)subData.get('Contact'), (Opportunity)subData.get('Opportunity'), (Zuora__CustomerAccount__c)subData.get('Zuora__CustomerAccount__c')));

		// Get Subscription to send Id
		Zuora__Subscription__c createdSubscription = (Zuora__Subscription__c)subData.get('Zuora__Subscription__c');

		// Get Opportunity to send Id
		Opportunity createdOpportunity = (Opportunity)subData.get('Opportunity');

		Database.executeBatch(new BatchGenerateQuoteRatePlans(createdSubscription.Id, createdOpportunity), 1);
	}
}