src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Phase 1</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operative_Owner__c</fullName>
        <label>Operative Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partners_SalesProfile__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Partners SalesProfiles</relationshipLabel>
        <relationshipName>Partners_SalesProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Account Location record</inlineHelpText>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners SalesProfiles</relationshipLabel>
        <relationshipName>Partners_SalesProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Partners SalesProfiles</relationshipLabel>
        <relationshipName>Partners_SalesProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partners_SalesProfile_GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Partners SalesProfile GUID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Freemium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Partners SalesProfile</label>
    <nameField>
        <label>Partners SalesProfile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners SalesProfiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <fields>
        <fullName>ZipCode__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code (External ID)</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testPartnersSalesProfileTrigger.cls
@isTest
private class testPartnersSalesProfileTrigger{
    @isTest static void test_method_one() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
        Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Deactivate_Trigger__c dtNote =  TestClassUtility.createNotesDeactivateTriggerSetting(true);

        Account testAccount = (Account)testData.get('Account');
        Zip__c testZip = (Zip__c)testData.get('Zip__c');
        Market__c testMarket = (Market__c)testData.get('Market__c');
        Category__c testCategory = (Category__c)testData.get('Category__c');
        // CSP-1999 Brand__c testBrand = (Brand__c)testData.get('Brand__c');

        dtNote.After_Delete__c = false;
        dtNote.After_Insert__c = false;
        dtNote.After_Update__c = false;
        dtNote.Before_Delete__c = false;
        dtNote.Before_Insert__c = false;
        dtNote.Before_Update__c = false;
        Update dtNote; 
        
        // Implement test code
        
            Account testAccount1 = new Account();
            testAccount1.Name = 'wakeinthemorningandistepoutside';
            testAccount1.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
            testAccount1.BU__c = 'Local';
            testAccount1.Website = 'www.asdfdgoosadfadsfgladfadfe.com';
            testAccount1.Type = 'Agency';
            testAccount1.BillingCountry = 'United States';
            testAccount1.BillingState = 'Alaska';
            testAccount1.BillingCity = 'US2';
            testAccount1.BillingStreet = 'US3';
            testAccount1.BillingPostalCode = testZip.zipcode__c;
            testAccount1.Operative_Owner__c = userList[0].Name;
            testAccount1.parentId = testAccount.id;
            // CSP-1999 testAccount1.Primary_Brand__c = testBrand.id;
            testAccount1.Primary_Category__c = testCategory.id;
            testAccount1.Local_Sales_Market__c = testMarket.id;
            insert testAccount1;
            
            Partners_SalesProfile__c testpsp = new Partners_SalesProfile__c();
            testpsp.Name = 'test name';
            testpsp.Tier__c = 'Freemium';
            testpsp.Location__c = testAccount1.id;
            testpsp.Partners_SalesProfile_GUID__c ='testPartners_SalesProfile_GUID1';
            insert testpsp;
            
            
            PartnersSalesProfileTriggerHandler testPSPTH = new PartnersSalesProfileTriggerHandler();
            testPSPTH.bulkBefore();
            testPSPTH.beforeInsert(testpsp);
            testPSPTH.beforeUpdate(testpsp,testpsp);
            testPSPTH.beforeDelete(testpsp);
            testPSPTH.afterDelete(testpsp);
        
    }
    
    @isTest static void test_method_Two() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
        Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Deactivate_Trigger__c dtNote =  TestClassUtility.createNotesDeactivateTriggerSetting(true);
        Account testAccount = (Account)testData.get('Account');
        Zip__c testZip = (Zip__c)testData.get('Zip__c');
        Market__c testMarket = (Market__c)testData.get('Market__c');
        Category__c testCategory = (Category__c)testData.get('Category__c');
        // CSP-1999 Brand__c testBrand = (Brand__c)testData.get('Brand__c');

        dtNote.After_Delete__c = false;
        dtNote.After_Insert__c = false;
        dtNote.After_Update__c = false;
        dtNote.Before_Delete__c = false;
        dtNote.Before_Insert__c = false;
        dtNote.Before_Update__c = false;
        Update dtNote; 
        
        // Implement test code
        
            Account testAccount1 = new Account();
            testAccount1.Name = 'anditakeadeepbreathWHATSGOINGON';
            testAccount1.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
            testAccount1.BU__c = 'Local';
            testAccount1.Website = 'www.sadfadsfadsfdsafgadsfdasfoogle.com';
            testAccount1.Type = 'Agency';
            testAccount1.BillingCountry = 'United States';
            testAccount1.BillingState = 'Alaska';
            testAccount1.BillingCity = 'US2';
            testAccount1.BillingStreet = 'US3';
            testAccount1.BillingPostalCode = testZip.zipcode__c;
            testAccount1.Operative_Owner__c = userList[0].Name;
            testAccount1.parentId = testAccount.id;
            testAccount1.ProductType__c = 'Internet';
            // CSP-1999 testAccount1.Primary_Brand__c = testBrand.id;
            testAccount1.Primary_Category__c = testCategory.id;
            testAccount1.Local_Sales_Market__c = testMarket.id;
            insert testAccount1;
            
            Partners_SalesProfile__c testpsp = new Partners_SalesProfile__c();
            testpsp.Name = 'test name';
            testpsp.Tier__c = 'Freemium';
            testpsp.Location__c = testAccount1.id;
            testpsp.Partners_SalesProfile_GUID__c ='testPartners_SalesProfile_GUID1';
            insert testpsp;
            
            
            
            testpsp.Tier__c = 'Standard';
            update testpsp;
            
            
            Partners_SalesProfile__c testpsp1 = new Partners_SalesProfile__c();
            testpsp1.Name = 'test name1';
            testpsp1.Tier__c = 'Freemium';
            testpsp1.Location__c = testAccount1.id;
            testpsp1.Partners_SalesProfile_GUID__c ='testPartners_SalesProfile_GUID';
            insert testpsp1;
            
            testAccount1.ProductType__c = 'Internet';
            update testAccount1;
            testpsp.Tier__c = 'Standard1';
            update testpsp;
            
            testAccount1.ProductType__c = '';
            update testAccount1;
            testpsp.Tier__c = 'Standard';
            update testpsp;
        
         
    }
    
    
}