src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assignment_History__c.object
<CustomObject>
    <description>CSP-1851 | this object is used to track the history of how Lead/Account assignment rules are assigning records to users</description>
    <fields>
        <fullName>Local_Sales_Rep_Assignment__c</fullName>
        <description>CSP-1851</description>
        <label>Local Sales Rep Assignment</label>
        <referenceTo>Local_Sales_Rep_Assignment__c</referenceTo>
        <relationshipLabel>Assignment History</relationshipLabel>
        <relationshipName>Assignment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assignment History</label>
    <nameField>
        <displayFormat>AH-{0000000000}</displayFormat>
        <label>Assignment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Sales_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zip Code</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Local Sales Rep Assignment</label>
    <nameField>
        <label>Local Sales Rep Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Sales Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchAssignmentHistoryUpdateTest.cls
@isTest
private class BatchAssignmentHistoryUpdateTest {
    @isTest 
    static void setup() {
    	Account testAcc = TestClassUtility.createAccount(true);

    	Category__c testCat = TestClassUtility.createCategory(true);
    	Market__c testMarket = TestClassUtility.createMarket(true);
    	Zip__c testZip = TestClassUtility.createZip(true); 

    	Local_Sales_Rep_Assignment__c localSalesAssgnRec = TestClassUtility.createLocalSalesRepAssignment(false, testCat, testMarket, testZip);
    	localSalesAssgnRec.Zip_Code__c = null;
    	insert localSalesAssgnRec;
                                                                      
    	Assignment_History__c assignmentHistoryRec = new Assignment_History__c();
    	assignmentHistoryRec.Local_Sales_Rep_Assignment__c = localSalesAssgnRec.Id;
    	insert assignmentHistoryRec;

    	Test.startTest();
        BatchAssignmentHistoryUpdate assignmentHistoryUpdateObj = new BatchAssignmentHistoryUpdate();
        Id batchId = Database.executeBatch(assignmentHistoryUpdateObj, 100);
        Test.stopTest();

    }
    
}