src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>Phase 1 National</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Phase 1 National</description>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DefaulCBSSValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CSP-1128</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>DefaultCBSSValues</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Region</label>
        <lookupFilter>
            <active>false</active>
            <infoMessage>Local Sales Region is filtered based on Primary Brand.  You may override this filter manually by clicking &quot;Show All Results&quot; below.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VendorLookupControllerTest.cls
/**
 * Test Class for : VendorLookupController
 */
@isTest
private class VendorLookupControllerTest {

    static testMethod void testVendorLookupController() {
        //DefaulCBSSValues__c createCBSSSetting = TestClassUtility.createCBSSSetting(true);
        
        Market__c testMarket = TestClassUtility.createMarket(false);
        testMarket.Market_ID__c = '222';
        testMarket.Active__c = true;
        //testMarket.Local_Sales_Region__c = testRegion.id;
        insert testMarket;
        
        RecordType accLocalRecordType = [SELECT Id, Name, SObjectType FROM RecordType WHERE SObjectType = 'Account' AND Name LIKE '%local%' AND IsActive = true LIMIT 1];

        Account parentObj = TestClassUtility.createAccount(false);
        parentObj.shippingPostalCode = '12345';
        parentObj.BillingPostalCode = '12345';
        parentObj.Phone = '1910101381';
        parentObj.Email__c = 'asd1312@asdas21213.com';
        parentObj.RecordTypeId = accLocalRecordType.Id;
        insert parentObj;

        Account accObj = TestClassUtility.createAccount(false);
        accObj.ParentId = parentObj.id;
        accObj.shippingPostalCode = '54321';
        accObj.BillingPostalCode = '54321';
        accObj.RecordTypeId = accLocalRecordType.Id;
        accObj.Email__c = '21s1212@AJKDHN132.com';
        insert accObj;
        
        System.currentPageReference().getParameters().put('accId', accObj.id);
        System.currentPageReference().getParameters().put('lksrch', 'Test');
        VendorLookupController controllerObj = new VendorLookupController();
        controllerObj.getFormTag();
        controllerObj.getTextBox();
    }
}