src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CreditHold__c</fullName>
        <label>Credit Hold</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_on_Payment_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box to identify whether a customer is on Payment Arrangement or not.</description>
        <label>Customer on Payment Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Taxonomy_ID__c</fullName>
        <description>Taxonomy GUID (Length must be 36 characters including hyphens)</description>
        <externalId>true</externalId>
        <inlineHelpText>Taxonomy ID</inlineHelpText>
        <label>Taxonomy ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>CreditHold__c</fullName>
        <description>Credit Hold Value from zuora customer account. SF-2064</description>
        <label>Credit Hold</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Category_Taxonomy_ID__c</fullName>
        <description>SF-1821</description>
        <label>Category Taxonomy ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <description>SF-1821</description>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_ID__c</fullName>
        <description>A textfield that captures the ID of the parent Quote Rate Plan in order to sync it to the resulting Subscription Product Charge record. Created specifically for Inventory management, could potentially also be used for Fulfillment purposes.</description>
        <label>Quote Rate Plan ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountSummaryControllerTest.cls
/*******************************************************************************
 *  Summary         : Test class for Account Summary Controller
 *  Refer Object    : 
 *  Author          : Nick
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
private class AccountSummaryControllerTest {

    @isTest static void summaryTest() {
        // Use TestClassUtility to build local data WITH subscription data

        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
        Test.startTest();

        Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
                                                                            (Contact)testObjects.get('Contact'), 
                                                                            (Opportunity)testObjects.get('Opportunity') , 
                                                                            (Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));

        Account testAccount = (Account)testObjects.get('Account');
        
        
        // Test base functionality
        AccountSummaryController.getSummaryData(testAccount.Id, 'all');
        AccountSummaryController.getSummaryData(null, 'active');
        AccountSummaryController.getSummaryData(testAccount.Id, 'completedlast90');

        // Test credit hold display logic
        testAccount.CreditHold__c = 'Yes';
        update testAccount;
        Test.stopTest();
        AccountSummaryController.getSummaryData(testAccount.Id, 'all');

        testAccount.CreditHold__c = 'No';
        testAccount.Customer_on_Payment_Arrangement__c = true;
        update testAccount;
        AccountSummaryController.getSummaryData(testAccount.Id, 'all');
        
        // Test Market and Category logic
        Category__c testCategory = (Category__c)testObjects.get('Category__c');

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = (Zuora__SubscriptionProductCharge__c)testsub.get('Zuora__SubscriptionProductCharge__c');

        zqu__QuoteRatePlan__c testQuoteRatePlan = (zqu__QuoteRatePlan__c)testsub.get('zqu__QuoteRatePlan__c');

        testCategory.Taxonomy_ID__c = 'testcategoryId';
        update testCategory;

        // Extra Subscription Product Charge Logic
        testSubscriptionProductCharge.Market_ID__c = '222';
        testSubscriptionProductCharge.Category_Taxonomy_ID__c = 'testcategoryId';
        testSubscriptionProductCharge.Quote_Rate_Plan_ID__c = testQuoteRatePlan.Id;
        update testSubscriptionProductCharge;

        AccountSummaryController.getSummaryData(testAccount.Id, 'all');

        // Instantiate wrapper class
        AccountSummaryController.AccountData testAccountData = new AccountSummaryController.AccountData();

    }
}