src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Hold_Expiry_Date__c</fullName>
        <inlineHelpText>The date that this inventory slot is reserved through.  If a spot has a hold expiry date of 2/1/2017, for example, it becomes available as soon as the date switches to 2/2/2017</inlineHelpText>
        <label>Held Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <inlineHelpText>The Product Rate Plan represents the product in a specific market/category.  In essence, this is the product we are tracking inventory against.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Waitlist_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waitlist Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Available for Purchase</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Waitlist__c.object
<CustomObject>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <inlineHelpText>The product (by market and category) that the customer is waitlisted for</inlineHelpText>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Inventory is not managed for that Product Rate Plan, therefore it cannot have a waitlist.</errorMessage>
            <filterItems>
                <field>zqu__ProductRatePlan__c.Capacity__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>zqu__ProductRatePlan__c.Capacity__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Waitlist</relationshipLabel>
        <relationshipName>Waitlists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Waitlist</label>
    <nameField>
        <displayFormat>WAIT-{000000}</displayFormat>
        <label>Waitlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WaitlistModalControllerTest.cls
@isTest
private class WaitlistModalControllerTest {

    //static testMethod void myUnitTest() {
        
    //    System.debug('setup products to make sure we have at least some data for testing');
    //    //testDataFactory dataFactory = new testDataFactory();
    //    //dataFactory.CreateLocalTestObjects();
    //    SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
    //                                             'Complete',
    //                                             '{"companyName": "Test Account"}',
    //                                             null);
    //    Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        
    //    Test.startTest();
    //        Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
    //    Test.stopTest();
        
    //    Account testAccount = (Account)testObjects.get('Account');
        
    //    zqu__ZProduct__c testProduct = TestClassUtility.createProduct(true);
    //    zqu__ProductRatePlan__c testZquProductRatePlan = TestClassUtility.createProductRatePlan(true, testProduct);
        
    //    List<zqu__ProductRatePlan__c> ratePlans = new List<zqu__ProductRatePlan__c>();
        
    //    WaitlistModalController wm = new WaitlistModalController();
        
    //    // set the product rate plan
    //    wm.OpenModal(testZquProductRatePlan.Id);
    //    // read the value we just inserted
    //    string val = wm.ProductRatePlanId;
        
    //    // add a few waitlist items
    //    wm.SaveNewWaitlist(testZquProductRatePlan.Id, testAccount.Id);
    //    wm.SaveNewWaitlist(testZquProductRatePlan.Id, testAccount.Id);
    //    wm.SaveNewWaitlist(testZquProductRatePlan.Id, testAccount.Id);
    //    wm.SaveNewWaitlist(testZquProductRatePlan.Id, testAccount.Id);
        
    //    // add some inventory
    //    Inventory__c inv = new Inventory__c();
    //    inv.Waitlist_Account__c = testAccount.Id;
    //    inv.Product_Rate_Plan__c = testZquProductRatePlan.Id;
    //    inv.Inventory_Hold_Expiry_Date__c = Date.Today().addDays(3);
    //    insert inv;
        
    //    // retrieve the waitlists
    //    List<Waitlist__c> waitlists = wm.getWaitlists();
        
    //    // reorder the list
    //    wm.SelectedWaitlistId = waitlists[2].Id;
    //    wm.MoveUp();
    //    wm.MoveDown();
    //    wm.MoveToBottom();
    //    wm.DeleteWaitlist();
        
    //    // retrieve the inventory
    //    List<Inventory__c> invList = wm.getAccountsOnDeck();
    //    wm.SelectedInventoryId = invList[0].id;
        
    //    // change inventory
    //    wm.HoldInventory();
    //    wm.DeleteInventory();
        
    //    // test page methods
    //    wm.getCanDeleteAnyWaitlist();
    //    wm.getCanReorderAnyWaitlist();
    //    wm.CloseModal();
    //    wm.getRatePlan();
    //    wm.AddAccount();

        
    //}
}