src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Inventory_Hold_Expiry_Date_Offsets__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For setting the number of days to offset the inventory expiry date when dealing with different objects.  Negative numbers mean before the date in question, positive numbers mean after the date in question.</description>
    <label>Inventory Hold Expiry Date Offsets</label>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Subscription_Being_Renewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Being Renewed</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Renewal Dashboard Subscription)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCreateInventoryForRenewalQuoteTest.cls
@isTest
private class BatchCreateInventoryForRenewalQuoteTest {
  static testMethod void testMethod1() {
  	Inventory_Hold_Expiry_Date_Offsets__c invHoldExpDate = Inventory_Hold_Expiry_Date_Offsets__c.getOrgDefaults();
  	Map<String,SObject> testMap = TestClassUtility.buildLocalData(TRUE);
  	
  	Test.startTest();
  	
  	Account testAccount = (Account)testMap.get('Account');
	    
  	Zuora__Subscription__c testSub = TestClassUtility.createSubscription(false, testAccount);
	testSub.Zuora__TermEndDate__c = Date.today().adddays(1);
	insert testSub;
	
	zqu__Quote__c testQuote = (zqu__Quote__c)testMap.get('zqu__Quote__c');
	testQuote.Subscription_Being_Renewed__c = testSub.Id;
	testQuote.zqu__ValidUntil__c = Date.today().adddays(10);
	update testQuote;
	
	
	BatchCreateInventoryForRenewalQuote b = new BatchCreateInventoryForRenewalQuote();
	database.executebatch(b);
	Test.stopTest();
  }
}