src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Used to hold Fulfillment Information received from Partners through the REST API</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>Moved from ZProduct</description>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>BOWPFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPWPref</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOW KSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOF PFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KNF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCG</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The deprecated Product SKU field.</description>
        <inlineHelpText>This field will be auto-generated if no value specified.</inlineHelpText>
        <label>SKU (Deprecated)</label>
        <length>70</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepId__c</fullName>
        <label>RenewalRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteAmendment__c.object
<CustomObject>
    <description>QuoteAmendment is used to make changes to a Quote.</description>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The identification for the Quote that is being amended.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Amendments</relationshipLabel>
        <relationshipName>Quote_Amendments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Amendment</label>
    <nameField>
        <label>Quote Amendment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteAmendment__c</fullName>
        <description>The identification of the amendment that this quote rate plan applies to.</description>
        <label>Quote Amendment</label>
        <referenceTo>zqu__QuoteAmendment__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionRatePlanZuoraId__c</fullName>
        <description>The identification number of the subscription rate plan that the amendment is modifying. Required if AmendmentType is set to RemoveProduct or UpdateProduct.</description>
        <label>Subscription Rate Plan Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepID__c</fullName>
        <label>RenewalRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan Charge associated with a Product Rate Plan Charge.</description>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepId__c</fullName>
        <label>RenewalRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>SF-583</description>
        <label>Job Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSD_ID__c</fullName>
        <label>RSD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepId__c</fullName>
        <label>RenewalRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuoteRatePlanChargeTriggerTest.cls
/* 
<class>
  <name>QuoteRatePlanChargeTriggerTest</name>
  <purpose>For testing save/delete events on a Zuora QuoteRatePlanCharge</purpose>
  <created>
    <by>Jonathan Satterfield</by>
    <date>7/22/2015</date>
    <ticket>SF-598, SF-599, SF-601</ticket>
  </created>
</class>
*/

/* 
<class>
  <name>QuoteRatePlanChargeTriggerTest</name>
  <purpose>For testing save/delete events on a Zuora QuoteRatePlanCharge and 
           record the Job Type & product Type from Zproducts on each QuoteRatePlanCharge record
  </purpose>
  <Modified>
    <by>Vijay Ram</by>
    <date>8/02/2015</date>
    <ticket>SF-583</ticket>
  </Modified>
</class>
*/

@isTest
public class QuoteRatePlanChargeTriggerTest {
    /* 
    <method>
      <name>TestUpdateIDsForCommissionTracking</name>
      <purpose>Test the QuoteRatePlanChargeTriggerHandler.UpdateIDsForCommissionTracking method</purpose>
      <created>
        <by>Jonathan Satterfield</by>
        <date>7/22/2015</date>
        <ticket>SF-598, SF-599, SF-601</ticket>
      </created>
    </method>
    */
    
     /* 
    <method>
      <name>TestUpdateIDsForCommissionTracking</name>
      <purpose>Test the QuoteRatePlanChargeTriggerHandler.RecordZProductJobType method</purpose>
      <created>
        <by>Vijay ram</by>
        <date>8/3/2015</date>
        <ticket>SF-583</ticket>
      </created>
    </method>
    */
    static testMethod void TestUpdateIDsForCommissionTracking() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Test.startTest();

        Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testLocalData.get('Account');
        Opportunity testOpp = (Opportunity)testLocalData.get('Opportunity');
        Contact testContact = (Contact)testLocalData.get('Contact');
      
        testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
        update testAccount;

        Test.stopTest();
        
        zqu__Quote__c testZQuote = TestClassUtility.createQuote(false, testOpp,testAccount,testContact);
        testZQuote.SalesRepId__c = '12345';
        testZQuote.RenewalRepId__c = '12345';
        testZQuote.RSD_Id__c = '11111';
        insert testZQuote;
        
        System.debug('Quote Created');

        zqu__QuoteAmendment__c testZQuoteAmendment = TestClassUtility.createQuoteAmendment(true,testZQuote);

        Product2 testProduct = TestClassUtility.createLocalProduct2(false);
        testProduct.Name = 'Test Product';
        testProduct.Job_Type__c = 'PRO'; 
        testProduct.zqu__SKU__c = 'test1234'; 
        testProduct.zqu__ZuoraId__c = 'test123456'; 
        insert testProduct;

        System.debug('Product Created');

        zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true,testProduct);

        System.debug('Product Rate Plan Created');

        zqu__ProductRatePlanCharge__c testProductRatePlanCharge = TestClassUtility.createProductRatePlanCharge(true,testProductRatePlan);

        System.debug('Product Rate Plan Charge Created');

        zqu__QuoteRatePlan__c testQuoteRatePlan = TestClassUtility.createQuoteRatePlan(false,testZQuote,testProductRatePlan);
        testQuoteRatePlan.zqu__QuoteAmendment__c = testZQuoteAmendment.Id;
        testQuoteRatePlan.zqu__SubscriptionRatePlanZuoraId__c = '';
        insert testQuoteRatePlan;

        System.debug('Quote Rate Plan for NewProduct Created');

        zqu__QuoteRatePlan__c testQuoteRatePlan2 = TestClassUtility.createQuoteRatePlan(false,testZQuote,testProductRatePlan);
        testQuoteRatePlan2.zqu__QuoteAmendment__c = testZQuoteAmendment.Id;
        testQuoteRatePlan2.zqu__SubscriptionRatePlanZuoraId__c = 'abc123';
        testQuoteRatePlan2.zqu__AmendmentType__c = 'UpdateProduct';
        insert testQuoteRatePlan2;

        System.debug('Quote Rate Plan for UpdateProduct Created');

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge.zqu__Total__c = 123;
        testQuoteRatePlanCharge.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge.List_Price__c = '';
        testQuoteRatePlanCharge.Location_Vendor__c = testAccount.id;
        insert testQuoteRatePlanCharge;

        System.debug('Quote Rate Plan Charge Created');

        List<zqu__QuoteRatePlanCharge__c> qrpcList = new List<zqu__QuoteRatePlanCharge__c>();

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge2 = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge2.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge2.zqu__Total__c = 123;
        testQuoteRatePlanCharge2.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge2.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge2.List_Price__c = '';
        testQuoteRatePlanCharge2.Location_Vendor__c = testAccount.id;
        qrpcList.add(testQuoteRatePlanCharge2);

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge3 = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge3.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge3.zqu__Total__c = 123;
        testQuoteRatePlanCharge3.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge3.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge3.List_Price__c = '';
        qrpcList.add(testQuoteRatePlanCharge3);

        insert qrpcList;     
    }
    
    static testMethod void TestUpdateIDsForCommissionTracking_two() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Test.startTest();

        Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testLocalData.get('Account');
        Opportunity testOpp = (Opportunity)testLocalData.get('Opportunity');
        Contact testContact = (Contact)testLocalData.get('Contact');
        
        testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
        update testAccount;
        
        Test.stopTest();

        zqu__Quote__c testZQuote = TestClassUtility.createQuote(false, testOpp,testAccount,testContact);
        testZQuote.SalesRepId__c = '12345';
        testZQuote.RenewalRepId__c = '12345';
        testZQuote.RSD_Id__c = '11111';
        insert testZQuote;

        System.debug('Quote Created');

        zqu__QuoteAmendment__c testZQuoteAmendment = TestClassUtility.createQuoteAmendment(true,testZQuote);

        Product2 testProduct = TestClassUtility.createLocalProduct2(false);
        testProduct.Name = 'Test Product';
        testProduct.Job_Type__c = 'PRO'; 
        testProduct.zqu__SKU__c = 'test1234'; 
        testProduct.zqu__ZuoraId__c = 'test123456'; 
        insert testProduct;

        System.debug('Product Created');

        zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true,testProduct);

        System.debug('Product Rate Plan Created');

        zqu__ProductRatePlanCharge__c testProductRatePlanCharge = TestClassUtility.createProductRatePlanCharge(true,testProductRatePlan);

        System.debug('Product Rate Plan Charge Created');

        zqu__QuoteRatePlan__c testQuoteRatePlan = TestClassUtility.createQuoteRatePlan(false,testZQuote,testProductRatePlan);
        testQuoteRatePlan.zqu__QuoteAmendment__c = testZQuoteAmendment.Id;
        testQuoteRatePlan.zqu__SubscriptionRatePlanZuoraId__c = '';
        insert testQuoteRatePlan;

        System.debug('Quote Rate Plan for NewProduct Created');

        zqu__QuoteRatePlan__c testQuoteRatePlan2 = TestClassUtility.createQuoteRatePlan(false,testZQuote,testProductRatePlan);
        testQuoteRatePlan2.zqu__QuoteAmendment__c = testZQuoteAmendment.Id;
        testQuoteRatePlan2.zqu__SubscriptionRatePlanZuoraId__c = 'abc123';
        testQuoteRatePlan2.zqu__AmendmentType__c = 'UpdateProduct';
        insert testQuoteRatePlan2;

        System.debug('Quote Rate Plan for UpdateProduct Created');

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge.zqu__Total__c = 123;
        testQuoteRatePlanCharge.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge.List_Price__c = '';
        testQuoteRatePlanCharge.Location_Vendor__c = testAccount.id;
        insert testQuoteRatePlanCharge;

        System.debug('Quote Rate Plan Charge Created');

        List<zqu__QuoteRatePlanCharge__c> qrpcList = new List<zqu__QuoteRatePlanCharge__c>();

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge2 = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge2.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge2.zqu__Total__c = 123;
        testQuoteRatePlanCharge2.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge2.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge2.List_Price__c = '';
        testQuoteRatePlanCharge2.Location_Vendor__c = testAccount.id;
        qrpcList.add(testQuoteRatePlanCharge2);

 
        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge3 = TestClassUtility.createQuoteRatePlanCharge(false,testQuoteRatePlan,testProductRatePlanCharge);
        testQuoteRatePlanCharge3.zqu__ListPrice__c = 123;
        testQuoteRatePlanCharge3.zqu__Total__c = 123;
        testQuoteRatePlanCharge3.Quote_Rate_Plan_ID__c = '';
        testQuoteRatePlanCharge3.zqu__ListPrice__c = 10.00;
        testQuoteRatePlanCharge3.List_Price__c = ''; 
        qrpcList.add(testQuoteRatePlanCharge3);
        
        insert qrpcList;
       
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Zuora_Id__c = 'abc123';
        insert testSubscription;

        Zuora__Product__c testZuoraProduct = TestClassUtility.createZuoraProduct(true);
      
        Zuora__Subscription__c testSub = TestClassUtility.createSubscription(true,testAccount);
        
        Zuora__SubscriptionProductCharge__c testZSubProductCharge = TestClassUtility.createSubscriptionProductCharge(true,testSub,testZuoraProduct);
        
        QuoteRatePlanChargeTriggerHandler.UpdateIDsForCommissionTracking(qrpcList);    
    }

}