src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Card_Declined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Card Declined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Data__c</fullName>
        <inlineHelpText>Used to hold Fulfillment Information received from Partners through the REST API</inlineHelpText>
        <label>Fulfillment Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consecutive_Credit_Card_Failure_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Consecutive Credit Card Failure Config</label>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Sold_To_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field will hold the lookup relationship for the Sold To Contact that is being used to sync Sold To information to Zuora.</description>
        <label>Sold To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold To Billing Accounts</relationshipLabel>
        <relationshipName>Sold_To_Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <label>Default Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>CC_Failure_Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CC Failure Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__BankIdentificationNumber__c</fullName>
        <description>This is the first six digits of the PaymentMethod, such as the credit card number or account number.</description>
        <inlineHelpText>This is the first six digits of the PaymentMethod, such as the credit card number or account number.</inlineHelpText>
        <label>Bank Identification Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default payment method or not</description>
        <inlineHelpText>Default payment method or not</inlineHelpText>
        <label>Default Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__NumConsecutiveFailures__c</fullName>
        <label>Number of Consecutive Failures</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentMethodNewTriggerHandlerTest.cls
/* 
<class>
  <name>PaymentMethodNewTriggerHandler</name>
  <purpose>For testing the PaymentMethodNewTriggerHandler class</purpose>
  <created>
    <by>Hari Mohan</by>
    <date>10/2/2015</date>
    <ticket>SF-1182</ticket>
  </created>
</class>
*/
@isTest
private class PaymentMethodNewTriggerHandlerTest {
    
    @isTest static void test_method_one() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
       
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtOppMapByName = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        
        
        Test.startTest();
        Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        List<Consecutive_Credit_Card_Failure_Config__c> consecFailureList = Consecutive_Credit_Card_Failure_Config__c.getAll().Values();
        

        Account testAccount = (Account)testLocalData.get('Account');
        testAccount.Card_Declined__c = false;
        update testAccount;

        Deactivate_Trigger__c dtNote = TestClassUtility.createNotesDeactivateTriggerSetting(false);
        dtNote.After_Delete__c = false;
        dtNote.After_Insert__c = false;
        dtNote.After_Update__c = false;
        dtNote.Before_Delete__c = false;
        dtNote.Before_Insert__c = false;
        dtNote.Before_Update__c = false;
        insert dtNote;
        
        testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
        update testAccount;

        Contact con = (Contact)testLocalData.get('Contact');

        Zuora__CustomerAccount__c testZuoraCustomerAccount = (Zuora__CustomerAccount__c)testLocalData.get('Zuora__CustomerAccount__c');
        testZuoraCustomerAccount.Sold_To_Contact__c = con.id;
        List<Zuora__PaymentMethod__c> testPaymentMethods = new List<Zuora__PaymentMethod__c>();

        Zuora__PaymentMethod__c testPaymentMthd = TestClassUtility.createPaymentMethod(FALSE,testZuoraCustomerAccount);
        testPaymentMthd.Zuora__External_Id__c ='PaymentMethodNewTriggerHandler01';
        testPaymentMthd.CC_Failure_Notification_Sent__c = false;
        testPaymentMthd.Zuora__NumConsecutiveFailures__c = 3;
        testPaymentMthd.Zuora__DefaultPaymentMethod__c = true;
        insert testPaymentMthd;
 
        Zuora__PaymentMethod__c testPaymentMthd1 = TestClassUtility.createPaymentMethod(FALSE,testZuoraCustomerAccount);
        testPaymentMthd1.Zuora__External_Id__c ='PaymentMethodNewTriggerHandler02';
        testPaymentMthd1.CC_Failure_Notification_Sent__c = false;
        testPaymentMthd1.Zuora__NumConsecutiveFailures__c = 0;
        testPaymentMthd1.Zuora__BankIdentificationNumber__c = '411112';
        testPaymentMthd1.Zuora__DefaultPaymentMethod__c = true;
        insert testPaymentMthd1;

        PaymentMethodNewTriggerHandler pmnt = new PaymentMethodNewTriggerHandler();
        pmnt.emailsAndTasksCreation(testPaymentMthd);

        Test.stopTest();

    } 
    
    
    @isTest static void test_method_two() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtOppMapByName = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        
        Test.startTest();
        Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
       
        Test.stopTest();
        Account testAccount = (Account)testLocalData.get('Account');
      
        testAccount.Card_Declined__c = true;
        update testAccount;


        Deactivate_Trigger__c dtNote = TestClassUtility.createNotesDeactivateTriggerSetting(false);
        dtNote.After_Delete__c = false;
        dtNote.After_Insert__c = false;
        dtNote.After_Update__c = false;
        dtNote.Before_Delete__c = false;
        dtNote.Before_Insert__c = false;
        dtNote.Before_Update__c = false;
        insert dtNote; 

        testAccount.Fulfillment_Data__c = '{ "tier" : "Freemium", "reviewId" : "review Id", "parentGUID" : "37e0c6b9-6f4f-4dd4-a3f4-9707e9dc4bbc", "marketCode" : "228", "categoryId" : "8aa9a07b-fcd8-46ed-a98f-8f3e12689dd2" }';
        update testAccount;
        
        Zuora__CustomerAccount__c testZuoraCustomerAccount = (Zuora__CustomerAccount__c)testLocalData.get('Zuora__CustomerAccount__c');

        Zuora__PaymentMethod__c testPaymentMthd = TestClassUtility.createPaymentMethod(false,testZuoraCustomerAccount);
        testPaymentMthd.CC_Failure_Notification_Sent__c = false;
        testPaymentMthd.Zuora__NumConsecutiveFailures__c = 3;
        testPaymentMthd.Zuora__DefaultPaymentMethod__c = true;

        Zuora__PaymentMethod__c testPaymentMthd1 = TestClassUtility.createPaymentMethod(false,testZuoraCustomerAccount);
        testPaymentMthd1.Zuora__External_Id__c = '2c92c0f94fd7f22b014ff62286456cdf';
        testPaymentMthd1.CC_Failure_Notification_Sent__c = false;
        testPaymentMthd1.Zuora__NumConsecutiveFailures__c = 0;   
        testPaymentMthd1.Zuora__BankIdentificationNumber__c = '411112';
        testPaymentMthd1.Zuora__DefaultPaymentMethod__c = true;
        List<Zuora__PaymentMethod__c> updatezpmlist = new List<Zuora__PaymentMethod__c>();
        updatezpmlist.add(testPaymentMthd);

        insert updatezpmlist;

        List<Consecutive_Credit_Card_Failure_Config__c> consecFailureList = Consecutive_Credit_Card_Failure_Config__c.getAll().Values();          

    }      
}