src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__HostedPageLiteSetting__c.object
<CustomObject>
    <fields>
        <fullName>zqu__ComponentName__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__PageId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Id of the Payment Page in Zuora.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Id of the Payment Page in Zuora.</inlineHelpText>
        <label>Page Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethodType__c</fullName>
        <label>Payment Method Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Payment Pages Setting</label>
    <nameField>
        <label>Payment Pages Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Pages Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateNewPaymentMethodControllerTest.cls
/*******************************************************************************
 *  Summary         : Test class for paymentmethod Controller
 *  Refer Object    : 
 *  Author          : Nick
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
private class CreateNewPaymentMethodControllerTest{

    private static testmethod void test_method_one() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Map<String, SObject> zqDataMap = TestClassUtility.buildZQUTestObjects(false);

        Test.startTest();

        zqu__Quote__c testQuote = TestClassUtility.createQuote(true, 
            (Opportunity)zqDataMap.get('Opportunity'), 
            (Account)zqDataMap.get('Account'), 
            (Contact)zqDataMap.get('Contact'));

        zqu__HostedPageLiteSetting__c testzquHostedPageLiteSetting = new zqu__HostedPageLiteSetting__c ();
        testzquHostedPageLiteSetting.zqu__PaymentMethodType__c = 'Credit Card';
        testzquHostedPageLiteSetting.zqu__PageId__c = '8aa9a07b';
        testzquHostedPageLiteSetting.zqu__ComponentName__c = 'testComponentName';
        insert testzquHostedPageLiteSetting;
        
        test.setCurrentPageReference(Page.CreateNewPaymentMethod);
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        CreateNewPaymentMethodController testcase = new CreateNewPaymentMethodController(sc); 
        string pageId = testcase.pageId;
        
        Test.stopTest();
    }
}