src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Strategy_Specialist</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Callback__c.object
<CustomObject>
    <description>Object named &quot;Callback&quot; which will be used to store callbacks generated through the system</description>
    <fields>
        <fullName>Subscription_Charge_Number__c</fullName>
        <description>CSP-1464 | used to keep track of which Subscription Product Charge with which the Callback is associated</description>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <description>Name of the Subscription for which this Callback is associated. Specifically added to query/delete Callbacks for Charges that were removed in an Amendment Quote. (CSP-1464)</description>
        <externalId>true</externalId>
        <label>Subscription Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Callback</label>
    <nameField>
        <label>Callback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactions</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <formula>Account.Strategy_Specialist__r.FirstName + &apos; &apos; +  Account.Strategy_Specialist__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Strategist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Charge_Number__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <description>Lists the zuora subscription number (e.g. A-S00142538)</description>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <label>Account Manager</label>
        <relationshipName>Strategy_Specialist</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Zuora__Product__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_True_Status__c</fullName>
        <formula>Zuora__Subscription__r.True_Subscription_Status__c</formula>
        <label>Sub True Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__ProductSKU__c</fullName>
        <label>Product SKU (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <description>The version of the rate plan charge. Each time a charge is amended, Zuora creates a new version of the rate plan charge.</description>
        <label>Version</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraSubscriptionPCTriggerHandlerTest.cls
@isTest
private class ZuoraSubscriptionPCTriggerHandlerTest {
	
    @testSetup 
    static void createTestData(){

		Group g1 = new Group(Name = 'Asset Collection Queue', type = 'Queue');
        insert g1;
        QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
        insert q1;   
	}

    static testMethod void testMethod1() {

        Profile standardProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = TestClassUtility.createUser(true, standardProfile);
        
        Account testAccount = TestClassUtility.createAccount(false);
        testAccount.Strategy_Specialist__c = testUser.Id;
        insert testAccount;

        Contact testContact = TestClassUtility.createContact(true, testAccount);

        AccountContactRole testPrimaryAccContRole = TestClassUtility.createAccountContactRole(true,testAccount,testContact);
        AccountContactRole testNonPrimaryAccContRole = TestClassUtility.createAccountContactRole(false,testAccount,testContact);
        testNonPrimaryAccContRole.IsPrimary = false;
        testNonPrimaryAccContRole.Role = 'Employee';
        insert testNonPrimaryAccContRole;

        Zuora__Subscription__c testZuoraSubscriptionCancelled = TestClassUtility.createSubscription(false, testAccount);
        testZuoraSubscriptionCancelled.Zuora__Status__c = 'Cancelled';
        testZuoraSubscriptionCancelled.Zuora__Version__c = 2;
        
        Zuora__Subscription__c testZuoraSubscriptionV2 = TestClassUtility.createSubscription(false, testAccount);
        testZuoraSubscriptionV2.Zuora__Version__c = 2;
        
        Zuora__Subscription__c testZuoraSubscriptionV1 = TestClassUtility.createSubscription(false, testAccount);
        testZuoraSubscriptionV1.Zuora__Version__c = 1;

        List<Zuora__Subscription__c> zuoraSubList = new List<Zuora__Subscription__c>{testZuoraSubscriptionCancelled,
																					testZuoraSubscriptionV2,
																					testZuoraSubscriptionV1};
        insert zuoraSubList;

        Zuora__Product__c testZuoraProduct = TestClassUtility.createZuoraProduct(true);
        // Zuora__SubscriptionProductCharge__c(Sub_True_Status__c = 'Cancelled')
        Zuora__SubscriptionProductCharge__c testZuoraSubPCCancelled = TestClassUtility.createSubscriptionProductCharge(false, 
																													   testAccount, 
																								        	           testZuoraSubscriptionCancelled, 
																										               testZuoraProduct);
        testZuoraSubPCCancelled.Zuora__EffectiveStartDate__c = Date.today().addMonths(-5);
        testZuoraSubPCCancelled.Zuora__EffectiveEndDate__c = Date.today().addMonths(5);
        testZuoraSubPCCancelled.Product_Type__c = 'Transactions';
        // Zuora__SubscriptionProductCharge__c(Sub_True_Status__c = 'Active') 
        Zuora__SubscriptionProductCharge__c testZuoraSubPCActiveV1 = TestClassUtility.createSubscriptionProductCharge(false, 
																			 										  testAccount, 
																											          testZuoraSubscriptionV1, 
																    										          testZuoraProduct);
        testZuoraSubPCActiveV1.Zuora__EffectiveStartDate__c = Date.today().addMonths(-5);
        testZuoraSubPCActiveV1.Zuora__EffectiveEndDate__c = Date.today().addMonths(5);
        testZuoraSubPCActiveV1.Product_Type__c = 'Transactions';
        testZuoraSubPCActiveV1.Zuora__ProductSKU__c = 'test01';
        testZuoraSubPCActiveV1.Zuora__Account__c = testAccount.Id;
        Zuora__SubscriptionProductCharge__c testZuoraSubPCActiveV2 = TestClassUtility.createSubscriptionProductCharge(false, 
																													testAccount, 
																										        	testZuoraSubscriptionV2, 
																										        	testZuoraProduct);
        testZuoraSubPCActiveV2.Zuora__EffectiveStartDate__c = Date.today().addMonths(-5);
        testZuoraSubPCActiveV2.Zuora__EffectiveEndDate__c = Date.today().addMonths(5);
        testZuoraSubPCActiveV2.Product_Type__c = 'Transactions';
        testZuoraSubPCActiveV2.Zuora__SubscriptionChargeNumber__c = 'Test001';
        // Zuora__SubscriptionProductCharge__c(Sub_True_Status__c = 'Active', Name.containsIgnoreCase('20% Down')) 
        Zuora__SubscriptionProductCharge__c testZuoraSubPCActiveDown = TestClassUtility.createSubscriptionProductCharge(false, 
																														testAccount, 
																												        testZuoraSubscriptionV2, 
																											        	testZuoraProduct);
        testZuoraSubPCActiveDown.Zuora__EffectiveStartDate__c = Date.today().addMonths(-5);
        testZuoraSubPCActiveDown.Zuora__EffectiveEndDate__c = Date.today().addMonths(5);
        testZuoraSubPCActiveDown.Product_Type__c = 'Transactions';
        testZuoraSubPCActiveDown.Name = 'Test Subscription Product Charge - 20% Down';

        List<Zuora__SubscriptionProductCharge__c> subPCList = new List<Zuora__SubscriptionProductCharge__c>{testZuoraSubPCCancelled, 
																											testZuoraSubPCActiveV2,
																											testZuoraSubPCActiveV1,
																											testZuoraSubPCActiveDown};
        
        Callback__c testCallBack = TestClassUtility.createCallback(false);
        testCallBack.Subscription_Name__c = testZuoraSubscriptionV2.Name;
        testCallBack.Subscription_Charge_Number__c = testZuoraSubPCActiveV2.Zuora__SubscriptionChargeNumber__c;
        insert testCallBack;


	    Test.startTest();
        insert subPCList;
        Test.stopTest();
    }

    static testMethod void testUpdateDataToZuora() {
    	Map<String, String> zspcZuoraIdMap = new Map<String, String>();
        zspcZuoraIdMap.put('123', 'abc');
        Test.startTest();
        ZuoraSubscriptionPCTriggerHandler.updateDataToZuora(zspcZuoraIdMap);
        Test.stopTest();
    }

    
        
}