src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Preferred_Payment_Schedule__c</fullName>
        <label>Preferred Payment Schedule</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>True_TCV_JSON_Response__c</fullName>
        <description>(CSP-1181) store the JSON response returned while retrieving the Quote&apos;s true TCV amount</description>
        <label>True TCV JSON Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__InitialTerm__c</fullName>
        <description>The Initial Term of the Quote.</description>
        <inlineHelpText>The Initial Term of the Quote.</inlineHelpText>
        <label>Initial Term</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethod__c</fullName>
        <description>The Payment Method for the Quote.</description>
        <inlineHelpText>The Payment Method for the Quote.</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionTermEndDate__c</fullName>
        <description>Only for Amendment quotes, contains the term end date of the base subscription</description>
        <inlineHelpText>The term end date of the subscription is amendment on</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentSchBreakdownControllerTestClass.cls
@isTest 
private class PaymentSchBreakdownControllerTestClass {
    
    public static String JsonStr = 
                                  '{"success" : true, '+
                                 '"contractedMrr" : 1065.000000000, '+
                                 '"totalContractedValue" : 12780.000000000, '+
                                 '"amount" : 12780.00, '+
                                 '"amountWithoutTax" : 12780.00, '+
                                 '"taxAmount" : 0.00, '+
                                 '"invoiceTargetDate" : "2018-06-06", '+
                                
                                 '"invoiceItems" : [ { '+
                                 '  "serviceStartDate" : "2016-07-15", '+
                                   '"serviceEndDate" : "2016-08-14", '+
                                   '"chargeAmount" : 70.00, '+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : " Charge", '+
                                   '"productName" : "Storefront", '+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131", '+
                                   '"quantity" : 1, '+
                                   '"unitOfMeasure" : "" '+
                                 '}, { '+
                                   '"serviceStartDate" : "2016-07-15", '+
                                   '"serviceEndDate" : "2016-08-14", '+
                                   '"chargeAmount" : 1005.00, '+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : "Recurring Charge", '+
                                   '"productName" : "Premium Featured Vendor", '+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a", '+
                                   '"quantity" : 1, '+
                                   '"unitOfMeasure" : "" '+
                                '}, { '+
                                   '"serviceStartDate" : "2016-01-15", '+
                                   '"serviceEndDate" : "2016-09-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : "Recurring Charge", '+
                                   '"productName" : "Featured", '+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : "" '+
                                '}, { '+
                                
                                '"serviceStartDate" : "2016-01-15", '+
                                   '"serviceEndDate" : "2016-09-14",'+
                                   '"chargeAmount" : 90.00,'+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : "Weekly Charge", '+
                                   '"productName" : "Vendor", '+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : "" '+
                                '}, { '+
                                
                                '"serviceStartDate" : "2016-01-15", '+
                                   '"serviceEndDate" : "2016-09-14",'+
                                   '"chargeAmount" : 90.00,'+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : "Monthly Charge", '+
                                   '"productName" : "Premium", '+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : "" '+
                                '}, { '+
                                
                                   '"serviceStartDate" : "2016-08-15",'+
                                   '"serviceEndDate" : "2016-09-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2016-09-15",'+
                                   '"serviceEndDate" : "2016-10-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2016-09-15",'+
                                   '"serviceEndDate" : "2016-10-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2016-10-15",'+
                                   '"serviceEndDate" : "2016-11-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2016-10-15",'+
                                   '"serviceEndDate" : "2016-11-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2016-11-15",'+
                                   '"serviceEndDate" : "2016-12-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                    '"serviceStartDate" : "2016-11-15",'+
                                   '"serviceEndDate" : "2016-12-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2016-12-15",'+
                                   '"serviceEndDate" : "2017-01-14",'+
                                   '"chargeAmount" : 99.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2016-12-15",'+
                                   '"serviceEndDate" : "2017-01-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                     '"serviceStartDate" : "2017-01-15",'+
                                   '"serviceEndDate" : "2017-02-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-01-15",'+
                                   '"serviceEndDate" : "2017-02-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-02-15",'+
                                   '"serviceEndDate" : "2017-03-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-02-15",'+
                                   '"serviceEndDate" : "2017-03-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-03-15",'+
                                   '"serviceEndDate" : "2017-04-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-03-15",'+
                                   '"serviceEndDate" : "2017-04-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-04-15",'+
                                   '"serviceEndDate" : "2017-05-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2017-04-15",'+
                                   '"serviceEndDate" : "2017-05-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2017-05-15",'+
                                   '"serviceEndDate" : "2017-06-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                '}, { '+
                                   '"serviceStartDate" : "2017-05-15",'+
                                   '"serviceEndDate" : "2017-06-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2017-06-15",'+
                                   '"serviceEndDate" : "2017-07-14",'+
                                   '"chargeAmount" : 60.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Storefront",'+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : ""'+
                                 '}, { '+
                                   '"serviceStartDate" : "2017-06-15",'+
                                   '"serviceEndDate" : "2017-07-14",'+
                                   '"chargeAmount" : 1005.00,'+
                                   '"chargeDescription" : null,'+
                                   '"chargeName" : "Recurring Charge",'+
                                   '"productName" : "Premium Featured Vendor",'+
                                   '"productRatePlanChargeId" : "2c92a0fc5269262e015270ab7ff74e4a",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : "" '+
                                '}, { '+
                                
                                   '"serviceStartDate" : "2014-01-15", '+
                                   '"serviceEndDate" : "2014-09-14",'+
                                   '"chargeAmount" : 90.00,'+
                                   '"chargeDescription" : null, '+
                                   '"chargeName" : "Weekly Charge", '+
                                   '"productName" : "Vendor", '+
                                   '"productRatePlanChargeId" : "2c92a0ff526932600152748622a93131",'+
                                   '"quantity" : 1,'+
                                   '"unitOfMeasure" : "" '+
                                '}]}';
    
    
    static testMethod void parseJSONPaymentBreakdownStringTest() {
        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);

        Account testAccount = (Account)testObjects.get('Account');
        Contact testContact = (Contact)testObjects.get('Contact');
        Opportunity testOpportunity = (Opportunity)testObjects.get('Opportunity');
        
        // Create quote 
        zqu__Quote__c testQuote = TestClassUtility.createQuote(true, testOpportunity, testAccount, testContact);
        testQuote.True_TCV_JSON_Response__c = JsonStr;
        testQuote.zqu__InitialTerm__c = 12;
        testQuote.zqu__TermStartDate__c = Date.today();
        testQuote.zqu__BillCycleDay__c = '12';
        // Added Payment Method to be check for extra coverage(adds 30 days to due date)
        testQuote.zqu__PaymentMethod__c = 'Check';
        // Check cannot have a MONTHLY payment schedule
        testQuote.Preferred_Payment_Schedule__c = 'Annual';
        update testQuote;
        
        System.currentPageReference().getParameters().put('quoteId', testQuote.Id);
        
        Test.startTest();
          PaymentSchBreakdownController paymentSchController = new PaymentSchBreakdownController();
          paymentSchController.parseJSONPaymentBreakdownString();
        Test.stopTest();
    }

    static testMethod void negativePaymentScheduleTest() {
      PaymentSchBreakdownController paymentSchController = new PaymentSchBreakdownController();
      paymentSchController.parseJSONPaymentBreakdownString();

      Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);

      Account testAccount = (Account)testObjects.get('Account');
      Contact testContact = (Contact)testObjects.get('Contact');
      Opportunity testOpportunity = (Opportunity)testObjects.get('Opportunity');

      // Create quote 
      zqu__Quote__c testQuote = TestClassUtility.createQuote(true, testOpportunity, testAccount, testContact);
      //testQuote.True_TCV_JSON_Response__c = JsonStr;
      testQuote.zqu__InitialTerm__c = 12;
      testQuote.zqu__TermStartDate__c = Date.today();
      testQuote.zqu__BillCycleDay__c = '12';
      // Added Payment Method to be check for extra coverage(adds 30 days to due date)
      testQuote.zqu__PaymentMethod__c = 'Check';
      // Check cannot have a MONTHLY payment schedule
      testQuote.Preferred_Payment_Schedule__c = 'Annual';
      testQuote.zqu__SubscriptionTermEndDate__c = Date.today().addMonths(12);
      update testQuote;

      System.currentPageReference().getParameters().put('quoteId', testQuote.Id);
        
      Test.startTest();
        paymentSchController = new PaymentSchBreakdownController();
        paymentSchController.parseJSONPaymentBreakdownString();
      Test.stopTest();
    }

    static testMethod void wrapperClassTest() {
      new PaymentSchBreakdownController.BreakdownWrapper(Date.today(), 'Something', new PaymentSchBreakdownController.InvoiceItems());

      new PaymentSchBreakdownController.ZuoraSubscPreview(new List<PaymentSchBreakdownController.InvoiceItems>(), true);
    }
}