src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NVMContactWorld__Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>NVMContactWorld__baseURL__c</fullName>
        <inlineHelpText>URL used to access ContactWorld API.  Please ensure that it is in the list of allowed Remote Sites.</inlineHelpText>
        <label>ContactWorld URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>NVMContactWorld__clientId__c</fullName>
        <label>ContactWorld Account Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVMContactWorld__clientSecret__c</fullName>
        <label>ContactWorld API Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token_Callout_URL__c</fullName>
        <label>Token Callout URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Settings</label>
</CustomObject>

src/classes/NewVoiceMediaUtilityTest.cls
@isTest
private class NewVoiceMediaUtilityTest {
    static testMethod void testMethod1() {
        createNvmSettings();
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'OK',
                                                 '{"access_token":"123","token_type":"bearer","expires_in":3600,"scope":"newvoicemedia.com/api/statistics newvoicemedia.com/api/callcontrol newvoicemedia.com/api/callrecording newvoicemedia.com/api/account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        // NewVoiceMediaUtility.pauseCallRecording();
        NewVoiceMediaUtility.pauseOrResumeCallRecording('Paused');
        // NewVoiceMediaUtility.resumeCallRecording();
        NewVoiceMediaUtility.pauseOrResumeCallRecording('Started');
        NewVoiceMediaUtility.getNVMCallRecordingPauseCookie();
        
    }

    static testMethod void testMethod2() {
        createNvmSettings();
        // Test pauseCallRecording exception
        // NewVoiceMediaUtility.pauseCallRecording();
        NewVoiceMediaUtility.pauseOrResumeCallRecording('Paused');
    }


    static testMethod void testMethod4() {
        createNvmSettings();
        Cache.Org.put('local.NVM.token', 'testToken', 3600, Cache.Visibility.ALL, true);
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'OK',
                                                 '{"links":[{"rel":"testrel","href":"testhref"}],"id":"testId","currentCallGuid":"testcurrentCallGuid"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        NewVoiceMediaUtility.pauseOrResumeCallRecording('Paused');
        // NewVoiceMediaUtility.pauseCallRecording();
        
    }

    public static void createNvmSettings(){
        NVMContactWorld__Settings__c nvmSettings = new NVMContactWorld__Settings__c();
        nvmSettings.NVMContactWorld__clientId__c = 'test';
        nvmSettings.NVMContactWorld__clientSecret__c = 'test';
        nvmSettings.NVMContactWorld__baseURL__c = 'https://test/';
        nvmSettings.Token_Callout_URL__c = 'v0/oauth2/token';
        insert nvmSettings;
    }


}