src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_on_Payment_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box to identify whether a customer is on Payment Arrangement or not.</description>
        <label>Customer on Payment Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <description>Plan to Deprecated for CSP-2731
SF-613</description>
        <label>Local Paid Status(deprecated)</label>
        <picklist>
            <picklistValues>
                <fullName>Unpaid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Longest_Past_Due_Date__c</fullName>
        <description>This field holds the due date of the longest invoice with outstanding balance associated with the account.</description>
        <label>Longest Past Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Past_Due_Balance__c</fullName>
        <description>This field holds the sum of past due balances of all the invoice associated with the account.</description>
        <label>Past Due Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>CSP-1326</description>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Purpose__c</fullName>
        <inlineHelpText>Choose the purpose for the communication</inlineHelpText>
        <label>Task Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>First Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Conversation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working on Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B/Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Knot Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Ads (non-storefronts)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storefront/Theknot.com/Planner App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscriptions and Freemiums</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Calc/PDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tours, Concierge, TRX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <formula>TEXT(Account.Local_Paid_Status__c)</formula>
        <label>Local Paid Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_Past_Due__c</fullName>
        <formula>Today() - Account.Longest_Past_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This number calculates by looking at the Longest Past Due Date on the Account and gives the amount of days between then and today</inlineHelpText>
        <label>Number of Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Handling abnormal case data</description>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice_Past_Due_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Create_ARR_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check-box field that controls whether to create a task for ARR when the invoice is past due certain number of days.</description>
        <label>Create ARR Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Days_Past_Due__c</fullName>
        <label>Number Of Days Past Due</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_Email_To_Account_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine if an Email should also be sent to the Account Owner when an Account is past due.</description>
        <label>Send Email To Account Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Email_To_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check-box field that controls whether to send email communication to Customer or not when an invoice is past due certain days.</description>
        <label>Send Email To Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Past Due Config</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Failure_Area__c</fullName>
        <description>Field used to describe where an error originated from - helpful in tracking down failure source.</description>
        <label>Failure Area</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative.One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote to Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCV Calculation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zuora Sync</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Field used to describe the severity of the failure.</description>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trivial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field will hold the lookup relationship for the Bill To Contact that is being used to sync Bill To information to Zuora.</description>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To Billing Accounts</relationshipLabel>
        <relationshipName>Bill_To_Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToWorkEmail__c</fullName>
        <label>Bill To Work E-mail</label>
        <type>Email</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Original Rep</inlineHelpText>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchAccountPastDueBalanceEmailsAndTasks.cls
global class BatchAccountPastDueBalanceEmailsAndTasks implements Database.Batchable<sObject>, Database.Stateful {
    ////////////////////////////
    // STATIC FINAL VARIABLES //
    ////////////////////////////
    public static final OrgWideEmailAddress THE_KNOT_ACC_ORG_WIDE_ADDR;
    private static final Map<Date, Invoice_Past_Due_Config__c> PAST_DUE_DATE_MAP;
    private static final Map<String, EmailTemplate> EMAIL_TEMPLATE_MAP;

    ////////////////////////////
    // PUBLIC CLASS VARIABLES //
    ////////////////////////////
    public String query; 
    public List<String> emailAttachmentAuthFormIdList;
    
    /////////////////////////////
    // PRIVATE CLASS VARIABLES //
    /////////////////////////////
    private Set<Id> missingContactSet;

    // CSP-2646 Update Past Due Notices to Paid Accounts
    // retrieve the active subscription under the paid account for send the 70 days email to sales rep on the subscription.
    // only send email to paid account for the past due balance
    private static final String queryStr = ' SELECT '
                                            +   'Id, '
                                            +   'Name, '
                                            +   'Longest_Past_Due_Date__c, '
                                            +   'Payment_Type__c, '
                                            +   'Customer_on_Payment_Arrangement__c, '
                                            +   'Past_Due_Balance__c, '
                                            +   'CBBS__c, '
                                            +   'CBBS__r.IsActive, '
                                            +   'CBBS__r.Name, '
                                            +   'CBBS__r.Email, '
                                            +   'CBBS__r.Phone, '
                                            +   'Owner.IsActive, '
                                            +   'OwnerId, '
                                            +   'Owner.ARR__c, '
                                            +   'Owner.Email, '
                                            +   'Owner.Arr__r.IsActive, '
                                            +   'Owner.ARR__r.Name, '
                                            +   'Owner.ARR__r.Email, '
                                            +   'Owner.ARR__r.Phone, '
                                            +   '( '
                                                +   'SELECT '
                                                    +   'Id, '
                                                    +   'Zuora__Account__c, '
                                                    +   'Zuora__BillToName__c, '
                                                    +   'Bill_To_Contact__c, '
                                                    +   'Bill_To_Contact__r.Email, '
                                                    +   'Bill_To_Contact__r.FirstName, '
                                                    +   'Zuora__BillToWorkEmail__c '
                                                +   'FROM '
                                                    +   'Zuora__R00N40000001kyLcEAI__r '
                                            +   '), '
                                            +   '( '
                                                +   'SELECT '
                                                    +   'Id, '
                                                    +   'Sales_Rep__c, '
                                                    +   'Sales_Rep__r.Email, '
                                                    +   'Sales_Rep__r.IsActive '
                                                +   'FROM '
                                                    +   'Zuora__Subscriptions__r '
                                                +   'WHERE '
                                                    +   'Zuora__TermEndDate__c > TODAY'
                                            +   ') '
                                        +   'FROM '
                                            +   'Account '
                                        +   'WHERE '
                                            +   'Past_Due_Balance__c > 10.00 '
                                        +   'AND '
                                            +   'Customer_on_Payment_Arrangement__c = false '
                                        +   'AND '
                                            +   'Local_Paid_Status__c = \'Paid\'' 
                                        +   'AND '
                                            +'{WHERECLAUSE}';
    ////////////////////////
    // STATIC INITIALIZER //
    ////////////////////////
    static {
        List<XO_Exception__c> exceptionList = new List<XO_Exception__c>();

        try {
            THE_KNOT_ACC_ORG_WIDE_ADDR = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address = 'theknotaccounting@xogrp.com' LIMIT 1];
        } catch (Exception e) {
            XO_Exception__c xoException = ExceptionUtility.consumeException(e, false);
            xoException.Severity__c = 'Critical';
            xoException.Failure_Area__c = 'Email Notification';

            exceptionList.add(xoException);
        }

        // RETRIEVE ALL NEEDED EMAL TEMPLATES
        List<EmailTemplate> emailTemplateList = [SELECT Id, DeveloperName FROM EmailTemplate WHERE DeveloperName IN ('Past_Due_Warning', 'Past_Due_Warning_Cancel')];
        Map<String, EmailTemplate> tempEmailTemplateMap = new Map<String, EmailTemplate>();
        for(Integer i = 0; i < emailTemplateList.size(); i++) {
            EmailTemplate currentTemplate = emailTemplateList[i];
            tempEmailTemplateMap.put(currentTemplate.DeveloperName, currentTemplate);
        }

        EMAIL_TEMPLATE_MAP = tempEmailTemplateMap;

        // CUSTOM SETTING RETRIEVAL AND MAP BUILDING
        Map<String, Invoice_Past_Due_Config__c> pastDueConfigMap = Invoice_Past_Due_Config__c.getAll();
        List<Invoice_Past_Due_Config__c> pastDueList = pastDueConfigMap.values();
        Map<Date, Invoice_Past_Due_Config__c> tempDateMap = new Map<Date, Invoice_Past_Due_Config__c>();
        for(Integer i = 0; i < pastDueList.size(); i++) {
            Invoice_Past_Due_Config__c currentPastDueCustomSetting = pastDueList[i];
            Date previousDate = Date.today().addDays((Integer)currentPastDueCustomSetting.Number_Of_Days_Past_Due__c * -1);
            tempDateMap.put(previousDate, currentPastDueCustomSetting);
        }

        // Set the final value for the map
        PAST_DUE_DATE_MAP = tempDateMap;

        insert exceptionList;
    }
    
    global BatchAccountPastDueBalanceEmailsAndTasks() {
        missingContactSet = new Set<Id>();

        // Transform Map keyset into Date list then send to method which builds query
        query = generateAccountPDBQueryString(new List<Date>(PAST_DUE_DATE_MAP.keySet()));

        // set attachment doc id
        emailAttachmentAuthFormIdList = new List<String>();
        for (Document authDoc : [SELECT Id FROM Document WHERE Name = 'TheKnot CC ACH Authorization Form' LIMIT 1]) {
            emailAttachmentAuthFormIdList.add(String.valueOf(authDoc.Id));
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Database.QueryLocator retVal = Database.getQueryLocator(query);
        return retVal;
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        // Retrieve fallback user for notifications
        User fallbackUser = getFallbackTaskUser();

        List<Messaging.SingleEmailMessage> emailList= new List<Messaging.SingleEmailMessage>();
        List<Task> taskList = new List<Task>();
        
        for(Account acc: scope) {
            if(!PAST_DUE_DATE_MAP.containsKey(acc.Longest_Past_Due_Date__c)) {
                continue;
            }

            Invoice_Past_Due_Config__c currentPastDueConfig = PAST_DUE_DATE_MAP.get(acc.Longest_Past_Due_Date__c);

            Integer daysLate = (Integer)currentPastDueConfig.Number_Of_Days_Past_Due__c;
            
            // CSP-2431 : Duplicate Past Due Tasks; We only created ONE task for an account
            // If the custom setting "Create ARR Task" value is checked then create a task for the Account ARR
            if (currentPastDueConfig.Create_ARR_Task__c) {
                createTask(acc, daysLate, taskList, fallbackUser);
            }
            
            // csp-2032 :dupEmailsSet was added to prevent multiple emails to be send for multiple billing accounts with the same email
            Set<String> dupEmailsSet = new Set<String>();
            
            for(Zuora__CustomerAccount__c billingAccountRec : acc.R00N40000001kyLcEAI) {
                // CSP-2294 - Skip records who end with .UAT to prevent hitting limits in test environment
                if(String.isNotBlank(billingAccountRec.Bill_To_Contact__r.Email) && 
                    billingAccountRec.Bill_To_Contact__r.Email.endsWith('.uat')) {
                    continue;
                }
                
                // if the contact is null, notify the administrator via email about the missing contact and then move on to the 
                // next record in the loop
                if(String.isBlank(billingAccountRec.Bill_To_Contact__c)) {
                    missingContactSet.add(billingAccountRec.Id);
                    continue;
                }
                
                // If the custom setting has the value "Send Email to Customer" checked then send email
                if(currentPastDueConfig.Send_Email_To_Customer__c && !dupEmailsSet.contains(billingAccountRec.Bill_To_Contact__r.Email)) {
                    createEmail(acc, billingAccountRec.Bill_To_Contact__c, daysLate, emailList);
                    dupEmailsSet.add(billingAccountRec.Bill_To_Contact__r.Email);
                }
                
                // Comment for ticket CSP-2431, the task is created for Account not for every Billing account, so this logig move out from the billing account loop
                // If the custom setting "Create ARR Task" value is checked then create a task for the Account ARR
                // if (currentPastDueConfig.Create_ARR_Task__c) {
                //     createTask(acc, daysLate, taskList, fallbackUser);
                // }
                // If the custom setting "Send Email To Account Owner" value is checked then send an email to the Account Owner
                if(currentPastDueConfig.Send_Email_To_Account_Owner__c && !dupEmailsSet.contains(billingAccountRec.Bill_To_Contact__r.Email)) {
                    emailList.add(createAccountOwnerEmail(acc));
                    dupEmailsSet.add(billingAccountRec.Bill_To_Contact__r.Email);
                }
            }
        }
        
        List<XO_Exception__c> xoExceptionList = new List<XO_Exception__c>();
        
        //send email to the customer
        if(!emailList.isEmpty()) {
            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailList, false);
            // CSP-2905 Notification for Failed Emails
            xoExceptionList.addAll(ExceptionUtility.consumeException(results, Label.Past_Due_Email_Exception));
        }

        //Try inserting all the task in the taskList.. Ignore those records which cannot be inserted due to certain error
        if(!taskList.isEmpty()) {
            Database.SaveResult[] srList = Database.Insert(taskList, false);
            xoExceptionList.addAll(ExceptionUtility.consumeException(srList));
        }

        if(xoExceptionList.size() >0){
            insert xoExceptionList;
        }
    }
    
    /**
     *   [createTask: This method is used to create a task by using date from the account]
     *   @author [Ruchit S]
     *   @date   2017-08-13
     *   @param  {[type]}   acc              [current account]
     *   @param  {[type]}   contactId        [contact id]
     *   @param  {[type]}   daysLate         [number of days the customer is late from making the payments]
     *   @param  {[type]}   emailsToSendList [list of emails to be send]
     */
    private void createEmail(Account acc, Id contactId, Integer daysLate, List<Messaging.SingleEmailMessage> emailsToSendList) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setTargetObjectId(contactId);
        if(daysLate < 60) {
            EmailTemplate pastDueTemplate = EMAIL_TEMPLATE_MAP.get('Past_Due_Warning');
            email.setTemplateId(pastDueTemplate.Id);
        } else {
            EmailTemplate pastDueTemplate = EMAIL_TEMPLATE_MAP.get('Past_Due_Warning_Cancel');
            email.setTemplateId(pastDueTemplate.Id);
        }                       
        email.setWhatId(acc.Id);
        // CSP-2416 : customer to be able to reply to past due notifications and have the CBSS receive it.
        if(String.isNotBlank(acc.CBBS__c) && String.isNotBlank(acc.CBBS__r.Email)){
            email.setReplyTo(acc.CBBS__r.Email);
        }
        email.setSaveAsActivity(true); // save email as activity on the targetObjId (i.e. Contact)
        if (daysLate >= 45) {
            List<String> ccEmailAddresses = new List<String>();
            ccEmailAddresses.add(acc.Owner.Email);
            email.setCcAddresses(ccEmailAddresses);
        }
        email.setOrgWideEmailAddressId(THE_KNOT_ACC_ORG_WIDE_ADDR.Id);
        emailsToSendList.add(email);
    }

    public static Messaging.SingleEmailMessage createAccountOwnerEmail(Account acc) {
        Messaging.SingleEmailMessage accountOwnerEmail = new Messaging.SingleEmailMessage();
                
        String title = Label.UPCOMING_CANCELLATION;
        String body = Label.PAST_DUE_85_DAYS + '\n'
        + '<br/><br/> Account Name: ' + acc.Name + '\n'
        + '<br/> Past Due Amount: ' + acc.Past_Due_Balance__c;

        accountOwnerEmail.setHtmlBody(EmailUtility.createEmailBody(title, body));
        accountOwnerEmail.setSubject(title);

        // CSP-2646 Update Past Due Notices to Paid Accounts
        // send 70 days email to the sales rep of active subscripiton under the account
        List<String> toAddressesList = new List<String>();
        Set<String> salesEmailDupeSet = new Set<String>();
        if (!acc.Zuora__Subscriptions__r.isEmpty()) {
            for (Zuora__Subscription__c cuurentSub :  acc.Zuora__Subscriptions__r) {
                if (!salesEmailDupeSet.contains(cuurentSub.Sales_Rep__r.Email)) {
                    toAddressesList.add(cuurentSub.Sales_Rep__r.Email);
                    salesEmailDupeSet.add(cuurentSub.Sales_Rep__r.Email);
                }
            }
        }
        else{
            toAddressesList.add(acc.Owner.Email);
        }

        accountOwnerEmail.setToAddresses(toAddressesList);

        // CSP-2416 : customer to be able to reply to past due notifications and have the CBSS receive it.
        if(String.isNotBlank(acc.CBBS__c) && String.isNotBlank(acc.CBBS__r.Email)){
            accountOwnerEmail.setReplyTo(acc.CBBS__r.Email);
        }
        accountOwnerEmail.setWhatId(acc.Id);
        accountOwnerEmail.setSaveAsActivity(true);
        accountOwnerEmail.setOrgWideEmailAddressId(THE_KNOT_ACC_ORG_WIDE_ADDR.Id);

        return accountOwnerEmail;
    }
    
    /**
     *   [createTask: This method is used to create a task by using data from the current account]
     *
     *   @author [Ruchit S]
     *   @date   2017-08-13
     */
    private void createTask(Account acc, Integer daysLate, List<Task> tasksToBeInsertedList, User fallbackUser){
        Task tsk = new Task();
        tsk.ActivityDate = Date.Today();
        tsk.WhatId = acc.Id;
        tsk.Type = 'Other';
        tsk.Purpose__c = 'Other';
        tsk.Status = 'Not Started';
        tsk.Subject = 'Account : '+ acc.Name + ' is ' + String.valueOf(daysLate) + ' days past Due date';
        tsk.Description = 'Account : '+ acc.Name + ' is ' + String.valueOf(daysLate) + ' days past Due date';

        // Determine what User should be assigned as the owner of the newly created task. Only Active Users can
        // have a task assigned to them. The next assignment order will be used if a User is found to not be
        // active. System Administrator is the final assignment option.
        // Order of assignment:
        //  1. Account CBSS
        //  2. Account Owner ARR
        //  3. Account Owner
        //  4. "Brandi Rojas" (CSP-1540)
        //  5. "System Administrator"
        if(String.isNotBlank(acc.CBBS__c) && acc.CBBS__r.IsActive) {
            tsk.OwnerId = acc.CBBS__c;
        } else if(String.isNotBlank(acc.Owner.ARR__c) && acc.Owner.ARR__r.IsActive) {
            tsk.OwnerId = acc.Owner.Arr__c;
        } else if(acc.Owner.IsActive) {
            tsk.OwnerId = acc.OwnerId;
        } else {
            tsk.OwnerId = fallbackUser.Id;
            // Adding additional message on Description field to dictate why this Task was assigned to them.
            tsk.Description += '\r\n'
                            +   'This task is being assigned you as all other available Users for assignment '
                            +   'on this Account were inactive or invalid.';
        }

        tasksToBeInsertedList.add(tsk);
    }

    //////////////////
    // FINISH BLOCK //
    //////////////////
    global void finish(Database.BatchableContext BC) {
        // If the contact set has values generate an email with an attachment to send to Sales Support
        if(!missingContactSet.isEmpty()) {
            BatchCCDeclinedReminder.notifyAdminAboutMissingContact(new List<Id>(missingContactSet));
            //notifyAdminAboutMissingContact(new List<Id>(missingContactSet));
        }

        // run the BatchCCDeclinedReminder job
        // CSP-2032
        // Set batch size from default(200) to 50. The sendEmail method is inserting a task in a FOR loop for every successful email
        // that is sent. This is causing the Task trigger to fire for every email that is sent. 
        Database.executebatch(new BatchCCDeclinedReminder(), 50);
    }
    
    private String generateAccountPDBQueryString(List<Date> dateList) {
        // futureDate is used as a default value for the query, this is used so in the event that the custom
        // setting doesn't contain any values, the query will still be valid but won't return any results 
        Date futureDate = Date.today().addDays(100);
        String baseQuery = queryStr;

        String whereClauseStr = '(Longest_Past_Due_Date__c = ' + String.valueOf(futureDate);
        for (Date overdueDate : dateList) {
            whereClauseStr += (' OR Longest_Past_Due_Date__c = ' + String.valueOf(overdueDate));
        }
        whereClauseStr += ')';

        baseQuery = baseQuery.replace('{WHERECLAUSE}', whereClauseStr);

        return baseQuery;
    }

    /**
     *   Method used to retrieve a fallback user which will be used if no other user is available. The current fallback
     *   User is "Brandi Rojas" as per CSP-1540 but also there is another fallback to a System Administrator in case
     *   the "Brandi Rojas" user goes inactive.
     *
     *   @author Justin
     *   @date   2016-11-04
     *   @return {User}     The fallback user which was found.
     */
    private static User getFallbackTaskUser() {
        for(User fallbackUser : [SELECT Id, Name FROM User WHERE Username = 'brojas@xogrp.com' AND IsActive = true LIMIT 1]) {
            return fallbackUser;
        }

        for(User fallbackUser : [SELECT Id, Name FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1]) {
            return fallbackUser;
        }

        return null;
    }
}