src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Plan to Deprecated for CSP-2731
Phase 1</description>
        <label>Region</label>
        <picklist>
            <controllingField>ConciergeState__c</controllingField>
            <picklistValues>
                <fullName>Appalachian Plateau</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlanta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Suburb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Suburbs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central East FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Pittsburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Valley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central West FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chesapeake Bay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal Plain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>​Dallas/Fort Worth​</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Same_Address_as_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the address will update every time the Account address changes.  Be sure to uncheck this if you make a custom address, or it will be overwritten the next time the Account is changed.</inlineHelpText>
        <label>Same Address as Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Generate_Quote_Pdf_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Generate Quote Pdf Config</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_AR_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1511. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - AR&quot; user lookup field and assigns an approval Task to the selected user.</description>
        <inlineHelpText>SF-1511. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - AR&quot; user lookup field and assigns an approval Task to the selected user.</inlineHelpText>
        <label>Approval Process Assignment - AR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Manager_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1506. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - Manager&quot; user lookup field and assigns an approval Task to the selected user.</description>
        <inlineHelpText>SF-1506. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - Manager&quot; user lookup field and assigns an approval Task to the selected user.</inlineHelpText>
        <label>Approval Process Assignment - Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact who signs the contract in EchoSign.</inlineHelpText>
        <label>Contract Signer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lock_Quotes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lock Quotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Three_Business_Days_From_Today__c</fullName>
        <description>Used in &quot;Send For Signature&quot; validation</description>
        <label>EchoSign Expiration Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Fulfillment_Response__c.object
<CustomObject>
    <label>Partner Fulfillment Response</label>
    <nameField>
        <displayFormat>PFR-{0000000}</displayFormat>
        <label>Partner Fulfillment Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Fulfillment Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchedulableTestClass.cls
@isTest
private class SchedulableTestClass {
	
	@isTest static void schFulfillmentResponseDeletion() {
	  /*Partner_Fulfillment_Response__c testPartnerFulfillment = new Partner_Fulfillment_Response__c();
    testPartnerFulfillment.CreatedDate = DateTime.newInstance(Date.today().addMonths(-2), Time.newInstance(0, 0, 0, 0));
    insert testPartnerFulfillment;*/
    
    SchFulfillmentResponseDeletion fulSch = new SchFulfillmentResponseDeletion();
    fulSch.execute(null);
	}

  @isTest static void schEchoSignNotification() {
    List<RecordType> recordTypes = [select Id, Name, sObjectType from RecordType where name like '%local%' and IsActive = true];
    Map<String, RecordType> objectTypeToRecordTypeMap = new Map<String, RecordType>();
    for(Integer i = 0; i < recordTypes.size(); i++) {
      RecordType currentRT = recordTypes[i];
      objectTypeToRecordTypeMap.put(currentRT.sObjectType, currentRT);
    }

    User currentUser = [Select Id, FirstName, LastName, UserName, Email, Phone, ManagerID from User where id != :UserInfo.getUserId() AND isActive = true AND ManagerID != null limit 1];

    Generate_Quote_Pdf_Config__c newGQP = new Generate_Quote_Pdf_Config__c();
    newGQP.Name = 'Production';
    newGQP.URL__c = 'http://www.xogrpinc.com';
    insert newGQP;

    // AccountLocalTriggerHandler Line 17 dependancy. Wtf?
    Market__c testMarket = new Market__c();
    testMarket.Market_ID__c = '222';
    testMarket.Short_Description__c = 'Blah';
    insert testMarket;

    Account testAccount = new Account();
    testAccount.Name = 'Test Account';
    testAccount.Region__c = 'Test Region';
    testAccount.OwnerId = currentUser.Id;
    if(objectTypeToRecordTypeMap.containsKey('Account')) {
      RecordType accRT = objectTypeToRecordTypeMap.get('Account');
      testAccount.RecordTypeId = accRT.Id;
    }
    insert testAccount;

    Opportunity testOpp = new Opportunity();
    testOpp.Name = 'Test Opportunity';
    testOpp.AccountId = testAccount.Id;
    testOpp.CloseDate = Date.Today()-10;
    testOpp.StageName = 'Prospecting';
    testOpp.Opportunity_Expiration_Date__c = Date.today();
    testOpp.Approval_Process_AR_Assignment__c = False;
    testOpp.Approval_Process_Manager_Assignment__c = False;
    testOpp.Three_Business_Days_From_Today__c = DateUtility.addBusinessDays(Date.today(), -1);
    testOpp.Lock_Quotes__c = False;
    if(objectTypeToRecordTypeMap.containsKey('Opportunity')) {
      RecordType oppRT = objectTypeToRecordTypeMap.get('Opportunity');
      testOpp.RecordTypeId = oppRT.Id;
    }
    insert testOpp;

    Contact testContact = new Contact();
    testContact.Same_Address_as_Account__c = true;
    testContact.LastName = 'test';
    testContact.Email = 'abc@invalid1gmail.com';
    testContact.AccountId = testAccount.Id;
    insert testContact;

    testOpp.StageName = 'Pending Client Approval';
    testOpp.Contract_Signer__c = testContact.Id;
    update testOpp;
    // Expired notification email
    Test.startTest();
      SchEchoSignNotification echoSch = new SchEchoSignNotification();
      echoSch.execute(null);
    Test.stopTest();

    // Two Day notification email
    testOpp.Three_Business_Days_From_Today__c = DateUtility.addBusinessDays(Date.today(), 2);
    update testOpp;
    SchEchoSignNotification echoSch2 = new SchEchoSignNotification();
    echoSch2.execute(null);
  }
}