src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>Phase 1 National</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>text(Primary_Category__r.Category_Group__c)</formula>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DynamicsLeadID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Dynamics Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroArea__c</fullName>
        <formula>Zip__r.MetroArea__r.Name</formula>
        <label>Metro Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SubCategory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taxonomy_ID__c</fullName>
        <description>Taxonomy GUID (Length must be 36 characters including hyphens)</description>
        <externalId>true</externalId>
        <inlineHelpText>Taxonomy ID</inlineHelpText>
        <label>Taxonomy ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/Generate_Quote_Pdf_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Generate Quote Pdf Config</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>text(Primary_Category__r.Category_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DynamicsLeadID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Dynamics Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select active Markets within the Primary Brand</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select an active Category</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Local_Sales_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zip Code</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Local Sales Rep Assignment</label>
    <nameField>
        <label>Local Sales Rep Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Sales Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a sales rep</errorMessage>
            <filterItems>
                <field>User.Division</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroArea__c.object
<CustomObject>
    <label>Metro Area</label>
    <nameField>
        <label>Metro Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metro Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XO_Group_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Turn_on_Fulfillment_Callouts__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Turns on and off partner fulfillment and account update callouts.</inlineHelpText>
        <label>Turn on Fulfillment Callouts</label>
        <type>Checkbox</type>
    </fields>
    <label>XO Group Settings</label>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <fields>
        <fullName>Local_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Zips</relationshipLabel>
        <relationshipName>Zips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroArea__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metro Area</label>
        <referenceTo>MetroArea__c</referenceTo>
        <relationshipLabel>Zips</relationshipLabel>
        <relationshipName>Zips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code (External ID)</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadManualStorefrontFulfillmentCTest.cls
@isTest
public class LeadManualStorefrontFulfillmentCTest {
    public static testMethod void test_method_one() {
        
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
        
        Generate_Quote_Pdf_Config__c GQPF = new Generate_Quote_Pdf_Config__c();
        GQPF.name = 'Production';
        GQPF.URL__c = 'www.baidu.com';
        insert GQPF;

        Market__c testMarket = new Market__c();
        testMarket.Name = 'Test Market';
        testMarket.Short_Description__c = 'Test Market';
        testMarket.Market_ID__c = '222';
        testMarket.Active__c = true;
        insert testMarket;
        
        // CSP-1999 
        // Brand__c testBrand = new Brand__c();
        // testBrand.RecordTypeId = Schema.SObjectType.Brand__c.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        // testBrand.Name = 'Test Knot Brand';
        // testBrand.Active__c = true;
        // insert testBrand;
        
        Category__c testCategory = new Category__c();
        testCategory.Active__c = true;
        testCategory.RecordTypeId = rtCategoryMapByName.get('Local').getRecordTypeId();
        testCategory.Name = 'Test Category';
        testCategory.Short_Description__c = 'Test Category';
        //CSP-1999 testCategory.Primary_Brand__c = testBrand.Id;
        testCategory.Category_Group__c = 'Primary';
        testCategory.Taxonomy_ID__c = 'testcategoryId';
        insert testCategory;
        
        MetroArea__c ma = new MetroArea__c();
        ma.name = 'test';
        insert ma;
        
        Zip__c zip = new Zip__c();
        zip.MetroArea__c = ma.id;
        zip.ZipCode__c = '12121';
        Zip.name = '12121';
        Zip.Local_Market__c = testMarket.id;
        insert zip;
        
        Local_Sales_Rep_Assignment__c  lsra = new Local_Sales_Rep_Assignment__c();
        lsra.Name = 'test name';
        lsra.Category__c = testCategory.id;
        lsra.Sales_Rep__c = UserInfo.getUserId();
        lsra.Zip_Code__c = zip.id;
        insert lsra;
        
        Lead testLead = new Lead();
        testLead.FirstName='Test';
        testLead.LastName='Lead';
        testLead.Phone='12345678';
        testLead.Email='test@test.com';
        testLead.Company='Test Company';
        testLead.Local_Sales_Market__c = testMarket.id;
        testLead.Primary_Category__c = testCategory.id;
        //CSP-1999  testLead.Primary_Brand__c = testBrand.id;
        testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
        testLead.PostalCode = zip.ZipCode__c;
        testLead.DynamicsLeadID__c = 'testDynamicsLeadID';
        insert testLead;
        
        Test.startTest();
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"locations": null,"errors": [{"message":"error message"}]}',
                                                 null);
        Test.setMock(HttpCalloutMock.class,fakeResponse );
        test.setCurrentPageReference(Page.LeadManualStorefrontFulfillment);
        ApexPages.StandardController sc = new ApexPages.StandardController(testLead);
        LeadManualStorefrontFulfillmentContr testcase = new LeadManualStorefrontFulfillmentContr(sc); 

        testcase.fulfillStorefront();
        testcase.saveData();
        testcase.recordPageRedirect();
        
        Test.stopTest();
    }
    
    public static testMethod void test_method_two() {
        
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
        
        Generate_Quote_Pdf_Config__c GQPF = new Generate_Quote_Pdf_Config__c();
        GQPF.name = 'Production';
        GQPF.URL__c = 'www.baidu.com';
        insert GQPF;
        
        

        Market__c testMarket = new Market__c();
        testMarket.Name = 'Test Market';
        testMarket.Short_Description__c = 'Test Market';
        testMarket.Market_ID__c = '222';
        testMarket.Active__c = true;
        insert testMarket;
        
        
        // Brand__c testBrand = new Brand__c();
        // testBrand.RecordTypeId = Schema.SObjectType.Brand__c.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        // testBrand.Name = 'Test Knot Brand';
        // testBrand.Active__c = true;
        // insert testBrand;
        
        Category__c testCategory = new Category__c();
        testCategory.Active__c = true;
        testCategory.RecordTypeId = rtCategoryMapByName.get('Local').getRecordTypeId();
        testCategory.Name = 'Test Category';
        testCategory.Short_Description__c = 'Test Category';
        //CSP-1999  testCategory.Primary_Brand__c = testBrand.Id;
        testCategory.Category_Group__c = 'Primary';
        testCategory.Taxonomy_ID__c = 'testcategoryId';
        insert testCategory;
        
        MetroArea__c ma = new MetroArea__c();
        ma.name = 'test';
        insert ma;
        
        Zip__c zip = new Zip__c();
        zip.MetroArea__c = ma.id;
        zip.ZipCode__c = '12121';
        Zip.name = '12121';
        Zip.Local_Market__c = testMarket.id;
        insert zip;
        
        Local_Sales_Rep_Assignment__c  lsra = new Local_Sales_Rep_Assignment__c();
        lsra.Name = 'test name';
        lsra.Category__c = testCategory.id;
        lsra.Sales_Rep__c = UserInfo.getUserId();
        lsra.Zip_Code__c = zip.id;
        insert lsra;
        
        Lead testLead = new Lead();
        testLead.FirstName='Test';
        testLead.LastName='Lead';
        testLead.Phone='12345678';
        testLead.Email='test@test.com';
        testLead.Company='Test Company';
        testLead.Local_Sales_Market__c = testMarket.id;
        testLead.Primary_Category__c = testCategory.id;
        //CSP-1999  testLead.Primary_Brand__c = testBrand.id;
        testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
        testLead.PostalCode = zip.ZipCode__c;
        testLead.DynamicsLeadID__c = 'testDynamicsLeadID';
        insert testLead;
        
        Deactivate_Trigger__c dt = new Deactivate_Trigger__c();
        dt.name = 'Note';
        dt.After_Delete__c = false;
        dt.After_Insert__c = false;
        dt.After_Update__c = false;
        dt.Before_Delete__c = false;
        dt.Before_Insert__c = false;
        dt.Before_Update__c = false;
        insert dt;
        
        XO_Group_Settings__c xoSetting = XO_Group_Settings__c.getInstance();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        upsert xoSetting;
        
        Test.startTest();
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"locations": [{"locationId":"locationId", "fulfilledStorefronts":null, "errors": [{"message":"error message"}]}],"errors": null}',
                                                 null);
        Test.setMock(HttpCalloutMock.class,fakeResponse );
        test.setCurrentPageReference(Page.LeadManualStorefrontFulfillment);
        ApexPages.StandardController sc = new ApexPages.StandardController(testLead);
        LeadManualStorefrontFulfillmentContr testcase = new LeadManualStorefrontFulfillmentContr(sc); 
        
        
        testcase.fulfillStorefront();
        
        Test.stopTest();
    }
    
    public static testMethod void test_method_three() {
        
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtCategoryMapByName = Schema.SObjectType.Category__c.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
        
        Generate_Quote_Pdf_Config__c GQPF = new Generate_Quote_Pdf_Config__c();
        GQPF.name = 'Production';
        GQPF.URL__c = 'www.baidu.com';
        insert GQPF;
        
        XO_Group_Settings__c xoSetting = XO_Group_Settings__c.getInstance();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        upsert xoSetting;
        
        
        Market__c testMarket = new Market__c();
        testMarket.Name = 'Test Market';
        testMarket.Short_Description__c = 'Test Market';
        testMarket.Market_ID__c = '222';
        testMarket.Active__c = true;
        insert testMarket;
        
        // CSP-1999 
        // Brand__c testBrand = new Brand__c();
        // testBrand.RecordTypeId = Schema.SObjectType.Brand__c.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        // testBrand.Name = 'Test Knot Brand';
        // testBrand.Active__c = true;
        // insert testBrand;
        
        Category__c testCategory = new Category__c();
        testCategory.Active__c = true;
        testCategory.RecordTypeId = rtCategoryMapByName.get('Local').getRecordTypeId();
        testCategory.Name = 'Test Category';
        testCategory.Short_Description__c = 'Test Category';
        //CSP-1999  testCategory.Primary_Brand__c = testBrand.Id;
        testCategory.Category_Group__c = 'Primary';
        testCategory.Taxonomy_ID__c = 'testcategoryId';
        insert testCategory;
        
        MetroArea__c ma = new MetroArea__c();
        ma.name = 'test';
        insert ma;
        
        Zip__c zip = new Zip__c();
        zip.MetroArea__c = ma.id;
        zip.ZipCode__c = '12121';
        Zip.name = '12121';
        Zip.Local_Market__c = testMarket.id;
        insert zip;
        
        Local_Sales_Rep_Assignment__c  lsra = new Local_Sales_Rep_Assignment__c();
        lsra.Name = 'test name';
        lsra.Category__c = testCategory.id;
        lsra.Sales_Rep__c = UserInfo.getUserId();
        lsra.Zip_Code__c = zip.id;
        insert lsra;
        
        Lead testLead = new Lead();
        testLead.FirstName='Test';
        testLead.LastName='Lead';
        testLead.Phone='12345678';
        testLead.Email='test@test.com';
        testLead.Company='Test Company';
        testLead.Local_Sales_Market__c = testMarket.id;
        testLead.Primary_Category__c = testCategory.id;
        //CSP-1999  testLead.Primary_Brand__c = testBrand.id;
        testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
        testLead.PostalCode = zip.ZipCode__c;
        testLead.DynamicsLeadID__c = 'testDynamicsLeadID';
        insert testLead;
        
        Test.startTest();
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"locations": null,"errors": [{"message":"error message"}]}',
                                                 null);
        Test.setMock(HttpCalloutMock.class,fakeResponse );
        test.setCurrentPageReference(Page.LeadManualStorefrontFulfillment);
        ApexPages.StandardController sc = new ApexPages.StandardController(testLead);
        LeadManualStorefrontFulfillmentContr testcase = new LeadManualStorefrontFulfillmentContr(sc); 

        testcase.fulfillStorefront();
        Test.stopTest();
    }
    
}