src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>AccountStatus__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SoldToCountry__c</fullName>
        <description>SF-2177</description>
        <label>Sold To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToAddress1__c</fullName>
        <label>Bill To Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCity__c</fullName>
        <label>Bill To Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCountry__c</fullName>
        <label>Bill To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToPostalCode__c</fullName>
        <label>Bill To Address Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToState__c</fullName>
        <label>Bill To Address State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToWorkEmail__c</fullName>
        <label>Bill To Work E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestZuoraBillingAccountTrigger.cls
@isTest
private class TestZuoraBillingAccountTrigger{

    static testMethod void test_method_one() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Account testAccount = (Account)testData.get('Account');
        
        Zuora__CustomerAccount__c testZuoraCustomerAccount = new Zuora__CustomerAccount__c(); 
        testZuoraCustomerAccount.Name = 'Test Billing Account'; 
        testZuoraCustomerAccount.Zuora__Account__c = testAccount.id;
        testZuoraCustomerAccount.Zuora__BillToAddress1__c = '123 ABC Dr';
        testZuoraCustomerAccount.Zuora__BillToCity__c = 'Austin'; 
        testZuoraCustomerAccount.Zuora__BillToCountry__c = 'United States';  
        testZuoraCustomerAccount.Zuora__BillToName__c = 'Test'; 
        testZuoraCustomerAccount.Zuora__BillToPostalCode__c = '77857'; 
        testZuoraCustomerAccount.Zuora__BillToState__c = 'Texas'; 
        testZuoraCustomerAccount.Zuora__BillToWorkEmail__c = 'abc@gmail.com';  
        testZuoraCustomerAccount.Zuora__Zuora_Id__c = '2c92c0f94ed8d0d7014ee476a6e419ee'; 
        testZuoraCustomerAccount.AccountStatus__c = 'Active';
        insert testZuoraCustomerAccount;
         
    }


    static testMethod void test_method_two() {   
        
        Zuora__CustomerAccount__c testZuoraCustomerAccount1 = new Zuora__CustomerAccount__c(); 
        testZuoraCustomerAccount1.Name = 'Test Billing Account'; 
        testZuoraCustomerAccount1.Zuora__BillToAddress1__c = '123 ABC Dr';
        testZuoraCustomerAccount1.Zuora__BillToCity__c = 'Austin'; 
        testZuoraCustomerAccount1.Zuora__BillToCountry__c = 'United States';  
        testZuoraCustomerAccount1.Zuora__BillToName__c = 'Test'; 
        testZuoraCustomerAccount1.Zuora__BillToPostalCode__c = '77857'; 
        testZuoraCustomerAccount1.Zuora__BillToState__c = 'Texas'; 
        testZuoraCustomerAccount1.Zuora__BillToWorkEmail__c = 'abc@gmail.com';  
        testZuoraCustomerAccount1.Zuora__Zuora_Id__c = '2c92c0f94ed8d0d7014ee476a6e419ee'; 
        testZuoraCustomerAccount1.AccountStatus__c = 'Active';
        testZuoraCustomerAccount1.SoldToCountry__c = 'USA';

        Zuora__CustomerAccount__c testZuoraCustomerAccount2 = new Zuora__CustomerAccount__c(); 
        testZuoraCustomerAccount2.Name = 'Test Billing Account'; 
        testZuoraCustomerAccount2.Zuora__BillToAddress1__c = '123 ABC Dr';
        testZuoraCustomerAccount2.Zuora__BillToCity__c = 'Austin'; 
        testZuoraCustomerAccount2.Zuora__BillToCountry__c = 'United States';  
        testZuoraCustomerAccount2.Zuora__BillToName__c = 'Test'; 
        testZuoraCustomerAccount2.Zuora__BillToPostalCode__c = '77857'; 
        testZuoraCustomerAccount2.Zuora__BillToState__c = 'Texas'; 
        testZuoraCustomerAccount2.Zuora__BillToWorkEmail__c = 'abc@gmail.com';  
        testZuoraCustomerAccount2.Zuora__Zuora_Id__c = '2c92c0f94ed8d0d7014ee476a6e419ee'; 
        testZuoraCustomerAccount2.AccountStatus__c = 'Active';
        testZuoraCustomerAccount1.SoldToCountry__c = 'Finland';
        

        ZuoraBillingAccountTriggerHandler.setUpdateContactsFlagOnContactUpdate(testZuoraCustomerAccount1, testZuoraCustomerAccount2);
    }
}