src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feature_Requested_Cancelled__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested Cancelled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Product_Charge_Number__c</fullName>
        <label>Sub Product Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>CaseID + SubsProductChargeID</description>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Feature Requested Cancelled</label>
    <nameField>
        <displayFormat>FRC-{00000}</displayFormat>
        <label>Feature Requested Cancelled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Requested Cancelled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseDAOTest.cls
@IsTest
private class CaseDAOTest {
  @IsTest
  static void testGetRecordTypeByNameSuccess() {
    String name = '1 - Cancels';

    Test.startTest();
    RecordType rts = RecordTypeDAO.getInstance().getRecordTypeByName(name);
    Test.stopTest();

    System.assert(rts != null, 'Should return item.');
  }

  @IsTest
  static void testGetCaseByAccountAndRecordType() {
    List<RecordType> cancelRecordTypes = [SELECT
        Id
      FROM RecordType
      WHERE Name = '1 - Cancels'
    ];

    Account acc = new Account();
    acc.Name = 'Account Temp';
    insert acc;

    Contact cont = new Contact();
    cont.FirstName = 'Test';
    cont.LastName = 'Contact';
    cont.AccountId = acc.Id;
    insert cont;

    Case cancelledCase = new Case();
    cancelledCase.AccountId = acc.Id;
    cancelledCase.RecordTypeId = cancelRecordTypes.get(0).Id;
    cancelledCase.Origin = 'Phone';
    cancelledCase.ContactId = cont.Id;
    insert cancelledCase;

    Test.startTest();
    Case c = CaseDAO.getInstance().getCaseByAccountAndRecordType(acc.Id, cancelRecordTypes.get(0).Id);
    Test.stopTest();

    System.assert(c != null, 'Should return contact.');
    System.assertEquals('Phone', c.Origin, 'Should have correct origin.');
    System.assertEquals(cont.Id, c.ContactId, 'Should have contact id.');
    System.assertEquals(acc.Id, c.AccountId, 'Should have account id.');
  }

  @IsTest
  static void testUpsertCase() {
    Account acc = new Account();
    acc.Name = 'Temp Account';
    insert acc;

    Contact cont = new Contact();
    cont.FirstName = 'Test';
    cont.LastName = 'Contact';
    cont.AccountId = acc.Id;
    insert cont;

    Case c = new Case();
    insert c;
    c.Origin = 'Web';
    c.ContactId = cont.Id;

    Test.startTest();
    Case newCase = CaseDAO.getInstance().upsertCase(c);
    Test.stopTest();

    System.assert(newCase != null, 'Should return case');
    System.assertEquals('Web', newCase.Origin, 'Should have correct origin.');
    System.assertEquals(cont.Id, newCase.ContactId, 'Should have correct contact id.');
  }

  @IsTest
  static void testgetWithFeatureRequestCanceled() {

    Account acc = new Account();
    acc.Name = 'Temp Account';
    insert acc;

    Contact cont = new Contact();
    cont.FirstName = 'Test';
    cont.LastName = 'Contact';
    cont.AccountId = acc.Id;
    insert cont;

    Case c = new Case();
    c.Origin = 'Web';
    c.ContactId = cont.Id;
    insert c;

    Feature_Requested_Cancelled__c frc = new Feature_Requested_Cancelled__c();
    frc.Case__c = c.Id;
    frc.Status__c = 'Cancelled';
    frc.UniqueId__c = 'abc123';
    frc.Sub_Product_Charge_Number__c = 'a1b2c3';
    insert frc;

    Test.startTest();
    Case testCase = CaseDAO.getInstance().getWithFeatureRequestCancelled(c.Id);
    Test.stopTest();

    System.assertNotEquals(testCase, null);
    System.assertEquals(1, testCase.Feature_Requested_Cancelled__r.size());
    Feature_Requested_Cancelled__c testFRC = testCase.Feature_Requested_Cancelled__r[0];
    System.assertEquals(frc.Id, testFRC.Id);
  }
}