src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Strategy_Specialist</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renew_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renew Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Preferred_Payment_Schedule__c</fullName>
        <label>Preferred Payment Schedule</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>True_TCV_JSON_Response__c</fullName>
        <description>(CSP-1181) store the JSON response returned while retrieving the Quote&apos;s true TCV amount</description>
        <label>True TCV JSON Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>True_TCV__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>(CSP-1181) Used to replace Zuora&apos;s out-of-the-box TCV functionality since it doesn&apos;t work properly in all cases</description>
        <label>True TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account associated with this Quote.</description>
        <inlineHelpText>The Account associated with this Quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__BillingCycleDay__c</fullName>
        <description>(Deprecated)</description>
        <formula>TEXT(DAY( zqu__StartDate__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>(Deprecated)</inlineHelpText>
        <label>(Deprecated)BillingCycleDay</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__InitialTerm__c</fullName>
        <description>The Initial Term of the Quote.</description>
        <inlineHelpText>The Initial Term of the Quote.</inlineHelpText>
        <label>Initial Term</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_TCV__c</fullName>
        <description>TCV value which is got by previewing the quote from Zuora</description>
        <inlineHelpText>TCV value which is got by previewing the quote from Zuora.</inlineHelpText>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionTermEndDate__c</fullName>
        <description>Only for Amendment quotes, contains the term end date of the base subscription</description>
        <inlineHelpText>The term end date of the subscription is amendment on</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraAccountID__c</fullName>
        <label>Zuora Account ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutoRenewalNotificationEmailController.cls
public with sharing class AutoRenewalNotificationEmailController {
	public Id quoteId {get;set;}
	public zqu__Quote__c zQuote {
		get{
			if (zQuote == null) {
					zQuote = new zqu__Quote__c();
			}
			List<zqu__Quote__c> quoteList = [SELECT Id,Name,zqu__Account__r.Name, Preferred_Payment_Schedule__c, zqu__BillCycleDay__c,zqu__BillingCycleDay__c, 
																					True_TCV__c, zqu__SubscriptionTermEndDate__c, 
																					zqu__Opportunity__r.Renew_Subscription__r.Zuora__NextRenewalDate__c, zqu__Account__r.Owner.FirstName, zqu__Account__r.Owner.LastName, 
																					zqu__Account__r.Owner.Email, zqu__Account__r.Owner.Phone, zqu__Account__r.Strategy_Specialist__r.LastName,
																					zqu__Account__r.Strategy_Specialist__r.FirstName, zqu__Account__r.Strategy_Specialist__r.Email,True_TCV_JSON_Response__c,
																					zqu__Account__r.Strategy_Specialist__r.Phone, zqu__Previewed_TCV__c, zqu__InitialTerm__c, zqu__ZuoraAccountID__c,zqu__TermStartDate__c 
																			FROM zqu__Quote__c 
																			WHERE Id = :quoteId limit 1];
			if (quoteList.size()>0) {
				zQuote = (zqu__Quote__c)quoteList[0];
			}
			return zQuote;
		} 
		set;
	}

	public List<String> ratePlanNameList {
		get{
			if (ratePlanNameList == null ) {
				ratePlanNameList = new List<String>();
			}
			List<zqu__QuoteRatePlan__c> quoteRatePlanList = [SELECT Name
																			FROM zqu__QuoteRatePlan__c 
																			WHERE zqu__Quote__c = :quoteId ];
			if (quoteRatePlanList.size()>0) {
				for (Integer i = 0; i< quoteRatePlanList.size(); i++) {
					zqu__QuoteRatePlan__c quoteRatePlan = (zqu__QuoteRatePlan__c)quoteRatePlanList[i];
					ratePlanNameList.add(quoteRatePlan.Name);
				}
			}
			return ratePlanNameList;
		} 
		set;
	}

	// Breakdown the True_TCV_JSON_Response__c of quote to get the total Amount to billed
	public Decimal totalAmount{
		get{
			Decimal totalAmountPeriod = 0;

			if (zQuote != null) {
				// CSP-2667 Adding more than 60 services
				// Used an attachment to store the True_TCV_JSON_Response__c if the response is too long
				// if the True_TCV_JSON_Response__c is blank, we query the response attachment
				String attName = String.valueOf(zQuote.Id) + 'JSON.txt';
				List<Attachment> attList = new List<Attachment>();
				if (String.isBlank(zQuote.True_TCV_JSON_Response__c)) {
					attList = [SELECT Id,Body FROM Attachment WHERE ParentId =: zQuote.Id AND Name = : attName LIMIT 1];
				}
				

				if (String.isNotBlank(zQuote.True_TCV_JSON_Response__c) || !attList.isEmpty()) {
					String jsonResponse = '';
					// if the True_TCV_JSON_Response__c is not blank, we use True_TCV_JSON_Response__c to generate totalAmountPeriod
					if (String.isNotBlank(zQuote.True_TCV_JSON_Response__c)){
						jsonResponse = zQuote.True_TCV_JSON_Response__c;
					}
					else{
						jsonResponse = attList[0].Body.toString();
					}
					// breakdown the response JSON
					// PaymentSchBreakdownController.ZuoraSubscPreview jsonSubPreview = (PaymentSchBreakDownController.ZuoraSubscPreview)JSON.deserialize(zQuote.True_TCV_JSON_Response__c, PaymentSchBreakDownController.ZuoraSubscPreview.class);
          PaymentSchBreakdownController.ZuoraSubscPreview jsonSubPreview = (PaymentSchBreakDownController.ZuoraSubscPreview)JSON.deserialize(jsonResponse, PaymentSchBreakDownController.ZuoraSubscPreview.class);
          List<PaymentSchBreakdownController.InvoiceItems> jsonInvoiceItems = jsonSubPreview.invoiceItems;

          // get the StartDate and Enddate
          Date subscriptionStartDate = zQuote.zqu__TermStartDate__c;
          Date subscriptionEndDate;
          if(zQuote.zqu__SubscriptionTermEndDate__c != null) {
            subscriptionEndDate = zQuote.zqu__SubscriptionTermEndDate__c;
          } else {
            subscriptionEndDate = zQuote.zqu__TermStartDate__c.addMonths(Integer.valueOf(zQuote.zqu__InitialTerm__c));
          }

          Date bcdAlignmentDate = Date.newInstance(subscriptionStartDate.year(), subscriptionStartDate.month(), Integer.valueOf(zQuote.zqu__BillCycleDay__c));

          // get the tatal Amount base the StartDate and billed date
          while(bcdAlignmentDate <= subscriptionEndDate) {
            Decimal grandTotal = 0;

            for(Integer i = 0; i < jsonInvoiceItems.size(); i++) {
            	PaymentSchBreakdownController.InvoiceItems currentInvoiceItem = jsonInvoiceItems[i];
              if(currentInvoiceItem.serviceStartDate <= bcdAlignmentDate) {
                grandTotal += currentInvoiceItem.chargeAmount;
                jsonInvoiceItems.remove(i);
                i--;
              }
            }

            if(totalAmountPeriod < grandTotal) {
            	totalAmountPeriod = grandTotal;
            }

            bcdAlignmentDate = bcdAlignmentDate.addMonths(1);
          }
				}
				
			}
			return totalAmountPeriod;
		} 
		set;
	}

	// get the billed period base the Preferred_Payment_Schedule__c of quote
	public String totalAmountToBilled{
		get{
			String totalAmountToBilled = '';
			if (zQuote.Preferred_Payment_Schedule__c =='Month') {
				totalAmountToBilled = 'each Month';
			}
			else if(zQuote.Preferred_Payment_Schedule__c =='Quarter'){
				totalAmountToBilled = 'each Quarterly';
			}
			else if (String.isNotBlank(zQuote.Preferred_Payment_Schedule__c)) {
				totalAmountToBilled = zQuote.Preferred_Payment_Schedule__c + 'ly';
			}
			return totalAmountToBilled;
		}
		set;
	}

	// Get the url of JPike Signature picture
	public String signatureDucomentId{
		get{
			String emailSignatureName = Label.AutoRenewalNotificationEmail4;
			String signatureDucomentId = System.URL.getSalesforceBaseUrl().toExternalForm() + '/servlet/servlet.ImageServer?id=';
			List<Document> documentList = [select Id from Document where DeveloperName =: emailSignatureName];
			if (!documentList.isEmpty()) {
		  	signatureDucomentId +=  String.valueOf(documentList[0].Id);
			}
			signatureDucomentId += '&oid=' + UserInfo.getOrganizationId();
			return signatureDucomentId;
		}
		set;
	}
	public AutoRenewalNotificationEmailController() {
		
	}
}