src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_on_Payment_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box to identify whether a customer is on Payment Arrangement or not.</description>
        <label>Customer on Payment Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Longest_Past_Due_Date__c</fullName>
        <description>This field holds the due date of the longest invoice with outstanding balance associated with the account.</description>
        <label>Longest Past Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Account_CBSS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-596 | If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</description>
        <inlineHelpText>If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</inlineHelpText>
        <label>Override Account CBSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_Due_Balance__c</fullName>
        <description>This field holds the sum of past due balances of all the invoice associated with the account.</description>
        <label>Past Due Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice_Past_Due_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Number_Of_Days_Past_Due__c</fullName>
        <label>Number Of Days Past Due</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_Email_To_Account_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine if an Email should also be sent to the Account Owner when an Account is past due.</description>
        <label>Send Email To Account Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Email_To_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check-box field that controls whether to send email communication to Customer or not when an invoice is past due certain days.</description>
        <label>Send Email To Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Past Due Config</label>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field will hold the lookup relationship for the Bill To Contact that is being used to sync Bill To information to Zuora.</description>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To Billing Accounts</relationshipLabel>
        <relationshipName>Bill_To_Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchAccountPastDueBalanceTest.cls
@isTest
private class BatchAccountPastDueBalanceTest {
		
	static testMethod void testMethod1() {
		Invoice_Past_Due_Config__c ipdc = TestClassUtility.createInvoicePastDueConfig(true);
		Map<String,SObject> testMap = TestClassUtility.buildLocalData(false);

		Map<Integer, Date> daysLateDateMap = new Map<Integer, Date>();
		user currentUser  = [Select id, name, email from User where id=: UserInfo.getUserId()];
		
		Test.startTest();
		Integer daysPastDue = (Integer)ipdc.Number_Of_Days_Past_Due__c;
		Date pastDueDate = Date.today().addDays(daysPastDue * -1);

		Account acc = (Account)testMap.get('Account');
		Zuora__CustomerAccount__c ca = (Zuora__CustomerAccount__c)testMap.get('Zuora__CustomerAccount__c');
		Contact con = (Contact)testMap.get('Contact');

		// ca.Bill_To_Contact__c = con.id;
		// update ca;

		acc.Past_Due_Balance__c = 100.0;
		acc.Customer_on_Payment_Arrangement__c = false;
		acc.Longest_Past_Due_Date__c = pastDueDate;
		acc.CBBS__c = currentUser.ID;
		acc.Override_Account_CBSS__c = true;

		update acc;

		BatchAccountPastDueBalanceEmailsAndTasks bb = new BatchAccountPastDueBalanceEmailsAndTasks();
		Database.executeBatch(bb);
		
		Test.stopTest();
	}

	static testMethod void testMethod2() {
		Invoice_Past_Due_Config__c ipdc = TestClassUtility.createInvoicePastDueConfig(true);
		ipdc.Send_Email_To_Account_Owner__c = true;
		ipdc.Number_Of_Days_Past_Due__c = 75;
		ipdc.Send_Email_To_Customer__c = false;
		update ipdc;

		user currentUser  = [Select id, name, email from User where id=: UserInfo.getUserId()];

		Map<String,SObject> testMap = TestClassUtility.buildLocalData(false);

		Map<Integer, Date> daysLateDateMap = new Map<Integer, Date>();

		Test.startTest();
		Integer daysPastDue = (Integer)ipdc.Number_Of_Days_Past_Due__c;
		Date pastDueDate = Date.today().addDays(daysPastDue * -1);

		Account acc = (Account)testMap.get('Account');
		Zuora__CustomerAccount__c ca = (Zuora__CustomerAccount__c)testMap.get('Zuora__CustomerAccount__c');
		Contact con = (Contact)testMap.get('Contact');

		// ca.Bill_To_Contact__c = con.id;
		// update ca;

		acc.Past_Due_Balance__c = 100.0;
		acc.Customer_on_Payment_Arrangement__c = false;
		acc.Longest_Past_Due_Date__c = pastDueDate;
		acc.CBBS__c = currentUser.ID;
		acc.Override_Account_CBSS__c = true;

		update acc;

		BatchAccountPastDueBalanceEmailsAndTasks bb = new BatchAccountPastDueBalanceEmailsAndTasks();
		Database.executeBatch(bb);
		
		Test.stopTest();
	}
}