src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ActiveSubscriptionTCVSummary__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>CSP-1486 | sums up the TCV values of all active Subscription&apos;s belonging to this Account.</description>
        <inlineHelpText>Sums up the TCV values of all active Subscription&apos;s belonging to this Account</inlineHelpText>
        <label>Active Subscription TCV Summary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Phase 1 National</description>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Strategy_Specialist</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auto_Reply_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>if this field checked, we should auto reply the email for review case,
if unchecked, we must not reply.</description>
        <label>Auto Reply Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-2806 the case has been closed flag</description>
        <label>Case Closed Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Adjusted Cancel Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blank Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Resolved (Until bonus has fully changed over)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Reporter Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efforts Exhausted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Faith Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructions/Policy Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max attempts no contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max Attempts - No Written Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promised Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refusal to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested Contract Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested to Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Remains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved Hard Concessions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved No Concessions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reported_By__c</fullName>
        <label>Reported By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Type__c</fullName>
        <label>Reporter Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Core Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Core Sales Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Core Finance - ARR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Core Regional Sales (RSR, RSD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Core Strategy Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helpdesk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporter_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>username of reporter if a user of salesforce</description>
        <label>Internal Reporter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_TimeStamp__c</fullName>
        <description>CSP-2528  Store current time from status &quot;New&quot; to any other status.</description>
        <label>Response TimeStamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Response_Times__c</fullName>
        <description>CSP-2528 Response Times from status &quot;New&quot; to any other status.</description>
        <label>Response Times(Hours)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <formula>Account.Strategy_Specialist__r.FirstName + &apos; &apos; +  Account.Strategy_Specialist__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Strategist</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Inbound</fullName>
        <active>true</active>
        <businessProcess>Inbound</businessProcess>
        <description>CSP-2750 Inbound Cases</description>
        <label>Inbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feature_Requested_Cancelled__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested Cancelled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>CaseID + SubsProductChargeID</description>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Feature Requested Cancelled</label>
    <nameField>
        <displayFormat>FRC-{00000}</displayFormat>
        <label>Feature Requested Cancelled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Requested Cancelled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <description>The number Id of the Sales Rep</description>
        <externalId>true</externalId>
        <inlineHelpText>Sales Rep Id from External System</inlineHelpText>
        <label>SalesRep ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <label>Account Manager</label>
        <relationshipName>Strategy_Specialist</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Zuora__Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCaseTrigger.cls
@isTest
private class TestCaseTrigger {
  @testSetup static void createTestData(){
    TestClassUtility.createTriggerHandlerAccessSetting(true,'Case','CaseTriggerHandler');

  }

  @isTest static void createCaseWithoutRecordType() {
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
    User u = new User(
      Alias = 'standt', 
      Email = 'standarduser@testorg.com',
      EmailEncodingKey = 'UTF-8', 
      LastName = 'Testing', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US', 
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles', 
      SalesRepID__c = '12345',
      UserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'
    );

    System.runAs(u) {
      Case mockCase = new Case();
      Test.startTest();

      insert mockCase;
   
      Test.stopTest();  

      system.assert(mockCase.Id != null); 
    }  
  }

  @isTest static void testAssignRecentCaseOwners() {
    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();
    Account acc = TestClassUtility.createAccount(true);
    Contact con = TestClassUtility.createContact(true, acc);
    
    Set<Id> accountSet = new Set<Id>{acc.Id};
    Map<Id, Contact> relatedContactMap = new Map<Id, Contact>();
    relatedContactMap.put(con.Id, con);

    Case mockCase = new Case();
    mockCase.recordTypeId = rtMapByName.get('Inbound').getRecordTypeId();
    mockCase.AccountId = acc.id;
    insert mockCase;

    Test.startTest();

    List<Case> ownerAssignmentCaseList =  new List<Case>();
    Case mockCase0 = new Case();
    mockCase0.recordTypeId = rtMapByName.get('Inbound').getRecordTypeId();
    mockCase0.AccountId = acc.id;
    mockCase0.OwnerId = [SELECT Id FROM User WHERE Id !=: UserInfo.getUserId() LIMIT 1].Id;
    ownerAssignmentCaseList.add(mockCase0);

    Case mockCase1 = new Case();
    mockCase1.recordTypeId = rtMapByName.get('Inbound').getRecordTypeId();    
    mockCase1.ContactId = con.id;
    mockCase1.OwnerId = [SELECT Id FROM User WHERE Id !=: UserInfo.getUserId() LIMIT 1].Id;
    ownerAssignmentCaseList.add(mockCase1);

    CaseTriggerHandler.assignRecentCaseOwners(ownerAssignmentCaseList, accountSet, relatedContactMap);
    Test.stopTest();

    system.assert(mockCase0.OwnerId == UserInfo.getUserId());
    system.assert(mockCase1.OwnerId == UserInfo.getUserId());
  }

  @isTest static void createReviewCase() {
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
    User u = new User(
      Alias = 'standt', 
      isActive = true,
      title = 'Account Manager',
      Email = 'testEmail@test.com',
      EmailEncodingKey = 'UTF-8', 
      LastName = 'Testing', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US', 
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles', 
      SalesRepID__c = '12345',
      UserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'
    );
    insert u;

    Test.startTest();

    String content = 'Review Details:\r\n';
           content += 'Review Id: 1356749,\r\n';
           content += 'Storefront Id: 6fc9aed0-29c7-4cee-be59-a38f00f7a395,\r\n'; 
           content += 'Display Id: 665527,\r\n';
           content += 'Date: 10/3/2016 10:14 AM,\r\n';
           content += 'Reviewer: 2840263e-d206-4551-bcc5-6818d76772c2.\r\n';

    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();
    Map<String,Schema.RecordTypeInfo> rtAccMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
    Account acc = TestClassUtility.createAccount(false);
    acc.RecordTypeId = rtAccMapByName.get('Local').getRecordTypeId();
    acc.Email__c = 'testEmail@test.com';
    acc.Strategy_Specialist__c = UserInfo.getUserId();
    acc.OwnerId = u.Id;
    insert acc;

    Contact con = TestClassUtility.createContact(false, acc);
    con.Email = acc.Email__c;
    insert con;

    Contact con2 = TestClassUtility.createContact(false, acc);
    Database.DMLOptions newDMLO = new Database.DMLOptions();
    newDMLO.DuplicateRuleHeader.allowSave = true;
    Database.insert(con2, newDMLO);

    Case mockCase0 = new Case();
    mockCase0.Description = content;  
    mockCase0.recordTypeId = rtMapByName.get('Inbound').getRecordTypeId();
    mockCase0.SuppliedEmail = con.Email;
    mockCase0.AccountId = acc.id;

    Case mockCase1 = new Case();
    mockCase1.Description = content;
    mockCase1.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase1.SuppliedEmail = con.Email;

    Case mockCase2 = new Case();
    mockCase2.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase2.AccountId = acc.id;

    Case mockCase3 = new Case();
    mockCase3.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase3.ContactId = con.id;

    Case mockCase4 = new Case();
    mockCase4.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase4.ContactId = con.id;
    mockCase4.Status = 'new';

    Case mockCase5 = new Case();
    mockCase5.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase5.ContactId = con.id;
    mockCase5.SuppliedEmail = con.Email;

    Case mockCase6 = new Case();
    mockCase6.Description = content;  
    mockCase6.recordTypeId = rtMapByName.get('Inbound').getRecordTypeId();
    mockCase6.SuppliedEmail = con.Email;

    insert new list<Case>{mockCase0, mockCase1, mockCase2, mockCase3, mockCase4, mockCase5, mockCase6};

    mockCase3.ContactId = con2.id;

    mockCase4.Status = 'Waiting on Edit';

    update new List<Case>{mockCase3, mockCase4};

    Test.stopTest();

    for(Case caseAssert : [SELECT Response_TimeStamp__c, Response_Times__c, Reported_by__c, SuppliedEmail, 
                            Auto_Reply_Flag__c, Reporter_User_Name__c, Reporter_Type__c
                            FROM Case]){
      if(caseAssert.Id == mockCase0.Id){
        system.assert(caseAssert.Reported_by__c == caseAssert.SuppliedEmail);
        system.assert(caseAssert.Auto_Reply_Flag__c == true);
      }else if(caseAssert.Id == mockCase4.Id){
        system.assert(caseAssert.Response_TimeStamp__c != null);
        system.assert(caseAssert.Response_Times__c != null);
      }
    }
  }

  @isTest static void createReviewCase2() {  
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
    User u = new User(
      Alias = 'standt', 
      Email = 'abc@abc.com',
      EmailEncodingKey = 'UTF-8', 
      isActive = true,
      LastName = 'Testing', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US', 
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles', 
      SalesRepID__c = '12345',
      UserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'
    );
    User u2 = new User(
      Alias = 'stand', 
      Email = 'abc@abc.com',
      EmailEncodingKey = 'UTF-8', 
      isActive = true,
      LastName = 'Testing2', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US', 
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles', 
      SalesRepID__c = '54321',
      UserName = 'standarduser2' + DateTime.now().getTime() + '@testorg.com'
    );
    insert new list<User>{u, u2};

    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();
    Account acc = TestClassUtility.createAccount(false);
    acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Local').getRecordTypeId();
    acc.Strategy_Specialist__c = UserInfo.getUserId();
    acc.Email__c = 'abc@abc.com';

    Account acc2 = TestClassUtility.createAccount(false);
    acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Local').getRecordTypeId();
    acc2.Strategy_Specialist__c = UserInfo.getUserId();
    acc2.Email__c = 'abc@abc.com';

    insert new list<Account>{acc, acc2};

    Contact con = TestClassUtility.createContact(false, acc);
    con.Email = 'abc@abc.com';
    insert con;
    
    Case mockCase = new Case();
    
    mockCase.recordTypeId = rtMapByName.get('3 - Reviews').getRecordTypeId();
    mockCase.SuppliedEmail = 'abc@abc.com';

    Test.startTest();

    insert mockCase;

    Test.stopTest();

    Case caseAssert = [SELECT Reporter_User_Name__c,Reporter_Type__c FROM Case WHERE Id =: mockCase.Id Limit 1];
    system.assert(caseAssert.Reporter_User_Name__c == null);
    system.assert(caseAssert.Reporter_Type__c == null);
  }

  @isTest static void createCancelCase() {
    String content = 'Review Details:\r\n';
           content += 'Review Id: 1356749,\r\n';
           content += 'Storefront Id: 6fc9aed0-29c7-4cee-be59-a38f00f7a395,\r\n'; 
           content += 'Display Id: 665527,\r\n';
           content += 'Date: 10/3/2016 10:14 AM,\r\n';
           content += 'Reviewer: 2840263e-d206-4551-bcc5-6818d76772c2.\r\n';

    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();

    Account acc = TestClassUtility.createAccount(true);
    acc.Strategy_Specialist__c = UserInfo.getUserId();
    acc.ActiveSubscriptionTCVSummary__c = 5001;
    update acc;

    Account acc2 = TestClassUtility.createAccount(true);
    acc.Strategy_Specialist__c = UserInfo.getUserId();
    acc.ActiveSubscriptionTCVSummary__c = 4500;
    update acc2;

    Contact con = TestClassUtility.createContact(true, acc);
    Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
    User u = new User(
      Alias = 'standt', 
      Email = con.Email,
      EmailEncodingKey = 'UTF-8', 
      isActive = true,
      LastName = 'Testing', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US', 
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles', 
      SalesRepID__c = '12345',
      UserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'
    );
    insert u;
    
    Case mockCaseWithoutEmail = new Case();
    mockCaseWithoutEmail.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();
    mockCaseWithoutEmail.Description = content;
    mockCaseWithoutEmail.AccountId = acc.id;
    mockCaseWithoutEmail.ContactId = con.id;

    Case mockCaseWithEmail = new Case();
    mockCaseWithEmail.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();
    mockCaseWithEmail.Description = content;
    mockCaseWithEmail.ContactId = con.id;
    mockCaseWithEmail.SuppliedEmail = con.Email;

    Case mockCaseWithoutEmail2 = new Case();
    mockCaseWithoutEmail2.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();
    mockCaseWithoutEmail2.Description = content;
    mockCaseWithoutEmail2.AccountId = acc2.id;
    mockCaseWithoutEmail2.ContactId = con.id;

    Case mockCaseWithoutAccount = new Case();
    mockCaseWithoutAccount.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();
    mockCaseWithoutAccount.Description = content;
    mockCaseWithoutAccount.ContactId = con.id;

    Test.startTest();

    insert new list<Case>{mockCaseWithoutEmail, mockCaseWithEmail, mockCaseWithoutEmail2, mockCaseWithoutAccount};

    Test.stopTest();

    for(Case caseAssert : [SELECT Priority, Reporter_User_Name__c FROM Case]){
      if(caseAssert.Id == mockCaseWithEmail.Id){
        system.assert(caseAssert.Reporter_User_Name__c != null);
      }else if(caseAssert.Id == mockCaseWithoutEmail.Id){
        system.assert(caseAssert.Priority == 'High');
      }else if(caseAssert.Id == mockCaseWithoutEmail2.Id){
        system.assert(caseAssert.Priority == 'Medium');
      }
    }
  }

  @isTest static void updateCancelCase(){
    
    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();

    Account acct = TestClassUtility.createAccount(true);
    Contact cont = TestClassUtility.createContact(true);
    Zuora__Subscription__c Subscription = TestClassUtility.createSubscription(true, acct);

    Zuora__Product__c testProduct = TestClassUtility.createZuoraProduct(true);

    Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = TestClassUtility.createSubscriptionProductCharge(true, acct, Subscription, testProduct);

    Case testCaseWithAccId = new Case();
    testCaseWithAccId.Status = 'new';
    testCaseWithAccId.AccountId = acct.Id;
    testCaseWithAccId.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();

    Case testCaseWithOwnerId = new Case();
    testCaseWithOwnerId.Status = 'new';
    testCaseWithOwnerId.AccountId = acct.Id;
    testCaseWithOwnerId.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();

    Case testCaseWithoutAccId = new Case();
    testCaseWithoutAccId.Status = 'new';
    testCaseWithoutAccId.AccountId = acct.Id;
    testCaseWithoutAccId.ContactId = cont.Id;
    testCaseWithoutAccId.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();

    Case testCaseWithAccId2 = new Case();
    testCaseWithAccId2.Status = 'new';
    testCaseWithAccId2.AccountId = acct.Id;
    testCaseWithAccId2.recordTypeId = rtMapByName.get('1 - Cancels').getRecordTypeId();

    insert new List<Case>{testCaseWithAccId, testCaseWithoutAccId, testCaseWithOwnerId, testCaseWithAccId2};

    Feature_Requested_Cancelled__c testCancelledFRC = new Feature_Requested_Cancelled__c();
    testCancelledFRC.Case__c = testCaseWithAccId.Id;
    testCancelledFRC.Status__c = 'Cancelled';
    testCancelledFRC.UniqueId__c = '1234';  

    Feature_Requested_Cancelled__c testNoCancelledFRC = new Feature_Requested_Cancelled__c();
    testNoCancelledFRC.Case__c = testCaseWithAccId2.Id;
    testNoCancelledFRC.Status__c = 'Cancelled';
    testNoCancelledFRC.Subscription_Product_Charge__c = testSubscriptionProductCharge.Id;
    testNoCancelledFRC.UniqueId__c = '123';  
    insert new List<Feature_Requested_Cancelled__c>{testCancelledFRC, testNoCancelledFRC};

    Test.startTest();
    testCaseWithOwnerId.OwnerId = [SELECT Id FROM User WHERE Id !=: UserInfo.getUserId() LIMIT 1].Id;

    testCaseWithoutAccId.AccountId = null;

    testCaseWithAccId2.Outcome__c = 'Cancelled';
    testCaseWithAccId2.Status = 'Closed';
    testCaseWithAccId2.Case_Closed_Flag__c = false;

    List<Case> caseListToUpdate = new List<Case>{testCaseWithOwnerId, testCaseWithoutAccId, testCaseWithAccId2};
    Database.update(caseListToUpdate, false);

    Integer invocations = Limits.getEmailInvocations();
    system.assert(invocations > 0);
    Test.stopTest();
  }

  @isTest static void updateOnboardingCase(){
    User u = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
    Group testGroup;
    QueuesObject testQueue;
    System.runAs(u){
      testGroup = new Group(Name = 'test group', type = 'Queue');
      insert testGroup;

      testQueue = new QueueSObject(QueueID = testGroup.id, SobjectType = 'Case');
      insert testQueue;
    }
    
    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();

    Account acct = TestClassUtility.createAccount(false);
    acct.Name = 'testAccount1';
    Account acct2 = TestClassUtility.createAccount(false);
    acct2.Name = 'testAccount2';
    insert new List<Account>{acct, acct2};

    Contact cont = TestClassUtility.createContact(false);
    cont.FirstName = 'Stuck';
    cont.LastName = 'testContact1';
    Contact cont2 = TestClassUtility.createContact(false);
    cont2.FirstName = 'Rogers';
    cont2.LastName = 'testContact2';
    insert new List<Contact>{cont, cont2};


    Zuora__Subscription__c Subscription = TestClassUtility.createSubscription(true, acct);
    Zuora__Product__c testProduct = TestClassUtility.createZuoraProduct(true);

    Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = TestClassUtility.createSubscriptionProductCharge(true, acct, Subscription, testProduct);

    Case testNoCancelledCase = new Case();
    testNoCancelledCase.Status = 'new';
    testNoCancelledCase.AccountId = acct.Id;
    testNoCancelledCase.ContactId = cont.Id;
    testNoCancelledCase.recordTypeId = rtMapByName.get('2 - Onboarding').getRecordTypeId();

    Case testCaseWithQueue = new Case();
    testCaseWithQueue.Status = 'new';
    testCaseWithQueue.AccountId = acct2.Id;
    testCaseWithQueue.ContactId = cont2.Id;
    testCaseWithQueue.OwnerId = testGroup.Id;
    testCaseWithQueue.recordTypeId = rtMapByName.get('2 - Onboarding').getRecordTypeId();
    Test.startTest();
    insert new List<Case>{testNoCancelledCase, testCaseWithQueue};
    
    Feature_Requested_Cancelled__c testNoCancelledFRC = new Feature_Requested_Cancelled__c();
    testNoCancelledFRC.Case__c = testNoCancelledCase.Id;
    testNoCancelledFRC.Status__c = 'Cancelled';
    testNoCancelledFRC.Subscription_Product_Charge__c = testSubscriptionProductCharge.Id;
    testNoCancelledFRC.UniqueId__c = '123';  
    insert testNoCancelledFRC;

    testCaseWithQueue.OwnerId = UserInfo.getUserId();
    testNoCancelledCase.Outcome__c = 'Cancelled';
    testNoCancelledCase.Status = 'Closed';
    testNoCancelledCase.Case_Closed_Flag__c = false;
    update new List<Case>{testNoCancelledCase, testCaseWithQueue};
   
    Test.stopTest();

    List<Task> onboardingTaskList = [SELECT Id FROM Task WHERE Purpose__c = 'Onboarding'];
    system.assert(onboardingTaskList.size() > 0);
  }
}