src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Last_Expiry_Date_for_Account__c</fullName>
        <inlineHelpText>This date represents the value of the expiry date the last time it was held by a waitlisted Account.  It prevents users from artificially extending the expiry date by adding quote after quote after quote.</inlineHelpText>
        <label>Last Expiry Date for Account</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_RatePlan_Id__c</fullName>
        <inlineHelpText>The Id of the Subscription Product Rate Plan (this is a Zuora Id).  This is maintained as a reference to the Rate Plan object, as the charge itself may be deleted and rebuilt by an external system (Zuora).</inlineHelpText>
        <label>Subscription RatePlan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waitlist_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waitlist Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Available for Purchase</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanEffectiveEndDate__c</fullName>
        <label>Rate Plan Effective End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchInventoryNewScheduledJobTest.cls
/*******************************************************************************
 *  Summary         : Test class for BatchInventoryNewScheduledJob
 *  Refer Object    : 
 *  Author          : Scott
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
public class BatchInventoryNewScheduledJobTest {
	static testMethod void testScheduledJob() {
		
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		
		Test.startTest();

		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
														 					(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));

		Account testAccount = (Account)testObjects.get('Account');
		Inventory__c testInventory = (Inventory__c)testsub.get('Inventory__c');
		testInventory.Waitlist_Account__c = testAccount.Id;
		testInventory.Last_Expiry_Date_for_Account__c = NULL;
		testInventory.Subscription_RatePlan_Id__c = 'New Rate Plan';
		update testInventory;
		

		Zuora__SubscriptionProductCharge__c testProductCharge = (Zuora__SubscriptionProductCharge__c)testsub.get('Zuora__SubscriptionProductCharge__c');
		testProductCharge.Zuora__RatePlanEffectiveEndDate__c = System.today() + 11;
		testProductCharge.Zuora__ChargeNumber__c = 'New Rate Plan';
		update testProductCharge;

		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		BatchInventoryNewScheduledJob binsj = new BatchInventoryNewScheduledJob();
		String sch = '0 1 0 * * ?';
		System.schedule('Test Inventory Job', sch, binsj);

		Test.stopTest();
	}
}