src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ThoughtStarter_RFP__c.object
<CustomObject>
    <fields>
        <fullName>Account_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Account Strategist</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CTR__c</fullName>
        <label>CTR (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Campaign_Category__c</fullName>
        <label>Campaign Category</label>
        <picklist>
            <picklistValues>
                <fullName>Agency &gt; Agency &gt; Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive &gt; Automotive &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Accessories &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Baby Fashion &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Bridal Fashion &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Children&apos;s Clothing &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; General Fashion &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Jewelry &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Maternity Fashion &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Shoes &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Shoes &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance and Insurance &gt; Finance and Insurance &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floral &gt; Floral &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; Baby Food &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; General Food &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; Wine and Spirits &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Baby Health &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Beauty &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; General Health &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Hospital &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Pharmaceutical &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Baby Gear &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Electronics &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Furnishings &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; General Home &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Home Improvement &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Real Estate &gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Registry &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Registry &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Tabletop &gt; Bridal Endemic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_End_Date__c</fullName>
        <label>Campaign End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign_Start_Date__c</fullName>
        <label>Campaign Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clicks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clicks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deliverable__c</fullName>
        <label>Deliverable</label>
        <picklist>
            <picklistValues>
                <fullName>Word (.doc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PowerPoint (.ppt)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Due_Date__c</fullName>
        <label>Desired Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_to_Client__c</fullName>
        <label>Due to Client</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Internal_Due_Date__c</fullName>
        <label>Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Budget__c</fullName>
        <label>Maximum Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Multiple_Spends__c</fullName>
        <label>Multiple Spends</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Formal RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proactive RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ThoughtStarter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Dev_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Dev Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Developer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Sales Development</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ThoughtStarters_RFPs_SalesDev</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spend_Type__c</fullName>
        <label>Spend Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incremental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Production__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if you are ready to submit the ThoughtStarter/RFP for materials development</inlineHelpText>
        <label>Submitted for Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Audience__c</fullName>
        <label>Target Audience</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ThoughtStarter / RFP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ThoughtStarters / RFPs</pluralLabel>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <label>RFP</label>
    </recordTypes>
    <recordTypes>
        <fullName>ThoughtStarter</fullName>
        <active>true</active>
        <label>ThoughtStarter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestThoughtStarterRFPTrigger.cls
@isTest
private class TestThoughtStarterRFPTrigger {
    static testMethod void test_method_one() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Opportunity testOpportunity = (Opportunity)testData.get('Opportunity');
        
        Map<String,Schema.RecordTypeInfo> rtTSRFPMapByName = Schema.SObjectType.ThoughtStarter_RFP__c.getRecordTypeInfosByName();
        
        Id pricebookId = Test.getStandardPricebookId();

        //Create your product
        Product2 prod = new Product2(
            Name = 'Uncategorized Revenue',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prod;
        
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        ThoughtStarter_RFP__c testThoughtStarter = new ThoughtStarter_RFP__c();
        testThoughtStarter.Opportunity__c = testOpportunity.Id;
        testThoughtStarter.RecordTypeId = rtTSRFPMapByName.get('ThoughtStarter').getRecordTypeId();
        testThoughtStarter.Account_Strategist__c = UserInfo.getUserId();
        testThoughtStarter.Clicks__c = true;
        testThoughtStarter.CTR__c = 2;
        testThoughtStarter.Desired_Due_Date__c = date.today();
        testThoughtStarter.Internal_Due_Date__c = date.today();
        testThoughtStarter.Deliverable__c = 'Word (.doc)';
        testThoughtStarter.Target_Audience__c = 'test';
        testThoughtStarter.Campaign_Start_Date__c = date.today();
        testThoughtStarter.Campaign_End_Date__c = date.today();
        testThoughtStarter.Budget__c = 10;
        testThoughtStarter.Submitted_for_Production__c = true;
        
        insert testThoughtStarter;
        
        testThoughtStarter.Budget__c = 11;
        testThoughtStarter.Sales_Dev_Needed__c = false;
        update testThoughtStarter;
        
        Task newTask = new Task();
        newTask.OwnerId = [select id from user where UserRole.DeveloperName = 'Sales_Development' limit 1].id;
        newTask.WhatId = testThoughtStarter.Id;
        newTask.Type = 'Other';
        newTask.Purpose__c = 'Produce ';
        newTask.ActivityDate = testThoughtStarter.Internal_Due_Date__c;
        newTask.Subject = ' has been submitted';
        insert newTask;
        
        Task newTask1 = new Task();
        newTask1.OwnerId = [select id from user where UserRole.DeveloperName = 'Sales_Development' limit 1].id;
        newTask1.WhatId = testThoughtStarter.Id;
        newTask1.Type = 'Other';
        newTask1.Purpose__c = 'Produce ';
        newTask1.ActivityDate = testThoughtStarter.Internal_Due_Date__c;
        newTask1.Subject = ' has been submitted';
        insert newTask1;
        
        testThoughtStarter.Sales_Dev_Needed__c = True;
        testThoughtStarter.Sales_Developer__c = [select id from user where userrole.name = 'Sales Development' limit 1].id;
        update testThoughtStarter;
        
    }
    
    
    static testMethod void test_method_two() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Opportunity testOpportunity = (Opportunity)testData.get('Opportunity');
        
        Map<String,Schema.RecordTypeInfo> rtTSRFPMapByName = Schema.SObjectType.ThoughtStarter_RFP__c.getRecordTypeInfosByName();
        
        Id pricebookId = Test.getStandardPricebookId();

        //Create your product
        Product2 prod = new Product2(
            Name = 'Uncategorized Revenue',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prod;
        
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        testOpportunity.Pricebook2Id = pricebookId;
        update testOpportunity;
        
        ThoughtStarter_RFP__c testThoughtStarter = new ThoughtStarter_RFP__c();
        testThoughtStarter.Opportunity__c = testOpportunity.Id;
        testThoughtStarter.RecordTypeId = rtTSRFPMapByName.get('RFP').getRecordTypeId();
        testThoughtStarter.Account_Strategist__c = UserInfo.getUserId();
        testThoughtStarter.Clicks__c = true;
        testThoughtStarter.CTR__c = 2;
        testThoughtStarter.Desired_Due_Date__c = date.today();
        testThoughtStarter.Internal_Due_Date__c = date.today();
        testThoughtStarter.Deliverable__c = 'Word (.doc)';
        testThoughtStarter.Target_Audience__c = 'test';
        testThoughtStarter.Campaign_Start_Date__c = date.today();
        testThoughtStarter.Campaign_End_Date__c = date.today();
        testThoughtStarter.Budget__c = 10;
        testThoughtStarter.Submitted_for_Production__c = true;
        testThoughtStarter.Description__c = 'test';
        testThoughtStarter.Request_Type__c = 'Formal RFP';
        testThoughtStarter.Campaign_Category__c = 'Agency > Agency > Agency';
        testThoughtStarter.Due_to_Client__c = date.today();
        testThoughtStarter.Maximum_Budget__c= 20;
        testThoughtStarter.Spend_Type__c = 'New';
        testThoughtStarter.Multiple_Spends__c = 'Yes';
        insert testThoughtStarter;
        
        testThoughtStarter.Budget__c = 11;
        update testThoughtStarter;
        
    }
}