src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Print_Specialist__c</fullName>
        <description>CSP-3057</description>
        <formula>if(isblank(Local_Sales_Market__r.Print_Specialist__c),&quot;Print Specialist&quot;,Local_Sales_Market__r.Print_Specialist__r.FirstName&amp;&apos; &apos; &amp;Local_Sales_Market__r.Print_Specialist__r.LastName)</formula>
        <label>Print Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the RSR of the Acct owner</description>
        <label>RSR</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>RSR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsRSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOR(deprecated)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Sales_Operations</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_SOR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Strategy_Specialist</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Print_Specialist__c</fullName>
        <label>Print Specialist</label>
        <relationshipName>Print_Specialist</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>RSR__c</fullName>
        <label>RSR</label>
        <relationshipName>RSR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>SOR__c</fullName>
        <label>SOR</label>
        <relationshipName>SOR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Strategy_Specialist__c</fullName>
        <label>Account Manager</label>
        <relationshipName>Strategy_Specialist</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LocalSalesRepTeamAssignmentController.cls
public without sharing class LocalSalesRepTeamAssignmentController {
	public List<User> salesRepList {get; set;}

	public LocalSalesRepTeamAssignmentController() {
		salesRepList = [select Id, FirstName, LastName, ManagerId, ARR__c, RSR__c, Strategy_Specialist__c, Print_Specialist__c, SOR__c from User where UserRole.Name like '%Local Core Account Executive%' and IsActive = true order by FirstName];
	}

	public void saveSalesRepRecord(){
		Map<Id, User> oldValue = new Map<Id, User>();
		for(User record : [select Id, FirstName, LastName, ManagerId, ARR__c, RSR__c, Strategy_Specialist__c, Print_Specialist__c, SOR__c from User where UserRole.Name like '%Local Core Account Executive%' and IsActive = true order by FirstName]){
			oldValue.put(record.Id, record);
		}

		List<User> updateUserList = new List<User>();
		for(User record : salesRepList){
			if(record.ManagerId != oldValue.get(record.Id).ManagerId || record.ARR__c != oldValue.get(record.Id).ARR__c || record.RSR__c != oldValue.get(record.Id).RSR__c || record.Strategy_Specialist__c != oldValue.get(record.Id).Strategy_Specialist__c || record.Print_Specialist__c != oldValue.get(record.Id).Print_Specialist__c || record.SOR__c != oldValue.get(record.Id).SOR__c){
				updateUserList.add(record);
			}
		}

		update updateUserList;

		salesRepList = [select Id, FirstName, LastName, ManagerId, ARR__c, RSR__c, Strategy_Specialist__c, Print_Specialist__c, SOR__c from User where UserRole.Name like '%Local Core Account Executive%' and IsActive = true order by FirstName];
	}
}