src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Status_Change_Date__c</fullName>
        <description>SF-1302</description>
        <label>Active Status Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Inactive_Reason__c</fullName>
        <description>Plan to Deprecated for CSP-2731
SF-1302</description>
        <label>Inactive Reason(deprecated)</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Plan to Deprecated for CSP-2892</description>
        <label>Active(deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <description>Plan to Deprecated for CSP-2731
SF-613</description>
        <label>Local Paid Status(deprecated)</label>
        <picklist>
            <picklistValues>
                <fullName>Unpaid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Longest_Past_Due_Date__c</fullName>
        <description>This field holds the due date of the longest invoice with outstanding balance associated with the account.</description>
        <label>Longest Past Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Need_to_Create_CB_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this field updated to True from False, create a Client Billing Case for the account. 

If the Past due balance reset to 0, uncheck this field
If the account past due balance &gt;0 and Payment Type == ACH or CC and longest past due date is 8 days before today, check this field on batch BatchMoveCustomerToCreditHold 
If the account past due balance &gt;0 and Payment Type == Check and longest past due date is 15 days before today, check this field on batch BatchMoveCustomerToCreditHold</description>
        <label>Need to Create CB Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_Due_Balance__c</fullName>
        <description>This field holds the sum of past due balances of all the invoice associated with the account.</description>
        <label>Past Due Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Due_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is enabled during the daily batch run if there are any invoice with outstanding balance associated with the particular customer.</description>
        <label>Past Due Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>CSP-1326</description>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <formula>TEXT(Account.Local_Paid_Status__c)</formula>
        <label>Local Paid Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Amount_Past_Due__c</fullName>
        <label>Amount Past Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <label>Default Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Promise_to_Pay_Date__c</fullName>
        <label>Promise to Pay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM account that the invoice is associated to.</description>
        <inlineHelpText>The CRM account that the invoice is associated to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Balance2__c</fullName>
        <description>The balance due on the invoice after the value for the Amount field is applied.</description>
        <inlineHelpText>The balance due on the invoice after the value for the Amount field is applied.</inlineHelpText>
        <label>Balance</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Zuora billing account that the invoice is for.</description>
        <inlineHelpText>The Zuora billing account that the invoice is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>ZInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__DueDate__c</fullName>
        <description>The date by which the payment for this invoice is due.</description>
        <inlineHelpText>The date by which the payment for this invoice is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchMoveCustomerToCreditHold.cls
/* 
<class>
  <name>BatchMoveCustomerToCreditHold</name>
  <purpose>The purpose of this batch class is to,
            1. Identify all those Invoices which has past due balance
            2. Move Account/customer associated with the invoice to credit Hold Status, if, the past due balance of any of the invoice is greater than Zero
            3. Revoke customer from Credit Hold Status if all the past due balance has been paid in Full
            4. Create promise to pay reminder for the ARR 
            5. Send out Invoice Past Due notification to the customers and track down the email sent in the acitivity history
  </purpose>
  <created>
    <by>Hari Mohan</by>
    <date>10/2/2015</date>
    <ticket>SF-1095, SF-1172, SF-1174, SF-1175, SF-1176, SF-1177, SF-1187, CSP-757</ticket>
  </created>
</class>
*/
global class BatchMoveCustomerToCreditHold implements Database.Batchable<sObject> {
    global BatchMoveCustomerToCreditHold() {
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dateToday = Date.today();
        //Date prevDay = Date.today().addDays(-15);
        String accountWithInvoiceQuery = 'SELECT '
                                        +   'Id '
                                    +   ' FROM '
                                        +   ' Account '
                                    +   ' WHERE '
                                        +   'RecordType.Name = \'Local\''
                                    +   ' AND '
                                        +   'Id IN (SELECT Zuora__Account__c FROM Zuora__ZInvoice__c WHERE Zuora__DueDate__c < :dateToday)';


        return Database.getQueryLocator(accountWithInvoiceQuery);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        //A decimal field which holds the sum of due balances of all the invoices associated with an account
        Decimal dueBalance = 0;
        Boolean pastDueInvoice;
        Date longestPastDueDate;
        List<Account> accUpdList = new List<Account>();
        Map<id,Zuora__CustomerAccount__c> ZCAMap = new Map<id,Zuora__CustomerAccount__c>();
        String paymentType;
        
        Date dateToday = Date.today();
        String accountChildQuery = 'SELECT '
                                        +   'Id, '
                                        +   'Longest_Past_Due_Date__c, '
                                        +   'Past_Due_Invoice__c, '
                                        +   'Past_Due_Balance__c, '
                                        +   'Local_Paid_Status__c, '
                                        +   'Local_Active__c, '
                                        +   'Active_Status_Change_Date__c, '
                                        +   'Need_to_Create_CB_Case__c, '
                                        +   'Inactive_Reason__c, '
                                        +   'ProductType__c, '
                                        +   '(SELECT '
                                            +   'Id, '
                                            +   'Name, '
                                            +   'Zuora__Account__c, '
                                            +   'Zuora__Account__r.Owner.ARR__c, '
                                            +   'Zuora__Account__r.OwnerId, '
                                            +   'Promise_to_Pay_Date__c, '
                                            +   'Zuora__Balance2__c, '
                                            +   'Zuora__DueDate__c, '
                                            +   'Zuora__BillingAccount__c, '
                                            +   'Zuora__BillingAccount__r.Amount_Past_Due__c, '
                                            +   'Zuora__BillingAccount__r.Zuora__DefaultPaymentMethod__c '
                                        +   ' FROM '
                                            +   ' Zuora__Invoices__r '
                                        +   ' WHERE ' 
                                            +   ' Zuora__DueDate__c < :dateToday) '
                                    +   ' FROM '
                                        +   ' Account '
                                    +   ' WHERE '
                                        +   ' Id IN :scope';

        List<Account> accountsWithChildInvoices = Database.query(accountChildQuery);

        for(Integer i = 0; i < accountsWithChildInvoices.size(); i++) {
            Account acc = accountsWithChildInvoices[i];
            dueBalance = 0;
            longestPastDueDate = null;
            pastDueInvoice = False;
            paymentType = null;
            
            for(Integer j = 0; j < acc.Zuora__Invoices__r.size(); j++) {
                Zuora__ZInvoice__c zInv = acc.Zuora__Invoices__r[j];
                if(zInv.Zuora__Balance2__c > 0 && zInv.Zuora__DueDate__c < Date.Today()){
                    if(longestPastDueDate == null){
                        longestPastDueDate = zInv.Zuora__DueDate__c;
                        // csp-1326: Setting the payment type to check if its a check customer. This flag is used in BatchAccountPastDueBalanceEmailsAndTask
                        // to check if its a check customer and if they are 15 days past due. If they are we send out an email to the customer
                        // and create a task for the ARR
                        paymentType = zInv.Zuora__BillingAccount__r.Zuora__DefaultPaymentMethod__c; 
                    }else{
                        paymentType = longestPastDueDate > zInv.Zuora__DueDate__c ? zInv.Zuora__BillingAccount__r.Zuora__DefaultPaymentMethod__c : paymentType;
                        longestPastDueDate = longestPastDueDate > zInv.Zuora__DueDate__c ? zInv.Zuora__DueDate__c : longestPastDueDate;
                    }

                    dueBalance = dueBalance+zInv.Zuora__Balance2__c;
                    pastDueInvoice = True;
                    //zInv.Zuora__BillingAccount__r.Amount_Past_Due__c = zInv.Zuora__BillingAccount__r.Amount_Past_Due__c + zInv.Zuora__Balance2__c;
                    
                    if(!ZCAMap.containsKey(zInv.Zuora__BillingAccount__c)){
                        ZCAMap.put(zInv.Zuora__BillingAccount__c, new Zuora__CustomerAccount__c(id = zInv.Zuora__BillingAccount__c,Amount_Past_Due__c = zInv.Zuora__Balance2__c));
                    }else{
                        ZCAMap.get(zInv.Zuora__BillingAccount__c).Amount_Past_Due__c = ZCAMap.get(zInv.Zuora__BillingAccount__c).Amount_Past_Due__c + zInv.Zuora__Balance2__c;
                    }
                }
            }

            // this set is used to determine whether the account needs to also be update in Partners
            if(acc.Longest_Past_Due_Date__c != longestPastDueDate || acc.Past_Due_Invoice__c != pastDueInvoice || acc.Past_Due_Balance__c != dueBalance){
                acc.Longest_Past_Due_Date__c = longestPastDueDate;
                acc.Past_Due_Invoice__c = pastDueInvoice;
                acc.Past_Due_Balance__c = dueBalance;
            }
            if(paymentType != null) {
                acc.Payment_Type__c = paymentType;
            }

            // CSP-2782 Client Billing Case Open Logic
            // The new field Need_to_Create_CB_Case__c used for creating case
            // if the account's past due balance is greater 0 and the Payment_Type__c is ACH or CreditCard, 
            // and Longest_Past_Due_Date__c is 8 days past,  we should created a new client billing case
            if (acc.Past_Due_Balance__c > 0 
                && (acc.Payment_Type__c == 'ACH' || acc.Payment_Type__c == 'CreditCard')
                // && acc.Longest_Past_Due_Date__c <= Date.today().addDays(-8) 
                && acc.Need_to_Create_CB_Case__c == false) {

                 acc.Need_to_Create_CB_Case__c = true;
             } else if(acc.Past_Due_Balance__c > 0 
                && acc.Payment_Type__c == 'Check' 
                && acc.Longest_Past_Due_Date__c < Date.today().addDays(-15) 
                && acc.Need_to_Create_CB_Case__c == false){

                acc.Need_to_Create_CB_Case__c = true;
             }else if ((acc.Past_Due_Balance__c == 0 || acc.Past_Due_Balance__c == NULL) && acc.Need_to_Create_CB_Case__c == True) {
                 acc.Need_to_Create_CB_Case__c = false;
             }


            accUpdList.add(acc);
        }
        
        List<XO_Exception__c> xoExceptionList = new List<XO_Exception__c>();
                       
        //Try updating all the Accounts in the accUpdList.. Ignore those records which cannot be updated due to certain error..
        if(!accUpdList.isEmpty()){
            Database.SaveResult[] dbSaveResult = Database.Update(accUpdList, false);
            xoExceptionList.addAll(ExceptionUtility.consumeException(dbSaveResult));
        }
        
        //Try updating all the Billing Account in the ZCAMap.. Ignore those records which cannot be updated due to certain error..
        if(!ZCAMap.isEmpty()){
            Map<id,Zuora__CustomerAccount__c> ZCAMAPOld  = new Map<id,Zuora__CustomerAccount__c>([select id,Amount_Past_Due__c from Zuora__CustomerAccount__c where id in : ZCAMap.keyset()]);
            for(id idstring : ZCAMap.keyset()){
                if(ZCAMAPOld.get(idstring).Amount_Past_Due__c == ZCAMap.get(idstring).Amount_Past_Due__c){
                    ZCAMap.remove(idstring);
                }
            }
            Database.SaveResult[] dbSaveResult = Database.Update(ZCAMap.values(), false);
            
            xoExceptionList.addAll(ExceptionUtility.consumeException(dbSaveResult));
        }
        
        if(xoExceptionList.size() > 0){
            insert xoExceptionList;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        // the BatchLocalAccountActiveStatus needs to be run in a low batch size due to a subquery in the execute method
        Database.ExecuteBatch(new BatchLocalAccountActiveStatus(), 500);
    }
    
}