src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToName__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteCreateCancellationCTest.cls
@isTest
public class ZuoraQuoteCreateCancellationCTest{
    public static testMethod void test_method_one() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
        Test.startTest(); 
            // Map<String, SObject> localObjects = TestClassUtility.buildLocalData(false);
        
            // Account testAccount = (Account)localObjects.get('Account');
            // Opportunity testOpp = (Opportunity)localObjects.get('Opportunity');
            // Zuora__CustomerAccount__c testBillingAccount = (Zuora__CustomerAccount__c)localObjects.get('Zuora__CustomerAccount__c');

            // Map<String, SObject> subscriptionObjects = TestClassUtility.buildSubscriptionData(testAccount, (Contact)localObjects.get('Contact'), testOpp, (Zuora__CustomerAccount__c)localObjects.get('Zuora__CustomerAccount__c'));
            
            // Zuora__Subscription__c testSub = (Zuora__Subscription__c)subscriptionObjects.get('Zuora__Subscription__c');
            // zqu__Quote__c testQuote = (zqu__Quote__c)subscriptionObjects.get('zqu__Quote__c');
            
            // testBillingAccount.Zuora__SoldToName__c = 'Bob Test';
            // testBillingAccount.Zuora__BillCycleDay__c = 'EOM';
            // update testBillingAccount;
        Test.stopTest();
        
        // testSub.Zuora__Zuora_Id__c = '2c92c0f94ed8d0d7014ee476a6e419ef'; 
        // testSub.Zuora__TermEndDate__c = date.today();
        // update testSub;
        
        
        
        // test.setCurrentPageReference(Page.ZuoraQuoteCreateCancellation);
        // System.currentPageReference().getParameters().put('oppId', testQuote.zqu__Opportunity__c );
        // // System.currentPageReference().getParameters().put('billingAccountId', testBillingAccount.Zuora__Zuora_Id__c );
        // // System.currentPageReference().getParameters().put('subscriptionId', testSub.Zuora__Zuora_Id__c );
        // ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        
        // ZuoraQuoteCreateCancellationController testcase = new ZuoraQuoteCreateCancellationController(sc); 
        
        // testcase.initializeQuote();
        
        //testBillingAccount.Zuora__BillCycleDay__c = '552';
        //update testBillingAccount;
        //testcase.initializeQuote();
        
        //testBillingAccount.Zuora__BillCycleDay__c = '5a2';
        //update testBillingAccount;
        //testcase.initializeQuote();
        
        // testcase.updateCancellationEffectiveDate();
        
        // String getImgUrl =  testcase.getImgUrl();
        
        // testcase.goNavigateBack();
        
        // testcase.goNavigateNext();
    }
    
}