src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCategory__c</fullName>
        <description>Phase 1 National</description>
        <label>Account Category</label>
        <picklist>
            <picklistValues>
                <fullName>Agency &gt; Agency &gt; Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive &gt; Automotive &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Accessories &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Baby Fashion &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Bridal Fashion &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Children&apos;s Clothing &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; General Fashion &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Jewelry &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Maternity Fashion &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Shoes &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion &gt; Shoes &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance and Insurance &gt; Finance and Insurance &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floral &gt; Floral &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; Baby Food &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; General Food &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage &gt; Wine and Spirits &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Baby Health &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Beauty &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; General Health &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Hospital &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Beauty &gt; Pharmaceutical &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Baby Gear &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Electronics &gt; Non-Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Furnishings &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; General Home &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Home Improvement &gt; Home Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Real Estate &gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Registry &gt; Baby Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Registry &gt; Bridal Endemic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &gt; Tabletop &gt; Bridal Endemic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NationalTSRFPAccFieldMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>National ThoughtStarter and RFP Field Mapping with Accounts</description>
    <fields>
        <fullName>Account_Field_API_Name__c</fullName>
        <label>Account Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_RFP_API_Name__c</fullName>
        <label>TS/RFP API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NationalTSRFPAccFieldMap</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AccStrategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Phase 1 National</description>
        <label>Account Strategist</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Account Strategist</value>
            </filterItems>
            <filterItems>
                <field>User.Username</field>
                <operation>equals</operation>
                <value>naste@xogrp.com</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ThoughtStarter_RFP__c.object
<CustomObject>
    <fields>
        <fullName>Account_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Account Strategist</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Budget__c</fullName>
        <label>Maximum Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>ThoughtStarters_RFPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Dev_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Dev Needed</label>
        <type>Checkbox</type>
    </fields>
    <label>ThoughtStarter / RFP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ThoughtStarters / RFPs</pluralLabel>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <label>RFP</label>
    </recordTypes>
    <recordTypes>
        <fullName>ThoughtStarter</fullName>
        <active>true</active>
        <label>ThoughtStarter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ThoughtStarterRFPEditController.cls
public with sharing class ThoughtStarterRFPEditController {

	public Map<Id, String> rtMapById {get; set;}
	public ThoughtStarter_RFP__c tsRFPRecord {get; set;}
	public Opportunity oppRecord {get; set;}
	public String requiredFields {get; set;}

	private static final List<NationalTSRFPAccFieldMap__c> mappedAccountFieldsList = NationalTSRFPAccFieldMap__c.getAll().values();
	private String queryString = 'select {fieldMap} Id from Account where Id =: parentAccountId';
	private String parentAccountId;
	private Account relatedAccount;

	public ThoughtStarterRFPEditController(ApexPages.StandardController stdController) {
		requiredFields = '';
		Map<String,Schema.RecordTypeInfo> rtMapInfo = Schema.SObjectType.ThoughtStarter_RFP__c.getRecordTypeInfosByName();
		rtMapById = new Map<Id, String>();
		for(Schema.RecordTypeInfo record : rtMapInfo.values()){
			rtMapById.put(record.getRecordTypeId(), record.getName());
		}

		tsRFPRecord = (ThoughtStarter_RFP__c) stdController.getRecord();
		tsRFPRecord.RecordTypeId = rtMapInfo.get(ApexPages.currentPage().getParameters().get('Type')).getRecordTypeId();
		tsRFPRecord.Opportunity__c = ApexPages.currentPage().getParameters().get('OpportunityId');
		oppRecord = [select Id, Name, Amount, AccountId, Account.AccountCategory__c, AccStrategist__c from Opportunity where Id =: tsRFPRecord.Opportunity__c];

		tsRFPRecord.Name = (rtMapById.get(tsRFPRecord.RecordTypeId).contains('ThoughtStarter')) ? 'TS' + '-' + oppRecord.Name : rtMapById.get(tsRFPRecord.RecordTypeId) + '-' + oppRecord.Name;
		tsRFPRecord.Account_Strategist__c = oppRecord.AccStrategist__c;

		if(rtMapById.get(tsRFPRecord.RecordTypeId).contains('ThoughtStarter')){
			tsRFPRecord.Sales_Dev_Needed__c = true;
			tsRFPRecord.Budget__c = oppRecord.Amount;

			List<Schema.FieldSetMember> tsFieldList = SObjectType.ThoughtStarter_RFP__c.FieldSets.Required_ThoughtStarter_Fields.getFields();
			for(Integer i = 0; i < tsFieldList.size(); i++) {
				Schema.FieldSetMember currentField = tsFieldList[i];
				requiredFields += currentField.getFieldPath() + ',';
			}
		}

		if(rtMapById.get(tsRFPRecord.RecordTypeId).contains('RFP')){
			tsRFPRecord.Maximum_Budget__c = oppRecord.Amount;

			List<Schema.FieldSetMember> rfpFieldList = SObjectType.ThoughtStarter_RFP__c.FieldSets.Required_RFP_Fields.getFields();
			for(Integer i = 0; i < rfpFieldList.size(); i++) {
				Schema.FieldSetMember currentField = rfpFieldList[i];
				requiredFields += currentField.getFieldPath() + ',';
			}
		}

		if(!mappedAccountFieldsList.isEmpty()){
            if(String.isBlank(parentAccountId)){
                parentAccountId = oppRecord.AccountId;
            }
            populateWithAccountInfo();
        }
	}

	private void populateWithAccountInfo(){
        List<String> fieldList = new List<String>();

        for(Integer i = 0; i < mappedAccountFieldsList.size(); i++) {
        	NationalTSRFPAccFieldMap__c currentMappedField = mappedAccountFieldsList[i];

        	fieldList.add(currentMappedField.Account_Field_API_Name__c);
        }

        queryString = queryString.replace('{fieldMap}', String.join(fieldList, ',') + ',');

        relatedAccount = Database.query(queryString);

        for(Integer i = 0; i < mappedAccountFieldsList.size(); i++) {
        	NationalTSRFPAccFieldMap__c currentMappedField = mappedAccountFieldsList[i];

        	tsRFPRecord.put(currentMappedField.TS_RFP_API_Name__c, relatedAccount.get(currentMappedField.Account_Field_API_Name__c));
        }
    }

}