src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormant</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_at_Every_Month__c</fullName>
        <description>Store the value from the start to the month before Last month</description>
        <label>Live at Every Month</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Live_at_Last_Month_Start__c</fullName>
        <description>CSP-3159 Last AM Transfer Date
Total Value of &quot;Live&quot; items as of the first of the last month</description>
        <label>Live at Last Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Live_at_Month_Start__c</fullName>
        <description>Total Value of &quot;Live&quot; items as of the first of the current month</description>
        <label>Live at Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>CommissionLineItemStatus__c</fullName>
        <description>A field to tag the subs line items status for 2019 Commission (CSP-3086)</description>
        <formula>IF(OR(CONTAINS(Name,&apos;#&apos; ),Name=&apos;CES Charge Migrated&apos;),
  &apos;Migrated-Expired&apos;,
  IF(Zuora__Subscription__r.Zuora__TermStartDate__c&gt;Zuora__Subscription__r.Zuora__TermEndDate__c, 
    &apos;Invalid&apos;,
    IF(Zuora__Subscription__r.Product_Line__c=&apos;Internet&apos;,
      If(Zuora__EffectiveStartDate__c&gt;Today(), 
        &apos;Pending&apos;,
        If(Zuora__EffectiveEndDate__c&gt;=Today(), 
          &apos;Live&apos;,
          If(Zuora__Subscription__r.Zuora__Status__c=&apos;Cancelled&apos;, 
            &apos;Cancelled&apos;, 
            &apos;Expired&apos;
          )
        )
      ),  
      IF(Zuora__Subscription__r.Product_Line__c=&apos;Direct Mail&apos;,
        If( And(year(LDE_Email_Launch_Date__c)= year(today()),month(LDE_Email_Launch_Date__c)= month(today())), 
          &apos;Live&apos;,
          If( today() &lt; LDE_Email_Launch_Date__c, 
            &apos;Pending&apos;,
            If(Zuora__Subscription__r.Zuora__Status__c=&apos;Cancelled&apos;,
              &apos;Cancelled&apos;, 
              &apos;Expired&apos;
            )
          )
        ),
        IF(Zuora__Subscription__r.Product_Line__c=&apos;Print&apos;,
          If( And(year(X1st_cover_ship_date__c)= year(today()),month(X1st_cover_ship_date__c)= month(today())), 
            &apos;Live&apos;,
            If( today() &lt; X1st_cover_ship_date__c, 
              &apos;Pending&apos;,
              If(Zuora__Subscription__r.Zuora__Status__c=&apos;Cancelled&apos;, 
                &apos;Cancelled&apos;, 
                &apos;Expired&apos;)
            )
          )  
          ,&quot;Unknown&quot;
        )
      )
    )
  )
)</formula>
        <label>Commission Line Item Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__TotalContractValue__c</fullName>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCalculateLiveChargeTCVMonthly.cls
/*
 *   CSP-3159 Last AM Transfer Date 
 *   This batch used to Calculate total TCV for all items marked "Live" for the Account  
 *   @Author  Mason
 *   @Date    2018-09-10
 *   @period  Monthly  
 */
global class BatchCalculateLiveChargeTCVMonthly implements Database.Batchable<sObject> {
    private String query;
    public String filter;

  
    global Database.QueryLocator start(Database.BatchableContext bc) {
        query = 'SELECT Id, Last_AM_Transfer__c, Live_at_Last_Month_Start__c, Live_at_Every_Month__c, Live_at_Month_Start__c '
                + 'FROM Account WHERE RecordType.Name = \'Local\' '
                + 'AND Account_Status__c = \'Active\' '
                + 'AND Last_AM_Transfer__c != null ';
        
        if(String.isNotBlank(filter)) {
            query += filter;
        }

        System.debug(LoggingLevel.INFO, '*** query: ' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Account> scope) {
        Decimal tempTCV;
        //Store all Account Id for query Sub charge
        Set<Id> accIdSet = new Set<Id>();
        //Store Account and Total TCV mapping
        Map<Id, Decimal> accIdTotalTCVMap = new Map<Id, Decimal>();
     
        //Collect all Account Id for query Sub charge
        for(Account acc : scope) {
            accIdSet.add(acc.Id);
            // Put field Live at Last Month Start value to field Live at Every Month
            if(acc.Live_at_Last_Month_Start__c != null) {
               if(acc.Live_at_Every_Month__c == null) {
                  acc.Live_at_Every_Month__c = acc.Live_at_Last_Month_Start__c + ' |';
               }
               else {
                  acc.Live_at_Every_Month__c += ' ' + acc.Live_at_Last_Month_Start__c + ' |';
               }
            }
            
            // Put field Live at Month Start value to field Live at Last Month Start
            acc.Live_at_Last_Month_Start__c = acc.Live_at_Month_Start__c != null? acc.Live_at_Month_Start__c: null;

            // Initial Live at Month start 
            acc.Live_at_Month_Start__c = 0;
        }

        //Calculate total TCV for all items marked "Live" for the Account
        for(Zuora__SubscriptionProductCharge__c charge : [SELECT Id, Zuora__Account__c, Zuora__TotalContractValue__c 
                                                            FROM Zuora__SubscriptionProductCharge__c 
                                                            WHERE CommissionLineItemStatus__c = 'Live' AND Zuora__Account__c IN: accIdSet]) {
            //Initial tempTCV
            tempTCV = 0;
            //Get every Account and total Live charge TCV value
            if(String.isNotBlank(charge.Zuora__Account__c) && charge.Zuora__TotalContractValue__c != null ) {
                if(!accIdTotalTCVMap.containsKey(charge.Zuora__Account__c)) {
                    accIdTotalTCVMap.put(charge.Zuora__Account__c, charge.Zuora__TotalContractValue__c);
                } 
                else {
                    tempTCV = accIdTotalTCVMap.get(charge.Zuora__Account__c) + charge.Zuora__TotalContractValue__c;
                    accIdTotalTCVMap.put(charge.Zuora__Account__c, tempTCV);
                }
            }
        }

        // Get current total TCV value to fill in Live At Month Start
        for(Account acc : scope) {
            if(accIdTotalTCVMap.containsKey(acc.Id)) {
                acc.Live_at_Month_Start__c = accIdTotalTCVMap.get(acc.Id);
            }
        }

        // Update Account Live at Mont Start
        if(!scope.isEmpty()) {
            List<XO_Exception__c> xoExceptionList = new List<XO_Exception__c>();
            List<Database.SaveResult> resultList = Database.update(scope, false);
            xoExceptionList.addAll(ExceptionUtility.consumeException(resultList));

            if (!xoExceptionList.isEmpty()) {
                insert xoExceptionList;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}