src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Phase 1</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConciergePrgQua__c</fullName>
        <description>Phase 1</description>
        <label>Concierge program qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified from Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified for Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fulfill_Storefront__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Claim Storefront</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operative_Owner__c</fullName>
        <label>Operative Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <description>Phase 1 of National</description>
        <label>National</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Group_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Turn_on_Fulfillment_Callouts__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Turns on and off partner fulfillment and account update callouts.</inlineHelpText>
        <label>Turn on Fulfillment Callouts</label>
        <type>Checkbox</type>
    </fields>
    <label>XO Group Settings</label>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RequestStorefrontRepublishControllerTest.cls
@isTest 
private class RequestStorefrontRepublishControllerTest {
    
    @isTest static void test_method_one() {
        // testDataFactoryT tdf = new testDataFactoryT();
        // tdf.CreateLocalTestObjects();
        test.startTest();
        Map<String,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        test.stopTest();

        Account testAccount = (Account)testLocalData.get('Account');
        testAccount.Fulfill_Storefront__c = false;
        update testAccount;
        
        // Zuora__Subscription__c testZquSubscription = new Zuora__Subscription__c();
        // testZquSubscription.Name = 'Test Subscription';
        // testZquSubscription.Zuora__SubscriptionStartDate__c = Date.Today();
        // testZquSubscription.Zuora__SubscriptionEndDate__c = Date.Today() + 365;
        // testZquSubscription.Zuora__Status__c = 'Active';
        // testZquSubscription.Zuora__Account__c = tdf.testAccount.Id;
        // testZquSubscription.Zuora__Zuora_Id__c = 'abc123';
        // insert testZquSubscription;
        Zuora__Subscription__c testZSub = TestClassUtility.createSubscription(false,testAccount);
        testZSub.Zuora__Zuora_Id__c = 'abc123';
        insert testZSub;
        
        //Test.startTest();
        PageReference pageRef = Page.RequestStorefrontRepublish;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('acctId', testAccount.Id);

        RequestStorefrontRepublishController rsfrc = new RequestStorefrontRepublishController();
        rsfrc.updateAccount();
        rsfrc.fulfillStorefront();
        
        //Test.stopTest();
    }
   
    @isTest static void test_method_Four() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account", "errors" : [{"message": "errors message"}]}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        XO_Group_Settings__c xoSetting = new XO_Group_Settings__c();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        insert xoSetting;


        Test.startTest();
        Map<String ,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        Test.stopTest();
        
        Account testAccount = (Account)testLocalData.get('Account');
        testAccount.Fulfill_Storefront__c = false;
        update testAccount;

        PageReference pageRef = Page.RequestStorefrontRepublish;
        Test.setCurrentPage(pageRef);

        //ApexPages.currentPage().getParameters().put('acctId', tdf.testAccount.Id);
        ApexPages.currentPage().getParameters().put('acctId', testAccount.Id);

        RequestStorefrontRepublishController rsfrc = new RequestStorefrontRepublishController();
        rsfrc.initiateProcess();
        rsfrc.cancelProcess();
    }
    
    @isTest static void test_method_Five() {
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account", "locations" : [{"locationId": "errors message" , "errors": [{"message": "errors message"}]}]}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        XO_Group_Settings__c xoSetting = new XO_Group_Settings__c();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        insert xoSetting;

        // testDataFactoryT tdf = new testDataFactoryT();
        // tdf.CreateLocalTestObjects();

        // tdf.testAccount.Fulfill_Storefront__c = false;
        // update tdf.testAccount;

        Test.startTest();
        Map<String ,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        Test.stopTest();
        
        Account testAccount = (Account)testLocalData.get('Account');
        testAccount.Fulfill_Storefront__c = false;
        update testAccount;


        PageReference pageRef = Page.RequestStorefrontRepublish;
        Test.setCurrentPage(pageRef);

        //ApexPages.currentPage().getParameters().put('acctId', tdf.testAccount.Id);
        ApexPages.currentPage().getParameters().put('acctId', testAccount.Id);

        RequestStorefrontRepublishController rsfrc = new RequestStorefrontRepublishController();
        
    }
    
     @isTest static void test_method_Six() {
        // testDataFactoryT tdf = new testDataFactoryT();
        // tdf.CreateLocalTestObjects();

        // tdf.testAccount.Fulfill_Storefront__c = false;
        // update tdf.testAccount;
        
        Test.startTest();
        Map<String ,SObject> testLocalData = TestClassUtility.buildLocalData(false);
        Test.stopTest();
        
        Account testAccount = (Account)testLocalData.get('Account');
     
        testAccount.Fulfill_Storefront__c = false;
        update testAccount;
        // Account testAccount = new Account();
        // testAccount.Name = 'six Test child Account';
        // testAccount.Type = 'Agency';
        // testAccount.BillingCountry = 'United States';
        // testAccount.BillingState = 'Alaska';
        // testAccount.BillingCity = 'US2';
        // testAccount.BillingStreet = 'US3';
        // testAccount.BillingPostalCode = tdf.testZip.ZipCode__c;
        // testAccount.Website = 'www.google1.com';
        // testAccount.Primary_Brand__c = tdf.testBrand.id;
        // testAccount.Primary_Category__c = tdf.testCategory.id;
        // testAccount.Local_Sales_Market__c = tdf.testMarket.id;
        // insert testAccount;
        

        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
     
        testAccount.ConciergePrgQua__c = '';
        testAccount.Operative_Owner__c = userinfo.getuserID();
        //testAccount.ParentId =testAccount.id;
        testAccount.RecordTypeId = rtMapByName.get('National').getRecordTypeId();
        testAccount.BU__c = 'National';
        update testAccount;
        //Test.startTest();
        PageReference pageRef = Page.RequestStorefrontRepublish;
        //Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('acctId', testAccount.Id);

        RequestStorefrontRepublishController rsfrc = new RequestStorefrontRepublishController();
        rsfrc.fulfillStorefront();
        
    }
}