src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>NeedToSendToZBilling__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether the Opportunity should be sent to ZBilling (CSP-634)</description>
        <inlineHelpText>Used to determine whether the Opportunity should be sent to ZBilling (CSP-634)</inlineHelpText>
        <label>Need To Send To ZBilling</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task_Creation_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Create_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Task</label>
        <type>Checkbox</type>
    </fields>
    <label>Task Creation Settings</label>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>This field is used to Copy the payment method that is selected during the quote process and will sync down to subscription in zuora</description>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Payment_Schedule__c</fullName>
        <label>Preferred Payment Schedule</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethod__c</fullName>
        <description>The Payment Method for the Quote.</description>
        <inlineHelpText>The Payment Method for the Quote.</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Z-Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendToZBillingUtilitiesTest.cls
@isTest
private class SendToZBillingUtilitiesTest {
	
	static testMethod void testOne() {
		
		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');

		Task_Creation_Settings__c taskCreationSetting = Task_Creation_Settings__c.getOrgDefaults();
		taskCreationSetting.Create_Task__c = true;
		taskCreationSetting.Name = 'Error_sending_a_quote_to_Zuora';
		upsert taskCreationSetting Task_Creation_Settings__c.Id;

		testOpp.NeedToSendToZBilling__c = true;
		testOpp.StageName = 'Client Approved';
		update testOpp;

		zqu__Quote__c zquQuote = new zqu__Quote__c();
		zquQuote.zqu__Opportunity__c = testOpp.id;
		zquQuote.zqu__Status__c = 'New'; 
		zquQuote.Name = 'Test Quote';
    zquQuote.Zqu__ValidUntil__c = Date.Today()-1;
    zquQuote.Product_Line__c = 'Internet';
    zquQuote.zqu__PaymentMethod__c = 'Check';
    zquQuote.Payment_Method__c = 'Check';
    zquQuote.Preferred_Payment_Schedule__c = 'Annual';
		insert zquQuote;

		Id opportunityId = testOpp.Id;
		SendToZBillingUtilities.futureChaining(opportunityId);
	}
	
	static testMethod void updateQuoteRecordTypeToReadOnlyOrEditableTest() {

		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
		Account testAcc = (Account)testObjects.get('Account');
		Contact testCon = (Contact)testObjects.get('Contact');
		zqu__Quote__c testQuote = TestClassUtility.createQuote(true, testOpp, testAcc, testCon);


		List<zqu__Quote__c> QuoteList = new List<zqu__Quote__c>();
		Task_Creation_Settings__c taskCreationSetting = Task_Creation_Settings__c.getOrgDefaults();
		taskCreationSetting.Create_Task__c = true;
		taskCreationSetting.Name = 'Error_sending_a_quote_to_Zuora';
		upsert taskCreationSetting Task_Creation_Settings__c.Id;

		testOpp.NeedToSendToZBilling__c = true;
		testOpp.StageName = 'Client Approved';
		update testOpp;

		zqu__Quote__c zquQuote = new zqu__Quote__c();
		zquQuote.zqu__Opportunity__c = testOpp.id;
		zquQuote.zqu__Status__c = 'New'; 
		zquQuote.Name = 'Test Quote';
    zquQuote.Zqu__ValidUntil__c = Date.Today()-1;
    zquQuote.Product_Line__c = 'Internet';
    zquQuote.zqu__PaymentMethod__c = 'Check';
    zquQuote.Payment_Method__c = 'Check';
    zquQuote.Preferred_Payment_Schedule__c = 'Annual';
		// insert zquQuote;
		zqu__Quote__c zquQuote2 = new zqu__Quote__c();
		zquQuote2.zqu__Opportunity__c = testOpp.id;
		zquQuote2.zqu__Status__c = 'New'; 
		zquQuote2.Name = 'Test Quote';
    zquQuote2.Zqu__ValidUntil__c = Date.Today()-1;
    zquQuote2.Product_Line__c = 'Internet';
    zquQuote2.zqu__PaymentMethod__c = 'Check';
    zquQuote2.Payment_Method__c = 'Check';
    zquQuote2.Preferred_Payment_Schedule__c = 'Annual';
		//insert zquQuote2;


		QuoteList.add(zquQuote);
		QuoteList.add(zquQuote2);
		insert QuoteList;

		Id opportunityId = testOpp.Id;
		SendToZBillingUtilities.futureChaining(opportunityId);
		
		SendToZBillingUtilities.updateQuoteRecordTypeToReadOnlyOrEditable(testQuote.Id, 'readOnly');
		SendToZBillingUtilities.updateQuoteRecordTypeToReadOnlyOrEditable(testQuote.Id, 'Editable');
	}
}