src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Feature_Requested_Cancelled__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Product_Charge_Number__c</fullName>
        <label>Sub Product Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>CaseID + SubsProductChargeID</description>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Feature Requested Cancelled</label>
    <nameField>
        <displayFormat>FRC-{00000}</displayFormat>
        <label>Feature Requested Cancelled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Requested Cancelled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FeatureRequestedCancelledControllerTest.cls
@isTest
private class FeatureRequestedCancelledControllerTest {
    static testMethod void testMethod1() {
        Test.startTest();
        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(false);
        Account acc = (Account)testObjects.get('Account');
        Test.stopTest();
        
        Case ca = new Case();
        ca.AccountId = acc.Id;
        insert ca;

        Feature_Requested_Cancelled__c frc1 = new Feature_Requested_Cancelled__c();
        frc1.Case__c = ca.Id;
        frc1.Sub_Product_Charge_Number__c = 'testnum';
        frc1.UniqueId__c = 'abcdefge';
        insert frc1;

        PageReference pageRef = Page.FeatureRequestedCancelledDetail;
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(new Feature_Requested_Cancelled__c());
        ApexPages.currentPage().getParameters().put('caseId', ca.Id);
        FeatureRequestedCancelledController newFRCController = new FeatureRequestedCancelledController(sc);

        List<FeatureRequestedCancelledController.SubsPCWrapper> wrapperList = new List<FeatureRequestedCancelledController.SubsPCWrapper>();
        FeatureRequestedCancelledController.SubsPCWrapper wrapper = new FeatureRequestedCancelledController.SubsPCWrapper();
        wrapper.isAdded = true;
        wrapperList.add(wrapper);
        newFRCController.subsPCWrappers = wrapperList;
        
        newFRCController.caseId = ca.Id;
        newFRCController.haveSubsPC = true;

        newFRCController.getFRCStatus();
        newFRCController.Save();
    }
}