src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>Phase 1 National</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>Phase 1</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConciergePrgQua__c</fullName>
        <description>Phase 1</description>
        <label>Concierge program qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified from Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified for Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DynamicsAccID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Location ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DynamicsLeadID__c</fullName>
        <description>Phase 1</description>
        <externalId>true</externalId>
        <label>Dynamics Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroArea__c</fullName>
        <formula>Zip__r.MetroArea__r.Name</formula>
        <label>Metro Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operative_Owner__c</fullName>
        <label>Operative Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Same_Address_as_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the address will update every time the Account address changes.  Be sure to uncheck this if you make a custom address, or it will be overwritten the next time the Account is changed.</inlineHelpText>
        <label>Same Address as Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deactivate_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Deactivate Trigger</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ConciergePrgQua__c</fullName>
        <description>Phase 1</description>
        <label>Concierge program qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified for Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified from Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select active Markets within the Primary Brand</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select an active Category</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Local_Sales_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zip Code</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Local Sales Rep Assignment</label>
    <nameField>
        <label>Local Sales Rep Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Sales Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a sales rep</errorMessage>
            <filterItems>
                <field>User.Division</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <formula>Account.Local_Sales_Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Local Sales Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <formula>Account.Primary_Category__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Category</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Group_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Turn_on_Fulfillment_Callouts__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Turns on and off partner fulfillment and account update callouts.</inlineHelpText>
        <label>Turn on Fulfillment Callouts</label>
        <type>Checkbox</type>
    </fields>
    <label>XO Group Settings</label>
</CustomObject>

src/objects/Zip__c.object
<CustomObject>
    <fields>
        <fullName>MetroArea__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metro Area</label>
        <referenceTo>MetroArea__c</referenceTo>
        <relationshipLabel>Zips</relationshipLabel>
        <relationshipName>Zips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code (External ID)</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerCalloutsTest.cls
@isTest
private class PartnerCalloutsTest {
    @isTest static void test_method_One() {
        // Implement test code
        
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtOppMapByName = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> rtLeadMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
        
        XO_Group_Settings__c xoSetting = XO_Group_Settings__c.getInstance();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        upsert xoSetting;
        
        Market__c testMarket = new Market__c();
        testMarket.Name = 'Test Market';
        testMarket.Short_Description__c = 'Test Market';
        testMarket.Market_ID__c = '222';
        testMarket.Active__c = true;
        insert testMarket;
        
        MetroArea__c ma = new MetroArea__c();
        ma.name = 'test';
        insert ma;
        
        Zip__c zip = new Zip__c();
        zip.MetroArea__c = ma.id;
        zip.ZipCode__c = '12121';
        Zip.name = '12121';
        insert zip;
        
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
        testAccount.BU__c = 'Local';
        testAccount.Website = 'www.google.com';
        testAccount.Phone = '12345678';
        testAccount.Type = 'Agency';
        testAccount.BillingCountry = 'United States';
        testAccount.BillingState = 'Alaska';
        testAccount.BillingCity = 'US2';
        testAccount.BillingStreet = 'US3';
        testAccount.BillingPostalCode = '12121';
        testAccount.Operative_Owner__c = userList[0].Name;
        testAccount.Website = 'www.google.com';
        testAccount.ConciergePrgQua__c = 'In Program';
        testAccount.Type = 'Advertiser';
        testAccount.DynamicsAccID__c = 'TestRestAPIDynamicsPartnerAcctUpdateScheduleTest';
        insert testAccount;
        
        Contact testContact = new Contact();
        testContact.Same_Address_as_Account__c = true;
        testContact.LastName = 'test';
        testContact.Email = 'abc@gmail.com';
        testContact.AccountId = testAccount.Id;
        testContact.MailingCountry = 'United States';
        insert testContact;
        
        AccountContactRole acr = new AccountContactRole();
        acr.AccountId = testAccount.id;
        acr.ContactId = testContact.id;
        acr.Role = 'Primary';
        insert acr;
        
        
        Account testAccount1 = new Account();
        testAccount1.Name = 'Test Agency Account Wait What';
        testAccount1.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
        testAccount1.BU__c = 'Local';
        testAccount1.Website = 'www.notgoogle.com';
        testAccount1.Phone = '8397111211';
        testAccount1.BillingCountry = 'United States';
        testAccount1.BillingState = 'Alaska';
        testAccount1.BillingCity = 'US2';
        testAccount1.BillingStreet = 'US3';
        testAccount1.BillingPostalCode = '12121';
        testAccount1.Operative_Owner__c = userList[0].Name;
        testAccount1.ConciergePrgQua__c = 'In Program';
        testAccount1.Type = 'Advertiser';
        testAccount1.DynamicsAccID__c = 'TestRestAPIDynamicsPartnerAcctUpdateScheduleTest1';
        insert testAccount1;
        
        Contact testContact1 = new Contact();
        testContact1.Same_Address_as_Account__c = true;
        testContact1.LastName = 't1estte1st';
        testContact1.Email = 'abc@gmail1.com';
        testContact1.AccountId = testAccount1.Id;
        testContact1.MailingCountry = 'United States';
        insert testContact1;
        
        AccountContactRole acr1 = new AccountContactRole();
        acr1.AccountId = testAccount1.id;
        acr1.ContactId = testContact1.id;
        acr1.Role = 'Primary';
        insert acr1;
        
        
        Deactivate_Trigger__c dt = new Deactivate_Trigger__c();
        dt.name = 'Note';
        dt.After_Delete__c = false;
        dt.After_Insert__c = false;
        dt.After_Update__c = false;
        dt.Before_Delete__c = false;
        dt.Before_Insert__c = false;
        dt.Before_Update__c = false;
        insert dt;
        
        
        Local_Sales_Rep_Assignment__c  lsra = new Local_Sales_Rep_Assignment__c();
        lsra.Name = 'test name';
        //lsra.Category__c = testCategory.id;
        //lsra.Market__c = testMarket.id;
        lsra.Sales_Rep__c = UserInfo.getUserId();
        lsra.Zip_Code__c = zip.id;
        //insert lsra;
        
        Lead testLead = new Lead();
        testLead.FirstName='9823urasdfndsaiofhasdf';
        testLead.LastName='awe5cgh7ijyrtersrceastgefearfsxd';
        testLead.Company='nd;5#$@#Q$WAERxddcfs5gaebai';
        //testLead.Local_Sales_Market__c = testMarket.id;
        //testLead.Primary_Category__c = testCategory.id;
        //testLead.Primary_Brand__c = testBrand.id;
        testLead.recordtypeId = rtLeadMapByName.get('Local').getRecordTypeId();
        testLead.PostalCode = '88541';
        testLead.DynamicsLeadID__c = testAccount.DynamicsAccID__c;
        testLead.Street = 'US3';
        testLead.Phone = '8547458124';
        insert testLead;
        
        Test.startTest();
        List<RESTLocalStorefrontAPI.ObjectWrapper> accountUpdateList = new List<RESTLocalStorefrontAPI.ObjectWrapper>();
        RESTLocalStorefrontAPI.ObjectWrapper objWrapper = new RESTLocalStorefrontAPI.ObjectWrapper();
        objWrapper.companyId = testAccount.DynamicsAccID__c;
        objWrapper.locationId = testAccount.DynamicsAccID__c;
        accountUpdateList.add(objWrapper);
        
        PartnerCallouts pc = new PartnerCallouts();
        PartnerCallouts.partnerOrderCallout(JSON.serializePretty(accountUpdateList));
        
        accountUpdateList[0].companyId  = '';
        PartnerCallouts.partnerOrderCallout(JSON.serializePretty(accountUpdateList));
        
        accountUpdateList[0].companyId  =  testAccount1.DynamicsAccID__c;
        accountUpdateList[0].locationId=  testAccount.DynamicsAccID__c;
        PartnerCallouts.partnerOrderCallout(JSON.serializePretty(accountUpdateList));
        
        PartnerCallouts.nonFuturePartnerOrderCallout(JSON.serializePretty(accountUpdateList));
        
        PartnerCallouts.FulfillmentLocationWrapper FulfillmentLocationWrapper = new PartnerCallouts.FulfillmentLocationWrapper();
        String locationId = FulfillmentLocationWrapper.locationId;
        List<PartnerCallouts.FulfilledStorefrontWrapper> FulfilledStorefrontWrappers = FulfillmentLocationWrapper.fulfilledStorefronts;
        List< PartnerCallouts.FulfillmentErrorWrapper> FulfillmentErrorWrappers = FulfillmentLocationWrapper.errors;
        
        
        PartnerCallouts.FulfilledStorefrontWrapper FulfilledStorefrontWrapper = new PartnerCallouts.FulfilledStorefrontWrapper();

        String storefrontId = FulfilledStorefrontWrapper.storefrontId;
        String storefrontDisplayId = FulfilledStorefrontWrapper.storefrontDisplayId ;
        String storefrontName = FulfilledStorefrontWrapper.storefrontName ;
        String storefrontTier = FulfilledStorefrontWrapper.storefrontTier ;
        String storefrontStatus = FulfilledStorefrontWrapper.storefrontStatus ;
        String marketCode = FulfilledStorefrontWrapper.marketCode ;
        String categoryId = FulfilledStorefrontWrapper.categoryId ;
        String subscriptionId = FulfilledStorefrontWrapper.subscriptionId ;
        String lineItemId = FulfilledStorefrontWrapper.lineItemId ;
        List<PartnerCallouts.FulfilledAddOnsWrapper> fulfilledAddOns = FulfilledStorefrontWrapper.fulfilledAddOns;

        PartnerCallouts.FulfillmentErrorWrapper FulfillmentErrorWrapper = new PartnerCallouts.FulfillmentErrorWrapper();
        String message = FulfillmentErrorWrapper.message;
        Test.stopTest();
    }
    
}