src/objects/Callback__c.object
<CustomObject>
    <description>Object named &quot;Callback&quot; which will be used to store callbacks generated through the system</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Callbacks</relationshipLabel>
        <relationshipName>Callbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Possible_Renewal__c</fullName>
        <description>CSP-1869 | If &quot;Yes&quot; this means the creating Opportunity had a Type of &quot;Renewal&quot;, so this Callback record may be for a Subscription Renewal.</description>
        <inlineHelpText>If &quot;Yes&quot; this means the creating Opportunity had a Type of &quot;Renewal&quot;, so this Callback record may be for a Subscription Renewal.</inlineHelpText>
        <label>Is Possible Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Callbacks</relationshipLabel>
        <relationshipName>Callbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Callbacks</relationshipLabel>
        <relationshipName>Callbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIP_Account__c</fullName>
        <description>Account is a VIP Account (CSP-1449)</description>
        <formula>Account__r.VIP_Program__c</formula>
        <inlineHelpText>Account is a VIP Account</inlineHelpText>
        <label>VIP Account</label>
        <type>Checkbox</type>
    </fields>
    <label>Callback</label>
    <nameField>
        <label>Callback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Taxonomy_ID__c</fullName>
        <description>Taxonomy GUID (Length must be 36 characters including hyphens)</description>
        <externalId>true</externalId>
        <inlineHelpText>Taxonomy ID</inlineHelpText>
        <label>Taxonomy ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Category_Taxonomy_ID__c</fullName>
        <description>SF-1821</description>
        <label>Category Taxonomy ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Possible_Renewal__c</fullName>
        <description>CSP-1869 | if the creating Opportunity Type is &quot;Renewal&quot; this picklist will be set to &quot;Yes&quot;</description>
        <label>Is Possible Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <description>SF-1821</description>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CallbackTriggerHandler.cls
public without sharing class CallbackTriggerHandler implements XOTrigger{
	/**
	 * Method used to bulkify all data needed in any "before" action of a trigger.
	 */
	
	Set<Id> vipStrategySpecialistUserIdSet = new Set<Id>();
	Map<Id, Zuora__SubscriptionProductCharge__c> spcIdToSPCRecordMap = new Map<Id, Zuora__SubscriptionProductCharge__c>();
	Map<String, Id> marketIdToRecordIdMap = new Map<String, Id>();
	Map<String, Id> categoryTaxonomyIdToRecordIdMap = new Map<String, Id>();

	public void bulkBefore() {
		if (Trigger.isInsert) {
			Set<Id> spcIdSet = new Set<Id>();
			Set<String> marketIdSet = new Set<String>();
			Set<String> categoryIdSet = new Set<String>();

			// populate spcIdSet to use in query
			for (Integer i = 0; i < Trigger.new.size(); i++) {
				Callback__c callbackRecord = (Callback__c)Trigger.new[i];
				spcIdSet.add(callbackRecord.Subscription_Product_Charge__c);
			}

			// populate marketIdSet and categoryIdSet
			for (Zuora__SubscriptionProductCharge__c spcRecord : [SELECT Id, Market_ID__c, Category_Taxonomy_ID__c FROM Zuora__SubscriptionProductCharge__c WHERE Id IN :spcIdSet]) {
				spcIdToSPCRecordMap.put(spcRecord.Id, spcRecord);
				marketIdSet.add(spcRecord.Market_ID__c);
				categoryIdSet.add(spcRecord.Category_Taxonomy_ID__c);
			}

			// populate marketIdToRecordIdMap
			for (Market__c marketRecord : [SELECT Id, Market_ID__c FROM Market__c WHERE Market_ID__c IN :marketIdSet]) {
				marketIdToRecordIdMap.put(marketRecord.Market_ID__c, marketRecord.Id);
			}

			// populate categoryTaxonomyIdToRecordIdMap
			for (Category__c categoryRecord : [SELECT Id, Taxonomy_ID__c FROM Category__c WHERE Taxonomy_ID__c IN :categoryIdSet]) {
				categoryTaxonomyIdToRecordIdMap.put(categoryRecord.Taxonomy_ID__c, categoryRecord.Id);
			}
		}
		if (Trigger.isUpdate) {
			// CSP-1449 | if a Callback for a VIP Account is being reassigned, confirm the new owner is in the VIP Strategy Specialist permission set
			for (PermissionSetAssignment psa : [SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'VIP_Strategy_Specialist']) {
				vipStrategySpecialistUserIdSet.add(psa.AssigneeId);
			}
		}
	}
	
	/**
	 *   Method used to bulkify all data needed in any "after" action of a trigger.
	 */
	public void bulkAfter() {
		
	}
	
	/**
	 *   All before insert logic should be done here. This method is called iteratively and as such
	 *   should contain no actions which could potentially hit limits or is considered bad practice 
	 *   in the Salesforce environment.
	 *   
	 *   @param  {SObject}   so Single SObject representation of the object being acted upon.
	 */
	public void beforeInsert(SObject so) {
		Callback__c callbackRec = (Callback__c)so;

		// populate Market and Category lookups
		if (spcIdToSPCRecordMap.containsKey(callbackRec.Subscription_Product_Charge__c)) {
			Zuora__SubscriptionProductCharge__c spcRec = spcIdToSPCRecordMap.get(callbackRec.Subscription_Product_Charge__c);
			callbackRec.Market__c = marketIdToRecordIdMap.containsKey(spcRec.Market_ID__c) ? marketIdToRecordIdMap.get(spcRec.Market_ID__c) : null;
			callbackRec.Category__c = categoryTaxonomyIdToRecordIdMap.containsKey(spcRec.Category_Taxonomy_ID__c) ? categoryTaxonomyIdToRecordIdMap.get(spcRec.Category_Taxonomy_ID__c) : null;
		}

		// make sure the record's name max length is 80 characters
		if (callbackRec.Name.length() > 80) {
			callbackRec.Name = callbackRec.Name.left(80);
		}

		// CSP-1869 | if "Is_Possible_Renewal__c" is blank default to "No"
		callbackRec.Is_Possible_Renewal__c = String.isBlank(callbackRec.Is_Possible_Renewal__c) ? 'No' : callbackRec.Is_Possible_Renewal__c;
	}
	
	/**
	*   All before update logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentially hit limits or is considered bad practice
	*   in the Salesforce environment.
	*
	*   @param  {SObject}   oldSo Single SObject representation of the "old" copy of the current 
	*                             object being acted upon.
	*   @param  {SObject}   so    Single SObject representation of the object being acted upon.
	*/
	public void beforeUpdate(SObject oldSo, SObject so) {
		Callback__c callbackRec = (Callback__c)so;
		Callback__c oldCallbackRec = (Callback__c)oldSo;

		// CSP-1449 | if a Callback for a VIP Account is being reassigned, confirm the new owner is in the VIP Strategy Specialist permission set
		if (callbackRec.VIP_Account__c && callbackRec.OwnerId != oldCallbackRec.OwnerId && !vipStrategySpecialistUserIdSet.contains(callbackRec.OwnerId)) {
			callbackRec.addError('Callbacks for VIP Accounts can only be reassigned to VIP Strategy Specialists');
		}

		// make sure the record's name max length is 80 characters
		if (callbackRec.Name.length() > 80) {
			callbackRec.Name = callbackRec.Name.left(80);
		}

		// CSP-1869 | if "Is_Possible_Renewal__c" is blank default to "No"
		callbackRec.Is_Possible_Renewal__c = String.isBlank(callbackRec.Is_Possible_Renewal__c) ? 'No' : callbackRec.Is_Possible_Renewal__c;
	}

	/**
	*   All before delete logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment.
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void beforeDelete(SObject so) {
		Callback__c callbackRec = (Callback__c)so;
		
		//CSP-1450 : Restrict user to delete callback record.
		callbackRec.addError('Callback Delete is not allowed');
	}

	/**
	*   All after insert logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment. 
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void afterInsert(SObject so) {
		
		
	}
	
	/**
	*   All after update logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment.
	*   
	*   @param  {SObject}   oldSo Single SObject representation of the "old" copy of the current 
	*                             object being acted upon.
	*   @param  {SObject}   so    Single SObject representation of the object being acted upon.
	*/
	public void afterUpdate(SObject oldSo, SObject so) {

	}

	/**
	*   All after delete logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment. 
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void afterDelete(SObject so) {

	}

	/**
	*   All final logic in the "before" context should be done at this point such as modification to objects outside of
	*   the current object. At this point all updates to the current trigger transaction should be
	*   complete and all validation done.
	*/
	public void beforeAndFinally() {
		
	}
	
	/**
	*   All final logic in the "after" context should be done at this point such as modification to objects outside of
	*   the current object. At this point all updates to the current trigger transaction should be
	*   complete and all validation done.
	*/
	public void afterAndFinally() {
		
	}

}