src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Dollar_Amount_Saved__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Dollar amount saved (in contract)</description>
        <label>Dollar Amount Saved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Adjusted Cancel Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blank Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Resolved (Until bonus has fully changed over)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Reporter Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efforts Exhausted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Faith Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructions/Policy Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max attempts no contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max Attempts - No Written Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promised Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refusal to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested Contract Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested to Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Remains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved Hard Concessions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved No Concessions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Plan_Name__c</fullName>
        <description>Lists the product that was sold</description>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Type__c</fullName>
        <label>Rep Type</label>
        <picklist>
            <picklistValues>
                <fullName>BDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Saved_By__c</fullName>
        <label>Saved By</label>
        <picklist>
            <controllingField>Outcome__c</controllingField>
            <picklistValues>
                <fullName>Dashboard Walkthrough</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dedicated Point of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downsell/Remove Upgrades</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explanation of Stats/Clickthroughs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Make Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offering Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storefront Redesign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Market/Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset Expectations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Lists the end date of the product</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Thread_ID__c</fullName>
        <formula>&quot;ref:_&quot; 
&amp; LEFT($Organization.Id,5) 
&amp; SUBSTITUTE(RIGHT($Organization.Id,10), &quot;0&quot;, &quot;&quot; )
&amp; &quot;._&quot; 
&amp; LEFT(Id,5) 
&amp; SUBSTITUTE(Left(RIGHT(Id,10), 4), &quot;0&quot;, &quot;&quot;) 
&amp; RIGHT(Id,5) 
&amp; &quot;:ref&quot;</formula>
        <label>Thread ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feature_Requested_Cancelled__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>Subscription_Product_Charge__r.Zuora__BillingPeriod__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>Subscription_Product_Charge__r.Zuora__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Plan_Name__c</fullName>
        <formula>Subscription_Product_Charge__r.Zuora__RatePlanName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <formula>HYPERLINK( &quot;/&quot; &amp; Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__c, Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__r.FirstName &amp; &quot; &quot; &amp; Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__r.LastName
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested Cancelled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <formula>Subscription_Product_Charge__r.Zuora__Subscription__r.Zuora__TermEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Feature Requested Cancelled</label>
    <nameField>
        <displayFormat>FRC-{00000}</displayFormat>
        <label>Feature Requested Cancelled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Requested Cancelled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NotifyInternalCaseCancelsCaseController.cls
//Used to csp-2484 email template show case and Feature Request cancelled info
public without sharing class NotifyInternalCaseCancelsCaseController {
    public Id caseId {get;set;}
    public Case currentCase {
		get{
			if (currentCase == null) {
					currentCase = new Case();
			}
			//csp-2484 Find case and Feature Request cancelled info by case id 
			List<Case> caseList = [SELECT Id, Account.Name, CaseNumber, Owner.Name, RecordType.Name, Contact.Name, Saved_By__c, Outcome__c, Thread_ID__c, Rep_Type__c, 
															Dollar_Amount_Saved__c, (SELECT Id, Rate_plan_name__c, Status__c, case__c, Sales_Rep__c, Price__c, Period__c, 
																	Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__r.FirstName,
																	Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__c,Term_End_Date__c,
														 			Subscription_Product_Charge__r.Zuora__Subscription__r.Sales_Rep__r.LastName FROM Feature_Requested_Cancelled__r 
														 		WHERE Status__c != 'Requested Cancelled')
																FROM Case 
																WHERE Id = :caseId limit 1];
			if (!caseList.isEmpty()) {
				currentCase = (Case)caseList[0];
			}
			return currentCase;
		} 
		set;
	}
	public String caseLink{
		get{
			return URL.getSalesforceBaseUrl().toExternalForm() + '/' + caseId;
		}
		set;
	} 
}