src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Handling abnormal case data</description>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Failure_Area__c</fullName>
        <description>Field used to describe where an error originated from - helpful in tracking down failure source.</description>
        <label>Failure Area</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operative.One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote to Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCV Calculation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zuora Sync</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Object_Id__c</fullName>
        <label>Related Object Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Field used to describe the severity of the failure.</description>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trivial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__CommunicationProfile__c.object
<CustomObject>
    <label>Communication Profile</label>
    <nameField>
        <label>Communication Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>TEXT(zqu__Product__r.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__CommunicationProfile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication Profile</label>
        <referenceTo>zqu__CommunicationProfile__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteAmendment__c.object
<CustomObject>
    <description>QuoteAmendment is used to make changes to a Quote.</description>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The identification for the Quote that is being amended.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Amendments</relationshipLabel>
        <relationshipName>Quote_Amendments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Amendment</label>
    <nameField>
        <label>Quote Amendment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteChargeSummary__c.object
<CustomObject>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Quote Charge Summaries</relationshipLabel>
        <relationshipName>Quote_Charge_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>zqu__QuoteRatePlanCharge__c</referenceTo>
        <relationshipLabel>Quote Charge Summaries</relationshipLabel>
        <relationshipName>Quote_Charge_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The Quote rateplan this charge belongs to</description>
        <inlineHelpText>The Quote rateplan this charge belongs to</inlineHelpText>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Charge Summaries</relationshipLabel>
        <relationshipName>QuoteChargeSummarys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Charge Summary</label>
    <nameField>
        <label>Quote Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charge Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteAmendment__c</fullName>
        <description>The identification of the amendment that this quote rate plan applies to.</description>
        <label>Quote Amendment</label>
        <referenceTo>zqu__QuoteAmendment__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>LocationVendorDynamicsAccountID__c</fullName>
        <label>LocationVendorDynamicsAccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan Charge associated with a Product Rate Plan Charge.</description>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>LocationVendorDynamicsAccountID__c</fullName>
        <description>The external system GUID of the selected Location/Vendor Account that ties together Salesforce, Partners, Admin Panel, and any other systems.</description>
        <externalId>true</externalId>
        <inlineHelpText>The external system GUID of the selected Location/Vendor Account that ties together Salesforce, Partners, Admin Panel, and any other systems.</inlineHelpText>
        <label>LocationVendorDynamicsAccountID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanName__c</fullName>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchGenerateQuoteRatePlans.cls
global class BatchGenerateQuoteRatePlans implements Database.Batchable<sObject>, Database.Stateful {
	// Subscription being processed
	Zuora__Subscription__c currentSubscription;
	// New quote being generated
	zqu__Quote__c newQuote;
	// Map used to product rate plan
	Map<String, zqu__ProductRatePlan__c> nameToProductRateNameMap;
	// Processed rate plans in batch
	Set<String> ratePlansProcessed;
	// Opportunity being used to attach quote and line items
	Opportunity currentOpp;
	
	global BatchGenerateQuoteRatePlans(Id subscriptionId, Opportunity currentOpp) {
		zqu__CommunicationProfile__c defaultCommProfile;
		try {
			defaultCommProfile = [SELECT Id, Name FROM zqu__CommunicationProfile__c WHERE Name = 'Default Profile' LIMIT 1];
		} catch(Exception e) {
			ExceptionUtility.consumeException(e, true);
		}

		/*
			Try to query the Primary Contact role associated to the Opportunity AccountId lookup for the Opportunity Id that
			was provided. If this query fails(no primary or billing exists) then log error and instantiate and blank AccountContactRole
			which will cause the code below to populate blank values in Contact lookups.
		 */
		AccountContactRole primaryContactRole = ZuoraSubscriptionUtility.retrievePrimaryContactRole(currentOpp.Id);

		currentSubscription = Database.query(ZuoraSubscriptionUtility.SUBSCRIPTION_QUERY.replace('{WHERECLAUSE}', 'Id = :subscriptionId'));

		try {
			newQuote = ZuoraSubscriptionUtility.generateQuote(currentSubscription, currentOpp.Id, primaryContactRole, true);
		} catch(Exception e) {
			// Nothing to really rollback at this point but better safe than sorry
			delete newQuote;
			ExceptionUtility.consumeException(e, true);
			newQuote = null;
			return;	
		}

		// CSP-2323 - Only create quote for Print
		if(newQuote.Product_Line__c == 'Print') {
			return;
		}

		nameToProductRateNameMap = ZuoraSubscriptionUtility.buildProductRatePlanMap(currentSubscription.Zuora__Subscription_Product_Charges__r);

		ratePlansProcessed = new Set<String>();
		this.currentOpp = currentOpp;
	}
	
	// Iterable Batch Job - Not query selector
	global Iterable<SObject> start(Database.BatchableContext BC) {
		return currentSubscription.Zuora__Subscription_Product_Charges__r;
	}

  global void execute(Database.BatchableContext BC, List<SObject> scope) {
		// CSP-2323 - Only create quote for Print
		if(newQuote.Product_Line__c == 'Print') {
			return;
		}

		List<zqu__QuoteRatePlan__c> newQuoteRatePlanList = new List<zqu__QuoteRatePlan__c>();

		for(Integer i = 0; i < scope.size(); i++) {
			Zuora__SubscriptionProductCharge__c currentSubProductCharge = (Zuora__SubscriptionProductCharge__c)scope[i];

			// CSP-2167 - Same product but different location
			String uniqueKey = currentSubProductCharge.Zuora__RatePlanName__c + '' + currentSubProductCharge.LocationVendorDynamicsAccountID__c;
			if(!nameToProductRateNameMap.containsKey(currentSubProductCharge.Zuora__RatePlanName__c) || ratePlansProcessed.contains(uniqueKey)) {
				continue;
			}

			zqu__ProductRatePlan__c currentProductRatePlan = nameToProductRateNameMap.get(currentSubProductCharge.Zuora__RatePlanName__c);
			List<zqu__ProductRatePlanCharge__c> productRatePlanChargesList = currentProductRatePlan.R00N40000001mFVKEA2__r;
			
			Map<String, zqu__QuoteAmendment__c> prodRPCIdToQuoteAmendmentMap = new Map<String, zqu__QuoteAmendment__c>();
			for(Integer j = 0; j < productRatePlanChargesList.size(); j++) {
				zqu__ProductRatePlanCharge__c currentProdRatePlanCharge = productRatePlanChargesList[j];

				////////////////////////////
				// CREATE QUOTE AMENDMENT //
				////////////////////////////
				zqu__QuoteAmendment__c newQuoteAmendment = ZuoraSubscriptionUtility.generateQuoteAmendment(newQuote, currentProdRatePlanCharge, currentProductRatePlan, currentSubProductCharge);
				prodRPCIdToQuoteAmendmentMap.put(currentProdRatePlanCharge.Id, newQuoteAmendment);
			}

			// Insert in a FOR loop - Need the Quote Amendment Id's to create the Quote Rate Plan. Unfortunately can't get past
			// this and it is needed. This code will fail with large amounts of data being created - shouldn't be an issue for
			// 99% of the use cases.
			try {
				insert prodRPCIdToQuoteAmendmentMap.values();	
			} catch(Exception e) {
				delete newQuote;
				ExceptionUtility.consumeException(e, true);
				newQuote = null;
				return;
			}
			

			for(Integer j = 0; j < productRatePlanChargesList.size(); j++) {
				zqu__ProductRatePlanCharge__c currentProdRatePlanCharge = productRatePlanChargesList[j];
				// Shouldn't be possible - but just in case
				if(!prodRPCIdToQuoteAmendmentMap.containsKey(currentProdRatePlanCharge.Id)) {
					continue;
				}

				zqu__QuoteAmendment__c newQuoteAmendment = prodRPCIdToQuoteAmendmentMap.get(currentProdRatePlanCharge.Id);

				////////////////////////////
				// CREATE QUOTE RATE PLAN //
				////////////////////////////
				// Add Quote Rate Plan to list for insertion
				newQuoteRatePlanList.add(ZuoraSubscriptionUtility.generateQuoteRatePlan(newQuote, newQuoteAmendment, currentProductRatePlan, currentSubProductCharge));
				ratePlansProcessed.add(uniqueKey);
			}

			try {
				insert newQuoteRatePlanList;	
			} catch(Exception e) {
				delete newQuote;
				ExceptionUtility.consumeException(e, true);
				newQuote = null;
				return;
			}

			List<zqu__QuoteChargeSummary__c> newQuoteChargeSummaryList = new List<zqu__QuoteChargeSummary__c>();
			for(Integer j = 0; j < newQuoteRatePlanList.size(); j++) {
				zqu__QuoteRatePlan__c currentQuoteRatePlan = newQuoteRatePlanList[j];
				if(!nameToProductRateNameMap.containsKey(currentQuoteRatePlan.Name)) {
					continue;
				}

				currentProductRatePlan = nameToProductRateNameMap.get(currentQuoteRatePlan.Name);
				Map<String, zqu__QuoteRatePlanCharge__c> prodRPCIdToQuoteRatePlanChargeMap = new Map<String, zqu__QuoteRatePlanCharge__c>();

				for(Integer k = 0; k < productRatePlanChargesList.size(); k++) {
					zqu__ProductRatePlanCharge__c currentProdRatePlanCharge = productRatePlanChargesList[k];

					///////////////////////////////////
					// CREATE QUOTE RATE PLAN CHARGE //
					///////////////////////////////////
					zqu__QuoteRatePlanCharge__c newQuoteRatePlanCharge = ZuoraSubscriptionUtility.generateQuoteRatePlanCharge(currentQuoteRatePlan, currentProdRatePlanCharge);
					prodRPCIdToQuoteRatePlanChargeMap.put(currentProdRatePlanCharge.Id, newQuoteRatePlanCharge);				
				}

				// Insert in a FOR loop - Need the Quote Rate Plan Charge Id's to create the Quote Charge Summary. Unfortunately can't get past
				// this and it is needed. This code will fail with large amounts of data being created - shouldn't be an issue for
				// 99% of the use cases.
				try {
					insert prodRPCIdToQuoteRatePlanChargeMap.values();	
				} catch(Exception e) {
					delete newQuote;
					ExceptionUtility.consumeException(e, true);
					newQuote = null;
					return;
				}
				

				for(Integer k = 0; k < productRatePlanChargesList.size(); k++) {
					zqu__ProductRatePlanCharge__c currentProdRatePlanCharge = productRatePlanChargesList[k];
					if(!prodRPCIdToQuoteRatePlanChargeMap.containsKey(currentProdRatePlanCharge.Id)) {
						continue;
					}

					zqu__QuoteRatePlanCharge__c newQuoteRatePlanCharge = prodRPCIdToQuoteRatePlanChargeMap.get(currentProdRatePlanCharge.Id);

					/////////////////////////////////
					// CREATE QUOTE CHARGE SUMMARY //
					/////////////////////////////////
					newQuoteChargeSummaryList.add(ZuoraSubscriptionUtility.generateQuoteChargeSummary(currentProdRatePlanCharge, currentOpp.Id, newQuoteRatePlanCharge, currentQuoteRatePlan));
				}
			}

			// Insert the list of all new quote charge summaries
			try {
				insert newQuoteChargeSummaryList;
			} catch(Exception e) {
				delete newQuote;
				ExceptionUtility.consumeException(e, true);
				newQuote = null;
				return;
			}
		}
		
	}
	
	global void finish(Database.BatchableContext BC) {
		/////////////
		// FAILURE //
		/////////////
		if(newQuote == null) {
			Approval.unlock(currentOpp);

			currentOpp.StageName = 'Quote Generation Failed';
			update currentOpp;

			// Query used to get the current Opportunity being worked on so we can get the OwnerId for sending an email
			currentOpp = [SELECT Id, OwnerId, StageName, Name FROM Opportunity WHERE Id = :currentOpp.Id];

			OrgWideEmailAddress orgEmail = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply@xogrp.com' LIMIT 1];

			String bodyText;

			bodyText = 'The auto renewal quote generation for <a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + currentOpp.Id + '">' + currentOpp.Name + '</a> has failed. Manual generation is needed.';

			// Create Email about failure
			Messaging.SingleEmailMessage failureEmail = new Messaging.SingleEmailMessage();
			failureEmail.setHtmlBody(EmailUtility.createEmailBody('FAILURE', 'Renewal Quote Generation', bodyText));
      failureEmail.setSubject('Renewal Quote Generation Failure');
      failureEmail.setTargetObjectId(currentOpp.OwnerId);
      failureEmail.setSaveAsActivity(false);
      failureEmail.setOrgWideEmailAddressId(orgEmail.Id);

      try {
      	Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{failureEmail});
      } catch(Exception e) {
      	ExceptionUtility.consumeException(e, true);
      }

			return;
		}

		/////////////
		// SUCCESS //
		/////////////
		Approval.unlock(currentOpp);

		// CSP-2276 - Need to ensure all quote rate plans and charges align to the Preferred Payment Schedule on the Quote
		try {
			newQuote = ZuoraQuoteChooseNextActionController.RecalculateQuoteCharges(newQuote);	
		} catch(Exception e) {
			XO_Exception__c newException = ExceptionUtility.consumeException(e, false);
			newException.Related_Object_Id__c = newQuote.Id;
			newException.Failure_Area__c = 'Renewal Quote RecalculateQuoteCharges';
			newException.Severity__c = 'Minor';

			insert newException;
		}
		
		
		currentOpp.StageName = 'Prospecting';
		try {
			update currentOpp;	
		} catch(Exception e) {
			XO_Exception__c newException = ExceptionUtility.consumeException(e, false);
			newException.Related_Object_Id__c = currentOpp.Id;
			newException.Failure_Area__c = 'Opportunity';
			newException.Severity__c = 'Minor';

			insert newException;
		}
		
	}
	
}