src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <description>Inventory is available for deletion if it:
a) has expired
b) has a rate plan id but no corresponding rate plan, and was last modified in the last 30 minutes
or
c) has no value in the waitlisted account, rate plan id, or quote rate plan</description>
        <formula>OR(
 Inventory_Hold_Expiry_Date__c &lt; TODAY(),
 AND(
     NOT(ISBLANK( Subscription_RatePlan_Id__c )),
     ISBLANK( Subscription_Product_Charge__c ),
     (NOW() - LastModifiedDate) &gt; 0.02
    ),
 AND(
     ISBLANK( Waitlist_Account__c ),
     ISBLANK( Subscription_RatePlan_Id__c ),
     ISBLANK( Quote_Rate_Plan__c )
    )
)</formula>
        <inlineHelpText>If the hold date has expired, or we don&apos;t have this slot reserved for anyone in particular, the slot is available.</inlineHelpText>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Rate_Plans_With_Capacity__c</fullName>
        <description>csp-2658</description>
        <label>Rate Plans With Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Available__c</fullName>
        <formula>IF (
    Is_Inventory_Managed__c,
    (VALUE(Capacity__c) &gt; Inventory_Held__c),
    TRUE
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alterations+Preservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor(ette)Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfasts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boudoir Photographers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Open House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Salons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calligraphers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central &amp; South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceremony Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceremony Venues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dance Lessons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ensembles+Soloists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favors+Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Jewelry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inventory_Held__c</fullName>
        <inlineHelpText>The count of the inventory that is in use</inlineHelpText>
        <label>Inventory Held</label>
        <summaryForeignKey>Inventory__c.Product_Rate_Plan__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AK-Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL-Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR-Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ-Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ-Tucson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best of Weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Central CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Palm Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Sacramento/Tahoe/Reno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-San Fran/Bay Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Santa Barbara/Ventura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALIFORNIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAN-Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO-Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT-Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC-DC/MD/Northern VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dest Weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-Northern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-West Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA-Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA-Savannah/Coastal Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI-Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honeymoons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA-Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID-Idaho</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Inventory_Available__c</fullName>
        <inlineHelpText>Don&apos;t rely on this field having a value, it&apos;s only used as a data placeholder while loading the Inventory visualforce report.</inlineHelpText>
        <label>Next Inventory Available</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Available__c</fullName>
        <description>If the value of Capacity__c is blank/null, set the return value of the formula to 1,000,000 so that the logic in the InventoryUtilities.IsInventoryAvailable method always determines that inventory is available. Otherwise, return the value of Capacity__c - Inventory_Held__c.</description>
        <formula>IF(Value(BlankValue(Capacity__c,&quot;0&quot;)) = 0,1000000,VALUE(Capacity__c) - Inventory_Held__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waitlist_Count__c</fullName>
        <label>Waitlist Count</label>
        <summaryFilterItems>
            <field>Waitlist__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Waitlist__c.Product_Rate_Plan__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Rate_Plans_With_Capacity__c</fullName>
        <inlineHelpText>The number of rate plans that have a capacity</inlineHelpText>
        <label>Rate Plans With Capacity</label>
        <summaryFilterItems>
            <field>zqu__ProductRatePlan__c.Capacity__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>zqu__ProductRatePlan__c.Capacity__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>zqu__ProductRatePlan__c.zqu__Deleted__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>zqu__ProductRatePlan__c.zqu__ZProduct__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>ZProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WaitlistManagementController.cls
// This file was updated as part of the Zuora Managed Package upgrade. Referencees to ZProducts were updated to Product2
// Updated by - Ruchit S

public without sharing class WaitlistManagementController extends PageControllerBase{
	public string FilterProduct {get;set;}
	public string FilterAvailable {get;set;}
	public string FilterCategory {get;set;}
	public string FilterMarket {get;set;}
	
	public integer getMaximumQueryOrOffsetSize()
	{
		return maximumQueryOrOffsetSize;
	}
	
	private integer maximumQueryOrOffsetSize = 2000;
	
	private transient List<Product2> productData = new List<Product2>();
	private transient List<Category__c> categoryData = new List<Category__c>();
	private transient List<Market__c> marketData = new List<Market__c>();
	public List<SelectOption> searchableProducts {get;set;}{searchableProducts = new List<SelectOption>();}
	public List<SelectOption> categories {get;set;}{categories = new List<SelectOption>();}
	public List<SelectOption> markets {get;set;}{markets = new List<SelectOption>();}
	
	// pagination
	private integer counter=0;  //keeps track of the offset
	public integer list_size=20; //sets the page size or number of rows
   	public integer total_size; //used to show user the total size of the list
   	public integer previous_total_size = 0;
   	
   	public boolean ShowModal {get;set;}{ShowModal = false;}
   	
   	private transient List<zqu__ProductRatePlan__c> ProductRatePlans = new List<zqu__ProductRatePlan__c>();
	/* 
	 * Begin MODAL WAITLIST CODE
   	 * This section is needed in order to control the modal window.  Keep in mind this only works if you extend this class with PageControllerBase 
   	 */
   	 
   	public String SelectedRatePlanIdForWaitlistModal {get;set;} {SelectedRatePlanIdForWaitlistModal = '';}
   	public void ViewWaitlist()
   	{
   		myWaitlistModalController.OpenModal(SelectedRatePlanIdForWaitlistModal);
   	}
   	
   	public WaitlistModalController myWaitlistModalController {get;set;}
   	
   	public override void setComponentController(ComponentControllerBase compController) {
	    myWaitlistModalController = (WaitlistModalController)compController;
	}

	public override ComponentControllerBase getMyComponentController() {
	    return myWaitlistModalController;
	}
   	/* 
   	 * End MODAL WAITLIST CODE 
   	 */

	public WaitlistManagementController()
	{
		System.Debug('making a new rate plan');
		
		// get all the rate plans that have inventory controllers
		productData = [Select Id, Name
					   from Product2
					   where zqu__Deleted__c = false	 
					   and Rate_Plans_With_Capacity__c > 0
					   order by Name asc];

		System.debug(LoggingLevel.INFO, '*** FilterProduct: ' + FilterProduct);

		marketData = [Select Id, Name, Short_Description__c
					  from Market__c
					  where Active__c = true];
					  
		categoryData = [Select Id, Name, Short_Description__c
					    from Category__c
					    where Active__c = true];
					  		
		Map<Id, String> inventoryControlledProductMap = new Map<Id, String>();
		Map<String, String> inventoryControlledCategoryMap = new Map<String, String>();
		Map<String, String> inventoryControlledMarketMap = new Map<String, String>();
		
		//searchableProducts = new List<SelectOption>();
		searchableProducts.add(new SelectOption('','--None--'));
		categories.add(new SelectOption('','--None--'));
		markets.add(new SelectOption('','--None--'));
		
		for (Product2 eachProductItem : productData)
		{
			if (!inventoryControlledProductMap.containsKey(eachProductItem.Id))
			{
				inventoryControlledProductMap.put(eachProductItem.Id, eachProductItem.Name);
				searchableProducts.add(new SelectOption(eachProductItem.Id, eachProductItem.Name));
			}			
		}
		
		for (Category__c c : categoryData)
		{
			if (!inventoryControlledCategoryMap.containsKey(c.Short_Description__c))
			{
				inventoryControlledCategoryMap.put(c.Short_Description__c, c.Short_Description__c);
				categories.add(new SelectOption(c.Short_Description__c, c.Short_Description__c));								
			}
		}

		for (Market__c m : marketData)
		{
			if (!inventoryControlledMarketMap.containsKey(m.Short_Description__c))
			{
				inventoryControlledMarketMap.put(m.Short_Description__c, m.Short_Description__c);
				markets.add(new SelectOption(m.Short_Description__c, m.Short_Description__c));								
			}
		}

		// CSP-516 | sort the Market and Category dropdowns by alphabetical order
		categories.sort();
		markets.sort();
	}


	public List<zqu__ProductRatePlan__c> getProductRatePlans()
	{
		ProductRatePlans = new List<zqu__ProductRatePlan__c>();
		//string soql = '';
		string soql = 'Select Id, Name, Available__c, Capacity__c, Inventory_Held__c, Number_Available__c, Next_Inventory_Available__c, Waitlist_Count__c, Market__c, Category__c, zqu__Product__r.Name, zqu__Product__c';
		string soqlCount = 'select count()';
		string soqlFromWhere = ' from zqu__ProductRatePlan__c where Is_Inventory_Managed__c = true and zqu__Deleted__c = false and Is_Expired__c = false';
		
		if (FilterProduct != null && FilterProduct != '')
		{
			//soqlFromWhere += ' and zqu__ZProduct__c = \'' + FilterProduct + '\'';
			soqlFromWhere += ' and zqu__Product__c = \'' + FilterProduct + '\'';

		}
		
		if (FilterCategory != null && FilterCategory != '')
		{
			soqlFromWhere += ' and Category__c = \'' + string.escapeSingleQuotes(FilterCategory) + '\'';
		}

		if (FilterMarket != null && FilterMarket != '')
		{
			soqlFromWhere += ' and Market__c = \'' + string.escapeSingleQuotes(FilterMarket) + '\'';
		}
		
		if (FilterAvailable != null && FilterAvailable != '')
		{
			soqlFromWhere += ' and Available__c = ' + string.escapeSingleQuotes(FilterAvailable) ;
		}
		
		soqlCount += soqlFromWhere;
		soqlCount += ' limit ' + maximumQueryOrOffsetSize;
		System.Debug(soqlCount);
		
		total_size = database.countquery(soqlCount);
		if (total_size != previous_total_size)
		{
			counter = 0;
		}
		previous_total_size = total_size;

		soql += soqlFromWhere;
		soql += ' limit ' + list_size;
		soql += ' offset ' + TheCounter;

		ProductRatePlans = database.query(soql);
		System.Debug('Found rate plans: ' + ProductRatePlans.size());
		
		// get the first avaialable date for each unavailable inventory
		Map<ID, Date> nextAvailableMap = new Map<Id, Date>();
		for (zqu__ProductRatePlan__c prp : ProductRatePlans)
		{
			if (!prp.Available__c)
			{
				if (!nextAvailableMap.ContainsKey(prp.Id))
				{
					nextAvailableMap.put(prp.Id, Date.newinstance(1900,1,1));
				}
			}
		}
		
		if (nextAvailableMap.size() > 0)
		{
			// get the inventory
			List<Inventory__c> inventory = [Select Id, Inventory_Hold_Expiry_Date__c, Product_Rate_Plan__c 
											from Inventory__c 
											where Product_Rate_Plan__c in :nextAvailableMap.keyset() 
											order by Product_Rate_Plan__c, Inventory_Hold_Expiry_Date__c asc];
			for (Inventory__c inv : inventory)
			{
				nextAvailableMap.put(inv.Product_Rate_Plan__c, inv.Inventory_Hold_Expiry_Date__c);
			}
		}
		
		for (zqu__ProductRatePlan__c prp : ProductRatePlans)
		{
			if (nextAvailableMap.containsKey(prp.Id))
			{
				prp.Next_Inventory_Available__c = nextAvailableMap.get(prp.Id);
			}
		}
				
		return ProductRatePlans;
	}
	
	
	public boolean getOkToDisplayList()
	{
		return ProductRatePlans.size() > 0;
	}
	
	
   public integer TheCounter
   {
   		get
   		{
   			return counter;
   		}
   		set
   		{
   			counter = value;
   			if (counter > maximumQueryOrOffsetSize)
   			{
   				counter = maximumQueryOrOffsetSize;
   			}
   		}
   }

   public PageReference Beginning() { //user clicked beginning
      TheCounter = 0;
      return null;
   }

   public PageReference Previous() { //user clicked previous button
      TheCounter -= list_size;
      return null;
   }

   public PageReference Next() { //user clicked next button
      TheCounter += list_size;
      return null;
   }

   public PageReference End() { //user clicked end
      TheCounter = total_size - math.mod(total_size, list_size);
      return null;
   }

   public Boolean getDisablePrevious() { 
      //this will disable the previous and beginning buttons
      if (TheCounter>0) return false; else return true;
   }

   public Boolean getDisableNext() { //this will disable the next and end buttons
      if (TheCounter + list_size < total_size) return false; else return true;
   }

   public Integer getTotal_size() {
      return total_size;
   }

   public Integer getPageNumber() {
	  System.Debug(TheCounter);
	  System.Debug(list_size);
	  System.Debug(TheCounter/list_size);
      return TheCounter/list_size + 1;
   }

   public Integer getTotalPages() {
      if (math.mod(total_size, list_size) > 0) {
         return total_size/list_size + 1;
      } else {
         return (total_size/list_size);
      }
   }
}