src/objects/ChainBatchJob__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of batch jobs and whether or not to allow them to chain.  If blank, the batch job will assume that it&apos;s ok to run as a chain.</description>
    <fields>
        <fullName>Chain_Next_Batch_Job__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If true, this batch job is allowed to call the next job in the chain.</inlineHelpText>
        <label>Chain Next Batch Job</label>
        <type>Checkbox</type>
    </fields>
    <label>Chain Batch Job</label>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <description>Inventory is available for deletion if it:
a) has expired
b) has a rate plan id but no corresponding rate plan, and was last modified in the last 30 minutes
or
c) has no value in the waitlisted account, rate plan id, or quote rate plan</description>
        <formula>OR(
 Inventory_Hold_Expiry_Date__c &lt; TODAY(),
 AND(
     NOT(ISBLANK( Subscription_RatePlan_Id__c )),
     ISBLANK( Subscription_Product_Charge__c ),
     (NOW() - LastModifiedDate) &gt; 0.02
    ),
 AND(
     ISBLANK( Waitlist_Account__c ),
     ISBLANK( Subscription_RatePlan_Id__c ),
     ISBLANK( Quote_Rate_Plan__c )
    )
)</formula>
        <inlineHelpText>If the hold date has expired, or we don&apos;t have this slot reserved for anyone in particular, the slot is available.</inlineHelpText>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Held_By_Type__c</fullName>
        <formula>IF ( NOT(ISBLANK(Subscription_RatePlan_Id__c)), &apos;Subscription&apos;,
   IF ( NOT(ISBLANK(Quote_Rate_Plan__c)), &apos;Quote&apos;,
   IF ( NOT(ISBLANK(Waitlist_Account__c)), &apos;Account&apos;, &apos;&apos;)))</formula>
        <inlineHelpText>Returns blank if the slot is available, or Waitlist, Quote or Subscription if not available.</inlineHelpText>
        <label>Held By Type</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchRebuildInventory.cls
/* 
<Class>
  <name>BatchRebuildInventory</name>
  <purpose>Removes any subscription based inventory.  Based on configuration settings, conditionally calls batch to rebuild inventory from Subscription Rate Plan data
  </purpose>
  <created>
    <by>Steve O'Neal</by>
    <date>03/07/2016</date>
    <ticket>CSP-576</ticket>
  </created>
</Class>
*/
global class BatchRebuildInventory implements Database.Batchable<sObject> {
	public string query = '';
	private string BatchDelAvailInvName = 'BatchDeleteAvailableInventory';
	Map<String, ChainBatchJob__c> chainBatchJob = ChainBatchJob__c.getAll();
	
	global BatchRebuildInventory() {
		query = ' SELECT ID FROM Inventory__c WHERE Held_By_Type__c = \'Subscription\' or Available__c = true';
		System.Debug('Query (this query is static, FYI): ' + query);
		
		ChainBatchJob__c bdaiChainBatchJob = new ChainBatchJob__c();
		if (chainBatchJob.containsKey(BatchDelAvailInvName)) {
			bdaiChainBatchJob = chainBatchJob.get(BatchDelAvailInvName);
		} else {
			bdaiChainBatchJob.Name = BatchDelAvailInvName;
		}
		
		bdaiChainBatchJob.Chain_Next_Batch_Job__c = false;
		upsert bdaiChainBatchJob;
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		Database.QueryLocator retVal = Database.getQueryLocator(query);
		return retVal;
	}

 	global void execute(Database.BatchableContext BC, List<Inventory__c> scope) {
 		Database.DeleteResult[] dbDeleteResult = Database.delete(scope, false);
    List<XO_Exception__c> xoExceptionList = ExceptionUtility.consumeException(dbDeleteResult);
    if(xoExceptionList.size() > 0){
    	insert xoExceptionList;
    }	    
 	}
   	
  global void finish(Database.BatchableContext BC) {
		Boolean runNextBatchJob = true;
		if (chainBatchJob.containsKey('BatchRebuildInventory')) {
			runNextBatchJob = chainBatchJob.get('BatchRebuildInventory').Chain_Next_Batch_Job__c;
		}
		
		if (runNextBatchJob) {
	    BatchRebuildInventoryFromSubscriptions batch1 = new BatchRebuildInventoryFromSubscriptions();
	    Database.ExecuteBatch(batch1,200);
		}
  }
}