src/objects/ChainBatchJob__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of batch jobs and whether or not to allow them to chain.  If blank, the batch job will assume that it&apos;s ok to run as a chain.</description>
    <fields>
        <fullName>Chain_Next_Batch_Job__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If true, this batch job is allowed to call the next job in the chain.</inlineHelpText>
        <label>Chain Next Batch Job</label>
        <type>Checkbox</type>
    </fields>
    <label>Chain Batch Job</label>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Hold_Expiry_Date__c</fullName>
        <inlineHelpText>The date that this inventory slot is reserved through.  If a spot has a hold expiry date of 2/1/2017, for example, it becomes available as soon as the date switches to 2/2/2017</inlineHelpText>
        <label>Held Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <inlineHelpText>The Product Rate Plan represents the product in a specific market/category.  In essence, this is the product we are tracking inventory against.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the inventory slot is reserved by a quote, this field will identify which quote rate plan is holding it.</inlineHelpText>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory_Hold_Expiry_Date_Offsets__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For setting the number of days to offset the inventory expiry date when dealing with different objects.  Negative numbers mean before the date in question, positive numbers mean after the date in question.</description>
    <fields>
        <fullName>Subscription_Product_Charge_Day_Offset__c</fullName>
        <defaultValue>-7</defaultValue>
        <inlineHelpText>The number of work days before or after the subscription expire date to hold the inventory</inlineHelpText>
        <label>Subscription Product Charge Day Offset</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Hold Expiry Date Offsets</label>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Is_Inventory_Managed__c</fullName>
        <formula>BLANKVALUE(VALUE(Capacity__c), 0) &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Inventory Managed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Available__c</fullName>
        <description>If the value of Capacity__c is blank/null, set the return value of the formula to 1,000,000 so that the logic in the InventoryUtilities.IsInventoryAvailable method always determines that inventory is available. Otherwise, return the value of Capacity__c - Inventory_Held__c.</description>
        <formula>IF(Value(BlankValue(Capacity__c,&quot;0&quot;)) = 0,1000000,VALUE(Capacity__c) - Inventory_Held__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Subscription_Being_Renewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Being Renewed</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Renewal Dashboard Subscription)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Z-Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCreateInventoryForRenewalQuote.cls
/**
 *	Created the inventory for renewal Quote when the inventory of the original subscription has been released 
 *  Created by Tony
 */


global class BatchCreateInventoryForRenewalQuote implements Database.Batchable<sObject> {
	public String query;
	private Inventory_Hold_Expiry_Date_Offsets__c invHoldExpDate;
	private Date inventoryExpiredDate;
	private Date todayDate;
	global BatchCreateInventoryForRenewalQuote() {
		invHoldExpDate = Inventory_Hold_Expiry_Date_Offsets__c.getOrgDefaults();
		inventoryExpiredDate = DateUtility.AddBusinessDays(date.today(), -(Integer)invHoldExpDate.Subscription_Product_Charge_Day_Offset__c);
		todayDate = Date.today();
		query = 'SELECT Id, zqu__ProductRatePlan__c, zqu__Quote__r.zqu__ValidUntil__c, (SELECT Id FROM Inventory__r) ';
		query += 'FROM zqu__QuoteRatePlan__c WHERE zqu__Quote__r.Subscription_Being_Renewed__c != NULL ';
		query += 'AND zqu__Quote__r.Subscription_Being_Renewed__r.Zuora__TermEndDate__c <: inventoryExpiredDate ';
		query += 'AND zqu__Quote__r.zqu__ValidUntil__c >=: todayDate ';
		query += 'AND zqu__Quote__r.zqu__Status__c != \'Sent to Z-Billing\' ';
		query += 'AND zqu__ProductRatePlan__r.Is_Inventory_Managed__c = TRUE ';
		query += 'AND zqu__ProductRatePlan__r.Number_Available__c >0 ';

	}

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, list<zqu__QuoteRatePlan__c> scope) {
		List<Inventory__c> newInventoryList = new List<Inventory__c>();
		for (zqu__QuoteRatePlan__c qrp : scope){
			// only create inventory for the renewal quote with out inventory
			if (qrp.Inventory__r.size() < 1) {
				Inventory__c newInventory = new Inventory__c();
				newInventory.Product_Rate_Plan__c = qrp.zqu__ProductRatePlan__c;
				newInventory.Quote_Rate_Plan__c = qrp.Id;
				newInventory.Inventory_Hold_Expiry_Date__c = qrp.zqu__Quote__r.zqu__ValidUntil__c;
				newInventoryList.add(newInventory);
			}
		}
		if (!newInventoryList.isEmpty()) {
			List<Database.SaveResult> insertResultList = Database.insert(newInventoryList,false);
			List<XO_Exception__c> xoExceptionList = ExceptionUtility.consumeException(insertResultList);
			if (!xoExceptionList.isEmpty()) {
				insert xoExceptionList;
			}
		}
	}

	global void finish(Database.BatchableContext BC) {
		// run back the batch job BatchDeleteAvailableInventory
		string BatchDelAvailInvName = 'BatchDeleteAvailableInventory';
	
		Map<String, ChainBatchJob__c> chainBatchJob = ChainBatchJob__c.getAll();
		ChainBatchJob__c bdaiChainBatchJob = new ChainBatchJob__c();
		if (chainBatchJob.containsKey(BatchDelAvailInvName))
		{
			//System.Debug('Found a custom setting for ' + BatchDelAvailInvName);
			bdaiChainBatchJob = chainBatchJob.get(BatchDelAvailInvName);
		}
		else
		{
			//System.Debug('Creating a new custom setting for ' + BatchDelAvailInvName);
			bdaiChainBatchJob.Name = BatchDelAvailInvName;
		}
		//System.Debug('Turning on chaining for ' + BatchDelAvailInvName);
		bdaiChainBatchJob.Chain_Next_Batch_Job__c = true;
		upsert bdaiChainBatchJob;
  	//System.Debug('Exiting BatchRebuildInventoryFromSubscriptions.finish');
  	
  	// CSP-1796 | immediately run this job after to convert waitlist records to inventory
  	BatchDeleteAvailableInventory b = new BatchDeleteAvailableInventory();
		database.executebatch(b);
  }
}