src/objects/ChainBatchJob__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of batch jobs and whether or not to allow them to chain.  If blank, the batch job will assume that it&apos;s ok to run as a chain.</description>
    <fields>
        <fullName>Chain_Next_Batch_Job__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If true, this batch job is allowed to call the next job in the chain.</inlineHelpText>
        <label>Chain Next Batch Job</label>
        <type>Checkbox</type>
    </fields>
    <label>Chain Batch Job</label>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Held_By_Migrated_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when applicable during the BatchRebuildInventoryFromSubscriptions nightly batch job. This field is primarily used by the InventoryUtilities.IsInventoryAvailable method.</description>
        <label>Held By Migrated Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory_Hold_Expiry_Date__c</fullName>
        <inlineHelpText>The date that this inventory slot is reserved through.  If a spot has a hold expiry date of 2/1/2017, for example, it becomes available as soon as the date switches to 2/2/2017</inlineHelpText>
        <label>Held Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <inlineHelpText>The Product Rate Plan represents the product in a specific market/category.  In essence, this is the product we are tracking inventory against.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the inventory slot is reserved by a quote, this field will identify which quote rate plan is holding it.</inlineHelpText>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_RatePlan_Id__c</fullName>
        <inlineHelpText>The Id of the Subscription Product Rate Plan (this is a Zuora Id).  This is maintained as a reference to the Rate Plan object, as the charge itself may be deleted and rebuilt by an external system (Zuora).</inlineHelpText>
        <label>Subscription RatePlan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waitlist_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waitlist Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Available for Purchase</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory_Hold_Expiry_Date_Offsets__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For setting the number of days to offset the inventory expiry date when dealing with different objects.  Negative numbers mean before the date in question, positive numbers mean after the date in question.</description>
    <fields>
        <fullName>Subscription_Product_Charge_Day_Offset__c</fullName>
        <defaultValue>-7</defaultValue>
        <inlineHelpText>The number of work days before or after the subscription expire date to hold the inventory</inlineHelpText>
        <label>Subscription Product Charge Day Offset</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Hold Expiry Date Offsets</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Consolidate_Inventory__c</fullName>
        <description>Moved from ZProduct</description>
        <inlineHelpText>By default, inventory is controlled at the Product Rate Plan Allows inventory to roll up to a more general rate plan.</inlineHelpText>
        <label>Consolidate Inventory</label>
        <picklist>
            <picklistValues>
                <fullName>By Product and Market</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Is_Inventory_Managed__c</fullName>
        <formula>BLANKVALUE(VALUE(Capacity__c), 0) &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Inventory Managed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Product__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Do_not_create_inventory__c</fullName>
        <inlineHelpText>Typically if a rate plan has capacity, the charge would occupy an inventory slot.  By checking this (on record creation only), the inventory will not be created.  This is primarily for renewing migrated subscriptions.</inlineHelpText>
        <label>Do not create inventory</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Zuora__Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanEffectiveEndDate__c</fullName>
        <label>Rate Plan Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanId__c</fullName>
        <description>This field holds rateplan id.</description>
        <externalId>true</externalId>
        <label>RatePlan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanName__c</fullName>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchRebuildInventoryFromSubscriptions.cls
/* 
<Class>
  <name>BatchRebuildInventoryFromSubscriptions</name>
  <purpose>Creates inventory records based on the Subscription Product & Charge data
  </purpose>
  <created>
    <by>Steve O'Neal</by>
    <date>03/07/2016</date>
    <ticket>CSP-576</ticket>
  </created>
</Class>
*/
global class BatchRebuildInventoryFromSubscriptions implements Database.Batchable<sObject> {
	public string query = '';
	Map<String, Product2> productsMap = new Map<String, Product2>();
    Inventory_Hold_Expiry_Date_Offsets__c invHoldExpDate;
	
	global BatchRebuildInventoryFromSubscriptions()
	{
		invHoldExpDate = Inventory_Hold_Expiry_Date_Offsets__c.getOrgDefaults();
		
		List<Product2> productsWithCapacity = [select zqu__ZuoraId__c, Consolidate_Inventory__c from Product2 where zqu__Deleted__c = false];
		
		String queryRatePlanFilter = '';
		String comma = '';
		
		for (Product2 productWithCapacity : productsWithCapacity)
		{
			productsMap.put(productWithCapacity.zqu__ZuoraId__c, productWithCapacity);
			queryRatePlanFilter += comma + '\'' + productWithCapacity.zqu__ZuoraId__c + '\'';
			comma = ',';
		}
		
		query = ' SELECT ID, Name, Zuora__RatePlanName__c, Zuora__RatePlanEffectiveEndDate__c, Zuora__RatePlanId__c, Zuora__Subscription__r.Zuora__TermEndDate__c, Zuora__Product__r.Zuora__External_Id__c'
			  + ' FROM Zuora__SubscriptionProductCharge__c'
			  + ' WHERE Zuora__Product__r.Zuora__External_Id__c in (' + queryRatePLanFilter + ')'
			  + '   AND Zuora__Subscription__r.Zuora__TermEndDate__c >= TODAY'
			  + '   AND Name not in (\'Charge #01\',\'Charge #02\',\'Charge #03\',\'Charge #04\',\'Charge #05\',\'Charge #06\',\'Charge #07\',\'Charge #08\',\'Charge #09\',\'Charge #10\',\'Charge #11\',\'Charge #12\',\'80% Balance Due\')'
			  + '   AND Do_not_create_inventory__c != \'Yes\'';
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		Database.QueryLocator retVal = Database.getQueryLocator(query);
		return retVal;
	}
	
	global string NormalizeProductRatePlanName(string ratePlanName, string consolidateInventory)
	{
		string retVal = ratePlanName;

		// CSP-1766 | reduce retVal (ratePlanName) if charlength > 80; zqu__ProductRatePlan__c.Name has a max
		// length of 80 chars, but Zuora__SubscriptionProductCharge__c.Zuora__RatePlanName__c can be up to 255 chars
		if (retVal.length() > 80) {
			retVal = retVal.left(80);
		}
		
		retVal = retVal.Replace('^','|');
   		if (consolidateInventory == 'By Product and Market')
   		{
   			//if the ratePlanName is composed of ProductName and MarketName, we shouldn't do any thing
   			//if the ratePlanName is composed of ProductName and MarketName and CategoryName, we should delete the CategoryName from the ratePlanName
   			integer numberOfPipe = retVal.countMatches('|');
   			if(numberOfPipe > 1){
   				integer lastPipeIndex = retVal.lastIndexOf('|');
	   			if (lastPipeIndex > 0)
	   			{
	   				retVal = retVal.left(lastPipeIndex).trim();
	   			}
   			}
   		}
		return retVal;
	}

   	global void execute(Database.BatchableContext BC, List<Zuora__SubscriptionProductCharge__c> scope) {
		//System.Debug('Entering BatchRebuildInventoryFromSubscriptions.execute.');
   		List<Inventory__c> InventoryList = new List<Inventory__c>();
   		try
   		{
   			Set<string> ProductRatePlans = new Set<string>();
	   		for (Zuora__SubscriptionProductCharge__c spc : scope)
	   		{
	   			String ratePlanName = NormalizeProductRatePlanName(spc.Zuora__RatePlanName__c, productsMap.get(spc.Zuora__Product__r.Zuora__External_Id__c).Consolidate_Inventory__c);
	   			//System.Debug('Adding the rate plan ' + spc.Zuora__RatePlanName__c + ' to list as ' + ratePlanName);
	   			ProductRatePlans.add(ratePlanName);
	   		}
	   		
	   		//System.Debug('Fetch details for ' + ProductRatePlans.size() + ' rate plans');
			List<zqu__ProductRatePlan__c> productRatePlansWithCapacity = [Select Id, Name, zqu__Product__c, zqu__Product__r.zqu__ZuoraId__c from zqu__ProductRatePlan__c where Is_Inventory_Managed__c = true and zqu__Deleted__c = false and zqu__Product__r.zqu__Deleted__c = false and name in :ProductRatePlans];
			System.debug(LoggingLevel.INFO, '*** productRatePlansWithCapacity: ' + productRatePlansWithCapacity);

			//System.Debug('Create a map of the rate plans going forward and for legacy plans');
			Map<String, zqu__ProductRatePlan__c> productRatePlanConvertMap = new Map<String, zqu__ProductRatePlan__c>();
			for (zqu__ProductRatePlan__c prp : productRatePlansWithCapacity)
			{
				productRatePlanConvertMap.put(prp.Name, prp);
				productRatePlanConvertMap.put(prp.Name.Replace('|','^'), prp);
			}
			
	   		for (Zuora__SubscriptionProductCharge__c spc : scope)
	   		{
	   			String ratePlanName = NormalizeProductRatePlanName(spc.Zuora__RatePlanName__c, productsMap.get(spc.Zuora__Product__r.Zuora__External_Id__c).Consolidate_Inventory__c);
	   			if (productRatePlanConvertMap.ContainsKey(ratePlanName))
	   			{
		   			Inventory__c newInventory = new Inventory__c();
					newInventory.Product_Rate_Plan__c = productRatePlanConvertMap.get(ratePlanName).id;
					newInventory.Quote_Rate_Plan__c = null;
					newInventory.Waitlist_Account__c = null;
					newInventory.Subscription_Product_Charge__c = spc.id;
					newInventory.Subscription_RatePlan_Id__c = spc.Zuora__RatePlanId__c;
					newInventory.Inventory_Hold_Expiry_Date__c = DateUtility.AddBusinessDays(spc.Zuora__Subscription__r.Zuora__TermEndDate__c, (Integer)invHoldExpDate.Subscription_Product_Charge_Day_Offset__c);
					// set Held_By_Migrated_Subscription__c flag to true if held by migrated subscription
					if (spc.Name == 'Charge #00')
					{
						newInventory.Held_By_Migrated_Subscription__c = True;
					}
					if (newInventory.Inventory_Hold_Expiry_Date__c >= Date.Today())
					{
						InventoryList.add(newInventory);
					}
					else
					{
		   				//System.Debug('Inventory would have expired already - skipping inventory record for ' + spc.Zuora__RatePlanName__c + ' ' + spc.Name + '(' + spc.Id + ').');
					}
	   			}
	   			else
	   			{
	   				//System.Debug('Could not find a matching rate plan with capacity value - skipping inventory record for ' + spc.Zuora__RatePlanName__c + ' ' + spc.Name + '(' + spc.Id + ').');
	   			}
	   		}		
   		}
   		catch (Exception exceptionCreateInventory)
   		{
   			ExceptionUtility.consumeException(exceptionCreateInventory, true);		
   		}
   		
   		try
   		{
   			insert InventoryList;	
   		}
   		catch (Exception exceptionInsertInventory)
   		{
   			ExceptionUtility.consumeException(exceptionInsertInventory, true);
   		}
   		
   	}
   	
    global void finish(Database.BatchableContext BC)
    {
		// string BatchDelAvailInvName = 'BatchDeleteAvailableInventory';

		// Map<String, ChainBatchJob__c> chainBatchJob = ChainBatchJob__c.getAll();
		// ChainBatchJob__c bdaiChainBatchJob = new ChainBatchJob__c();
		// if (chainBatchJob.containsKey(BatchDelAvailInvName))
		// {
		// 	//System.Debug('Found a custom setting for ' + BatchDelAvailInvName);
		// 	bdaiChainBatchJob = chainBatchJob.get(BatchDelAvailInvName);
		// }
		// else
		// {
		// 	//System.Debug('Creating a new custom setting for ' + BatchDelAvailInvName);
		// 	bdaiChainBatchJob.Name = BatchDelAvailInvName;
		// }
		// //System.Debug('Turning on chaining for ' + BatchDelAvailInvName);
		// bdaiChainBatchJob.Chain_Next_Batch_Job__c = true;
		// upsert bdaiChainBatchJob;
		//   	//System.Debug('Exiting BatchRebuildInventoryFromSubscriptions.finish');

		//   	// CSP-1796 | immediately run this job after to convert waitlist records to inventory
		//  	BatchDeleteAvailableInventory b = new BatchDeleteAvailableInventory();
		// database.executebatch(b);
		// Created inventory for the renewal quote before movet the waitlist to inventory
		BatchCreateInventoryForRenewalQuote b = new BatchCreateInventoryForRenewalQuote();
		database.executebatch(b);
    }
}