src/objects/ChainBatchJob__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of batch jobs and whether or not to allow them to chain.  If blank, the batch job will assume that it&apos;s ok to run as a chain.</description>
    <fields>
        <fullName>Chain_Next_Batch_Job__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If true, this batch job is allowed to call the next job in the chain.</inlineHelpText>
        <label>Chain Next Batch Job</label>
        <type>Checkbox</type>
    </fields>
    <label>Chain Batch Job</label>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <description>Inventory is available for deletion if it:
a) has expired
b) has a rate plan id but no corresponding rate plan, and was last modified in the last 30 minutes
or
c) has no value in the waitlisted account, rate plan id, or quote rate plan</description>
        <formula>OR(
 Inventory_Hold_Expiry_Date__c &lt; TODAY(),
 AND(
     NOT(ISBLANK( Subscription_RatePlan_Id__c )),
     ISBLANK( Subscription_Product_Charge__c ),
     (NOW() - LastModifiedDate) &gt; 0.02
    ),
 AND(
     ISBLANK( Waitlist_Account__c ),
     ISBLANK( Subscription_RatePlan_Id__c ),
     ISBLANK( Quote_Rate_Plan__c )
    )
)</formula>
        <inlineHelpText>If the hold date has expired, or we don&apos;t have this slot reserved for anyone in particular, the slot is available.</inlineHelpText>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchDeleteAvailableInventory.cls
/* 
<Class>
  <name>BatchDeleteAvailableInventory</name>
  <purpose>To remove any unecessary inventory, freeing up product rate plans to be deleted
  </purpose>
  <created>
	<by>Steve O'Neal</by>
	<date>03/02/2016</date>
	<ticket>CSP-576</ticket>
  </created>
</Class>
*/
global class BatchDeleteAvailableInventory implements Database.Batchable<sObject> {
	public string query = '';
	
	global BatchDeleteAvailableInventory() {
		System.Debug('Entering constructor for BatchDeleteAvailableInventory');
		query = ' SELECT ID, available__c'
			  + ' FROM Inventory__c'
			  + ' WHERE available__c = TRUE';
			  
		System.Debug('Query: ' + query);
		System.Debug('Exiting constructor for BatchDeleteAvailableInventory');
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.Debug('Entering BatchDeleteAvailableInventory.start');
		Database.QueryLocator retVal = Database.getQueryLocator(query);
		System.Debug('Exiting BatchDeleteAvailableInventory.start');
		return retVal;
	}

	global void execute(Database.BatchableContext BC, List<Inventory__c> scope) {
		Database.DeleteResult[] dbDeleteResult = Database.delete(scope, false);
		List<XO_Exception__c> xoExceptionList = ExceptionUtility.consumeException(dbDeleteResult);
		if (xoExceptionList.size() > 0) {
			insert xoExceptionList;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		System.Debug('Entering BatchDeleteAvailableInventory.finish');
		Boolean runNextBatchJob = true;
		Map<String, ChainBatchJob__c> chainBatchJob = ChainBatchJob__c.getAll();
		if (chainBatchJob.containsKey('BatchDeleteAvailableInventory')) {
			runNextBatchJob = chainBatchJob.get('BatchDeleteAvailableInventory').Chain_Next_Batch_Job__c;
		}
		
		System.Debug('Run next batch job:' + runNextBatchJob);
		if (runNextBatchJob && !Test.isRunningTest()) {
			System.Debug('Running BatchConvertWaitlistToInventory next');
			BatchConvertWaitlistToInventory batch1 = new BatchConvertWaitlistToInventory();
			Database.ExecuteBatch(batch1,200);
			
		}
		
		System.Debug('Exiting BatchDeleteAvailableInventory.finish');
	}
}