src/objects/Compensation_Role__c.object
<CustomObject>
    <fields>
        <fullName>Compensation_Type__c</fullName>
        <label>Compensation Type</label>
        <picklist>
            <picklistValues>
                <fullName>NSBB</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Compensation_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Compensation Role</label>
    <nameField>
        <displayFormat>CompRole-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Compensation Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensation Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CompensationRoleTriggerTest.cls
@isTest
private class CompensationRoleTriggerTest {
    static testMethod void testMethod1() {
    	Test.startTest();
      Compensation_Role__c compRole1 = new Compensation_Role__c();
      compRole1.Sales_Rep__c = userInfo.getUserId();
      compRole1.Start_Date__c = system.today().addDays(-7);
      compRole1.End_Date__c = system.today().addDays(-5);
      compRole1.Compensation_Type__c = 'NSBB';
      insert compRole1;
      Test.stopTest();
    }
}