src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition #</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions_del</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <description>Revisited This. Ref : SF-1811</description>
        <label>Short Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Print_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Edition</label>
        <referenceTo>Edition__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Print Issues (Next Issue)</relationshipLabel>
        <relationshipName>Print_Issues2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Print_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select Active Markets</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_1st_Cover_Ship__c</fullName>
        <label>Publish/1st Cover Ship</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selling_Start_Date__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate a start date</inlineHelpText>
        <label>Selling Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_2__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 2 Contracts/Non-CR Ads</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Step_3__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 3 Contracts/CR Ads</label>
        <type>Date</type>
    </fields>
    <label>Print Issue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Print Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>Discount_Override__c</fullName>
        <description>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</description>
        <inlineHelpText>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</inlineHelpText>
        <label>Discount Override %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Print_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AK - Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL - Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR - Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Tucson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Central CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Palm Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - San Francisco/Bay Area/Northern CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Santa Barbara/Ventura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAN - Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO - Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT - Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC - Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL - Central FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL - Northern FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL - South FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL - West Coast FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA - Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA - Savannah/Coastal GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI - Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID - Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL - Central IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL - Chicago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL - Chicago Suburbs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN - Indiana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Charges__c</fullName>
        <label>Number of Charges</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Print_Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Print Issue that applies to a given product on a quote</inlineHelpText>
        <label>Print Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ChargeType__c</fullName>
        <label>Charge Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>zqu__EffectivePrice__c</fullName>
        <label>Effective Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Period__c</fullName>
        <label>Period</label>
        <picklist>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan Charge associated with a Product Rate Plan Charge.</description>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteRatePlanChargeTHTest.cls
@isTest
public class ZuoraQuoteRatePlanChargeTHTest {

	public static testMethod void testTheController1(){
		
		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		
		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		Market__c testMkt = TestClassUtility.createMarket(true);

		Map<String, SObject> testsub =TestClassUtility.buildSubscriptionData((Account)testObjects.get('Account'), 
																			(Contact)testObjects.get('Contact'), 
																			(Opportunity)testObjects.get('Opportunity') , 
																			(Zuora__CustomerAccount__c)testObjects.get('Zuora__CustomerAccount__c'));
		

		zqu__QuoteRatePlanCharge__c testQRP = (zqu__QuoteRatePlanCharge__c)testsub.get('zqu__QuoteRatePlanCharge__c');

		Publication__c testPublication = new Publication__c();
		testPublication.name = 'testPublication';
		testPublication.Short_Name__c = 'test';
		insert testPublication;

		Edition__c testEdition = new Edition__c();
		testEdition.name = 'testEdition';
		testEdition.Publication__c = testPublication.id;
		insert testEdition;


		Print_Issue__c pi1 =new Print_Issue__c();
		pi1.name = 'test name';
		pi1.Edition__c = testEdition.id;
		pi1.Print_Market__c = testMkt.id;
		pi1.Selling_Start_Date__c = date.today();
		pi1.Publish_1st_Cover_Ship__c = date.today();
		insert pi1;
		
		Print_Issue__c pi2 =new Print_Issue__c();
		pi2.name = 'test name';
		pi2.Edition__c = testEdition.id;
		pi2.Print_Market__c = testMkt.id;
		pi2.Selling_Start_Date__c = date.today();
		pi2.Publish_1st_Cover_Ship__c = date.today();
		insert pi2;
		
		Print_Issue__c pi =new Print_Issue__c();
		pi.name = 'test name';
		pi.Previous_Issue__c = pi1.id;
		pi.Next_Issue__c = pi2.id;
		pi.Edition__c = testEdition.id;
		pi.Print_Market__c = testMkt.id;
		pi.Selling_Start_Date__c = date.today();
		pi.Publish_1st_Cover_Ship__c = date.today();
		pi.Step_2__c = date.today().adddays(-1);
		pi.Step_3__c = date.today().adddays(-1);
		insert pi;
		
		//zqu__QuoteRatePlanCharge__c testZquQuoteRatePlanCharge = new zqu__QuoteRatePlanCharge__c();
		//testZquQuoteRatePlanCharge.Name = 'Test Quote Rate Plan Charge';  
		//testZquQuoteRatePlanCharge.zqu__QuoteRatePlan__c = testZquQuoteRatePlan.id; 
		//testZquQuoteRatePlanCharge.zqu__ProductRatePlanCharge__c = testZquProductRatePlanCharge.id;
		testQRP.zqu__Total__c = 1;
		testQRP.zqu__EffectivePrice__c = 20;
		testQRP.zqu__EffectivePrice__c = 15;
		testQRP.Product_Type__c = 'Print';
		testQRP.Print_Issue__c = pi.id;
		testQRP.zqu__ChargeType__c = 'Recurring';
		testQRP.List_Price__c = '12';
		testQRP.zqu__Period__c = 'Quarter';
		testQRP.zqu__Discount__c = 31;
		testQRP.Number_of_Charges__c = 3;
		testQRP.Discount_Override__c = 1;
		update testQRP;
		

		
		ZuoraQuoteRatePlanChargeTriggerHandler testcase = new ZuoraQuoteRatePlanChargeTriggerHandler();
		testcase.bulkBefore();
		testcase.bulkAfter();
		testcase.beforeInsert(testQRP);
		testcase.beforeUpdate(testQRP,testQRP);
		testcase.beforeDelete(testQRP);
		testcase.afterInsert(testQRP);
		testcase.afterUpdate(testQRP,testQRP);
		testcase.afterDelete(testQRP);
		testcase.andFinally();
		
		
		delete testQRP;
	}
}