src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition #</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions_del</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <description>Revisited This. Ref : SF-1811</description>
        <label>Short Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Print_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Edition</label>
        <referenceTo>Edition__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Years_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Year&apos;s Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Print Issues (Previous Year&apos;s Issue)</relationshipLabel>
        <relationshipName>Print_Issues1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Print_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select Active Markets</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_1st_Cover_Ship__c</fullName>
        <label>Publish/1st Cover Ship</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selling_End_Date__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate an end date</inlineHelpText>
        <label>Selling End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selling_Start_Date__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate a start date</inlineHelpText>
        <label>Selling Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_2__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 2 Contracts/Non-CR Ads</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Step_3__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 3 Contracts/CR Ads</label>
        <type>Date</type>
    </fields>
    <label>Print Issue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Print Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Print_Issue_Date_Offset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Choose the offset in number of days that the default dates should be for a Print Issue</description>
    <fields>
        <fullName>Offset_in_Days__c</fullName>
        <inlineHelpText>Number of days (plus or minus) from the publication date</inlineHelpText>
        <label>Offset in Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Print Issue Date Offset</label>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPrintIssueTrigger.cls
/**
 This class will test all Print Issues and supporting objects (Editions and Publications)
 */
@isTest
private class TestPrintIssueTrigger {

    static testMethod void test_method_one() {
        Test.startTest();
        Print_Issue_Date_Offset__c pido = new Print_Issue_Date_Offset__c();
        pido.name = 'Selling_End_Date__c';
        pido.Offset_in_Days__c = 2;
        insert pido;
        
        Publication__c testPublication = new Publication__c();
        testPublication.name = 'testPublication';
        testPublication.Short_Name__c = 'test';
        insert testPublication;

        Edition__c testEdition = new Edition__c();
        testEdition.name = 'testEdition';
        testEdition.Publication__c = testPublication.id;
        insert testEdition;
        
        Market__c testMarket = new Market__c();
        testMarket.Name = 'Test Market';
        testMarket.Short_Description__c = 'Test Market';
        testMarket.Market_ID__c = '999';
        testMarket.Active__c = true;
        insert testMarket;
        
        Print_Issue__c pi1 =new Print_Issue__c();
        pi1.name = 'test name';
        pi1.Edition__c = testEdition.id;
        pi1.Print_Market__c = testMarket.id;
        pi1.Publish_1st_Cover_Ship__c = date.today();
        try{
        insert pi1;
        }catch(exception e){}
        
        pi1.Selling_Start_Date__c = date.today();
        insert pi1;
        
        Print_Issue__c pi =new Print_Issue__c();
        pi.name = 'test name';
        pi.Previous_Years_Issue__c = pi1.id;
        pi.Edition__c = testEdition.id;
        pi.Print_Market__c = testMarket.id;
        pi.Publish_1st_Cover_Ship__c = date.today();
        pi.Step_2__c = date.today().adddays(-1);
        pi.Step_3__c = date.today().adddays(-1);
        try{
        insert pi;
        }catch(exception e){}
        
        Test.stopTest();
    }
}