src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Custom_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Custom Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition #</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions_del</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <description>Revisited This. Ref : SF-1811</description>
        <label>Short Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Print_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Custom_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, allows user to enter any name they choose.  When unchecked, the system will name the object</inlineHelpText>
        <label>Allow Custom Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Edition</label>
        <referenceTo>Edition__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Years_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Year&apos;s Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Print Issues (Previous Year&apos;s Issue)</relationshipLabel>
        <relationshipName>Print_Issues1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Print_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You may only select Active Markets</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Print Issues</relationshipLabel>
        <relationshipName>Print_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_1st_Cover_Ship__c</fullName>
        <label>Publish/1st Cover Ship</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selling_End_Date__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate an end date</inlineHelpText>
        <label>Selling End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selling_Start_Date__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate a start date</inlineHelpText>
        <label>Selling Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_3__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 3 Contracts/CR Ads</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Step_5__c</fullName>
        <inlineHelpText>Leave blank to have the system automatically calculate</inlineHelpText>
        <label>Step 5 Book to Printer</label>
        <type>Date</type>
    </fields>
    <label>Print Issue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Print Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Print_Issue_Date_Offset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Choose the offset in number of days that the default dates should be for a Print Issue</description>
    <fields>
        <fullName>Offset_in_Days__c</fullName>
        <inlineHelpText>Number of days (plus or minus) from the publication date</inlineHelpText>
        <label>Offset in Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Print Issue Date Offset</label>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintIssueTriggerHandler.cls
public with sharing class PrintIssueTriggerHandler {
	public static void SetDateDefaults(List<Print_Issue__c> printIssues)
	{
		// get all of the custom setting date offsets
		Map<string, Print_Issue_Date_Offset__c> dateOffsets = Print_Issue_Date_Offset__c.getAll();
		
		List<Print_Issue__c> previousYearIssues = new List<Print_Issue__c>();
		List<Id> previousYearIssueIds = new List<Id>();
		
		// first, get the list of previousYearIssue Ids we may need.  These are any Print Issues that don't have a Selling Start date and also have a previous year issue defined.
		for (Print_Issue__c PI : printIssues)
		{
			// selling start date is dependent on the PREVIOUS YEAR's data
			if (PI.Selling_Start_Date__c == null)
			{
				if(PI.Previous_Years_Issue__c == null)
				{
					PI.Selling_Start_Date__c.AddError('Because the Previous Year\'s Issue was not specified, you must enter a Selling Start Date');
				}
				else
				{
					previousYearIssueIds.add(PI.Previous_Years_Issue__c);
				}
			}
		}
		
		// get the needed previous year's issues from the db
		if (previousYearIssueIds.size() > 0)
		{
			previousYearIssues = [select Id, Step_3__c from Print_Issue__c where id =:previousYearIssueIDs];
		}
		
		
		// if any of the various publication schedule dates are empty, set them based on the publication date
		// loop over the Print Issues being saved
		for (Print_Issue__c PI : printIssues)
		{
			// loop through the Custom Settings where the offsets are defined
			for (Print_Issue_Date_Offset__c dateOffset : dateOffsets.values())
			{
				Date tmp = (Date)PI.get(dateOffset.Name);
				// only override the null values
				if (tmp == null)
				{
					// add the days defined in the offset
					PI.put(dateOffset.Name, PI.Publish_1st_Cover_Ship__c.addDays((integer)dateOffset.Offset_in_Days__c));
				}
			}

			/* Selling Start and End Dates */
			// selling start date is dependent on the PREVIOUS YEAR's data
			if (PI.Selling_Start_Date__c == null)
			{
				// we added the error above if needed, no need to check again	
				if(PI.Previous_Years_Issue__c != null)
				{
					for (Print_Issue__c lastYearsIssue : previousYearIssues)
					{
						if (lastYearsIssue.Id == PI.Previous_Years_Issue__c)
						{
							PI.Selling_Start_Date__c = lastYearsIssue.Step_5__c.addDays(1);
							break;
						}
					}
				} 
			}
			
			// selling end date is equal to step 5 if not specified
			if (PI.Selling_End_Date__c == null)
			{
				PI.Selling_End_Date__c = PI.Step_5__c;
			}
		}
		
		
	}
	
	// assigns a 'Print Issue' name and overrides anything the user entered
	public static void SetNamingConvention(List<Print_Issue__c> printIssues)
	{
		// we need data from the related Editions
		Map<Id, Market__c> marketMap = new Map<id, Market__c>();
		List<Id> marketIds = new List<Id>();
		Map<Id, Edition__c> editionsMap = new Map<Id, Edition__c>();
		List<Id> editionIds = new List<Id>();
		
		// get the list of Edition Ids and Markets
		for (Print_Issue__c PI : printIssues)
		{
			editionIds.add(PI.Edition__c);
			marketIds.add(PI.Print_Market__c);
		}
		
		if (editionIds.size() > 0)
		{
			editionsMap = new Map<Id, Edition__c>([Select Id, Name, Short_Name__c, Publication__c, Publication__r.Name, Publication__r.Short_Name__c from Edition__c where Id = :editionIds]);
		}
		
		if (marketIds.size() > 0)
		{
			marketMap = new Map<Id, Market__c>([Select Id, Name from Market__c where Id = :marketIds]);
		}
		
		
		// we also need editions
		
		
		for (Print_Issue__c PI : printIssues)
		{
			if (!PI.Allow_Custom_Name__c)
			{
				PI.Name = editionsMap.get(PI.Edition__c).Publication__r.Name + ' ' + marketMap.get(PI.Print_Market__c).Name + ' ' + editionsMap.get(PI.Edition__c).Name;
				PI.Short_Name__c = editionsMap.get(PI.Edition__c).Publication__r.Short_Name__c + ' ' + marketMap.get(PI.Print_Market__c).Name + ' ' + editionsMap.get(PI.Edition__c).Short_Name__c;
			}
		}
	}
}