src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteChargeDetail__c.object
<CustomObject>
    <description>This object is used to store the details (including billing metrics) for charges on a quote.</description>
    <fields>
        <fullName>Exist_Subscription_Id__c</fullName>
        <formula>zqu__Quote__r.zqu__ExistSubscriptionID__c</formula>
        <label>Exist Subscription Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Freed_By_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1543 | during Cancellation Quote creation, this checkbox is checked if the cancellation will free an Inventory slot</description>
        <inlineHelpText>CSP-1543 | during Cancellation Quote creation, this checkbox is checked if the cancellation will free an Inventory slot</inlineHelpText>
        <label>Inventory Freed By Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <formula>TEXT(zqu__Quote__r.zqu__SubscriptionType__c)</formula>
        <label>Subscription Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__OriginalId__c</fullName>
        <description>The Zuora Id of the original Rate Plan Charge this charge corresponds to.</description>
        <inlineHelpText>The Zuora Id of the original Rate Plan Charge this charge corresponds to.</inlineHelpText>
        <label>Original Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote Charge Detail</label>
    <nameField>
        <label>Quote Charge Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charge Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteChargeDetailTriggerHandler.cls
public without sharing class ZuoraQuoteChargeDetailTriggerHandler implements XOTrigger {
	////////////////////////
	// Instance Variables //
	////////////////////////
	
	Set<String> cancellationIdSet = new Set<String>();
	Map<String, Inventory__c> cancellationInventoryMap = new Map<String, Inventory__c>();


	/**
	*   Method used to bulkify all data needed in any "before" action of a trigger.
	*/
	public void bulkBefore() {
		if (Trigger.isInsert || Trigger.isUpdate) {
			for (Integer i = 0; i < Trigger.new.size(); i++) {
				zqu__QuoteChargeDetail__c newRec = (zqu__QuoteChargeDetail__c)Trigger.new[i];
				// CSP-1543 | if Cancellation Quote populate set for query
				if (newRec.Subscription_Type__c == 'Cancel Subscription') {
					cancellationIdSet.add(newRec.Exist_Subscription_Id__c);
				}
			}
			if (cancellationIdSet.size() > 0) {
				for (Inventory__c invRec : [SELECT Id, Subscription_Product_Charge__r.Zuora__Zuora_Id__c FROM Inventory__c WHERE Subscription_Product_Charge__r.Zuora__Subscription__r.Zuora__Zuora_Id__c IN :cancellationIdSet] ){
					cancellationInventoryMap.put(invRec.Subscription_Product_Charge__r.Zuora__Zuora_Id__c, invRec);
				}
			}
		}
	}

	/**
	*   Method used to bulkify all data needed in any "after" action of a trigger.
	*/
	public void bulkAfter() {

	}

	/**
	*   All before insert logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentially hit limits or is considered bad practice 
	*   in the Salesforce environment.
	*   
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void beforeInsert(SObject so) {
		zqu__QuoteChargeDetail__c newRec = (zqu__QuoteChargeDetail__c)so;

		// use newRec.zqu__OriginalId__c to match in cancellationInventoryMap
		if (cancellationInventoryMap.containsKey(newRec.zqu__OriginalId__c)) {
			cancellationInventoryMap.remove(newRec.zqu__OriginalId__c);
			newRec.Inventory_Freed_By_Cancellation__c = true;
		}
	}

	/**
	*   All before update logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentially hit limits or is considered bad practice
	*   in the Salesforce environment.
	*
	*   @param  {SObject}   oldSo Single SObject representation of the "old" copy of the current 
	*                             object being acted upon.
	*   @param  {SObject}   so    Single SObject representation of the object being acted upon.
	*/
	public void beforeUpdate(SObject oldSo, SObject so) {

	}

	/**
	*   All before delete logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment.
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void beforeDelete(SObject so) {

	}

	/**
	*   All after insert logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment. 
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void afterInsert(SObject so) {

	}

	/**
	*   All after update logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment.
	*   
	*   @param  {SObject}   oldSo Single SObject representation of the "old" copy of the current 
	*                             object being acted upon.
	*   @param  {SObject}   so    Single SObject representation of the object being acted upon.
	*/
	public void afterUpdate(SObject oldSo, SObject so) {

	}

	/**
	*   All after delete logic should be done here. This method is called iteratively and as such
	*   should contain no actions which could potentilly hit limits or is considered bad practice
	*   in the Salesforce environment. 
	*
	*   @param  {SObject}   so Single SObject representation of the object being acted upon.
	*/
	public void afterDelete(SObject so) {

	}

	/**
	*   All final logic in the "before" context should be done at this point such as modification to objects outside of
	*   the current object. At this point all updates to the current trigger transaction should be
	*   complete and all validation done.
	*/
	public void beforeAndFinally() {

	}

	/**
	*   All final logic in the "after" context should be done at this point such as modification to objects outside of
	*   the current object. At this point all updates to the current trigger transaction should be
	*   complete and all validation done.
	*/
	public void afterAndFinally() {

	}

	//////////////////////////
	// CUSTOM METHODS BELOW //
	//////////////////////////


}