src/objects/Inventory_Hold_Expiry_Date_Offsets__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For setting the number of days to offset the inventory expiry date when dealing with different objects.  Negative numbers mean before the date in question, positive numbers mean after the date in question.</description>
    <fields>
        <fullName>Account_Day_Offset__c</fullName>
        <defaultValue>3</defaultValue>
        <inlineHelpText>Number of work days from today&apos;s date to hold the inventory</inlineHelpText>
        <label>Account Day Offset</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Hold Expiry Date Offsets</label>
</CustomObject>

src/objects/Waitlist__c.object
<CustomObject>
    <label>Waitlist</label>
    <nameField>
        <displayFormat>WAIT-{000000}</displayFormat>
        <label>Waitlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchConvertWaitlistToInventoryTest.cls
@isTest
private class BatchConvertWaitlistToInventoryTest {
  
  @isTest static void batchTest() {
    // CREATE TEST DATA
    // zqu__ZProduct__c testProduct = TestClassUtility.createProduct(true);
    Product2 testProduct = TestClassUtility.createLocalProduct2(true);
    zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true, testProduct);
    Waitlist__c waitlist = TestClassUtility.createWaitlist(true,testProductRatePlan); 
    Inventory_Hold_Expiry_Date_Offsets__c invHoldExpDate = Inventory_Hold_Expiry_Date_Offsets__c.getOrgDefaults();
    invHoldExpDate.Account_Day_Offset__c = 2;
    upsert invHoldExpDate;

    // BEGIN TEST
    Test.startTest();
    BatchConvertWaitlistToInventory bct = new BatchConvertWaitlistToInventory();
    ID batchprocessid = Database.executeBatch(bct);
    Test.stopTest();
  } 
}