src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <description>Inventory is available for deletion if it:
a) has expired
b) has a rate plan id but no corresponding rate plan, and was last modified in the last 30 minutes
or
c) has no value in the waitlisted account, rate plan id, or quote rate plan</description>
        <formula>OR(
 Inventory_Hold_Expiry_Date__c &lt; TODAY(),
 AND(
     NOT(ISBLANK( Subscription_RatePlan_Id__c )),
     ISBLANK( Subscription_Product_Charge__c ),
     (NOW() - LastModifiedDate) &gt; 0.02
    ),
 AND(
     ISBLANK( Waitlist_Account__c ),
     ISBLANK( Subscription_RatePlan_Id__c ),
     ISBLANK( Quote_Rate_Plan__c )
    )
)</formula>
        <inlineHelpText>If the hold date has expired, or we don&apos;t have this slot reserved for anyone in particular, the slot is available.</inlineHelpText>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Held_By_Migrated_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when applicable during the BatchRebuildInventoryFromSubscriptions nightly batch job. This field is primarily used by the InventoryUtilities.IsInventoryAvailable method.</description>
        <label>Held By Migrated Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory_Hold_Expiry_Date__c</fullName>
        <inlineHelpText>The date that this inventory slot is reserved through.  If a spot has a hold expiry date of 2/1/2017, for example, it becomes available as soon as the date switches to 2/2/2017</inlineHelpText>
        <label>Held Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <inlineHelpText>The Product Rate Plan represents the product in a specific market/category.  In essence, this is the product we are tracking inventory against.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the inventory slot is reserved by a quote, this field will identify which quote rate plan is holding it.</inlineHelpText>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Waitlist_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waitlist Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Available for Purchase</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Available__c</fullName>
        <formula>IF (
    Is_Inventory_Managed__c,
    (VALUE(Capacity__c) &gt; Inventory_Held__c),
    TRUE
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Available__c</fullName>
        <description>If the value of Capacity__c is blank/null, set the return value of the formula to 1,000,000 so that the logic in the InventoryUtilities.IsInventoryAvailable method always determines that inventory is available. Otherwise, return the value of Capacity__c - Inventory_Held__c.</description>
        <formula>IF(Value(BlankValue(Capacity__c,&quot;0&quot;)) = 0,1000000,VALUE(Capacity__c) - Inventory_Held__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waitlist_Count__c</fullName>
        <label>Waitlist Count</label>
        <summaryFilterItems>
            <field>Waitlist__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Waitlist__c.Product_Rate_Plan__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteChargeDetail__c.object
<CustomObject>
    <description>This object is used to store the details (including billing metrics) for charges on a quote.</description>
    <fields>
        <fullName>Inventory_Freed_By_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1543 | during Cancellation Quote creation, this checkbox is checked if the cancellation will free an Inventory slot</description>
        <inlineHelpText>CSP-1543 | during Cancellation Quote creation, this checkbox is checked if the cancellation will free an Inventory slot</inlineHelpText>
        <label>Inventory Freed By Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Rate Plan this charge comes from.</description>
        <inlineHelpText>The Product Rate Plan this charge comes from.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Charge Details</relationshipLabel>
        <relationshipName>QuoteChargeDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The quote object this charge record belongs to.</description>
        <inlineHelpText>The quote object this charge record belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Charge Details</relationshipLabel>
        <relationshipName>QuoteChargeDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Charge Detail</label>
    <nameField>
        <label>Quote Charge Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charge Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>The Salesforce ID for the associated Account</description>
        <formula>zqu__Quote__r.zqu__Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</description>
        <inlineHelpText>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <description>The date the parent Quote is valid though.</description>
        <formula>zqu__Quote__r.zqu__ValidUntil__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date the parent Quote is valid though.</inlineHelpText>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora_Id_of_Migrated_Charge__c</fullName>
        <description>This Field is used to get populated by zuora Id of migrated charge.</description>
        <label>Zuora Id of Migrated Charge</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__AmendmentType__c</fullName>
        <description>The type of amendment being made.</description>
        <label>Amendment Type</label>
        <picklist>
            <picklistValues>
                <fullName>NewProduct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RemoveProduct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TermsAndConditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UpdateProduct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora_Id_of_Migrated_Charge__c</fullName>
        <description>This Field is used to get populated by zuora Id of migrated charge. After synced back from Zuora&apos;s Subscription Rate Plan Charge</description>
        <externalId>true</externalId>
        <label>Zuora Id of Migrated Charge</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InventoryUtilities.cls
/* 
<class>
  <name>InventoryUtilities</name>
  <purpose>Contains methods to assist in Inventory management</purpose>
  <created>
    <by>Jonathan Satterfield</by>
    <date>9/15/2015</date>
    <ticket>SF-1211</ticket>
  </created>
</class>
*/
public without sharing class InventoryUtilities {

	/* 
	<method>
	  <name>IsInventoryAvailable</name>
	  <purpose>Checks to see if Inventory records are available or can be created/modified as appropriate</purpose>
	  <created>
	    <by>Steve O'Neal</by>
	    <date>11/15/2015</date>
	    <ticket>SF-1211</ticket>
	  </created>
	</method>
	*/
	public static Map<Id,Boolean> IsInventoryAvailable(Set<Id> productRatePlanIdSet, Set<Id> quoteRatePlanIdSet, Id oppId) 
	{
		// map of QuoteRatePlan to Boolean (whether or not Inventory is available)
		// each QuoteRatePlanCharge record on the page will check this
		Map<Id,Boolean> inventoryAvailableForQuoteRatePlan = new Map<Id,Boolean>();

		// CSP-608; count migrated inventory records held by that account for a specific product rate plan
		// key: account id + prp id | value: set of Zuora Ids for Subscription Product Charges holding migrated inventory for this account + prp combo
		Map<String,Set<String>> countOfMigratedInventoryForAccountAndPRP = new Map<String,Set<String>>();
		Map<String,Set<String>> countOfMigratedInventoryForAccountAndPRPClone = new Map<String,Set<String>>();

		if (productRatePlanIdSet.size() > 0 && quoteRatePlanIdSet.size() > 0)
		{
			List<Inventory__c> inventoryUpsertList = new List<Inventory__c>();

			List<zqu__ProductRatePlan__c> prpList = [SELECT Id, Available__c, Waitlist_Count__c, Number_Available__c, 
													(SELECT Id, Account_ID__c, Quote_Expiration_Date__c, zqu__ProductRatePlan__c, zqu__AmendmentType__c, Zuora_Id_of_Migrated_Charge__c FROM zqu__Quote_Rate_Plans__r WHERE Id IN :quoteRatePlanIdSet), 
													(SELECT Id, Waitlist_Account__c, Quote_Rate_Plan__c, Product_Rate_Plan__c, Inventory_Hold_Expiry_Date__c, Held_By_Migrated_Subscription__c, Subscription_Product_Charge__r.Zuora__Account__c, Subscription_Product_Charge__r.Zuora__Zuora_Id__c FROM Inventory__r), 
													(SELECT Id FROM zqu__QuoteChargeDetails__r WHERE zqu__Quote__r.zqu__Opportunity__c = :oppId AND Inventory_Freed_By_Cancellation__c = true) 
													FROM zqu__ProductRatePlan__c WHERE Id IN :productRatePlanIdSet];

			for (zqu__ProductRatePlan__c prp : prpList) {

				// number of available Inventory slots for this Product Rate Plan
				Integer numberAvailableSlots = (Integer)prp.Number_Available__c;

				// CSP-1610 | if this is a "renewal" Opportunity doing a cancel/replace, set this Product Rate Plan's numberAvailableSlotsFromCancellation 
				// by the number of Inventory slots that will be freed by the Cancellation Quote; this value will be checked below
				Integer numberAvailableSlotsFromCancellation = prp.zqu__QuoteChargeDetails__r.size();			

				// set of QuoteRatePlan record IDs for QRPs that already have an associated Inventory record
				Set<Id> quoteRatePlansWithInventory = new Set<Id>();
				
				// "waitlist" Inventory records
				Map<String,List<Inventory__c>> waitlistInventoryMap = new Map<String,List<Inventory__c>>();

				// all that we do when we loop through the Inventory records is populate lists and maps
				// to be used in the QuoteRatePlan loop below, which is where we perform all of our logic
				for (Inventory__c inv : prp.Inventory__r) {

					if (inv.Quote_Rate_Plan__c != null) {
						quoteRatePlansWithInventory.add(inv.Quote_Rate_Plan__c);
					}

					// CSP-608; populate migrated inventory maps
					else if (inv.Held_By_Migrated_Subscription__c) {
						String tempMigratedInventoryMapKey = (String)inv.Subscription_Product_Charge__r.Zuora__Account__c + (String)inv.Product_Rate_Plan__c;
						Set<String> spcZIDs;
						if (countOfMigratedInventoryForAccountAndPRP.containsKey(tempMigratedInventoryMapKey)) {						
							spcZIDs = countOfMigratedInventoryForAccountAndPRP.get(tempMigratedInventoryMapKey);
						}
						else {
							spcZIDs = new Set<String>();
						}
						spcZIDs.add(inv.Subscription_Product_Charge__r.Zuora__Zuora_Id__c);
						countOfMigratedInventoryForAccountAndPRP.put(tempMigratedInventoryMapKey, spcZIDs);
						countOfMigratedInventoryForAccountAndPRPClone.put(tempMigratedInventoryMapKey, spcZIDs);
					}

					else if (inv.Waitlist_Account__c != null && inv.Quote_Rate_Plan__c == null) {
						String tempKey = String.valueOf(inv.Waitlist_Account__c).left(15) + String.valueOf(inv.Product_Rate_Plan__c);
						if (!waitlistInventoryMap.containsKey(tempKey)) {
							List<Inventory__c> newInvList = new List<Inventory__c>();
							newInvList.add(inv);
							waitlistInventoryMap.put(tempKey, newInvList);                                                   
						}
						else {
							List<Inventory__c> existingInvList = waitlistInventoryMap.get(tempKey);
							existingInvList.add(inv);
							waitlistInventoryMap.put(tempKey, existingInvList);
						}
					}
				}

				for (zqu__QuoteRatePlan__c qrp : prp.zqu__Quote_Rate_Plans__r) {
					String tempKey2 = String.valueOf(qrp.Account_ID__c) + String.valueOf(qrp.zqu__ProductRatePlan__c);
					String migratedInventoryMapKey = (String)(Id)qrp.Account_ID__c + (String)qrp.zqu__ProductRatePlan__c;

					System.debug('migrated inventory key:');
					System.debug(migratedInventoryMapKey);

					// SCENARIO 1: QuoteRatePlan already has a child Inventory record or it is part of a Renewal Quote
					if (quoteRatePlansWithInventory.contains(qrp.Id) || qrp.zqu__AmendmentType__c.containsIgnoreCase('renewal')) {
						// don't do anything
					}
					// SCENARIO 2: (CSP-1610) Inventory is going to be freed by a related Cancellation Quote on the same Opportunity
					else if (numberAvailableSlotsFromCancellation > 0) {
						numberAvailableSlotsFromCancellation--;
						// need to remove this QuoteRatePlan from the Id set so the check for Inventory being created down below doesn't include this QuoteRatePlan
						quoteRatePlanIdSet.remove(qrp.Id);
						// add this QuoteRatePlan to the inventoryAvailableForQuoteRatePlan stating it does have Inventory available
						inventoryAvailableForQuoteRatePlan.put(qrp.Id, true);
					}
					// SCENARIO 3: there's a "waitlist" Inventory record that the QuoteRatePlan can take control over
					else if (waitlistInventoryMap.containsKey(tempKey2)) {
						
						List<Inventory__c> invList = waitlistInventoryMap.get(tempKey2);
						if (invList.size() == 1) {
							Inventory__c invRecord = invList.remove(0);
							invRecord.Quote_Rate_Plan__c = qrp.Id;
							invRecord.Inventory_Hold_Expiry_Date__c = qrp.Quote_Expiration_Date__c;
							inventoryUpsertList.add(invRecord);
							// remove the key-value pair from the waitlistInventoryMap since the value (list) is now empty
							waitlistInventoryMap.remove(tempKey2);
						}
						// if multiple applicable "waitlisted" Inventory records exist, choose the oldest one
						else if (invList.size() > 1) {
							Integer listPosition = 0;
							Inventory__c tempInvRecord = null;
							for (Integer i = 0; i < invList.size(); i++) {
								// note to self: older < newer = True
								if (tempInvRecord == null || invList[i].Inventory_Hold_Expiry_Date__c < tempInvRecord.Inventory_Hold_Expiry_Date__c) {
									listPosition = i;
									tempInvRecord = invList[i];
								}
							}
							invList.remove(listPosition);
							tempInvRecord.Quote_Rate_Plan__c = qrp.Id;
							tempInvRecord.Inventory_Hold_Expiry_Date__c = qrp.Quote_Expiration_Date__c;
							inventoryUpsertList.add(tempInvRecord);
							waitlistInventoryMap.put(tempKey2, invList);				
						}
					}
					// SCENARIO 4: check for migrated inventory (CSP-608)
					else if (countOfMigratedInventoryForAccountAndPRP.containsKey(migratedInventoryMapKey)) {

						System.debug('FOUND MIGRATED');
						System.debug(countOfMigratedInventoryForAccountAndPRP);

						Set<String> currentCount = countOfMigratedInventoryForAccountAndPRP.get(migratedInventoryMapKey);
						if (currentCount.size() == 1) {
							countOfMigratedInventoryForAccountAndPRP.remove(migratedInventoryMapKey);
						}
						else {
							// can't remove a single set value by index, have to do this instead = /
							for (String sKey : currentCount) {
								currentCount.remove(sKey);
								break;
							}
							countOfMigratedInventoryForAccountAndPRP.put(migratedInventoryMapKey, currentCount);
						}
					}
					// SCENARIO 5: no Inventory record at all; find out if any slots are available
					else {
						// if there are open slots and this is for a new product, create a new Inventory record
						if (numberAvailableSlots > 0 && qrp.zqu__AmendmentType__c == 'NewProduct' && String.isBlank(qrp.Zuora_Id_of_Migrated_Charge__c)) {
							numberAvailableSlots--;
							Inventory__c newInvRecord = new Inventory__c();
							newInvRecord.Quote_Rate_Plan__c = qrp.Id;
							newInvRecord.Product_Rate_Plan__c = prp.Id;
							newInvRecord.Inventory_Hold_Expiry_Date__c = qrp.Quote_Expiration_Date__c;
							inventoryUpsertList.add(newInvRecord);
						}
					}
				}				
			}

			Database.upsert(inventoryUpsertList, False);


			// populate inventoryAvailableForQuoteRatePlan map here using query
			// it's possible that some upsert operations could have failed, so run a query
			// to populate the map after the DML statement

			List<zqu__QuoteRatePlan__c> finalQRPWithInventoryCheckList = [SELECT Id, zqu__AmendmentType__c, Account_ID__c, zqu__ProductRatePlan__c, Zuora_Id_of_Migrated_Charge__c, (SELECT ID FROM Inventory__r) FROM zqu__QuoteRatePlan__c WHERE Id IN :quoteRatePlanIdSet];

			Boolean updateFinalQRPWithInventoryCheckList = False;

			for (zqu__QuoteRatePlan__c zQRP : finalQRPWithInventoryCheckList) {

				// need to first cast zQRP.Account_ID__c to an Id, then back to String, in order to get the 18-digit key
				String migratedInventoryCloneMapKey = (String)(Id)zQRP.Account_ID__c + (String)zQRP.zqu__ProductRatePlan__c;

				System.debug('migrated inventory clone map key!');
				System.debug(migratedInventoryCloneMapKey);
				System.debug('migrated inventory clone map!');
				System.debug(countOfMigratedInventoryForAccountAndPRPClone);

			    // if at least one Inventory record present for QuoteRatePlan, save Id to Map with a "True" value
			    // also, if the QuoteRatePlan isn't for a new product or it's part of a renewal quote, flag it as True as well
			    if (zQRP.Inventory__r.size() > 0 || zQRP.zqu__AmendmentType__c != 'NewProduct') {
			    	inventoryAvailableForQuoteRatePlan.put(zQRP.Id, True);
			    }
			    // CSP-608: check for migrated inventory
			    else if (countOfMigratedInventoryForAccountAndPRPClone.containsKey(migratedInventoryCloneMapKey)) {
					Set<String> migratedInventoryCount = countOfMigratedInventoryForAccountAndPRPClone.get(migratedInventoryCloneMapKey);
					String migratedSPCZID;
					if (migratedInventoryCount.size() == 1) {
						// can't reference a single set value by index, have to do this instead = /
						for (String zIDValue : migratedInventoryCount) {
							migratedSPCZID = zIDValue;
							break;
						}
						countOfMigratedInventoryForAccountAndPRPClone.remove(migratedInventoryCloneMapKey);
					}
					else {
						for (String zIDValue2 : migratedInventoryCount) {
							migratedSPCZID = zIDValue2;
							migratedInventoryCount.remove(zIDValue2);
							break;
						}
						countOfMigratedInventoryForAccountAndPRPClone.put(migratedInventoryCloneMapKey, migratedInventoryCount);
					}

					zQRP.Zuora_Id_of_Migrated_Charge__c = migratedSPCZID;
					
					if (!updateFinalQRPWithInventoryCheckList) {
						updateFinalQRPWithInventoryCheckList = True;
					}

					inventoryAvailableForQuoteRatePlan.put(zQRP.Id, True);
			    }
			    // otherwise, put "False"
			    else {
			    	inventoryAvailableForQuoteRatePlan.put(zQRP.Id, False);
			    }
			}

			if (updateFinalQRPWithInventoryCheckList) {
				update finalQRPWithInventoryCheckList;
			}
		}

		return inventoryAvailableForQuoteRatePlan;
	}

	/* 
	<method>
	  <name>IsInventoryAvailable</name>
	  <purpose>Checks to see if Inventory records are available or can be created/modified as appropriate</purpose>
	  <created>
	    <by>Steve O'Neal</by>
	    <date>11/15/2015</date>
	    <ticket>SF-1211</ticket>
	  </created>
	</method>
	*/
	public static Map<Id,Boolean> IsInventoryAvailable(List<zqu__QuoteRatePlan__c> qrpList, Id oppId) {
		Set<Id> productRatePlanIdSet = new Set<Id>();
		Set<Id> quoteRatePlanIdSet = new Set<Id>();
		if (qrpList.size() > 0) {
			for (zqu__QuoteRatePlan__c qrp : qrpList) {
				// CSP-1963
				if(String.isNotBlank(qrp.Zuora_Id_of_Migrated_Charge__c)) {
					continue;
				}
				productRatePlanIdSet.add(qrp.zqu__ProductRatePlan__c);
				quoteRatePlanIdSet.add(qrp.Id);
			}
		}
		
		return IsInventoryAvailable(productRatePlanIdSet, quoteRatePlanIdSet, oppId);
	}
}