src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Salesforce_Generated_GUID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salesforce Generated GUID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Storefront_Status__c</fullName>
        <description>SF-1481, used for data migration purposes.</description>
        <label>Storefront Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unclaimed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claimed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MassConvertLocalLeadsController.cls
public without sharing class MassConvertLocalLeadsController {
	public String queryString {get;set;}
	public Boolean createOpportunity {get;set;}

	public MassConvertLocalLeadsController() {
		queryString = 'select Id from Lead where Storefront_Status__c = \'Claimed\' and Salesforce_Generated_GUID__c = false and IsConverted = false';
		createOpportunity = true;
	}

	public void executeBatchConvert(){
		String cleansedQueryString = String.escapeSingleQuotes(queryString);

		try{
			MassConvertLeadsBatch b = new MassConvertLeadsBatch(queryString, createOpportunity);
			database.executebatch(b, 10);
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Convert batch has been scheduled! Please go to Apex Jobs to view status!');
			ApexPages.addMessage(myMsg);
		}catch(Exception E){
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, E.getMessage());
    		ApexPages.addMessage(myMsg);
		}
	}
}