src/objects/NationalTSRFPAccFieldMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>National ThoughtStarter and RFP Field Mapping with Accounts</description>
    <fields>
        <fullName>Account_Field_API_Name__c</fullName>
        <label>Account Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_RFP_API_Name__c</fullName>
        <label>TS/RFP API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NationalTSRFPAccFieldMap</label>
</CustomObject>

src/objects/ThoughtStarter_RFP__c.object
<CustomObject>
    <fields>
        <fullName>Action_Explanation__c</fullName>
        <label>Action(s) Explanation:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ThoughtStarter / RFP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ThoughtStarters / RFPs</pluralLabel>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <label>RFP</label>
    </recordTypes>
    <recordTypes>
        <fullName>ThoughtStarter</fullName>
        <active>true</active>
        <label>ThoughtStarter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ThoughtStarterRFPEditControllerTest.cls
@isTest
private class ThoughtStarterRFPEditControllerTest {
    @isTest static void test_method_one() {
        NationalTSRFPAccFieldMap__c newTSRFPAcc = new NationalTSRFPAccFieldMap__c();
        newTSRFPAcc.Name = 'Test CS'; 
        newTSRFPAcc.Account_Field_API_Name__c = 'Name';
        newTSRFPAcc.TS_RFP_API_Name__c = 'Action_Explanation__c';
        insert newTSRFPAcc;
        
        Map<String, SObject> testObjects = TestClassUtility.buildNationalData();
        Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
    
        Test.startTest();
        PageReference pageRef = Page.ThoughtStarterRFPEdit;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('Type', 'ThoughtStarter');
        ApexPages.currentPage().getParameters().put('OpportunityId', testOpp.Id);

        ThoughtStarterRFPEditController contr = new ThoughtStarterRFPEditController(new ApexPages.StandardController(new ThoughtStarter_RFP__c()));

        ApexPages.currentPage().getParameters().put('Type', 'RFP');
        ApexPages.currentPage().getParameters().put('OpportunityId', testOpp.Id);

        contr = new ThoughtStarterRFPEditController(new ApexPages.StandardController(new ThoughtStarter_RFP__c()));
        Test.stopTest();
    }   
}