src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Close_Date__c</fullName>
        <inlineHelpText>The date the Opportunity actually closed</inlineHelpText>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Details__c</fullName>
        <label>Lost Reason Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <inlineHelpText>Select the primary reason that the Opportunity was lost</inlineHelpText>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Advertises w/a competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Already Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel/ Re-enter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact not responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of non-payment terms and conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of payment terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not contact again</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improperly Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue w/T&amp;Cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Client Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer doing weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason Given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Issue/Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Issue/Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhappy w/Results</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_Times_To_Extend__c</fullName>
        <defaultValue>0</defaultValue>
        <description>It used to stored extend times to auto close</description>
        <label># of Times To Extend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <businessProcess>Sales National</businessProcess>
        <description>Phase 1 National</description>
        <label>National</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCloseOpps.cls
/* 
<class>
  <name>BatchCloseOpps</name>
  <purpose>Auto closed the open Opp which is not modified in last 90 days.</purpose>
  <created>
    <by>Tony Liu</by>
    <date>07/07/2016</date>
    <ticket>CSP-1138</ticket>
  </created>
</class>
*/
public class BatchCloseOpps implements Database.Batchable<sObject> {
    private Set<String> oppStagesToIgnore;   
    private String query;
    private dateTime ToExpire;
    public BatchCloseOpps() {
        //Opportunity_Auto_Closed_Offsets__c OppAutoClosedOffsets = Opportunity_Auto_Closed_Offsets__c.getOrgDefaults();
        String dateOffset = !Test.isRunningTest()? Label.Opportunity_Auto_Closed_Offsets:'3';
        Integer daysToExpire = Integer.valueOf(dateOffset); 
        ToExpire = DateTime.now().adddays(daysToExpire);
        oppStagesToIgnore = new Set<String>{'Closed Won', 'Closed Lost'};

        // Nick Wu Modified CSP-1306 Opp-Auto Close Extension
        // Add No_of_Times_To_Extend__c in query
        query = 'SELECT Id, StageName,CloseDate,Actual_Close_Date__c, Lost_Reason__c, No_of_Times_To_Extend__c, CreatedDate FROM Opportunity WHERE Createddate <: ToExpire AND StageName NOT IN :oppStagesToIgnore AND RecordType.Name = \'National\'';
        
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        Database.QueryLocator retVal = Database.getQueryLocator(query);
        return retVal;
    }

    public void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        // CSP-1138 | close the Opportunity records which is opened too long
        for (Opportunity opp : scope) {

            // opp.StageName = 'Closed Lost';
            // opp.Lost_Reason__c = 'Expired';
            // opp.CloseDate = date.today();
            // opp.Lost_Reason_Details__c = 'Expired'; 

            // Nick Wu Modified CSP-1306 Opp-Auto Close Extension
            // Add logic to opp update if created date less then Number of times to extend multiple to 30 days
            // Check if No of Times to extend field if no being initialize, true then set default 0.
            if(opp.No_of_Times_To_Extend__c == null){
                opp.No_of_Times_To_Extend__c=0;
            }

            // Calculate the expireDays with adding the no of times to Extend * 30days
            Integer expireDays = Integer.valueOf(-(opp.No_of_Times_To_Extend__c*Integer.valueOf(Label.Opportunity_Auto_Closed_permanent_Day)));
            if(opp.CreatedDate <= ToExpire.addDays(expireDays)){
                opp.StageName = 'Closed Lost';
                opp.Lost_Reason__c = 'Expired';
                opp.CloseDate = date.today();
                opp.Lost_Reason_Details__c = 'Expired';
            }
        }
        
        Database.SaveResult[] dbSaveResult = Database.update(scope, false);
	    List<XO_Exception__c> xoExceptionList = ExceptionUtility.consumeException(dbSaveResult);
	    if(xoExceptionList.size() > 0){
	    	insert xoExceptionList;
	    }
    }

    public void finish(Database.BatchableContext BC) {
        // don't do anything
    }
}