src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <inlineHelpText>Select the primary reason that the Opportunity was lost</inlineHelpText>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Advertises w/a competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Already Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel/ Re-enter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact not responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of non-payment terms and conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of payment terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not contact again</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improperly Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue w/T&amp;Cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Client Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer doing weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason Given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Issue/Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Issue/Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhappy w/Results</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OppUpdateLastModifiedNumberOfDays__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CSP-1480</description>
    <label>OppUpdateLastModifiedNumberOfDays</label>
</CustomObject>

src/classes/BatchCloseExpiredLocalOppsSchedJobTest.cls
/*******************************************************************************
 *  Summary    : Test class for BatchCloseExpiredLocalOppsSchedJob
 *  Refer Object : 
 *  Author     : Nick
 *  RefactorDate : 12 Dec 2016
 *  Change Log   : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
private class BatchCloseExpiredLocalOppsSchedJobTest {
  
  @isTest static void test_method_one() {
    
    TestClassUtility.buildZQUTestObjects(false);
    
    Test.startTest();
    List<Opportunity> oppUpdateList = [SELECT Id, Opportunity_Expiration_Date__c, StageName, Lost_Reason__c FROM Opportunity WHERE RecordType.Name = 'Local'];
    for (Opportunity opp: oppUpdateList) {
      opp.StageName = 'Quoting';
      opp.Opportunity_Expiration_Date__c = Date.today() - 5;
    }
    Database.update(oppUpdateList, false);
    
    BatchCloseExpiredLocalOppsScheduledJob bct = new BatchCloseExpiredLocalOppsScheduledJob();
    String schedule = '0 0 23 * * ?';
    system.schedule('Nightly Update', schedule, bct );
    
    Test.stopTest();
  }

  @isTest static void test_method_two() {
    
    TestClassUtility.buildZQUTestObjects(false);
    OppUpdateLastModifiedNumberOfDays__c testOULMNOD = TestClassUtility.createOppUpdateLastModifiedNOD(TRUE);
    system.assertNotEquals(null,OppUpdateLastModifiedNumberOfDays__c.getInstance('StandardDaysCount'),'false');
    Test.startTest();
    List<Opportunity> oppUpdateList = [SELECT Id, Opportunity_Expiration_Date__c, StageName, Lost_Reason__c FROM Opportunity WHERE RecordType.Name = 'Local'];
    for (Opportunity opp: oppUpdateList) {
      opp.StageName = 'Quoting';
      opp.Opportunity_Expiration_Date__c = Date.today() - 5;
    }
    Database.update(oppUpdateList, false);
    
    BatchCloseExpiredLocalOppsScheduledJob bct = new BatchCloseExpiredLocalOppsScheduledJob();
    String schedule = '0 0 23 * * ?';
    system.schedule('Nightly Update', schedule, bct );
    
    Test.stopTest();
  }
}