src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_Flag_Skip_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</description>
        <inlineHelpText>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</inlineHelpText>
        <label>Skip EchoSign</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</description>
        <inlineHelpText>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>LocationVendorDynamicsAccountID__c</fullName>
        <label>LocationVendorDynamicsAccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Location/Vendor account that we are selling this product for.  For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location/Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LocalApprovalProcessUtilities.cls
global without sharing class LocalApprovalProcessUtilities {
	// CSP-572 | webservice called from Local Opp record detail page from a custom "Submit for Approval" button
	webservice static Boolean submitLocalOppForApproval(Id oppId) {
		// CSP-2232 and CSP-2349 
		// Check and update Commission charge type before Submit for Approval 
		// Commented by SF release 4.05
		//ZuoraQuoteEditLineItemsController.updateCommissionChargeType(oppId);

		// run product rules first
		LocalProductRules.evaluateOpportunity(oppId);
		// then, submit the Opportunity for approval
		Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
		app.setObjectId(oppId);
		Approval.ProcessResult result = Approval.process(app);
		return result.isSuccess();
	}

	webservice static String checkSubmitForApproval(Id oppId){
		//CSP - 2485 Disallow Sending Internet Quotes to Zuora without LocationId
		//Check below in the Quote Rate Plan if missing location id and LocationVendorDynamicsAccountID 
		List<zqu__QuoteRatePlanCharge__c> QuoteRatePlanChargeList = [SELECT Id, zqu__QuoteRatePlan__r.zqu__Quote__r.Product_Line__c,Location_Vendor__c
                                                                 FROM zqu__QuoteRatePlanCharge__c 
                                                                 WHERE zqu__QuoteRatePlan__r.zqu__Quote__r.zqu__Opportunity__c =: oppId  
                                                                  AND zqu__QuoteRatePlan__r.zqu__Quote__r.Product_Line__c = 'Internet' 
                                                                  AND (Location_Vendor__c = null 
                                                                    or LocationVendorDynamicsAccountID__c = null 
                                                                    or LocationVendorDynamicsAccountID__c = ''
                                                                    OR zqu__QuoteRatePlan__r.Location_Vendor__c = null)];
		//Disallow approval opportunity.	
		if(!QuoteRatePlanChargeList.isEmpty()) {
			return System.Label.MessageWithoutLocationId;
		}else{
			return 'true';
		}
	}

	// CSP-1787
	webservice static Boolean setOppSkipEchoSignFlagIfApplicableWebservice(Id oppId, String oppType, String userProfileName) {
		return setOppSkipEchoSignFlagIfApplicable(oppId, oppType, userProfileName);
	}

	/**
	 *   CSP-1787 | setOppSkipEchoSignFlagIfApplicable sets the Opportunity.Approval_Process_Flag_Skip_EchoSign__c checkbox to true
	 *   if the submitting user's profile is either Local Core Sales Operations or Systems Administrator and the Opportunity.Type is Renewal
	 *
	 *   @author Jonathan Satterfield
	 *   @date   2016-12-29
	 *   @param  {Id}   oppId
	 *   @param  {String}   oppType
	 *   @param  {String}   userProfileName
	 *   @return {Boolean}
	 */
	public static Boolean setOppSkipEchoSignFlagIfApplicable(Id oppId, String oppType, String userProfileName) {
		// default return value is true
		Boolean success = true;
		Set<String> userProfilesThatCanSkipEchoSignForRenewals = new Set<String>{'Local Core Sales Operations', 'System Administrator'};
		if (userProfilesThatCanSkipEchoSignForRenewals.contains(userProfileName) && oppType == 'Renewal') {
			// normally shouldn't perform DML in loop, but this SOQL query is limited to 1 record
			for (Opportunity oppRec : [SELECT Id, Approval_Process_Flag_Skip_EchoSign__c FROM Opportunity WHERE Id = :oppId LIMIT 1]) {
				// only update the Opportunity if needed
				if (oppRec.Approval_Process_Flag_Skip_EchoSign__c) {
					break;
				}
				oppRec.Approval_Process_Flag_Skip_EchoSign__c = true;
				Database.SaveResult dbUpdateResult = Database.update(oppRec, false);
				if (!dbUpdateResult.isSuccess()) {
					ExceptionUtility.consumeException(dbUpdateResult, true);
					success = false;
				}
			}
		}
		return success;
	}
}