src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_Flag_Autoreject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Opportunity should be automatically rejected, this field is checked by the ProductRulesAssessor.evaluateOpportunity method immediately prior to the Local Approval Process -- no specific Jira ticket exists for this requirement.</description>
        <label>Approval Process Flag - Autoreject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Flag_Discount_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1336. This flag is set when the ZuoraQuoteSelectProductDetailsController.navigateNext() is clicked (&quot;Edit Line Items&quot; page). In short, if any of the product discounts were manually changed to a higher percentage than what Steelbrick autocalculated, when the Quote is submitted for approval the sales rep&apos;s RSD will need to approve this Opportunity / children Quote records.</description>
        <label>Approval Process Flag - Discount Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Flag_Manager_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1506 (and pretty much all the Product Rules tickets)</description>
        <label>Approval Process Flag - Manager Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Info_For_Approver__c</fullName>
        <description>When the Product Rules are run for an Opportunity, this field is populated with information on the Quotes being submitted for Approval in order to help the designated approvers render a decision. Specifically, this field captures information on why an Opportunity requires manager approval, and/or why the Opportunity will be automatically rejected during the Approval Process.</description>
        <inlineHelpText>This field contains info on the Quotes being submitted for Approval to help approvers make a decision. Specifically, this field captures info on why an Opportunity first needs manager approval, and/or why it will be auto-rejected in the Approval Process.</inlineHelpText>
        <label>Approval Process - Info For Approver</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Print_Issue__c.object
<CustomObject>
    <label>Print Issue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Print Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Approval_Process_Flag_Discount_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1336. This flag is set when the ZuoraQuoteSelectProductDetailsController.navigateNext() is clicked (&quot;Edit Line Items&quot; page). In short, if any of the product discounts were manually changed to a higher percentage than what Steelbrick autocalculated, when the Quote is submitted for approval the sales rep&apos;s RSD will need to approve this Opportunity / children Quote records.</description>
        <label>Approval Process Flag - Discount Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>CannotBeSoldPast__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.CannotBeSoldPast__c)</formula>
        <label>Cannot Be Sold Past</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Override__c</fullName>
        <description>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</description>
        <inlineHelpText>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</inlineHelpText>
        <label>Discount Override %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</description>
        <inlineHelpText>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaximumSubscriptionTerm__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.Maximum_Subscription_Term__c)</formula>
        <label>Maximum Subscription Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MinimumSubscriptionTerm__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.Minimum_Subscription_Term__c)</formula>
        <label>Minimum Subscription Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NoAutomatedDiscount__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.No_Automated_Discount__c)</formula>
        <label>No Automated Discount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Issue_Next_Issue_ID__c</fullName>
        <formula>Print_Issue__r.Next_Issue__c</formula>
        <label>Print Issue - Next Issue ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Issue_Previous_Issue_ID__c</fullName>
        <formula>Print_Issue__r.Previous_Issue__c</formula>
        <label>Print Issue - Previous Issue ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Issue_Step_2_Date__c</fullName>
        <formula>Print_Issue__r.Step_2__c</formula>
        <label>Print Issue - Step 2 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Print_Issue_Step_3_Date__c</fullName>
        <formula>Print_Issue__r.Step_3__c</formula>
        <label>Print Issue - Step 3 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Print_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requires2X__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.Requires_2X__c)</formula>
        <label>Requires 2X</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequiresApproval__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.RequiresApproval__c)</formula>
        <label>Requires Approval</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequiresPaidStorefront__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.RequiresPaidStorefront__c)</formula>
        <label>Requires Paid Storefront</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Steelbrick_Calculated_Discount__c</fullName>
        <label>Steelbrick Calculated Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>zqu__AmendmentType__c</fullName>
        <description>The type of amendment being made.</description>
        <label>Amendment Type</label>
        <picklist>
            <picklistValues>
                <fullName>NewProduct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RemoveProduct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TermsAndConditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UpdateProduct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteProductName__c</fullName>
        <label>Quote Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>Discount_Override__c</fullName>
        <description>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</description>
        <inlineHelpText>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</inlineHelpText>
        <label>Discount Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Location/Vendor account that we are selling this product for.  For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location/Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Print_Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Print Issue that applies to a given product on a quote</inlineHelpText>
        <label>Print Issue</label>
        <referenceTo>Print_Issue__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>zqu__QuoteRatePlan__r.zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Steelbrick_Calculated_Discount__c</fullName>
        <description>The discount percent calculated by the Steelbrick Price Rules during the &quot;Add Products and Charges&quot; step of the Quote creation workflow.</description>
        <inlineHelpText>The discount percent calculated by the Steelbrick Price Rules during the &quot;Add Products and Charges&quot; step of the Quote creation workflow.</inlineHelpText>
        <label>Steelbrick Calculated Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>zqu__Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductRulesAssessor.cls
public without sharing class ProductRulesAssessor {

	public static void evaluateOpportunity(Id oppId) {

		/****************************/
		/* INITIALIZE CONTROL FLAGS */
		/****************************/

		Boolean evaluateInternetProducts = False;
		Boolean evaluatePrintProducts = False;
		Boolean evaluateLDEProducts = False;
		Boolean updateOpportunity = False;


		/************************/
		/* PERFORM BASE QUERIES */
		/************************/

		// To minimize queries, first query Opportunity and child Quote records...
		Opportunity opp = [SELECT Id, Approval_Process_Flag_Manager_Approval__c, Approval_Process_Flag_Autoreject__c, Approval_Process_Info_For_Approver__c, (SELECT Id, zqu__SubscriptionType__c, Product_Line__c, Approval_Process_Flag_Discount_Amount__c FROM zqu__Quotes__r) FROM Opportunity WHERE Id = :oppId LIMIT 1];
		
		// ...and then query QuoteRatePlan and QuoteRatePlanCharge records
		// note: all formula assessment fields (like "Requires2X__c") looking up to ProductRatePlan return TEXT values -- even "numerical" ones like "MinimumSubscriptionTerm__c"
		List<zqu__QuoteRatePlan__c> qrpList = [SELECT Id, zqu__QuoteProductName__c, Name, zqu__AmendmentType__c, zqu__Quote__c, zqu__Quote__r.zqu__Opportunity__c, Location_Vendor__c, CannotBeSoldPast__c, NoAutomatedDiscount__c, RequiresApproval__c, RequiresPaidStorefront__c, MaximumSubscriptionTerm__c, MinimumSubscriptionTerm__c, Requires2X__c, Print_Issue__c, Print_Issue_Next_Issue_ID__c, Print_Issue_Previous_Issue_ID__c, Print_Issue_Step_2_Date__c, Print_Issue_Step_3_Date__c, (SELECT Id, Name, Product_Name__c, Print_Issue__c, Location_Vendor__c, Steelbrick_Calculated_Discount__c, zqu__Discount__c, Discount_Override__c FROM zqu__Quote_Rate_Plan_Charges__r) FROM zqu__QuoteRatePlan__c WHERE zqu__Quote__r.zqu__Opportunity__c = :opp.Id];
	

		/***********************************/
		/* CREATE OPPORTUNITYQUOTESWRAPPER */
		/***********************************/

		OpportunityQuotesWrapper oqw = generateOpportunityQuotesWrapper(opp, qrpList);


		/*********************/
		/* SET CONTROL FLAGS */
		/*********************/

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteProductLine == 'Internet' && evaluateInternetProducts != True) {
				evaluateInternetProducts = True;
			}
			else if (qw.quoteProductLine == 'Print' && evaluatePrintProducts != True) {
				evaluatePrintProducts = True;
			}
			else if (qw.quoteProductLine == 'Direct Mail' && evaluateLDEProducts != True) {
				evaluateLDEProducts = True;
			}
		}


		/******************************************/
		/* RUN PRODUCT RULE EVALUATIONS AS NEEDED */
		/******************************************/

		// NOTE: each Product Line method also needs to evaluate their own cancellation rules
		// this applies to both 'cancellation' Quotes, and 'amendment' Quotes with line items being removed

		if (evaluateInternetProducts) {
			// add Internet method here
		}

		if (evaluatePrintProducts) {
			oqw = runPrintEvaluation(oqw);
		}

		if (evaluateLDEProducts) {
			// add LDE method here
		}


		/*********************/
		/* EVALUATE DISCOUNTS */
		/*********************/

		oqw = runDiscountEvaluation(oqw);


		/*****************************/
		/* UPDATE OPPORTUNITY RECORD */
		/*****************************/

		// if both reasonsForAutoreject and reasonsForManagerApproval have been updated, add them both to the Oppotunity.Approval_Process_Info_For_Approver__c field
		// and set the Opportunity.Approval_Process_Flag_Autoreject__c flag to True
		if (oqw.reasonsForAutoreject != '### REASONS FOR AUTOREJECT ###' && oqw.reasonsForManagerApproval != '### REASONS FOR MANAGER APPROVAL ###') {
			oqw.opp.Approval_Process_Info_For_Approver__c = oqw.reasonsForAutoreject + '\n\n' + oqw.reasonsForManagerApproval;
			oqw.opp.Approval_Process_Flag_Autoreject__c = True;
			updateOpportunity = True;
		}
		// if only reasonsForAutoreject has been updated, add it to the Oppotunity.Approval_Process_Info_For_Approver__c field
		// and set the Opportunity.Approval_Process_Flag_Autoreject__c flag to True
		else if (oqw.reasonsForAutoreject != '### REASONS FOR AUTOREJECT ###') {
			oqw.opp.Approval_Process_Info_For_Approver__c = oqw.reasonsForAutoreject;
			oqw.opp.Approval_Process_Flag_Autoreject__c = True;
			updateOpportunity = True;
		}
		// if only reasonsForManagerApproval has been updated, add it to the Oppotunity.Approval_Process_Info_For_Approver__c field
		// and set the Opportunity.Approval_Process_Flag_Manager_Approval__c flag to True
		else if (oqw.reasonsForManagerApproval != '### REASONS FOR MANAGER APPROVAL ###') {
			oqw.opp.Approval_Process_Info_For_Approver__c = oqw.reasonsForManagerApproval;
			oqw.opp.Approval_Process_Flag_Manager_Approval__c = True;
			updateOpportunity = True;			
		}
		else {
			//TODO: do we need to do anything for Autoapproval here? or just let it ride?
		}


		// finally, update the Opportunity if it doesn't qualify for Autoapproval
		if (updateOpportunity) {
			update oqw.opp;
		}
	}


	public static OpportunityQuotesWrapper generateOpportunityQuotesWrapper(Opportunity opp, List<zqu__QuoteRatePlan__c> qrpList) {
		// temporary map used to tie together the two query results
		// Key: ID of Quote | Value: QuotesWrapper instance
		Map<Id, QuotesWrapper> tempMap = new Map<Id, QuotesWrapper>();

		for (zqu__Quote__c qr : opp.zqu__Quotes__r) {
			QuotesWrapper qw = new QuotesWrapper();
			qw.quote = qr;
			qw.quoteProductLine = qr.Product_Line__c;
			qw.quoteSubscriptionType = qr.zqu__SubscriptionType__c;
			tempMap.put(qr.Id, qw);
		}

		for (zqu__QuoteRatePlan__c qrp : qrpList) {
			QuotesWrapper qWrap = tempMap.get(qrp.zqu__Quote__c);
			qWrap.quoteRatePlanChargeListMap.put(qrp.Id, qrp.zqu__Quote_Rate_Plan_Charges__r);
			qWrap.quoteRatePlanMap.put(qrp.Id, qrp);
		}

		OpportunityQuotesWrapper oqw = new OpportunityQuotesWrapper();
		oqw.opp = opp;
		oqw.quotesWrapperList = tempMap.values();

		// default the two Approval flags to False; if necessary, they'll be updated in the "UPDATE OPPORTUNITY RECORD"
		// section of the main evaluateOpportunity method above
		oqw.opp.Approval_Process_Flag_Autoreject__c = False;
		oqw.opp.Approval_Process_Flag_Manager_Approval__c = False;

		return oqw;
	}


	public class OpportunityQuotesWrapper {
		
		public Opportunity opp;
		public List<QuotesWrapper> quotesWrapperList;

		// whenever you append a string to reasonsForAutoreject or reasonsForManagerApproval,
		// be sure to always start with a newline symbol (e.g. "\n")
		public String reasonsForAutoreject;
		public String reasonsForManagerApproval;

		public OpportunityQuotesWrapper() {
			this.quotesWrapperList = new List<QuotesWrapper>();
			this.reasonsForAutoreject = '### REASONS FOR AUTOREJECT ###';
			this.reasonsForManagerApproval = '### REASONS FOR MANAGER APPROVAL ###';
		}
	}


	public class QuotesWrapper {

		public zqu__Quote__c quote;
		public String quoteProductLine;
		public String quoteSubscriptionType;

		// Key: ID of QuoteRatePlan | Value: QuoteRatePlan record
		public Map<Id, zqu__QuoteRatePlan__c> quoteRatePlanMap;

		// Key: ID of parent QuoteRatePlan | Value: list of QuoteRatePlanCharge records
		public Map<Id, List<zqu__QuoteRatePlanCharge__c>> quoteRatePlanChargeListMap;

		public QuotesWrapper() {
			this.quoteRatePlanMap = new Map<Id, zqu__QuoteRatePlan__c>();
			this.quoteRatePlanChargeListMap = new Map<Id, List<zqu__QuoteRatePlanCharge__c>>();
		}
	}


	public static OpportunityQuotesWrapper runPrintEvaluation(OpportunityQuotesWrapper oqw) {

		// add logic here; only record in the OpportunityQuotesWrapper you update is the Opportunity
		// note: in the QuotesWrapper, the two maps are initialized as empty maps, and then the "generateOpportunityQuotesWrapper"
		// method populates them if needed; in your code, it's probably a good idea to make sure these aren't empty before running logic

		// for Print, all "2x" products have to be on the same Quote, which makes evaluation simpler than Internet

		// Design Note: could potentially eliminate the nested FOR loops if we first added all the QuoteRatePlans
		// from all the "Print" QuotesWrappers to a single map; that said, doing so would make the "2x" evaluations trickier
		// and -- just a hunch/feeling -- could make it trickier to add additional functionality moving forward
		

		// this flag set to True when a Quote is for a Subscription Cancellation or when a line item is removed during a Subscription Amendment
		Boolean subscriptionCancellationOrProductRemovalFlag = False;

		// map initially populated for "2x" Print QuoteRatePlans, then processed at the end before Subscription Cancellations and Product Removals
		Map<String, List<zqu__QuoteRatePlan__c>> twoXMap = new Map<String, List<zqu__QuoteRatePlan__c>>();

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteProductLine == 'Print' && qw.quoteSubscriptionType == 'Cancel Subscription' && subscriptionCancellationOrProductRemovalFlag == False) {
				subscriptionCancellationOrProductRemovalFlag = True;
			}
			else if (qw.quoteProductLine == 'Print') {
				for (zqu__QuoteRatePlan__c qrp : qw.quoteRatePlanMap.values()) {
					if (qrp.zqu__AmendmentType__c == 'RemoveProduct' && subscriptionCancellationOrProductRemovalFlag == False) {
						subscriptionCancellationOrProductRemovalFlag = True;
					}
					else if (qrp.zqu__AmendmentType__c != 'RemoveProduct') {

						// NOTE: I forget, are we going to "autolink" Print Issue??
						// think we were going to do that, and also -- maybe -- automatically add the next Issue to the Quote
						// if so, we should create the Print_Issue__c lookup on the QuoteRatePlan, then populate info on QuoteRatePlanCharge if needed
						// PLUS, if lookup is populated then I can include it in the original query -- so we should do this
						// **** populate it using the value in the "Print Sequence" field!!! ****
						// 11-9-15 Note: already added "Print_Issue__c" lookup to QuoteRatePlan, as well as formula fields
						

						if (qrp.Requires2X__c == 'Yes') {
							// for now, populate the map above for processing after this FOR loop

							String keyString = qrp.zqu__QuoteProductName__c + String.valueOf(qrp.Print_Issue__c).left(15);
							// if map contains key, get and update list
							if (twoXMap.containsKey(keyString)) {
								List<zqu__QuoteRatePlan__c> tempQRPListFortwoXMap = twoXMap.get(keyString);
								tempQRPListFortwoXMap.add(qrp);
								twoXMap.put(keyString, tempQRPListFortwoXMap);
							}
							// otherwise create new list and add to map
							else {
								List<zqu__QuoteRatePlan__c> newQRPListFortwoXMap = new List<zqu__QuoteRatePlan__c>();
								newQRPListFortwoXMap.add(qrp);
								twoXMap.put(keyString, newQRPListFortwoXMap);
							}

						}

						// always requires approval (ex: BOW, at least for now)
						if (qrp.RequiresApproval__c == 'Yes') {
							oqw.reasonsForManagerApproval += '\nThe Product ' + qrp.zqu__QuoteProductName__c + ' always requires manager approval';
						}

						// NOTE: all these date evaluations assume that if the date isn't filled in on the Print Issue, then we should ignore the rule
						// Nick wu comment out these sell by dates restrictions of pritn issue for CSP-1114
						// if (qrp.CannotBeSoldPast__c == 'Step 2 Date') {
						// 	if (qrp.Print_Issue_Step_2_Date__c != null && qrp.Print_Issue_Step_2_Date__c < Date.today()) {
						// 		oqw.reasonsForManagerApproval += '\nThe Rate Plan ' + qrp.Name + ' for Product ' + qrp.zqu__QuoteProductName__c + ' cannot be sold past the Step 2 Date of the Print Issue';
						// 	}
						// }

						// if (qrp.CannotBeSoldPast__c == '3 Weeks Before Step 2 Date') {
						// 	if ((qrp.Print_Issue_Step_2_Date__c != null) && (qrp.Print_Issue_Step_2_Date__c - 21 < Date.today())) {
						// 		oqw.reasonsForManagerApproval += '\nThe Rate Plan ' + qrp.Name + ' for Product ' + qrp.zqu__QuoteProductName__c + ' cannot be sold after three weeks before the Step 2 Date of the Print Issue';
						// 	}
						// }

						// if (qrp.CannotBeSoldPast__c == 'Step 3 Date') {
						// 	if (qrp.Print_Issue_Step_3_Date__c != null && qrp.Print_Issue_Step_3_Date__c < Date.today()) {
						// 		oqw.reasonsForManagerApproval += '\nThe Rate Plan ' + qrp.Name + ' for Product ' + qrp.zqu__QuoteProductName__c + ' cannot be sold past the Step 3 Date of the Print Issue';
						// 	}
						// }
					}
				}
			}
		}

		if (!twoXMap.isEmpty()) {

			// TODO: add 2x logic here

		}

		if (subscriptionCancellationOrProductRemovalFlag) {
			oqw = printSubscriptionCancellationOrProductRemovalEvaluation(oqw);
		}

		return oqw;
	}



	// TODO: added "Location_Vendor__c" Account lookup to the QuoteRatePlan object, but needs to be populated!!!
	// 11-12-15 Note: the only LDE-specific rules are Cancellations, and Requires Paid Storefront "In Any Market/Category"
	public static OpportunityQuotesWrapper runLDEEvaluation(OpportunityQuotesWrapper oqw) {

		Boolean subscriptionCancellationOrProductRemovalFlag = False;

		List<zqu__QuoteRatePlan__c> ldeRequiresPaidStorefrontList = new List<zqu__QuoteRatePlan__c>();

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteProductLine == 'Direct Mail' && qw.quoteSubscriptionType == 'Cancel Subscription' && subscriptionCancellationOrProductRemovalFlag == False) {
				subscriptionCancellationOrProductRemovalFlag = True;
			}
			else if (qw.quoteProductLine == 'Direct Mail') {
				for (zqu__QuoteRatePlan__c qrp : qw.quoteRatePlanMap.values()) {
					if (qrp.zqu__AmendmentType__c == 'RemoveProduct' && subscriptionCancellationOrProductRemovalFlag == False) {
						subscriptionCancellationOrProductRemovalFlag = True;
					}
					else if (qrp.zqu__AmendmentType__c != 'RemoveProduct' && qrp.RequiresPaidStorefront__c == 'In Any Market/Category') {
						// add all "Requires Paid Storefront In Any Market/Category" LDE QRPs to a list
						ldeRequiresPaidStorefrontList.add(qrp);
					}
				}
			}
		}

		// if some of the LDE products require a paid storefront, run logic
		if (!ldeRequiresPaidStorefrontList.isEmpty()) {
			



		}

		if (subscriptionCancellationOrProductRemovalFlag) {
			oqw = ldeSubscriptionCancellationOrProductRemovalEvaluation(oqw);
		}

		return oqw;
	}



	public static OpportunityQuotesWrapper ldeSubscriptionCancellationOrProductRemovalEvaluation(OpportunityQuotesWrapper oqw) {

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteProductLine == 'Direct Mail' && qw.quoteSubscriptionType == 'Cancel Subscription') {
				oqw.reasonsForManagerApproval += '\nThe Quote with ID ' + String.valueOf(qw.quote.Id) + ' is for a Subscription Cancellation';
			}
			else if (qw.quoteProductLine == 'Direct Mail') {		
				for (zqu__QuoteRatePlan__c qrp : qw.quoteRatePlanMap.values()) {
					if (qrp.zqu__AmendmentType__c == 'RemoveProduct') {
						oqw.reasonsForManagerApproval += '\nA product is being removed/cancelled from an existing subscription - Product: ' + qrp.zqu__QuoteProductName__c + ' | Rate Plan: ' + qrp.Name;
					}
				}
			}
		}

		return oqw;
	}


















	public static OpportunityQuotesWrapper printSubscriptionCancellationOrProductRemovalEvaluation(OpportunityQuotesWrapper oqw) {

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteProductLine == 'Print' && qw.quoteSubscriptionType == 'Cancel Subscription') {
				oqw.reasonsForManagerApproval += '\nThe Quote with ID ' + String.valueOf(qw.quote.Id) + ' is for a Subscription Cancellation';
			}
			else if (qw.quoteProductLine == 'Print') {		
				for (zqu__QuoteRatePlan__c qrp : qw.quoteRatePlanMap.values()) {
					if (qrp.zqu__AmendmentType__c == 'RemoveProduct') {
						oqw.reasonsForManagerApproval += '\nA product is being removed/cancelled from an existing subscription - Product: ' + qrp.zqu__QuoteProductName__c + ' | Rate Plan: ' + qrp.Name;
					}
				}
			}
		}

		return oqw;
	}



    // SF-1336
    // TODO: remove the Discount flag fields on the Quote and the Opportunity records, no longer needed
    public static OpportunityQuotesWrapper runDiscountEvaluation(OpportunityQuotesWrapper oqw) {
    	
    	List<zqu__QuoteRatePlanCharge__c> qrpcList = new List<zqu__QuoteRatePlanCharge__c>();

		for (QuotesWrapper qw : oqw.quotesWrapperList) {
			if (qw.quoteSubscriptionType != 'Cancel Subscription' && !qw.quoteRatePlanChargeListMap.isEmpty()) {
				for (List<zqu__QuoteRatePlanCharge__c> eachList : qw.quoteRatePlanChargeListMap.values()) {
					qrpcList.addAll(eachList);
				}
			}
		}

		if (!qrpcList.isEmpty()) {
			for (zqu__QuoteRatePlanCharge__c qrpc : qrpcList) {
	    		if (qrpc.Discount_Override__c > qrpc.Steelbrick_Calculated_Discount__c) {
	    			oqw.reasonsForManagerApproval += '\nThe Rate Plan Charge "' + qrpc.Name + '" for Product "' + qrpc.Product_Name__c + '" has a Discount Override that is greater than what was autocalculated';
    			}			
			}
		}

		return oqw;
    }


}