src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task_Creation_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Create_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Task</label>
        <type>Checkbox</type>
    </fields>
    <label>Task Creation Settings</label>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Z-Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>Location_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</description>
        <inlineHelpText>The Location/Vendor account that we are selling this product for. For example if selling a storefront, select the location that this product will be fulfilled against.</inlineHelpText>
        <label>Location ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(zqu__ProductRatePlan__r.zqu__Product__r.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <description>The date the parent Quote is valid though.</description>
        <formula>zqu__Quote__r.zqu__ValidUntil__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date the parent Quote is valid though.</inlineHelpText>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ZProduct_Name__c</fullName>
        <formula>zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <label>ZProduct Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteProductName__c</fullName>
        <label>Quote Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchDelExpiredQuotesAssociatedWOpenOpty.cls
global class BatchDelExpiredQuotesAssociatedWOpenOpty implements Database.Batchable<sObject> {
	
	String query;
	Date expDate;
	Id recType;
	global BatchDelExpiredQuotesAssociatedWOpenOpty() {
		// expDate = Date.Today();
		// recType = [Select Id, Name From RecordType  Where SobjectType = 'Opportunity' and DeveloperName = 'Local' LIMIT 1].Id;
		// query = 'Select Id, Opportunity_Expiration_Date__c, Account.Owner.ARR__c, (Select Id, zqu__ValidUntil__c From Zqu__Quotes__r where zqu__Status__c = \'New\' and Zqu__ValidUntil__c <: expDate) From Opportunity where RecordTypeId =: recType and IsClosed = False and Opportunity_Expiration_Date__c <: expDate';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Opportunity> scope) {
		// Set<Id> quoteIds = new Set<Id>();
		// List<Task> tskInsertList = new List<Task>();
		// List<Zqu__Quote__c> zquQuoteList = new List<Zqu__Quote__c>();
		// List<String> prdList = new List<String>();
		
		// //Tickets CSP-937
  //       //check the Custom Settings Quote_Deleted field. if field is true then create task.
		// Task_Creation_Settings__c taskCreateSetting=Task_Creation_Settings__c.getValues('Quote_Deleted');
		
		// for(Opportunity opp : scope){
		// 	for(Zqu__Quote__c zqu : opp.Zqu__Quotes__r){
		// 		quoteIds.add(zqu.Id);
		// 	}
		// }
		// system.debug('******************'+quoteIds);
		// for(Zqu__Quote__c zq : [Select Id, Name, Zqu__Opportunity__c, Zqu__Opportunity__r.Account.Owner.ARR__c, Zqu__ValidUntil__c,
		// 								(Select Id, Name, Zqu__ProductRatePlan__c, zqu__ProductRatePlan__r.Name, Product_Type__c, Quote_Expiration_Date__c, Zqu__QuoteProductName__c, ZProduct_Name__c  From Zqu__Quote_Rate_Plans__r) 
		// 							From Zqu__Quote__c where Id IN: quoteIds]){
		// 	Integer count =0;
		// 	String str = '';
		// 	prdList = new List<String>();
		// 	zquQuoteList.add(zq);
		// 	//Tickets CSP-937
		// 	//check the Custom Settings Quote_Deleted field. if field is true then create task.
		// 	if(taskCreateSetting != null && taskCreateSetting.Create_Task__c){				
		// 		Task tsk = new Task();
		// 		tsk.ActivityDate = Date.Today();
		//  		tsk.OwnerId = zq.Zqu__Opportunity__r.Account.Owner.ARR__c;
		//   		tsk.WhatId = zq.Zqu__Opportunity__c;
		//   		tsk.Type = 'Quote Deleted';
		//    		tsk.Purpose__c = 'Quote Deleted';
		//    		tsk.Status = 'Not Started';
		//    		tsk.Subject = 'Quote Deleted :'+ zq.Name;
		// 	   	str = 'The Quote "'+zq.Name+'" expired on '+zq.Zqu__ValidUntil__c+' and has been deleted. The products that were associated with the quotes are ';	
		// 		for(Zqu__QuoteRatePlan__c zPlan : zq.Zqu__Quote_Rate_Plans__r){
		// 			str+= '\n\n Quote Rate Plan Name :'+zPlan.Name+','
		// 	   				+'\n Product Rate Plan :'+zPlan.zqu__ProductRatePlan__r.Name+','
		// 	   				+'\n Product Type :'+zPlan.Product_Type__c+','
		// 	   				+'\n Product Name :'+zPlan.Zqu__QuoteProductName__c
		// 	   				+'\n -------------------------------------------------';		   				
		// 			prdList.add(str);
		// 			str = '';
		// 		}
		// 		tsk.Description = ''+prdList;
		// 		tskInsertList.add(tsk);
		// 	}

		// }
		// system.debug('XXXXXXXXXXXXXXXXXXXXX'+zquQuoteList);
		// if(!tskInsertList.isEmpty())
		// 	Database.insert(tskInsertList, false);

		// if(!zquQuoteList.isEmpty())
		// 	Database.delete(zquQuoteList, false);
	}

	global void finish(Database.BatchableContext BC) {
		
	}
	
}