src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Client_Approved__c</fullName>
        <inlineHelpText>The date that the opportunity moved into Client Approved</inlineHelpText>
        <label>Date Client Approved</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Customer_Acceptance_Date__c</fullName>
        <inlineHelpText>Customer Acceptance Date should be on or after Service Activation Date.
If Customer Acceptance Date is not required in Zuora, the Service Activation Date will be used as the Customer Acceptance Date.</inlineHelpText>
        <label>Customer Acceptance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ElectronicPaymentMethodId__c</fullName>
        <description>This is the Zuora payment method id created by the HPM.</description>
        <inlineHelpText>This is the Zuora payment method id created by the HPM.</inlineHelpText>
        <label>Electronic Payment Method Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Is_Charge_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag to indicate whether the Quote Metrics need to be recalculated.</description>
        <inlineHelpText>The flag to indicate whether the Quote Metrics need to be recalculated.</inlineHelpText>
        <label>Is Charge Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethod__c</fullName>
        <description>The Payment Method for the Quote.</description>
        <inlineHelpText>The Payment Method for the Quote.</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Service_Activation_Date__c</fullName>
        <inlineHelpText>Service Activation Date should be on or after Start Date and cannot be after Customer Acceptance Date.
If Service Activation Date is not required in Zuora, the Start Date will be used as the Service Activation Date.</inlineHelpText>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__StartDate__c</fullName>
        <description>The Date that the Quote Starts.</description>
        <inlineHelpText>The Date that the Quote Starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionTermStartDate__c</fullName>
        <description>The term start date of the subscription is amendment on, only used for amendment Quote</description>
        <inlineHelpText>The term start date of the subscription is amendment on</inlineHelpText>
        <label>Subscription Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraAccountID__c</fullName>
        <label>Zuora Account ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>DiscountOverrideModified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1336. Required in the ZuoraQuoteSelectProductDetailsController to track when the Discount_Override__c field should not default to the zqu__Discount__c / Steelbrick_Calculated_Discount__c field value.</description>
        <label>DiscountOverrideModified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Override__c</fullName>
        <description>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</description>
        <inlineHelpText>If the sales rep chooses to give a different discount % than what was calculated by Steelbrick, the &quot;custom&quot; discount amount is entered here.</inlineHelpText>
        <label>Discount Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Id__c</fullName>
        <formula>zqu__QuoteRatePlan__r.zqu__Quote__r.Id</formula>
        <inlineHelpText>The Salesforce ID for the associated Quote</inlineHelpText>
        <label>Quote Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <description>Bill Cycle Day of RatePlan Charge</description>
        <label>Bill Cycle Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraQuotePMRController.cls
/* 
<class>
  <name>ZuoraQuotePMRController</name>
  <purpose>Redirects user to either Payment Method form or Quote record depending on
  where or not the Quote is for a new Billing Account</purpose>
  <created>
    <by>Jonathan Satterfield & Hari Mohan</by>
    <date>7/29/2015</date>
    <ticket>SF-714, SF-715</ticket>
  </created>
</class>
*/
public with sharing class ZuoraQuotePMRController {
    public Id quoteId {get;set;}
    public Id oppId {get;set;}
    public String paymentType {get;set;}
    public String billingAccountID {get;set;}
    public String electronicPaymentID {get;set;}
    public String subscriptionType {get;set;}
    public zqu__Quote__c tempQuote {get;set;}
    
    /* 
    <method>
      <name>ZuoraQuotePMRController</name>
      <purpose>Constructor method</purpose>
      <created>
        <by>Jonathan Satterfield & Hari Mohan</by>
        <date>7/29/2015</date>
        <ticket>SF-714, SF-715</ticket>
      </created>
    </method>
    */ 
    public ZuoraQuotePMRController(ApexPages.StandardController standardController) {

        quoteId = null;
        // Retrieve the quote
        zqu__Quote__c quote = (zqu__Quote__c)standardController.getRecord();
        if(quote != null) {
            quoteId = quote.id;
            tempQuote = [SELECT Id, zqu__SubscriptionType__c, zqu__ZuoraAccountID__c, zqu__Opportunity__c, zqu__PaymentMethod__c, zqu__ElectronicPaymentMethodId__c, zqu__Is_Charge_Expired__c, zqu__Opportunity__r.Date_Client_Approved__c,
                                                zqu__Customer_Acceptance_Date__c, zqu__TermStartDate__c, zqu__SubscriptionTermStartDate__c, zqu__StartDate__c, zqu__Service_Activation_Date__c, zqu__BillCycleDay__c FROM zqu__Quote__c WHERE Id = :quoteId];
            paymentType = tempQuote.zqu__PaymentMethod__c;
            billingAccountID = tempQuote.zqu__ZuoraAccountID__c;
            electronicPaymentID = tempQuote.zqu__ElectronicPaymentMethodId__c;
            oppId = tempQuote.zqu__Opportunity__c;
            subscriptionType = tempQuote.zqu__SubscriptionType__c;
        }
    }

    
    public ApexPages.PageReference updateDiscountsRunLocalProductRulesAndRedirect() {
        if (subscriptionType != 'Cancel Subscription') {
            updateDiscounts();
            // (SF-2036) this boolean needs to be set in order to run the zqu.zQuoteUtil.previewQuotes method on the ChooseNextAction page
            tempQuote.zqu__Is_Charge_Expired__c = True;
            List<zqu__Quote__c> qList = new List<zqu__Quote__c>();
            qList.add(tempQuote);
            OpportunitySendToZBillingController.SetQuoteDates(qList);
            update qList;
        }
        return redirect();
    }



    /* 
    <method>
      <name>redirect</name>
      <purpose>Redirects user to either Payment Method form or Quote record depending on
        where or not the Quote is for a new Billing Account</purpose>
      <created>
        <by>Jonathan Satterfield & Hari Mohan</by>
        <date>7/29/2015</date>
        <ticket>SF-714, SF-715</ticket>
      </created>
    </method>
    */
    public ApexPages.PageReference redirect() {
        // if new billing account and not a Check, return payment page if they have not entered a billing account or entered their payment ID
        if (
               (billingAccountID == null || billingAccountID == '') 
            && (electronicPaymentID == null || electronicPaymentID == '') 
            && (paymentType == zqu.PaymentPageController.PAYMENT_METHOD_TYPE_CREDIT_CARD 
                || paymentType == zqu.PaymentPageController.PAYMENT_METHOD_TYPE_ACH)
           )
        {
            return new PageReference('/apex/CreateNewPaymentMethod?id='+(String)quoteId+'&quoteType=Subscription&stepNumber=5');
        }
        // if existing billing account, redirect to Choose Next Action page
        else {
            return new PageReference('/apex/ZuoraQuoteChooseNextAction?id='+(String)quoteId+'&oppId='+(String)oppId+'&quoteType=Subscription&stepNumber=6');
        }
    }



    public void updateDiscounts() {
    
        // the DiscountOverrideModified__c boolean is set to true to maintain the new Discount_Override__c value between page loads
        // (otherwise the Discount_Override__c field is set to the value that Steelbrick calculated)
        // this boolean is reset to False after the page reloads

        String theQuoteId = String.valueOf(quoteId).left(15);
        List<zqu__QuoteRatePlanCharge__c> quoteRatePlanCharges = [SELECT Id, Quote_Id__c, Discount_Override__c, zqu__Discount__c, Product_Type__c FROM zqu__QuoteRatePlanCharge__c WHERE Quote_Id__c = :theQuoteId];
        if (!quoteRatePlanCharges.isEmpty()) {
            
            Boolean returnNullFlag = False;

            Map<Id,String> qrpcIdToDiscountOverrideStringMap = new Map<Id,String>();

            String productLine;

            for (zqu__QuoteRatePlanCharge__c chargeRecord : quoteRatePlanCharges) {
                qrpcIdToDiscountOverrideStringMap.put(String.valueOf(chargeRecord.Id).left(15),String.valueOf(chargeRecord.Discount_Override__c));
                //qrpcIdToDiscountOverrideStringMap.put(String.valueOf(chargeRecord.Id).left(15),String.valueOf(chargeRecord.zqu__Discount__c));

                if (String.isBlank(productLine)) {
                    productLine = chargeRecord.Product_Type__c;
                }
            }

            List<zqu.zChargeGroup> chargeGroupsToUpdate = new List<zqu.zChargeGroup>();
            List<zqu.zChargeGroup> chargeGroups = zqu.zQuoteUtil.getChargeGroups(String.valueOf(quoteId));

            for (zqu.zChargeGroup chargeGroup : chargeGroups) {
                if (chargeGroup.groupType != zqu.zChargeGroup.TYPE_AMENDMENT_REMOVEPRODUCT && chargeGroup.groupType != zqu.zChargeGroup.TYPE_RENEWAL_RENEWED && (chargeGroup.groupType != zqu.zChargeGroup.TYPE_AMENDMENT_ORIGINAL)) {// && productLine != 'Direct Mail')) {
                    for (zqu.zCharge charge : chargeGroup.zCharges) {
                        charge.discount = qrpcIdToDiscountOverrideStringMap.get(String.valueOf(charge.Id).left(15));
                    }
                    chargeGroup.zCharges = zqu.zQuoteUtil.calculateChargesOnDiscountChange(chargeGroup.zCharges);
                    chargeGroupsToUpdate.add(chargeGroup);
                }
            }
            // TODO: put a try/catch block here
            // ex: https://knowledgecenter.zuora.com/CA_Commerce/E_Development_Resources/C_Component_Library/G_Component_Library_Sample_Code/B_Managing_Charges_with_the_Product_Catalog/B_Use_the_Product_Catalog_to_Add%2C_Update%2C_and_Delete_Charges
            
            if (!chargeGroupsToUpdate.isEmpty()) {
                chargeGroupsToUpdate = zqu.zQuoteUtil.updateChargeGroups(chargeGroupsToUpdate);
            }

            // TODO: is this necessary still?
            update quoteRatePlanCharges;
        }
    }    
}