src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Product.</description>
        <inlineHelpText>The Effective End Date of the Product.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Product.</description>
        <inlineHelpText>The Effective Start Date of the Product.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Rate Plan.</description>
        <inlineHelpText>The Effective End Date of the Rate Plan.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Rate Plan.</description>
        <inlineHelpText>The Effective Start Date of the Rate Plan.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductRatePlanTriggerHandlerTest.cls
@isTest
private class ProductRatePlanTriggerHandlerTest {
	
	private static testmethod void test_method_one() {
		Product2 zp1 = TestClassUtility.createLocalProduct2(true);
		zqu__ProductRatePlan__c prp1 = TestClassUtility.createProductRatePlan(false, zp1);

		prp1.zqu__EffectiveStartDate__c = Date.today().addDays(-10);
		prp1.zqu__EffectiveEndDate__c = Date.today().addDays(-5);
		Database.insert(prp1, false);
	}

	private static testmethod void test_method_two() {
		Product2 zp1 = TestClassUtility.createLocalProduct2(true);
		zqu__ProductRatePlan__c prp1 = TestClassUtility.createProductRatePlan(false, zp1);

		prp1.zqu__EffectiveStartDate__c = Date.today().addDays(-10);
		prp1.zqu__EffectiveEndDate__c = Date.today().addDays(5);
		Database.insert(prp1, false);

		prp1.zqu__EffectiveEndDate__c = Date.today().addDays(6);
		Database.update(prp1, false);

		Database.delete(prp1, false);
	}	
}