src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ListPrice__c</fullName>
        <description>The List Price of the Rate Plan Charge.</description>
        <inlineHelpText>The List Price of the Rate Plan Charge.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanChargeTier__c.object
<CustomObject>
    <fields>
        <fullName>Last_Update_Attempted__c</fullName>
        <description>This field is used to stamp when the last update was attempted. When an update is successful this field will be empty but if the update failed it will have the last time it failed.</description>
        <inlineHelpText>The last time this tier was attempted to be updated to Zuora and failed.</inlineHelpText>
        <label>Last Update Attempted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Update_Zuora_Immediately__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to signify that this update should go to Zuora immediately.</description>
        <inlineHelpText>This field will immediately schedule this product to be updated to Zuora.</inlineHelpText>
        <label>Update Zuora Immediately</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora_Update_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine that the Product Rate Plan Charge Tier needs to be updated to Zuora or that the update is currently pending.</description>
        <inlineHelpText>An update is either needed or currently being processed.</inlineHelpText>
        <label>Zuora Update Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Price__c</fullName>
        <description>The price of the tier if the charge is a flat fee, or the price of each unit in the tier if the charge model is tiered pricing.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <description>The product rate plan charge associated with this tier. You can&apos;t create an unassociated tier.</description>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge Tier</relationshipLabel>
        <relationshipName>Product_RatePlan_Charge_Tier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge Tier</label>
    <nameField>
        <label>Tier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductRatePlanChargeTierTriggerTest.cls
@isTest
private class ProductRatePlanChargeTierTriggerTest {
	
	@isTest
	static void priceUpdateValidation() {
		// Create Test Product
		Product2 testProduct = TestClassUtility.createLocalProduct2(true);
		// Create Test Product Rate Plan
		zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(false);
		testProductRatePlan.zqu__Product__c = testProduct.Id;
		insert testProductRatePlan;
		// Create Test Product Rate Plan Charge
		zqu__ProductRatePlanCharge__c testProductRatePlanCharge = TestClassUtility.createProductRatePlanCharge(false);
		testProductRatePlanCharge.zqu__ProductRatePlan__c = testProductRatePlan.Id;
		insert testProductRatePlanCharge;
		// Create Test Product Rate Plan Charge Tier
		zqu__ProductRatePlanChargeTier__c testProductRatePlanChargeTier = new zqu__ProductRatePlanChargeTier__c();
		testProductRatePlanChargeTier.zqu__ProductRatePlanCharge__c = testProductRatePlanCharge.Id;
		testProductRatePlanChargeTier.zqu__Price__c = testProductRatePlanCharge.zqu__ListPrice__c;
		testProductRatePlanChargeTier.zqu__ZuoraId__c = 'someidforzuora';
		insert testProductRatePlanChargeTier;

		// Update Tier Price
		testProductRatePlanChargeTier.zqu__Price__c = 400000.00;
		update testProductRatePlanChargeTier;

		/*
			-- ASSERTION --
			The above price update should have auto flagged to "Zuora Update Pending" field to be true(checked)
		 */
		zqu__ProductRatePlanChargeTier__c assertFlagSet = [SELECT Id, Zuora_Update_Pending__c FROM zqu__ProductRatePlanChargeTier__c WHERE Id = :testProductRatePlanChargeTier.Id];
		System.assert(assertFlagSet.Zuora_Update_Pending__c);

		// This update should fail as no Zuora config is on during testing
		testProductRatePlanChargeTier.Update_Zuora_Immediately__c = true;
		// Force the batch job to run synchronously
		Test.startTest();
			update testProductRatePlanChargeTier;
		Test.stopTest();
		
		/*
			-- ASSERTION --
			The above update should have failed meaning that the "Last Update Attempted" field should now be populated with the latest
			attemp date time AND the "Zuora Update Pending" field should still be checked.
		 */
		assertFlagSet = [SELECT Id, Zuora_Update_Pending__c, Last_Update_Attempted__c FROM zqu__ProductRatePlanChargeTier__c WHERE Id = :testProductRatePlanChargeTier.Id];
		System.assert(assertFlagSet.Last_Update_Attempted__c != null);
		System.assert(assertFlagSet.Zuora_Update_Pending__c);
	}
}