src/objects/SF_LP_Market_Code_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Salesforce to Local Partners Market Code Map</description>
    <fields>
        <fullName>Partners_Market_Code_Map__c</fullName>
        <label>Partners Market Code Map</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_Market_Code__c</fullName>
        <label>Salesforce Market Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SF LP Market Code Map</label>
</CustomObject>

src/objects/XO_Group_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Turn_on_Fulfillment_Callouts__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Turns on and off partner fulfillment and account update callouts.</inlineHelpText>
        <label>Turn on Fulfillment Callouts</label>
        <type>Checkbox</type>
    </fields>
    <label>XO Group Settings</label>
</CustomObject>

src/classes/XOGroupSettingUtilityTest.cls
@isTest
private class XOGroupSettingUtilityTest{
    @isTest static void test_method_one() {
        XO_Group_Settings__c xoSetting = XO_Group_Settings__c.getInstance();
        xoSetting.Turn_on_Fulfillment_Callouts__c = true;
        upsert xoSetting;
        
        XOGroupSettingUtility XOGSU = new XOGroupSettingUtility();
        Boolean PartnerCallout = XOGroupSettingUtility.getPartnerCalloutSetting();
        Boolean alwaysSetCreditHold = XOGroupSettingUtility.alwaysSetCreditHoldToFalse();
        Boolean alwaysSetGeocodeOverride = XOGroupSettingUtility.alwaysSetGeocodeOverrideToTrue();
        
        SF_LP_Market_Code_Map__c sf = new SF_LP_Market_Code_Map__c();
        sf.name = 'test';
        sf.Partners_Market_Code_Map__c = '123';
        sf.Salesforce_Market_Code__c = '223';
        insert sf;
        
        Map<String, String> sfLPMarketCodeMap = XOGroupSettingUtility.sfLPMarketCodeMap();
        Map<String, String> lpSFMarketCodeMap = XOGroupSettingUtility.lpSFMarketCodeMap();
    }
   
}