src/objects/SF_LP_Market_Code_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Salesforce to Local Partners Market Code Map</description>
    <fields>
        <fullName>Partners_Market_Code_Map__c</fullName>
        <label>Partners Market Code Map</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_Market_Code__c</fullName>
        <label>Salesforce Market Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SF LP Market Code Map</label>
</CustomObject>

src/objects/XO_Group_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Always_Set_Credit_Hold_To_False__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-340</description>
        <label>Always Set Credit Hold To False</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Always_Set_Geocode_Override_To_True__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-387</description>
        <label>Always Set Geocode Override To True</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Turn_on_Fulfillment_Callouts__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Turns on and off partner fulfillment and account update callouts.</inlineHelpText>
        <label>Turn on Fulfillment Callouts</label>
        <type>Checkbox</type>
    </fields>
    <label>XO Group Settings</label>
</CustomObject>

src/classes/XOGroupSettingUtility.cls
public with sharing class XOGroupSettingUtility {
	private static XO_Group_Settings__c xoSetting = XO_Group_Settings__c.getInstance();

	public XOGroupSettingUtility() {
		
	}

	public static Boolean getPartnerCalloutSetting(){
		if(xoSetting == null){
			return false;
		}
		return xoSetting.Turn_on_Fulfillment_Callouts__c;
	}

	public static Map<String, String> lpSFMarketCodeMap(){
		Map<String, String> codeMap = new Map<String, String>();
		for(SF_LP_Market_Code_Map__c record : SF_LP_Market_Code_Map__c.getAll().values()){
            codeMap.put(record.Partners_Market_Code_Map__c, record.Salesforce_Market_Code__c);
        }
        return codeMap;
	}

	public static Map<String, String> sfLPMarketCodeMap(){
		Map<String, String> codeMap = new Map<String, String>();
		for(SF_LP_Market_Code_Map__c record : SF_LP_Market_Code_Map__c.getAll().values()){
            codeMap.put(record.Salesforce_Market_Code__c, record.Partners_Market_Code_Map__c);
        }
        return codeMap;
	}

	public static Boolean alwaysSetCreditHoldToFalse() {
		return xoSetting.Always_Set_Credit_Hold_To_False__c;
	}

	public static Boolean alwaysSetGeocodeOverrideToTrue() {
		return xoSetting.Always_Set_Geocode_Override_To_True__c;
	}
}