src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Disallow_Sales_Rep_On_Quotes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disallow Sales Rep On Quotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <description>The number Id of the Sales Rep</description>
        <externalId>true</externalId>
        <inlineHelpText>Sales Rep Id from External System</inlineHelpText>
        <label>SalesRep ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>TEXT(zqu__Product__r.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <label>AutoRenewal</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RenewalRepLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Reporting_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is billed for this Quote.</description>
        <inlineHelpText>The Contact that is billed for this Quote.</inlineHelpText>
        <label>Bill to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ElectronicPaymentMethodId__c</fullName>
        <description>This is the Zuora payment method id created by the HPM.</description>
        <inlineHelpText>This is the Zuora payment method id created by the HPM.</inlineHelpText>
        <label>Electronic Payment Method Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ExistSubscriptionID__c</fullName>
        <label>Exist Subscription ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethod__c</fullName>
        <description>The Payment Method for the Quote.</description>
        <inlineHelpText>The Payment Method for the Quote.</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SoldToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is sold to for this Quote.</description>
        <inlineHelpText>The Contact that is sold to for this Quote.</inlineHelpText>
        <label>Sold to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (Ship to Contact)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote_Template__c.object
<CustomObject>
    <description>Quote template for generate PDF or WORD</description>
    <fields>
        <fullName>zqu__IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate this template is the default one of the refer quote type</description>
        <inlineHelpText>Indicate this template is the default one of the refer quote type</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteAmendment__c.object
<CustomObject>
    <description>QuoteAmendment is used to make changes to a Quote.</description>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The identification for the Quote that is being amended.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Amendments</relationshipLabel>
        <relationshipName>Quote_Amendments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <description>The date when the new terms and conditions take effect.</description>
        <inlineHelpText>The date when the new terms and conditions take effect.</inlineHelpText>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Amendment</label>
    <nameField>
        <label>Quote Amendment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Product Rate Plan.</description>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <description>for CSP-1786</description>
        <label>AutoRenewal</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Subscriptions_Reporting_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteTriggerTest.cls
/* 
<class>
  <name>ZuoraQuoteTriggerTest</name>
  <purpose>For testing save/delete/update events on a Zuora Quote</purpose>
  <created>
    <by>Jonathan Satterfield</by>
    <date>7/22/2015</date>
    <ticket>SF-598, SF-599, SF-601</ticket>
  </created>
</class>
*/
//@isTest//(SeeAllData=True)
@isTest
public class ZuoraQuoteTriggerTest {

    static testMethod void testMethodBeforeInsert() {
        List<User> srUserList = [SELECT Id, SalesRepID__c, ManagerID, Manager.IsActive, Email 
                                    FROM User 
                                    WHERE isActive = True 
                                        AND Manager.IsActive = True 
                                        AND Disallow_Sales_Rep_On_Quotes__c = false LIMIT 20];

        List<User> srUserDSROQList = [SELECT Id, SalesRepID__c, ManagerID, Manager.IsActive, Email 
                                    FROM User 
                                    WHERE isActive = True 
                                        AND Manager.IsActive = True 
                                        AND Disallow_Sales_Rep_On_Quotes__c = TRUE LIMIT 20];

        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        
        Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);

        zqu__Quote_Template__c testZquQuoteTemplate = TestClassUtility.createQuoteTemplate(false);
        testZquQuoteTemplate.Name = 'Quote Template for TRX';
        testZquQuoteTemplate.zqu__IsDefault__c = FALSE;
        insert testZquQuoteTemplate;

        Test.startTest();

        Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
        Contact testContact = (Contact)testObjects.get('Contact');
        Account testAccount = (Account)testObjects.get('Account');

        Contact testErrorContact = TestClassUtility.createContact(false,testAccount);
        testErrorContact.FirstName = '';
        testErrorContact.LastName = 'testLaseName' + TestClassUtility.randomNumber(9);
        testErrorContact.Email = 'test_contact_email2_' + TestClassUtility.randomNumber(99) + '@faketesting' + TestClassUtility.randomNumber(99) + '.com';
        testErrorContact.MailingStreet = TestClassUtility.generateRandomStreet();
        testErrorContact.MailingCity = 'Austin';
        testErrorContact.MailingState = 'Texas';
        testErrorContact.MailingCountry = 'United States';
        testErrorContact.MailingPostalCode = TestClassUtility.generateRandomUSPostalCode();
        testErrorContact.Phone = TestClassUtility.randomNumber(9) + '98765432' + TestClassUtility.randomNumber(9);
        insert testErrorContact;
        // insert Internet New Sub Quote
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testOpp,testAccount,testContact);
        testZquQuote.zqu__SoldToContact__c = testErrorContact.Id;
        testZquQuote.zqu__BillToContact__c = testErrorContact.Id;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(-1);
        testZquQuote.SalesRepLookup__c = srUserDSROQList[0].id;
        testZquQuote.Reporting_Rep__c = srUserDSROQList[0].id;
        testZquQuote.RenewalRepLookup__c = srUserDSROQList[0].id;
        testZquQuote.AutoRenewal__c = 'YES';
        testZquQuote.Product_Line__c = 'Print';
        try{
            insert testZquQuote;
        }catch(Exception e){}

        testZquQuote.zqu__SoldToContact__c = testContact.Id;
        testZquQuote.zqu__BillToContact__c = testContact.Id;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.SalesRepLookup__c = srUserList[0].id;
        testZquQuote.Reporting_Rep__c = srUserList[0].id;
        testZquQuote.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote.Product_Line__c = 'Internet';
        try{
            insert testZquQuote;
        }catch(Exception e){}

        // insert Print Amend sub Quote
        Zuora__Subscription__c testSub = TestClassUtility.createSubscription(false,testAccount);
        testSub.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandler';
        insert testSub;

        zqu__Quote__c testZquQuote1 = TestClassUtility.createQuote(false,testOpp,testAccount,testContact);
        testZquQuote1.zqu__SoldToContact__c = testContact.Id;
        testZquQuote1.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote1.SalesRepLookup__c = srUserList[0].id;
        testZquQuote1.Reporting_Rep__c = srUserList[0].id;
        testZquQuote1.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote1.Product_Line__c = 'Print';
        testZquQuote1.zqu__SubscriptionType__c = 'Amend Subscription';
        testZquQuote1.zqu__ExistSubscriptionID__c = 'subfortestquotetriggerhandler';
        testZquQuote1.zqu__PaymentMethod__c = 'ACH';
        insert testZquQuote1;

        // insert transactions cancel sub quote
        zqu__Quote__c testZquQuote2 = TestClassUtility.createQuote(false,testOpp,testAccount,testContact);
        testZquQuote2.zqu__SoldToContact__c = testContact.Id;
        testZquQuote2.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote2.SalesRepLookup__c = srUserList[0].id;
        testZquQuote2.Reporting_Rep__c = srUserList[0].id;
        testZquQuote2.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote2.Product_Line__c = 'transactions';
        testZquQuote2.zqu__SubscriptionType__c = 'Cancel Subscription';
        testZquQuote2.zqu__ExistSubscriptionID__c = 'subfortestquotetriggerhandler';
        insert testZquQuote2;

        // insert transactions new sub quote
        zqu__Quote__c testZquQuote3 = TestClassUtility.createQuote(false,testOpp,testAccount,testContact);
        testZquQuote3.zqu__SoldToContact__c = testContact.Id;
        testZquQuote3.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote3.SalesRepLookup__c = srUserList[0].id;
        testZquQuote3.Reporting_Rep__c = srUserList[0].id;
        testZquQuote3.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote3.Product_Line__c = 'transactions';
        testZquQuote3.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote3.zqu__ExistSubscriptionID__c = 'subfortestquotetriggerhandler';
        insert testZquQuote3;

        Test.stopTest();
    }

    static testMethod void testUpdateMethodOne() {
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        List<User> srUserList = [SELECT Id, SalesRepID__c, ManagerID, Manager.IsActive, Email 
                                    FROM User 
                                    WHERE isActive = True 
                                        AND Manager.IsActive = True 
                                        AND Disallow_Sales_Rep_On_Quotes__c = false LIMIT 20];

        List<User> srUserDSROQList = [SELECT Id, SalesRepID__c, ManagerID, Manager.IsActive, Email 
                                    FROM User 
                                    WHERE isActive = True 
                                        AND Manager.IsActive = True 
                                        AND Disallow_Sales_Rep_On_Quotes__c = TRUE LIMIT 20];

        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        
        Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);

        zqu__Quote_Template__c testZquQuoteTemplate = TestClassUtility.createQuoteTemplate(false);
        testZquQuoteTemplate.Name = 'Quote Template for TRX';
        testZquQuoteTemplate.zqu__IsDefault__c = FALSE;
        insert testZquQuoteTemplate;
        

        

        Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
        Contact testContact = (Contact)testObjects.get('Contact');
        Account testAccount = (Account)testObjects.get('Account');

        Contact testErrorContact = TestClassUtility.createContact(false,testAccount);
        testErrorContact.FirstName = '';
        testErrorContact.LastName = 'testLaseName' + TestClassUtility.randomNumber(9);
        testErrorContact.Email = 'test_contact_email2_' + TestClassUtility.randomNumber(99) + '@faketesting' + TestClassUtility.randomNumber(99) + '.com';
        testErrorContact.MailingStreet = TestClassUtility.generateRandomStreet();
        testErrorContact.MailingCity = 'Austin';
        testErrorContact.MailingState = 'Texas';
        testErrorContact.MailingCountry = 'United States';
        testErrorContact.MailingPostalCode = TestClassUtility.generateRandomUSPostalCode();
        testErrorContact.Phone = TestClassUtility.randomNumber(9) + '98765432' + TestClassUtility.randomNumber(9);
        insert testErrorContact;
        // insert Internet New Sub Quote
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        Test.startTest();
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testOpp,testAccount,testContact);

        testZquQuote.zqu__SoldToContact__c = testContact.Id;
        testZquQuote.zqu__BillToContact__c = testContact.Id;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.SalesRepLookup__c = srUserList[0].id;
        testZquQuote.Reporting_Rep__c = srUserList[0].id;
        testZquQuote.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote.Product_Line__c = 'Internet';
        testZquQuote.zqu__ElectronicPaymentMethodId__c = 'testElectronicPaymentMethodId';
        insert testZquQuote;
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        // zqu__ProductRatePlan__c testPRP = TestClassUtility.
        zqu__QuoteAmendment__c testQAmendment = TestClassUtility.createQuoteAmendment(true,testZquQuote);

        zqu__QuoteRatePlan__c testQRP = TestClassUtility.createQuoteRatePlan(false);
        testQRP.zqu__QuoteAmendment__c = testQAmendment.id;
        testQRP.zqu__Quote__c = testZquQuote.Id;
        insert testQRP;

        zqu__ProductRatePlanCharge__c testPRPC = TestClassUtility.createProductRatePlanCharge(true);

        list<zqu__QuoteRatePlanCharge__c> testQRPCList = new list<zqu__QuoteRatePlanCharge__c>();
        zqu__QuoteRatePlanCharge__c  testQRPC = TestClassUtility.createQuoteRatePlanCharge(false,testQRP,testPRPC);
        testQRPCList.add(testQRPC);
        zqu__QuoteRatePlanCharge__c testQRPC1 = TestClassUtility.createQuoteRatePlanCharge(false,testQRP,testPRPC);
        testQRPC1.zqu__EffectivePrice__c = 10;
        testQRPCList.add(testQRPC1);
        zqu__QuoteRatePlanCharge__c testQRPC2 = TestClassUtility.createQuoteRatePlanCharge(false,testQRP,testPRPC);
        testQRPC2.zqu__EffectivePrice__c = 10;
        testQRPCList.add(testQRPC2);
        insert testQRPCList;
        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        testZquQuote.True_TCV__c = 10;
        testZquQuote.SalesRepLookup__c = srUserDSROQList[1].id;
        testZquQuote.Reporting_Rep__c = srUserDSROQList[1].id;
        testZquQuote.RenewalRepLookup__c = srUserDSROQList[1].id;
        testZquQuote.zqu__ValidUntil__c = Date.Today().addDays(10);
        testZquQuote.zqu__ElectronicPaymentMethodId__c = 'testElectronicPaymentMethodId1';
        testZquQuote.zqu__PaymentMethod__c = 'ACH';
        try{
          update testZquQuote;
        }catch(Exception e){}
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Zuora__Subscription__c testSub = TestClassUtility.createSubscription(false,testAccount);
        testSub.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandler';
        testSub.AutoRenewal__c = 'YES';
        insert testSub;

        Zuora__Product__c testProduct = TestClassUtility.createZuoraProduct(True);
        Zuora__SubscriptionProductCharge__c testSubProductCharge = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSub,testProduct);
        insert testSubProductCharge;
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        testZquQuote.zqu__ExistSubscriptionID__c = 'subfortestquotetriggerhandler';
        testZquQuote.zqu__SubscriptionType__c = 'Amend Subscription';
        testZquQuote.Product_Line__c = 'transactions';
        testZquQuote.SalesRepLookup__c = srUserList[1].id;
        testZquQuote.Reporting_Rep__c = srUserList[1].id;
        testZquQuote.RenewalRepLookup__c = srUserList[0].id;
        testZquQuote.zqu__ValidUntil__c = Date.Today().addDays(10);
        testZquQuote.zqu__Status__c = 'Sent to Z-Billing';
        testZquQuote.Subscription_Being_Renewed__c = testSub.id;
        update testZquQuote;

        ZuoraQuoteTriggerHandler.UpdatePotentialValueOfOpportunity(testOpp.id);
        delete testZquQuote;
        Test.stopTest();
    }
    
}