src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepId__c</fullName>
        <label>RenewalRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteCharge__c.object
<CustomObject>
    <description>The Charges that are related to a Quote.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepID__c</fullName>
        <label>RenewalRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The Quote related to the Charges.</description>
        <inlineHelpText>The Quote related to the Charges.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Charges</relationshipLabel>
        <relationshipName>QuoteCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Charge</label>
    <nameField>
        <label>Quote Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteChargeTriggerHandler.cls
/* 
<class>
  <name>ZuoraQuoteChargeTriggerHandler</name>
  <purpose>For handling save/update events on Zuora QuoteCharge records</purpose>
  <created>
    <by>Jonathan Satterfield</by>
    <date>7/22/2015</date>
    <ticket>SF-598, SF-599, SF-601</ticket>
  </created>
</class>
*/
public class ZuoraQuoteChargeTriggerHandler {
    /* 
    <method>
      <name>UpdateIDsForCommissionTracking</name>
      <purpose>When QuoteCharge records are created (when a Quote for new products is saved), record the
      SalesRepId, RenewalRepId, and the RSD_Id from the Quote on each QuoteCharge record</purpose>
	  <created>
	    <by>Jonathan Satterfield</by>
	    <date>7/22/2015</date>
	    <ticket>SF-598, SF-599, SF-601</ticket>
	  </created>
    </method>
    */
	public static void UpdateIDsForCommissionTracking(List<zqu__QuoteCharge__c> newQuoteChargeList) {
		Set<Id> parentQuoteIdSet = new Set<Id>();
		for (zqu__QuoteCharge__c newQC : newQuoteChargeList) {
			parentQuoteIdSet.add(newQC.zqu__Quote__c);
		}

		Map<Id,zqu__Quote__c> parentQuoteMap = new Map<Id,zqu__Quote__c>([SELECT Id, SalesRepId__c, RenewalRepId__c, RSD_Id__c FROM zqu__Quote__c WHERE Id IN :parentQuoteIdSet]);

		for (zqu__QuoteCharge__c qc : newQuoteChargeList) {
			if (qc.zqu__Quote__c != null) {
				zqu__Quote__c tempQuote = parentQuoteMap.get(qc.zqu__Quote__c);
				qc.SalesRepId__c = tempQuote.SalesRepId__c;
				qc.RenewalRepId__c = tempQuote.RenewalRepId__c;
				qc.RSD_Id__c = tempQuote.RSD_Id__c;
			}
		}
	}
}