src/objects/zqu__QuoteChargeDetail__c.object
<CustomObject>
    <description>This object is used to store the details (including billing metrics) for charges on a quote.</description>
    <fields>
        <fullName>Sent_to_ZBilling__c</fullName>
        <formula>ISPICKVAL(zqu__Quote__r.zqu__Status__c, &apos;Sent to Z-Billing&apos;)</formula>
        <label>Sent to Z-Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Charge Detail</label>
    <nameField>
        <label>Quote Charge Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charge Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteQuoteChargeDetailsScheduledJob.cls
// CSP-1834
global class DeleteQuoteChargeDetailsScheduledJob implements Schedulable {
	global void execute(SchedulableContext sc) {
		String queryString = 'SELECT Id FROM zqu__QuoteChargeDetail__c '
								+ 'WHERE Sent_To_ZBilling__c = true '
								+ 'AND SystemModstamp < ' + String.valueOf(DateTime.now().addMonths(-1).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\''));

		Database.executeBatch(new GenericBatchQueryDeletion(queryString));
	}
}