src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepId__c</fullName>
        <label>RenewalRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepId__c</fullName>
        <label>SalesRepId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is billed for this Quote.</description>
        <inlineHelpText>The Contact that is billed for this Quote.</inlineHelpText>
        <label>Bill to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteCharge__c.object
<CustomObject>
    <description>The Charges that are related to a Quote.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewalRepID__c</fullName>
        <label>RenewalRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <label>SalesRepID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The Quote related to the Charges.</description>
        <inlineHelpText>The Quote related to the Charges.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Charges</relationshipLabel>
        <relationshipName>QuoteCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Charge</label>
    <nameField>
        <label>Quote Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteChargeTriggerTest.cls
/* 
<class>
  <name>ZuoraQuoteChargeTriggerTest</name>
  <purpose>For testing save/delete events on a Zuora QuoteCharge</purpose>
  <created>
    <by>Jonathan Satterfield</by>
    <date>7/22/2015</date>
    <ticket>SF-598, SF-599, SF-601</ticket>
  </created>
</class>
*/
@isTest
public class ZuoraQuoteChargeTriggerTest {
    /* 
    <method>
      <name>TestUpdateIDsForCommissionTracking</name>
      <purpose>Test the ZuoraQuoteChargeTriggerHandler.UpdateIDsForCommissionTracking method</purpose>
      <created>
        <by>Jonathan Satterfield</by>
        <date>7/22/2015</date>
        <ticket>SF-598, SF-599, SF-601</ticket>
      </created>
    </method>
    */
    static testMethod void TestUpdateIDsForCommissionTracking() {

    	Test.startTest();
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Test.stopTest();
        Contact testContact = (Contact)testData.get('Contact');
        // first create and insert a zqu__Quote__c record
        zqu__Quote__c testQuote = new zqu__Quote__c();
        testQuote.Name = 'testQuote';
        testQuote.SalesRepId__c = '12345';
        testQuote.RenewalRepId__c = '12345';
        testQuote.RSD_Id__c = '11111';
        testQuote.zqu__BillToContact__c = testContact.Id;
        insert testQuote;

        // then create/attach/insert a zqu__QuoteCharge__c record
        zqu__QuoteCharge__c testQuoteCharge = new zqu__QuoteCharge__c();
        testQuoteCharge.zqu__Quote__c = testQuote.Id;
        insert testQuoteCharge;
        
        
        
        ZuoraQuoteChargeTriggerHandler2 zqcth2 = new ZuoraQuoteChargeTriggerHandler2();
        zqcth2.bulkAfter();
        //zqcth2.beforeInsert(testQuoteCharge);
        zqcth2.beforeUpdate(testQuoteCharge,testQuoteCharge);
        zqcth2.beforeDelete(testQuoteCharge);
        zqcth2.afterInsert(testQuoteCharge);
        zqcth2.afterUpdate(testQuoteCharge,testQuoteCharge);
        zqcth2.afterDelete(testQuoteCharge);
        
        zqcth2.andFinally();
    }
}