src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>OriginalSalesforceQuoteID__c</fullName>
        <description>SF-602</description>
        <label>OriginalSalesforceQuoteID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is billed for this Quote.</description>
        <inlineHelpText>The Contact that is billed for this Quote.</inlineHelpText>
        <label>Bill to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Hidden_Subscription_Name__c</fullName>
        <label>Hidden Subscription Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionVersion__c</fullName>
        <description>This is the version of the subscription</description>
        <label>Subscription Version</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>CreatingSalesforceQuoteID__c</fullName>
        <description>SF-602</description>
        <label>CreatingSalesforceQuoteID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NeedToUpdateSubscriptionCreator__c</fullName>
        <defaultValue>true</defaultValue>
        <description>SF-602</description>
        <label>Need To Update Subscription Creator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OriginalSalesforceQuoteID__c</fullName>
        <description>SF-602</description>
        <label>OriginalSalesforceQuoteID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionCreatorQueuedJobTest.cls
/* 
<class>
  <name>SubscriptionCreatorQueuedJobTest</name>
  <purpose>For testing the SubscriptionCreatorQueuedJob class</purpose>
  <created>
	<by>Jonathan Satterfield</by>
	<date>7/27/2015</date>
	<ticket>SF-602</ticket>
  </created>
</class>
*/ 
@isTest
public class SubscriptionCreatorQueuedJobTest {
	/* 
	<method>
	  <name>RunTest</name>
	  <purpose>Test the SubscriptionCreatorQueuedJob class</purpose>
	  <created>
		<by>Jonathan Satterfield</by>
		<date>7/27/2015</date>
		<ticket>SF-602</ticket>
	  </created>
	</method>
	*/
	@isTest static void TestSubscriptionCreatorQueuedJob_one() {

		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();
		
		Contact testContact = (Contact)testObjects.get('Contact');

		// first, create a "new" Quote to later tie to a Subscription
		zqu__Quote__c newQuote = new zqu__Quote__c();
		newQuote.OwnerId = UserInfo.getUserId();
		newQuote.zqu__BillToContact__c = testContact.Id;
		insert newQuote;

		// then, create an "amendment" Quote to later tie to a Subscription
		zqu__Quote__c amendmentQuote = new zqu__Quote__c();
		amendmentQuote.OwnerId = UserInfo.getUserId();
		amendmentQuote.zqu__SubscriptionVersion__c = 1;
		amendmentQuote.zqu__Hidden_Subscription_Name__c = 'AmendmentSubFromSalesforce';
		amendmentQuote.zqu__BillToContact__c = testContact.Id;
		insert amendmentQuote;

		// create new Subscription that originated in Zuora
		Zuora__Subscription__c newSubFromZuora = new Zuora__Subscription__c();
		newSubFromZuora.Name = 'NewSubFromZuora';
		newSubFromZuora.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		newSubFromZuora.NeedToUpdateSubscriptionCreator__c = True;
		newSubFromZuora.Zuora__Version__c = 1;
		newSubFromZuora.OwnerId = UserInfo.getUserId();
		newSubFromZuora.Product_Line__c = 'test';
		insert newSubFromZuora;

		// next, create "new" Subscription that originated in Salesforce
		Zuora__Subscription__c newSubFromSalesforce = new Zuora__Subscription__c();
		newSubFromSalesforce.Name = 'NewSubFromSalesforce';
		newSubFromSalesforce.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		newSubFromSalesforce.NeedToUpdateSubscriptionCreator__c = True;
		newSubFromSalesforce.Zuora__Version__c = 1;
		newSubFromSalesforce.OwnerId = UserInfo.getUserId();
		newSubFromSalesforce.OriginalSalesforceQuoteID__c = (String)newQuote.Id;
		newSubFromSalesforce.CreatingSalesforceQuoteID__c = (String)newQuote.Id;
		newSubFromSalesforce.Product_Line__c = 'test';
		insert newSubFromSalesforce;

		// then, create an "amendment" Subscription that originated in Salesforce
		Zuora__Subscription__c amendmentSubFromSalesforce = new Zuora__Subscription__c();
		amendmentSubFromSalesforce.Name = 'AmendmentSubFromSalesforce';
		amendmentSubFromSalesforce.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		amendmentSubFromSalesforce.NeedToUpdateSubscriptionCreator__c = True;
		amendmentSubFromSalesforce.Zuora__Version__c = 2;
		amendmentSubFromSalesforce.OwnerId = UserInfo.getUserId();
		amendmentSubFromSalesforce.OriginalSalesforceQuoteID__c = (String)amendmentQuote.Id;
		amendmentSubFromSalesforce.CreatingSalesforceQuoteID__c = (String)amendmentQuote.Id;
		amendmentSubFromSalesforce.Product_Line__c = 'test';
		insert amendmentSubFromSalesforce;

		// then, create an "amendment" Subscription that originated in Salesforce
		Zuora__Subscription__c amendmentSubFromZuora = new Zuora__Subscription__c();
		amendmentSubFromZuora.Name = 'AmendmentSubFromZuora';
		amendmentSubFromZuora.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		amendmentSubFromZuora.NeedToUpdateSubscriptionCreator__c = True;
		amendmentSubFromZuora.Zuora__Version__c = 3;
		amendmentSubFromZuora.OwnerId = UserInfo.getUserId();
		amendmentSubFromZuora.Product_Line__c = 'test';
		insert amendmentSubFromZuora;

		// Then, run the test
		ID jobID = System.enqueueJob(new SubscriptionCreatorQueuedJob());

	}
	
	@isTest
	static void TestSubscriptionCreatorQueuedJob_two() {

		Test.startTest();
		Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();
		
		Contact testContact = (Contact)testObjects.get('Contact');

		// first, create a "new" Quote to later tie to a Subscription
		zqu__Quote__c newQuote = new zqu__Quote__c();
		newQuote.OwnerId = UserInfo.getUserId();
		newQuote.zqu__BillToContact__c = testContact.Id;
		insert newQuote;

		// then, create an "amendment" Quote to later tie to a Subscription
		zqu__Quote__c amendmentQuote = new zqu__Quote__c();
		amendmentQuote.OwnerId = UserInfo.getUserId();
		amendmentQuote.zqu__SubscriptionVersion__c = 1;
		amendmentQuote.zqu__Hidden_Subscription_Name__c = 'AmendmentSubFromSalesforce';
		amendmentQuote.zqu__BillToContact__c = testContact.Id;
		insert amendmentQuote;

		// create new Subscription that originated in Zuora
		Zuora__Subscription__c newSubFromZuora = new Zuora__Subscription__c();
		newSubFromZuora.Name = 'NewSubFromZuora';
		newSubFromZuora.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		newSubFromZuora.NeedToUpdateSubscriptionCreator__c = True;
		newSubFromZuora.Zuora__Version__c = 1;
		newSubFromZuora.OwnerId = UserInfo.getUserId();
		newSubFromZuora.Product_Line__c = 'test';
		insert newSubFromZuora;

		// next, create "new" Subscription that originated in Salesforce
		Zuora__Subscription__c newSubFromSalesforce = new Zuora__Subscription__c();
		newSubFromSalesforce.Name = 'NewSubFromSalesforce';
		newSubFromSalesforce.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		newSubFromSalesforce.NeedToUpdateSubscriptionCreator__c = True;
		newSubFromSalesforce.Zuora__Version__c = 1;
		newSubFromSalesforce.OwnerId = UserInfo.getUserId();
		newSubFromSalesforce.OriginalSalesforceQuoteID__c = null;
		newSubFromSalesforce.CreatingSalesforceQuoteID__c = (String)newQuote.Id;
		newSubFromSalesforce.Product_Line__c = 'test';
		insert newSubFromSalesforce;

		// then, create an "amendment" Subscription that originated in Salesforce
		Zuora__Subscription__c amendmentSubFromSalesforce = new Zuora__Subscription__c();
		amendmentSubFromSalesforce.Name = 'AmendmentSubFromSalesforce';
		amendmentSubFromSalesforce.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		amendmentSubFromSalesforce.NeedToUpdateSubscriptionCreator__c = True;
		amendmentSubFromSalesforce.Zuora__Version__c = 2;
		amendmentSubFromSalesforce.OwnerId = UserInfo.getUserId();
		amendmentSubFromSalesforce.OriginalSalesforceQuoteID__c = (String)amendmentQuote.Id;
		amendmentSubFromSalesforce.CreatingSalesforceQuoteID__c = (String)amendmentQuote.Id;
		amendmentSubFromSalesforce.Product_Line__c = 'test';
		insert amendmentSubFromSalesforce;

		// then, create an "amendment" Subscription that originated in Salesforce
		Zuora__Subscription__c amendmentSubFromZuora = new Zuora__Subscription__c();
		amendmentSubFromZuora.Name = 'AmendmentSubFromZuora';
		amendmentSubFromZuora.Zuora__Zuora_Id__c = '2c92c0f84e713779014e73b9dfba42e1';
		amendmentSubFromZuora.NeedToUpdateSubscriptionCreator__c = True;
		amendmentSubFromZuora.Zuora__Version__c = 3;
		amendmentSubFromZuora.OwnerId = UserInfo.getUserId();
		amendmentSubFromZuora.Product_Line__c = 'test';
		insert amendmentSubFromZuora;

		// Then, run the test
		ID jobID = System.enqueueJob(new SubscriptionCreatorQueuedJob());
	}
}