src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alterations+Preservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor(ette)Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beauty-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfasts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boudoir Photographers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Open House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Salons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Shows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calligraphers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central &amp; South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceremony Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceremony Venues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dance Lessons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desserts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ensembles+Soloists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favors+Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Jewelry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AK-Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL-Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR-Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ-Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ-Tucson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best of Weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Central CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Palm Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Sacramento/Tahoe/Reno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-San Fran/Bay Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA-Santa Barbara/Ventura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALIFORNIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAN-Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO-Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT-Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC-DC/MD/Northern VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dest Weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-Northern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL-West Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA-Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA-Savannah/Coastal Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI-Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honeymoons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA-Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID-Idaho</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AK - Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL - Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR - Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Tucson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Atlanta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Bay Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Chicago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Dallas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Houston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - New Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - New York Metro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - North Carolina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Philadelphia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Seattle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - South Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - St. Louis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bump - Wash DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Central CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAN - Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Palm Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Sacramento/Tahoe/Reno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - San Diego</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddRemoveRatePlanTest.cls
/*******************************************************************************
 *  Summary	     : Test class for AddRemoveRatePlan
 *  Refer Object : 
 *  Author	     : Nick
 *  RefactorDate : 12 Dec 2016
 *  Change Log   : Refactoring by SF-2.6 release
 ******************************************************************************/
@isTest
private class AddRemoveRatePlanTest{

	private static testmethod void testAdd() {
		
		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		
		Map<String,SObject> testMap = TestClassUtility.buildLocalData(false);
		
		Test.startTest();
		
		List<String> addedRatePlans = new List<String>();
		
		Product2 zp = TestClassUtility.createLocalProduct2(true);
		 zqu__Quote__c q = TestClassUtility.createQuote(true, 
			(Opportunity)testMap.get('Opportunity') , 
			(Account)testMap.get('Account'), 
			(Contact)testMap.get('Contact'));
	
		zqu__ProductRatePlan__c prp = new zqu__ProductRatePlan__c(); 
		prp.Name = 'Rate Plan 1'; 
		prp.zqu__Product__c = zp.id; 
		prp.Capacity__c = '10';
		prp.Market__c = 'Test Market';
		prp.Category__c = 'Test Category';
		prp.zqu__ZuoraId__c = '2c92c0f94e4d3a3d014e655c28c50f5f';
		insert prp;

		zqu__ProductRatePlan__c prp2 = new zqu__ProductRatePlan__c();
		prp2.Name = 'NY - Long Island - Photographers'; 
		prp2.zqu__Product__c = zp.id; 
		prp2.Capacity__c = '10';
		prp2.Market__c = 'Test Market';
		prp2.Category__c = 'Test Category';
		prp2.zqu__ZuoraId__c = '2c92c0f94e4d3a3d014e655c28c50f5t';
		insert prp2;

		addedRatePlans.add(prp2.id);
		addedRatePlans.add(prp.id);

		String quoteId = q.id;
		AddRemoveRatePlan ARRP = new AddRemoveRatePlan();
		
		// avoid call out error in test class
		try {
			arrp.onAdd(quoteId,addedRatePlans);
		}
		catch (Exception e) {
		}

		Test.stopTest();
	}

	private static testmethod void testRemove() {
		
		SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
												 'Complete',
												 '{"companyName": "Test Account"}',
												 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		
		Map<String,SObject> testMap = TestClassUtility.buildLocalData(false);
		
		Test.startTest();

		List<String> addedRatePlans = new List<String>();
		
		Product2 zp =  TestClassUtility.createLocalProduct2(true);
		 zqu__Quote__c q = TestClassUtility.createQuote(true, 
			(Opportunity)testMap.get('Opportunity') , 
			(Account)testMap.get('Account'), 
			(Contact)testMap.get('Contact'));

		zqu__ProductRatePlan__c prp = new zqu__ProductRatePlan__c(); 
		prp.Name = 'Basic'; 
		prp.zqu__Product__c = zp.id; 
		prp.Capacity__c = '10';
		prp.Market__c = 'Test Market';
		prp.Category__c = 'Test Category';
		prp.zqu__ZuoraId__c = '2c92c0f94e4d3a3d014e655c28c50f5f';
		insert prp;

		List<String> removedRatePlans = new List<String>();
		removedRatePlans.add(prp.id);
		String quoteId = q.id;
		AddRemoveRatePlan ARRP = new AddRemoveRatePlan();

		// avoid call out error in test class
		try{
			arrp.onRemove(quoteId,removedRatePlans);
		}
		catch(exception e)
		{}
		Test.stopTest();
	}
}