src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>TEXT(zqu__Product__r.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <description>Sets the bill cycle day (BCD) for the charge. The BCD determines which day of the month customer is billed. The BCD value in the account can override the BCD in this object.</description>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>Auto-set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21st of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22nd of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23rd of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28th of the month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29th of the month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Preferred_Payment_Schedule__c</fullName>
        <label>Preferred Payment Schedule</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>Month</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>True_TCV_JSON_Response__c</fullName>
        <description>(CSP-1181) store the JSON response returned while retrieving the Quote&apos;s true TCV amount</description>
        <label>True TCV JSON Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__InitialTerm__c</fullName>
        <description>The Initial Term of the Quote.</description>
        <inlineHelpText>The Initial Term of the Quote.</inlineHelpText>
        <label>Initial Term</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__PaymentMethod__c</fullName>
        <description>The Payment Method for the Quote.</description>
        <inlineHelpText>The Payment Method for the Quote.</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionTermEndDate__c</fullName>
        <description>Only for Amendment quotes, contains the term end date of the base subscription</description>
        <inlineHelpText>The term end date of the subscription is amendment on</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionTermStartDate__c</fullName>
        <description>The term start date of the subscription is amendment on, only used for amendment Quote</description>
        <inlineHelpText>The term start date of the subscription is amendment on</inlineHelpText>
        <label>Subscription Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentSchBreakdownController.cls
public class PaymentSchBreakdownController {
    private static final STRING QUOTE_QUERY = 'SELECT '
                                                +   'Id, '
                                                +   'True_TCV_JSON_Response__c, '
                                                +   'zqu__BillCycleDay__c, '
                                                +   'zqu__SubscriptionType__c, '
                                                +   'zqu__SubscriptionTermStartDate__c, '
                                                +   'zqu__SubscriptionTermEndDate__c, '
                                                +   'zqu__TermStartDate__c, '
                                                +   'zqu__InitialTerm__c, '
                                                +   'Preferred_Payment_Schedule__c, '
                                                +   'Product_Line__c, '
                                                +   'zqu__PaymentMethod__c '
                                                +   ' FROM '
                                                +   'zqu__Quote__c'
                                                +   ' WHERE '
                                                +   '{WHERECLAUSE}';

    public List<BreakDownWrapper> breakdownWrapperList {get; private set;}
    
    public PaymentSchBreakdownController() {
    }

    // this method is for parsing the payment schedule breakdown which is in the form of a json
    public void parseJSONPaymentBreakdownString () {
        // Get Quote Id from URL parameters
        Id quoteId = System.currentPagereference().getParameters().get('quoteId'); 

        // TODO: Test what happens when no quote id provided
        if(String.isBlank(quoteId)) {
            return;    
        }

        // Query for Quote record details to be used later
        zqu__Quote__c quote = Database.query(QUOTE_QUERY.replace('{WHERECLAUSE}', 'Id = :quoteId'));
        
        String attName = String.valueOf(quoteId) + 'JSON.txt';

        List<Attachment> jsonAttList = new List<Attachment>();
        // TODO: Test what happens when no True TCV JSON
        // CSP-2667 Adding more than 60 services
        // if the True_TCV_JSON_Response__c is blank, we query the response attachment
        if(String.isBlank(quote.True_TCV_JSON_Response__c) ) {
            jsonAttList = [SELECT Id, Body FROM Attachment WHERE ParentId =: quoteId AND Name = : attName LIMIT 1];

            if (jsonAttList.isEmpty()) {
                return;
            }
        }

        breakdownWrapperList = new List<BreakdownWrapper>();

        // if(String.isNotBlank(quote.True_TCV_JSON_Response__c)) {
        // // if the True_TCV_JSON_Response__c is not blank, we use True_TCV_JSON_Response__c to generate preview file
        if (!jsonAttList.isEmpty() || String.isNotBlank(quote.True_TCV_JSON_Response__c)) {
            List<InvoiceItems> jsonInvoiceItems = new List<InvoiceItems>();
            if (String.isNotBlank(quote.True_TCV_JSON_Response__c)) {
                ZuoraSubscPreview jsonSubPreview = (PaymentSchBreakDownController.ZuoraSubscPreview)JSON.deserialize(quote.True_TCV_JSON_Response__c, PaymentSchBreakDownController.ZuoraSubscPreview.class);
                jsonInvoiceItems = jsonSubPreview.invoiceItems;
            }else{
                ZuoraSubscPreview jsonSubPreview = (PaymentSchBreakDownController.ZuoraSubscPreview)JSON.deserialize(jsonAttList[0].Body.toString(), PaymentSchBreakDownController.ZuoraSubscPreview.class);
                jsonInvoiceItems = jsonSubPreview.invoiceItems;
            }
            // List<InvoiceItems> jsonInvoiceItems = jsonSubPreview.invoiceItems;
            // CSP-2472 - Sort based on serviceStartDate
            jsonInvoiceItems.sort();
            System.debug(LoggingLevel.INFO, '***jsonInvoiceItems : ' + jsonInvoiceItems);
            Map<String, zqu__ProductRatePlanCharge__c> zuoraIdToProductRatePlanChargeMap = retrieveRatePlanCharges(jsonInvoiceItems);

            Date subscriptionStartDate = quote.zqu__TermStartDate__c;
            // CSP-2472
            if(!jsonInvoiceItems.isEmpty()) {
                InvoiceItems firstInvoiceItem = jsonInvoiceItems[0];
                if(firstInvoiceItem.serviceStartDate < subscriptionStartDate && firstInvoiceItem.serviceStartDate < subscriptionStartDate.addMonths(-1)) {
                    subscriptionStartDate = subscriptionStartDate.addMonths(-1);
                }
            }

            Date subscriptionEndDate;
            if(quote.zqu__SubscriptionTermEndDate__c != null) {
                subscriptionEndDate = quote.zqu__SubscriptionTermEndDate__c;
            } else {
                subscriptionEndDate = quote.zqu__TermStartDate__c.addMonths(Integer.valueOf(quote.zqu__InitialTerm__c));
            }

            // BillCycleDay is stored in a picklist as a string
            Date bcdAlignmentDate = Date.newInstance(subscriptionStartDate.year(), subscriptionStartDate.month(), Integer.valueOf(quote.zqu__BillCycleDay__c));
            
            while(bcdAlignmentDate <= subscriptionEndDate) {
                List<InvoiceItems> bcdInvoiceItemList = new List<InvoiceItems>();
                Decimal grandTotal = 0;

                for(Integer i = 0; i < jsonInvoiceItems.size(); i++) {
                    InvoiceItems currentInvoiceItem = jsonInvoiceItems[i];
                    System.debug('II -> ' + currentInvoiceItem);
                    if(currentInvoiceItem.serviceStartDate <= bcdAlignmentDate) {
                        if(zuoraIdToProductRatePlanChargeMap.containsKey(currentInvoiceItem.productRatePlanChargeId)) {
                            zqu__ProductRatePlanCharge__c currentProductRatePlanCharge = zuoraIdToProductRatePlanChargeMap.get(currentInvoiceItem.productRatePlanChargeId);
                            currentInvoiceItem.productRatePlanName = currentProductRatePlanCharge.zqu__ProductRatePlan__r.Name;

                            // CSP-2355 - Do not show service periods for Print or Direct Mail
                            if(currentProductRatePlanCharge.zqu__ProductRatePlan__r.Product_Line__c.equals('Print') || currentProductRatePlanCharge.zqu__ProductRatePlan__r.Product_Line__c.equals('Direct Mail')) {
                                currentInvoiceItem.serviceStartDate = null;
                                currentInvoiceItem.serviceEndDate = null;
                            }
                        }
                        grandTotal += currentInvoiceItem.chargeAmount;
                        bcdInvoiceItemList.add(currentInvoiceItem);
                        jsonInvoiceItems.remove(i);
                        i--;
                    }
                }

                if(!bcdInvoiceItemList.isEmpty()) {
                    Date dueDate = bcdAlignmentDate;
                    // Requirement for Check customers to have a Due Date 30 days from their Invoice Date
                    if(quote.zqu__PaymentMethod__c == 'Check') {
                        dueDate = dueDate.addDays(30);
                    }

                    breakdownWrapperList.add(new BreakDownWrapper(dueDate, quote.Preferred_Payment_Schedule__c, bcdInvoiceItemList, grandTotal));
                }

                bcdAlignmentDate = bcdAlignmentDate.addMonths(1);
            }
        }
    }

    /**
     *   Method used to retrieve related Rate Plan Charges to get the rate plan name for display user
     *
     *   @author Justin
     *   @date   2017-06-27
     *   @param  {List<InvoiceItems>}         currentInvoiceItemList           The list of invoice items to get the rate
     *                                                                         plan charge id values
     *   @return {Map<String, zqu__ProductRatePlanCharge__c>}                  The Map which is built that has the Zuora
     *                                                                         Id as the primary key.
     */
    private static Map<String, zqu__ProductRatePlanCharge__c> retrieveRatePlanCharges(List<InvoiceItems> currentInvoiceItemList) {
        Map<String, zqu__ProductRatePlanCharge__c> zuoraIdToProductRatePlanChargeMap = new Map<String, zqu__ProductRatePlanCharge__c>();
        // If the currentInvoiceItemList is empty then there is nothing to try and build...
        if(currentInvoiceItemList.isEmpty()) {
            return zuoraIdToProductRatePlanChargeMap;
        }

        Set<String> productRatePlanChargeIdSet = new Set<String>();

        // Loop through all InvoiceItems and grab the productRatePlanChargeId Ids
        for(Integer i = 0; i < currentInvoiceItemList.size(); i++) {
            InvoiceItems currentInvoiceItem = currentInvoiceItemList[i];
            // If the Product Rate Plan Charge Id is blank OR the set has the value already, continue to next iteration
            if(String.isBlank(currentInvoiceItem.productRatePlanChargeId) || productRatePlanChargeIdSet.contains(currentInvoiceItem.productRatePlanChargeId)) {
                continue;
            }

            productRatePlanChargeIdSet.add(currentInvoiceItem.productRatePlanChargeId);
        }

        // Query the needed data which will be returned as the value in the map
        List<zqu__ProductRatePlanCharge__c> productRatePlanChargeList = [SELECT Id, zqu__ProductRatePlan__r.Name, zqu__ProductRatePlan__r.Product_Line__c, zqu__ZuoraId__c FROM zqu__ProductRatePlanCharge__c WHERE zqu__ZuoraId__c IN :productRatePlanChargeIdSet];

        // Use a FOR loop to build the map as we are not setting the map key with the Salesforce Id but rather the
        // Zuora external Id
        for(Integer i = 0; i < productRatePlanChargeList.size(); i++) {
            zqu__ProductRatePlanCharge__c currentProductRatePlanCharge = productRatePlanChargeList[i];
            zuoraIdToProductRatePlanChargeMap.put(currentProductRatePlanCharge.zqu__ZuoraId__c, currentProductRatePlanCharge);
        }

        return zuoraIdToProductRatePlanChargeMap;
    }

    // Object used to tie front end data together for display
    public class BreakdownWrapper {
        public Date dueDate {get; private set;}
        public Decimal total {get; private set;}
        public String billingTerm {get; private set;}
        public List<InvoiceItems> invoiceItems {get; private set;}

        public BreakdownWrapper(Date setDueDate, String preferredPaymentSchedule, InvoiceItems newInvoiceItem) {
            dueDate = setDueDate;
            billingTerm = preferredPaymentSchedule;
            total = newInvoiceItem.chargeAmount;
            invoiceItems = new List<InvoiceItems>{newInvoiceItem};
        }

        public BreakdownWrapper(Date setDueDate, String preferredPaymentSchedule, List<InvoiceItems> newInvoiceItemsList, Decimal totalAmount) {
            dueDate = setDueDate;
            billingTerm = preferredPaymentSchedule;
            total = totalAmount;
            invoiceItems = newInvoiceItemsList;
        }
    }

    // Inner class which is used for serialization by readValuesAs. The entire json string(payload consisting of paymnet schedule
    // breakdown as per service periods) is parsed into an object which is instance of ZuoraSubscPreview in this case.
    public class ZuoraSubscPreview {
        public Boolean success {get; set;}    
        public List<InvoiceItems> invoiceItems {get; set;}
        
        public ZuoraSubscPreview(List<InvoiceItems> invItems, Boolean flag) {
            invoiceItems = invItems;
            success = flag;
        }
    }

    public class InvoiceItems implements Comparable {
        public Date serviceStartDate {get; set;}
        public Date serviceEndDate {get; set;}
        public Decimal chargeAmount {get; set;}
        public String chargeName {get; set;}
        public String productRatePlanChargeId {get; set;}
        public String productRatePlanName {get; set;} //ProductRatePlanName__c

        // CSP-2472 - Added the comparable implementation to sort invoice items based on serviceStartDate
        public Integer compareTo(Object compareTo) {
            InvoiceItems compareInvoiceItem = (InvoiceItems)compareTo;

            if(serviceStartDate == compareInvoiceItem.serviceStartDate) {
                return 0;
            }

            if(serviceStartDate > compareInvoiceItem.serviceStartDate) {
                return 1;
            }

            return -1;
        }
    }
}