src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account associated with this Quote.</description>
        <inlineHelpText>The Account associated with this Quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Amendment_Name__c</fullName>
        <description>New amendment name field to accommodate Opportunity Name</description>
        <label>Amendment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Calculate_Quote_Metrics_Through__c</fullName>
        <description>Select how you would like Quote Metrics values to be calculated</description>
        <inlineHelpText>Select how you would like Quote Metrics values to be calculated.If you select the End of Term option, Evergreen Subscription metrics will be calculated for 1 billing period.</inlineHelpText>
        <label>Calculate Quote Metrics Through</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__CancellationDate__c</fullName>
        <description>Date on which the cancellation is made.</description>
        <inlineHelpText>Date on which the cancellation is made.</inlineHelpText>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__CancellationEffectiveDate__c</fullName>
        <label>Cancellation Effective Date</label>
        <picklist>
            <picklistValues>
                <fullName>Enter a Date</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>End of Current Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Last Invoice Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Currency__c</fullName>
        <description>The Currency the Quote is in.</description>
        <inlineHelpText>The Currency the Quote is in.</inlineHelpText>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__ExistSubscriptionID__c</fullName>
        <label>Exist Subscription ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__InvoiceProcessingOption__c</fullName>
        <description>The option to determine which level the invoice will be generated when the quote is sent to Zuora.</description>
        <inlineHelpText>The option to determine which level the invoice will be generated when the quote is sent to Z-Billing.</inlineHelpText>
        <label>Invoice Processing Option</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Is_Charge_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag to indicate whether the Quote Metrics need to be recalculated.</description>
        <inlineHelpText>The flag to indicate whether the Quote Metrics need to be recalculated.</inlineHelpText>
        <label>Is Charge Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__StartDate__c</fullName>
        <description>The Date that the Quote Starts.</description>
        <inlineHelpText>The Date that the Quote Starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionVersion__c</fullName>
        <description>This is the version of the subscription</description>
        <label>Subscription Version</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraAccountID__c</fullName>
        <label>Zuora Account ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToName__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id (Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraQuoteCreateCancellationController.cls
public without sharing class ZuoraQuoteCreateCancellationController {

	public Opportunity theOpp {get;set;}
	public zqu__Quote__c theQuote {get;set;}
	public Zuora__CustomerAccount__c theCustomerAccount {get;set;}
	public Zuora__Subscription__c theSubscription {get;set;}
	public String oppLink {get;set;}
	public String accountLink {get;set;}
	public Date endOfLastInvoicePeriod {get;set;}
	public String cancellationEffectiveDate {get;set;}
	public List<SelectOption> cancellationEffectiveDateOptions {get;set;}
	// for ticket CSP-2514, the boolean param used for determine the user can check the Generate Invoice flag for cancel quote
	public Boolean isGenerateInvoice {get;set;}
	// constructor doesn't do anything because we need to perform a DML statement upon page load
	// therefore, all "initilization" code takes place below in the initializeQuote method
	public ZuoraQuoteCreateCancellationController(ApexPages.StandardController standardController) {
	}	


	public void initializeQuote() {
		// for ticket CSP-2514, only the special user can check the Generate Invoice flag for cancel quote
		Set<Id> generateCancelInvoiceUserIdSet = new Set<Id>();
		Group generateInvoiceGroup = [SELECT Id, Name, Type, (SELECT Id, UserOrGroupId FROM GroupMembers) FROM Group WHERE Name = 'GenerateCancelInvoiceUser'];
		for (GroupMember currntGM : generateInvoiceGroup.GroupMembers) {
			generateCancelInvoiceUserIdSet.add(currntGM.UserOrGroupId);
		}
		if (generateCancelInvoiceUserIdSet.contains(UserInfo.getUserId())) {
	    isGenerateInvoice = true;
		}else{
			isGenerateInvoice = false;
		}

		Id oppId = (Id)ApexPages.currentPage().getParameters().get('oppId');
		this.theOpp = [SELECT Id, Name, AccountId, Account.Name FROM Opportunity WHERE Id = :oppId LIMIT 1];

		String billingAccountId = ApexPages.currentPage().getParameters().get('billingAccountId');
		this.theCustomerAccount = [SELECT Id, Zuora__Account__c, Zuora__Zuora_Id__c, Zuora__BillCycleDay__c, Zuora__BillToName__c, Zuora__SoldToName__c FROM Zuora__CustomerAccount__c WHERE Zuora__Zuora_Id__c = :billingAccountId LIMIT 1];

		String subscriptionId = ApexPages.currentPage().getParameters().get('subscriptionId');
		this.theSubscription = [SELECT Id, Zuora__TermEndDate__c, Zuora__Version__c FROM Zuora__Subscription__c WHERE Zuora__Zuora_Id__c = :subscriptionId];

		this.endOfLastInvoicePeriod = returnEndOfLastInvoicePeriod(this.theCustomerAccount);

		this.cancellationEffectiveDateOptions = new List<SelectOption>();
		this.cancellationEffectiveDateOptions.add(new SelectOption('Enter a Date','Enter a Date'));
		this.cancellationEffectiveDateOptions.add(new SelectOption('End of Current Term','End of Current Term -- ' + this.theSubscription.Zuora__TermEndDate__c.format()));
		this.cancellationEffectiveDateOptions.add(new SelectOption('End of Last Invoice Period','End of Last Invoice Period -- ' + this.endOfLastInvoicePeriod.format()));

		this.oppLink = '<a href="' + System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + (String)this.theOpp.Id + '">' + this.theOpp.Name + '</a>';
		this.accountLink = '<a href="' + System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + (String)this.theOpp.AccountId + '">' + this.theOpp.Account.Name + '</a>';

		this.theQuote = new zqu__Quote__c();
		this.theQuote.Name = 'Quote for ' + theOpp.Name;
		this.theQuote.zqu__Opportunity__c = theOpp.Id;
		this.theQuote.zqu__Account__c = theOpp.AccountId;
		this.theQuote.zqu__ValidUntil__c = Date.today();
		this.theQuote.zqu__StartDate__c = Date.today();
		this.theQuote.zqu__CancellationDate__c = Date.today();
		this.theQuote.zqu__CancellationEffectiveDate__c = 'Enter a Date';
		this.theQuote.zqu__ExistSubscriptionID__c = ApexPages.currentPage().getParameters().get('subscriptionId');
		this.theQuote.zqu__SubscriptionType__c = 'Cancel Subscription';
		this.theQuote.RecordTypeId = Schema.SObjectType.zqu__Quote__c.RecordTypeInfosByName.get('Cancellation').RecordTypeId;
		this.theQuote.zqu__ZuoraAccountID__c = ApexPages.currentPage().getParameters().get('billingAccountId');
		this.theQuote.zqu__Currency__c = 'USD';
		this.theQuote.zqu__Amendment_Name__c = this.theQuote.Name;
		this.theQuote.zqu__SubscriptionVersion__c = this.theSubscription.Zuora__Version__c;
		// (SF-2036) this boolean needs to be set in order to run the zqu.zQuoteUtil.previewQuotes method on the ChooseNextAction page
		this.theQuote.zqu__Is_Charge_Expired__c = True;

		// these two values I hardcoded in, but not 100% sure they couldn't change
		this.theQuote.zqu__Calculate_Quote_Metrics_Through__c = 'EOT';
		this.theQuote.zqu__InvoiceProcessingOption__c = 'Subscription';

		insert this.theQuote;
	}


	public Date returnEndOfLastInvoicePeriod(Zuora__CustomerAccount__c customerAccount) {

		Date endOfLastInvoicePeriod;

		String bcdFirstThreeChars = customerAccount.Zuora__BillCycleDay__c.left(3);
		String bcdFirstTwoChars = customerAccount.Zuora__BillCycleDay__c.left(2);
		String bcdFirstChar = customerAccount.Zuora__BillCycleDay__c.left(1);

		// end of month
		if (bcdFirstThreeChars == 'EOM') {
			// current month
			if (Date.today().day() < Date.daysInMonth(Date.today().year(), Date.today().month())) {
				endOfLastInvoicePeriod = Date.newInstance(Date.today().year(), Date.today().month(), Date.daysInMonth(Date.today().year(), Date.today().month()));
			}
			// next month
			else {
				// if the month is December...
				if (Date.today().month() == 12) {
					endOfLastInvoicePeriod = Date.newInstance(Date.today().year() + 1, 1, Date.daysInMonth(Date.today().year() + 1, 1));
				}
				// and if the month is not December...
				else {
					endOfLastInvoicePeriod = Date.newInstance(Date.today().year(), Date.today().month() + 1, Date.daysInMonth(Date.today().year(), Date.today().month() + 1));
				}
			}
		}
		// any other day
		else {
			// first find if day is double digits, e.g. the 10th, the 22nd, etc., or single digits
			Integer billingDay;
			
			if (bcdFirstTwoChars.right(1) == '0' || bcdFirstTwoChars.right(1) == '1' || 
				bcdFirstTwoChars.right(1) == '2' || bcdFirstTwoChars.right(1) == '3' || 
				bcdFirstTwoChars.right(1) == '4' || bcdFirstTwoChars.right(1) == '5' || 
				bcdFirstTwoChars.right(1) == '6' || bcdFirstTwoChars.right(1) == '7' || 
				bcdFirstTwoChars.right(1) == '8' || bcdFirstTwoChars.right(1) == '9') {

				billingDay = Integer.valueOf(bcdFirstTwoChars);
			}
			else {
				billingDay = Integer.valueOf(bcdFirstChar);
			}
			// current month
			if (Date.today().day() < billingDay) {
				endOfLastInvoicePeriod = Date.newInstance(Date.today().year(), Date.today().month(), billingDay);
			}
			// next month
			else {
				// if the month is December...
				if (Date.today().month() == 12) {
					endOfLastInvoicePeriod = Date.newInstance(Date.today().year() + 1, 1, billingDay);
				}
				// and if the month is not December...
				else {
					endOfLastInvoicePeriod = Date.newInstance(Date.today().year(), Date.today().month() + 1, billingDay);
				}
			}
		}

		return endOfLastInvoicePeriod;
	}


	public void updateCancellationEffectiveDate() {

		if (cancellationEffectiveDate == 'Enter a Date') {
			this.theQuote.zqu__CancellationDate__c = Date.today();
		}
		else if (cancellationEffectiveDate == 'End of Current Term') {
			this.theQuote.zqu__CancellationDate__c = this.theSubscription.Zuora__TermEndDate__c;
		}
		// a.k.a. End of Last Invoice Period
		else {
			this.theQuote.zqu__CancellationDate__c = this.endOfLastInvoicePeriod;
		}
	}


	// TODO: add try-catch blocks in this method
	public void createCancellationAmendment(Id quoteId) {
		zqu.zQuoteUtil.createCancellationAmendment(quoteId);
	}


	public String getImgUrl() {
		String imgDocId = '';

		try {
			Document imgDoc = [Select Id from Document d where d.DeveloperName = 'ZuoraTabImage' limit 1];
			imgDocId = imgDoc.Id;
		}
		catch(Exception e) {}
		
		return System.URL.getSalesforceBaseUrl().toExternalForm().replace('https','http')+'/servlet/servlet.ImageServer?id='+imgDocId+'&oid='+UserInfo.getOrganizationId();
	}


	public PageReference goNavigateBack() {
		Map<String, String> customUrlParameters = new Map<String, String>{'oppId' => this.theOpp.Id};
		return zqu.QuoteWizardManager.navigateBack(customUrlParameters);
	}


	public PageReference goNavigateNext() {
		// CSP-506 | set Start Date to equal the Cancellation Date
		this.theQuote.zqu__StartDate__c = this.theQuote.zqu__CancellationDate__c;
		
		update this.theQuote;
		createCancellationAmendment(this.theQuote.Id);
		Map<String, String> customUrlParameters = new Map<String, String>{'Id' => this.theQuote.Id, 'oppId' => this.theOpp.Id, 'quoteType' => 'Cancellation'};
		return zqu.QuoteWizardManager.navigateNext(customUrlParameters);
	}

}