src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZProductTriggerHandlerTest.cls
@isTest
private class ZProductTriggerHandlerTest {

	private static testmethod void test_method_one() {
		// non-deleted ZProduct insertion
		zqu__ZProduct__c zp1 = TestClassUtility.createProduct(false);
		Database.insert(zp1, false);

		// non-deleted ZProduct updated so zqu__Deleted__c == true
		zp1.zqu__Deleted__c = true;
		Database.update(zp1, false);

		// deleted ZProduct insertion
		zqu__ZProduct__c zp2 = TestClassUtility.createProduct(false);
		zp2.zqu__Deleted__c = true;
		Database.insert(zp2, false);
	}
}